pentaho/pentaho-kettle

engine/src/org/pentaho/di/job/entries/getpop/JobEntryGetPOP.java
engine/src/org/pentaho/di/job/entries/sftp/JobEntrySFTP.java
ui/src/org/pentaho/di/ui/job/entries/getpop/JobEntryGetPOPDialog.java
ui/src/org/pentaho/di/ui/job/entries/sftp/JobEntrySFTPDialog.java
ui/src/org/pentaho/di/ui/job/entries/sftpput/JobEntrySFTPPUTDialog.java
ui/src/org/pentaho/di/ui/trans/steps/mailinput/MailInputDialog.java
ui/src/org/pentaho/di/ui/trans/steps/ssh/SSHDialog.java

[SP-3063][PDI-15703] Test transformation fails with encrypted password in a parameter for several steps
-added decrypting password

[SP-3063][PDI-15703] Test transformation fails with encrypted password in a parameter for several steps

---

engine/src/org/pentaho/di/job/entries/getpop/JobEntryGetPOP.java
engine/src/org/pentaho/di/job/entries/sftp/JobEntrySFTP.java
ui/src/org/pentaho/di/ui/job/entries/getpop/JobEntryGetPOPDialog.java
ui/src/org/pentaho/di/ui/job/entries/sftp/JobEntrySFTPDialog.java
ui/src/org/pentaho/di/ui/job/entries/sftpput/JobEntrySFTPPUTDialog.java
ui/src/org/pentaho/di/ui/trans/steps/mailinput/MailInputDialog.java
ui/src/org/pentaho/di/ui/trans/steps/ssh/SSHDialog.java

[SP-3064][PDI-15703] Test transformation fails with encrypted password in a parameter for several steps
-added decrypting password

[SP-3064][PDI-15703] Test transformation fails with encrypted password in a parameter for several steps

---

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Fixed removing row when parsing a null field

SP-3021 - Backport of PDI-15681 - JSON Input Step Removes Row when Parsing a Null Field

---

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Skip checking equality of json results size if it's size is 0

SP-3026 - Backport of PDI-15379 - Component failure "Input JSON" only in version 6.1.0.1-196. In the 5.2.0.0 version works correctly

---

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/exception/JsonInputException.java
plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

PDI-15196 - Fixed skipping rows if json field is null, empty or if there are no matches with json fields and at the same time there are no additional not null row fields. Corrected filtering out rows

SP-3068 - Backport of PDI-15196 - JSON Input Step does not ignore missing paths

---

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java

- reverted because is not full fix

[PDI-14797] Get Filenames Step issue with VFS and WinSSHD

---

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java

- reverted because is not full fix

[SP-3054][PDI-14797] Get Filenames Step issue with VFS and WinSSHD

---

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java

- reverted because is not full fix

[SP-3055][PDI-14797] Get Filenames Step issue with VFS and WinSSHD

---

engine/src/org/pentaho/di/repository/filerep/KettleFileRepository.java
engine/test-src/org/pentaho/di/repository/filerep/KettleFileRepositoryTest.java

@bmorrise @mdamour1976  please review

[BACKLOG-12472] Internal.Entry.Current.Directory in file repo

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java

[BACKLOG-10377] move SpoonStart extension point after spoon opens

---

core/src/org/pentaho/di/core/Const.java
engine/src/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java
engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java
ui/src/org/pentaho/di/ui/spoon/trans/LogBrowser.java

Revert of https://github.com/pentaho/pentaho-kettle/pull/3126
I need to marge it before I send new PR.
@pamval, @tkafalas, @mdamour1976, @tgf could you please review?

[PDI-15156] revert of previous fix

---

core/src/org/pentaho/di/core/database/DatabaseMeta.java
core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java

- set using pluginId insteadof constant
- add unit test

[PRD-5778]-JDBC connection details still remains even after removing from Options tab for MsSQL connections.JDBC connection details still remains

---

dbdialog/build.xml
engine/build.xml

[ENGOPS-2667] Removing custom antcontrib target

---

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaTest.java

- NPE and OutOfBounds were fixed
- added tests
- checkstyle improvements

[PDI-15821] java.lang.ArrayIndexOutOfBoundsException with metadata injection and microsoft excel input step

---

ui/src/org/pentaho/di/ui/spoon/partition/PartitionSettings.java
ui/test-src/org/pentaho/di/ui/spoon/partition/PartitionSettingsTest.java

Preventing NPE when the scheme name is not defined (null)

PDI-14227 - Can't enable partitioning on table input step

---

engine/src/org/pentaho/di/trans/steps/dimensionlookup/messages/messages_en_US.properties

@bmorrise, @mdamour1976 please review.

[BACKLOG-9795] - Add Metadata Injection (MDI) support to the Dimension lookup/update Step - add missed UI message

---

engine/src/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java
engine/test-src/org/pentaho/di/trans/steps/exceloutput/ExcelOutputTest.java

@mbatchelor, @duarteteixeira, could you please take a look?

[PDI-14420] - Excel Output with Append option is not working

---

dbdialog/build.xml
engine/build.xml

[ENGOPS-2667] Removing antcontrib targets(part II)

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputMultiCharDelimiterTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/files/multi_delim.csv

enclosure character fields lose last character
- fixed multi character delimiter processing in CsvInputStep

[PDI-14650] In csv input when using multiple character delimiter and an

---

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaTest.java

Reverts pentaho/pentaho-kettle#3246

Revert "[PDI-15821] java.lang.ArrayIndexOutOfBoundsException with metadata injection and microsoft excel input step"

---

plugins/repositories-plugin/repositories-plugin-core/src/main/resources/web/js/controllers.js

[BACKLOG-13673] Repository flow is not pointing to the right screens now

---

core/src/org/pentaho/di/core/row/RowMeta.java
core/test-src/org/pentaho/di/core/row/RowMetaTest.java

- replaced null field names with empty strings

[PDI-13829] NPE - pressing verify this transformation

---

engine/src/org/pentaho/di/trans/steps/fuzzymatch/FuzzyMatch.java
engine/test-src/org/pentaho/di/trans/steps/fuzzymatch/FuzzyMatchTest.java

PDI-15591 - Fuzzy Match step throws NullPointerException on null data fields

---

engine/src/org/pentaho/di/trans/steps/ldapinput/LdapSslProtocol.java

-added resolving variable for trust store path

[PDI-13754] LDAP Input Step - Using variable for "Trust store path"

---

engine/src/org/pentaho/di/trans/steps/propertyinput/PropertyInput.java
engine/test-src/org/pentaho/di/trans/steps/propertyinput/PropertyInputMetaTest.java

[PDI-15737] File encoding setting for INI files in Property Step are ignored
fix and test

[PDI-15737] File encoding setting for INI files in Property Step are ignored

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInputMeta.java
engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java
ui/src/org/pentaho/di/ui/trans/steps/textfileoutput/TextFileOutputDialog.java

[PDI-15650] Text file output: No header is created if header & append are checked
-added supporting case:
File Exists = N	  Flag Set = N	Add Header =Y	Append =Y
Result = File is created, header is written at top of file (this changed by the fix)
@mbatchelor Could you please review and merge it? It works correct locally.

[PDI-15650] Text file output: No header is created if header & append are checked

---

engine/src/org/pentaho/di/core/KettleEnvironment.java
engine/src/org/pentaho/di/engine/ExecutionEngine.java
engine/src/org/pentaho/di/engine/ExecutionEnginePluginType.java
engine/src/org/pentaho/di/engine/IExecutionEngine.java
plugins/execution-engine-plugin/pom.xml
plugins/execution-engine-plugin/res/version.xml
plugins/execution-engine-plugin/src/main/java/org/pentaho/engine/foobar/FooBarOSGiEngine.java
plugins/execution-engine-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugins/pom.xml

@mkambol @CodeOnCoffee @ccaspanello 
Cherry-pick of @andrei-viaryshka's work into the AEL branch

execution engine plugin - wip

---

engine/src/org/pentaho/di/trans/TransMeta.java
engine/test-src/org/pentaho/di/trans/TransMetaTest.java
ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
ui/test-src/org/pentaho/di/ui/spoon/trans/TransGraphTest.java

multiselect. Note - cross-commits - this commit is for PDI-14763, previous commit for PDI-14724

[PDI-14724] - Non detached steps can be hidden if they are part of a

---

engine/src/org/pentaho/di/trans/steps/mondrianinput/MondrianHelper.java
engine/src/org/pentaho/di/trans/steps/mondrianinput/MondrianInput.java
engine/src/org/pentaho/di/trans/steps/mondrianinput/messages/messages_en_US.properties

[PDI-14120] - MondrianInput should provide linenr logging

[PDI-12263] - MondrianInput should release resources as soon as possible

---

core/src/org/pentaho/di/core/row/ValueMetaAndData.java

[PDI-14417] Filter rows step behaviour with inputting dates - problem with EnterValueDialog
-fixed regression, using conversion mask for Data type

[PDI-14417] Filter rows step behaviour with inputting dates - problem with EnterValueDialog

---

core/src/org/pentaho/di/core/row/ValueMetaAndData.java

[SP-3149][PDI-14417] Filter rows step behaviour with inputting dates - problem with EnterValueDialog
-fixed regression, using conversion mask for Data type

[SP-3149][PDI-14417] Filter rows step behaviour with inputting dates - problem with EnterValueDialog

---

core/src/org/pentaho/di/core/row/ValueMetaAndData.java

[SP-3150][PDI-14417] Filter rows step behaviour with inputting dates - problem with EnterValueDialog
-fixed regression, using conversion mask for Data type

[SP-3150][PDI-14417] Filter rows step behaviour with inputting dates - problem with EnterValueDialog

---

ui/ivy.xml
ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
ui/src/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java
ui/src/org/pentaho/di/ui/spoon/trans/executionstate/api/ExecutionState.java
ui/src/org/pentaho/di/ui/spoon/trans/executionstate/api/ExecutionStateEvent.java
ui/src/org/pentaho/di/ui/spoon/trans/executionstate/api/ExecutionStatePublisher.java
ui/src/org/pentaho/di/ui/spoon/trans/executionstate/api/ExecutionStateSubscriber.java
ui/src/org/pentaho/di/ui/spoon/trans/executionstate/impl/local/LocalExecutionState.java
ui/src/org/pentaho/di/ui/spoon/trans/executionstate/impl/local/LocalExecutionStatePublisher.java

Publishing step metrics with kettleclassic execution.

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java

If connected to a repository must import/save file before using DET

BACKLOG-11920 - Using DET with a trans loaded via open URL

---

assembly/ivy.xml

[CLEANUP] required dep exclusions

---

engine/src/org/pentaho/di/repository/RepositoryExtended.java
plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
ui/src/org/pentaho/di/ui/repository/RepositoryDirectoryUI.java
ui/src/org/pentaho/di/ui/repository/dialog/SelectDirectoryDialog.java
ui/src/org/pentaho/di/ui/repository/dialog/SelectObjectDialog.java
ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseController.java
ui/src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIRepositoryDirectory.java

[BACKLOG-14031] use filtered eager loading for pur repository open dialogs

---

ui/src/org/pentaho/di/ui/trans/steps/excelinput/ExcelInputDialog.java
ui/test-src/org/pentaho/di/ui/trans/steps/excelinput/ExcelInputDialogTest.java

[PDI-13930]Get Files from Header Row doesn't load more than 256 fields in Excel Input step
-extract method for processing workbook
-deleted hardcoded limit 256
-added test

[PDI-13930]Get Files from Header Row doesn't load more than 256 fields in Excel Input step

---

engine/src/org/pentaho/di/trans/steps/tableoutput/messages/messages_en_US.properties
ui/src/org/pentaho/di/ui/trans/steps/tableoutput/TableOutputDialog.java
ui/test-src/org/pentaho/di/ui/trans/steps/tableoutput/TableOutputDialogTest.java

New locale message were added.
Validation meta info were created before ddl creation.
Created unit test.

[PDI-13829]-NPE -pressing verify this transformation

---

pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/IHasConfig.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/IOperation.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/ITransformation.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/Status.java
pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicOperation.java
pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicTransformation.java
pdi-execution-engine/impl/kettle-native/src/main/java/org/pentaho/di/engine/kettlenative/impl/KettleNativeUtil.java
pdi-execution-engine/impl/kettle-native/src/main/java/org/pentaho/di/engine/kettlenative/impl/Operation.java
pdi-execution-engine/impl/kettle-native/src/main/java/org/pentaho/di/engine/kettlenative/impl/Transformation.java
pdi-execution-engine/impl/model/pom.xml
pdi-execution-engine/impl/model/src/main/java/org/pentaho/di/engine/model/Configurable.java
pdi-execution-engine/impl/model/src/main/java/org/pentaho/di/engine/model/Hop.java
pdi-execution-engine/impl/model/src/main/java/org/pentaho/di/engine/model/Operation.java
pdi-execution-engine/impl/model/src/main/java/org/pentaho/di/engine/model/Transformation.java
pdi-execution-engine/impl/pom.xml

@mkambol @CodeOnCoffee @ccaspanello

Trans model

---

pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicKettleExecutionContext.java
pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicUtils.java
pdi-execution-engine/impl/kettle-classic/src/test/java/org/pentaho/di/engine/kettleclassic/ClassicKettleEngineTest.java
ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java

@pentaho-nbaker @hudak @ccaspanello

[BACKLOG-14037]  Minor fixes to get classic engine running in spoon.

---

ui/src/org/pentaho/di/ui/spoon/ExpandedContentManager.java
ui/test-src/org/pentaho/di/ui/spoon/ExpandedContentManagerTest.java

Should be merged with https://github.com/pentaho/pentaho-det-ee/pull/347
@pentaho/bobafett please review

[BACKLOG-14076] Added browser.refresh after setUrl

---

engine/src/org/pentaho/di/trans/steps/dimensionlookup/DimensionLookup.java
engine/src/org/pentaho/di/trans/steps/dimensionlookup/DimensionLookupMeta.java
engine/src/org/pentaho/di/trans/steps/dimensionlookup/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/steps/dimensionlookup/DimensionLookupMetaInjectionTest.java
ui/src/org/pentaho/di/ui/trans/steps/dimensionlookup/DimensionLookupDialog.java

[BACKLOG-9795] - Add Metadata Injection (MDI) support to the Dimension lookup/update Step - add TYPE_OF_RETURN_FIELD property

---

core/src/org/pentaho/di/core/database/Database.java

Needs https://github.com/pentaho/pdi-dataservice-plugin/pull/84.
@pentaho/millenniumfalcon please review.

[BACKLOG-12456] Copy database's formatting mask metadata to step's metadata

---

engine/ivy.xml
engine/src/org/pentaho/di/core/KettleEnvironment.java
engine/src/org/pentaho/di/core/annotations/EnginePlugin.java
engine/src/org/pentaho/di/core/plugins/EnginePluginType.java
pdi-engine-api/pom.xml
pdi-engine-api/src/main/java/org/pentaho/di/engine/api/IEngine.java
plugins/pdi-execution-engine-plugin/pom.xml
plugins/pdi-execution-engine-plugin/src/main/java/org/pentaho/di/engine/foobar/FooBarOSGiEngine.java
plugins/pdi-execution-engine-plugin/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugins/pom.xml

Plumbing OSGi plugin for the execution engine.

[BACKLOG-12856] Create a first-pass plugin for the execution engine

---

ui/src/org/pentaho/di/ui/core/database/wizard/CreateDatabaseWizardPageJDBC.java
ui/src/org/pentaho/di/ui/core/database/wizard/messages/messages_en_US.properties

[BACKLOG-12891] it's impossible to create a connection to Pentaho Data Services via Connection Wizard with empty Web App Name

---

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaTest.java

[SP-3219] Backport of PDI-15821 - java.lang.ArrayIndexOutOfBoundsException with metadata injection and microsoft excel input step (7.0 Suite)

---

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java

[SP-3218] Backport of PDI-15821 - java.lang.ArrayIndexOutOfBoundsException with metadata injection and microsoft excel input step (6.1 Suite)

---

plugins/pdi-pur-plugin/ivy.xml

only merge after https://github.com/pedrofvteixeira/pentaho-platform/tree/BACKLOG-12101 merge

[BACKLOG-12101] Refactors pentaho-platform tests dependencies to Maven

---

core/src/org/pentaho/di/core/row/RowMeta.java
core/test-src/org/pentaho/di/core/row/RowMetaTest.java
engine/src/org/pentaho/di/trans/steps/tableoutput/messages/messages_en_US.properties
ui/src/org/pentaho/di/ui/trans/steps/tableoutput/TableOutputDialog.java
ui/test-src/org/pentaho/di/ui/trans/steps/tableoutput/TableOutputDialogTest.java

Replaced null field names with empty strings
New locale message were added.
Validation meta info were created before ddl creation.
Created unit test.
Fixed test warnings.

[SP-3153] - Backport of PDI-13829 - NPE - pressing verify this transformation (7.0 Suite)	

---

core/src/org/pentaho/di/core/row/RowMeta.java
core/test-src/org/pentaho/di/core/row/RowMetaTest.java
engine/src/org/pentaho/di/trans/steps/tableoutput/messages/messages_en_US.properties
ui/src/org/pentaho/di/ui/trans/steps/tableoutput/TableOutputDialog.java
ui/test-src/org/pentaho/di/ui/trans/steps/tableoutput/TableOutputDialogTest.java

Replaced null field names with empty strings.
New locale message were added.
Validation meta info were created before ddl creation.
Created unit test.
Fixed test warnings.

[SP-3154] - Backport of PDI-13829 - NPE - pressing verify this transformation (6.1 Suite)

---

engine/src/kettle-engines.xml
engine/src/org/pentaho/di/trans/Trans.java
engine/src/org/pentaho/di/trans/nextgen/StepDataInterfaceAdapter.java
engine/src/org/pentaho/di/trans/nextgen/StepInterfaceAdapter.java
engine/src/org/pentaho/di/trans/nextgen/TransAdapter.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/IExecutionContext.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/reporting/ISubscriptionManager.java
pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicUtils.java
ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java
ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
ui/src/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java
ui/src/org/pentaho/di/ui/trans/dialog/TransExecutionConfigurationDialog.java

Introducing Adapter classes to support running new Engine's using the legacy base classes and interfaces

Reverting migration to new APIs.

---

pdi-execution-engine/api/pom.xml
pdi-execution-engine/impl/kettle-classic/pom.xml
pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicKettleExecutionContext.java
pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicOperation.java
pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicTransformation.java
pdi-execution-engine/impl/kettle-native/pom.xml
pdi-execution-engine/impl/pom.xml
pdi-execution-engine/pom.xml

Upgrade to rxjava 2 && package API as an OSGi Bundle

---

ui/src/org/pentaho/di/ui/spoon/ExpandedContentManager.java
ui/test-src/org/pentaho/di/ui/spoon/ExpandedContentManagerTest.java

- refresh the browser after it starts loading the most recently set URL

[BACKLOG-14076,BACKLOG-14389] Hide the browser instead of closing it when leaving DET

---

pdi-engine-api/pom.xml
pdi-engine-daemon/assemblies/pdi-engine-daemon-assembly/pom.xml
pdi-engine-daemon/assemblies/pom.xml
pdi-engine-daemon/features/pdi-engine-daemon-feature/pom.xml
pdi-engine-daemon/features/pom.xml
pdi-engine-daemon/pdi-daemon-hdfs/pom.xml
pdi-engine-daemon/pdi-daemon-spark/pom.xml
pdi-engine-daemon/pom.xml
pdi-spark-application/assemblies/pdi-spark-driver-assembly/pom.xml
pdi-spark-application/assemblies/pom.xml
pdi-spark-application/features/pdi-spark-driver-feature/pom.xml
pdi-spark-application/features/pom.xml
pdi-spark-application/pdi-spark-driver/pom.xml
pdi-spark-application/pdi-spark-engine/pom.xml
pdi-spark-application/pom.xml

@hudak, @CodeOnCoffee, @mkambol

[BACKLOG-14071] Fixing/Adding POM files so we have a place to put code during AEL development.

---

pdi-execution-engine/api/pom.xml
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/IEngine.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/events/IPDIEvent.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/remote/IExecutionRequest.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/remote/Notification.java
pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/reporting/Topic.java
pdi-execution-engine/impl/kettle-classic/src/main/java/org/pentaho/di/engine/kettleclassic/ClassicKettleExecutionContext.java

@mkambol @CodeOnCoffee @ccaspanello

Remote Spark Client API

---

assembly/ivy.xml
plugins/kettle-json-plugin/ivy.xml

Reverts pentaho/pentaho-kettle#3428

Revert "SP-3204 - Backport of PDI-15059 - Spoon startup: Multiple and different slf4j-log4j jar files in the class path"

---

assembly/ivy.xml
plugins/kettle-xml-plugin/ivy.xml

[ENGOPS-2747] Metaverse dependencies fix

---

engine/ivy.xml
pdi-engine-api/api/pom.xml
pdi-engine-api/impl/model/pom.xml
pdi-engine-api/impl/pom.xml
pdi-engine-api/pom.xml

[BACKLOG-14309]  Making artifact names consistent

---

plugins/pdi-pur-plugin/ivy.xml

subject to merge of https://github.com/pentaho/pentaho-commons-json/pull/8

[ENGOPS-2639] json GAV change

---

engine/src/org/pentaho/di/trans/steps/dimensionlookup/DimensionLookupMeta.java
engine/test-src/org/pentaho/di/trans/steps/dimensionlookup/DimensionLookupMetaTest.java

@bmorrise , @mdamour1976 please review.

[BACKLOG-9795] - Add Metadata Injection (MDI) support to the Dimension lookup/update Step - fix save fieldUpdate(RETURN_TYPE) to repository

---

pdi-execution-engine/api/src/main/java/org/pentaho/di/engine/api/remote/ExecutionRequest.java
pdi-execution-engine/impl/pom.xml
pdi-execution-engine/impl/remote-spark-client/pom.xml
pdi-execution-engine/impl/remote-spark-client/src/main/java/org/pentaho/di/engine/remote/client/Context.java
pdi-execution-engine/impl/remote-spark-client/src/main/java/org/pentaho/di/engine/remote/client/SparkClientEngine.java
pdi-execution-engine/impl/remote-spark-client/src/test/java/org/pentaho/di/engine/remote/client/ContextTest.java
pdi-execution-engine/impl/remote-spark-client/src/test/java/org/pentaho/di/engine/remote/client/SparkClientEngineTest.java

[BACKLOG-14307]Remote engine client

---

engine/src/org/pentaho/di/trans/steps/mapping/Mapping.java
engine/src/org/pentaho/di/trans/steps/simplemapping/SimpleMapping.java
engine/test-src/org/pentaho/di/trans/steps/mapping/MappingUnitTest.java
engine/test-src/org/pentaho/di/trans/steps/simplemapping/SimpleMappingTest.java

-added setting flag in true ( in consistency with SimpleMapping )
-added correct processing this flag in dispose() ( in consistency with SimpleMapping )
-added removing from collection active transformation not only in case waiting sub transformation

[PDI-13103] Flag wasStarted in MappingData never set to true

---

engine/src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFiles.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesIT.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesTest.java

find file in subfolder, relative to destination directory
add unit and integration tests
rename to camel case

[PDI-14334] Copy Files - overwrites files if subfolders used

---

core/src/org/pentaho/di/core/row/ValueMetaInterface.java
core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/org/pentaho/di/core/row/value/ValueMetaTimestamp.java

[BACKLOG-12456] Add the format mask to metadata used in pdi preview.

---

engine/src/org/pentaho/di/trans/Trans.java
engine/src/org/pentaho/di/trans/ael/adapters/StepDataInterfaceEngineAdapter.java
engine/src/org/pentaho/di/trans/ael/adapters/StepInterfaceEngineAdapter.java
engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java
engine/src/org/pentaho/di/trans/ael/adapters/TransMetaConverter.java
engine/src/org/pentaho/di/trans/step/BaseStep.java
engine/test-src/org/pentaho/di/trans/ael/adapters/StepInterfaceEngineAdapterTest.java
engine/test-src/org/pentaho/di/trans/ael/adapters/TransMetaConverterTest.java
ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java

Engine can now be selected by setting a parameter called 'engine'
with a value of the engine's plugin id.  This will be replaced with
UI options eventually.

[BACKLOG-14309]  Adapter classes for interacting with an Engine

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteBigCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteLittleCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiBytePatternMatcher.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputDoubleLineEndTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java

- refactored processing csv data
- minor refactoring unit tests

[PDI-15922]-Missing data when using delimiters like "aa" in the CSV file

---

ui/src/org/pentaho/di/ui/spoon/ExpandedContentManager.java
ui/test-src/org/pentaho/di/ui/spoon/ExpandedContentManagerTest.java

Should be merged together with https://github.com/pentaho/pentaho-det/pull/582
@pentaho/bobafett please review

[BACKLOG-14361] Open det without reloading browser page

---

pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/ExecutionContext.java

@hudak @ccaspanello @CodeOnCoffee

[BACKLOG-14309]  Adding ExecutionContext.withParams

---

engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

[PDI-15650] Text file output: No header is created if header & appendare checked
-added fixing for case when filename in stream

[PDI-15650] Text file output: No header is created if header & appendare checked

---

engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

[SP-3185][PDI-15650] Text file output: No header is created if header& append are checked
-added fixing for case when filename in stream

[SP-3185][PDI-15650] Text file output: No header is created if header& append are checked

---

engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

[SP-3186][PDI-15650] Text file output: No header is created if header& append are checked
-added fixing for case when filename in stream

[SP-3186][PDI-15650] Text file output: No header is created if header& append are checked

---

core/src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta.java
core/test-src/org/pentaho/di/core/database/MSSQLServerDatabaseMetaTest.java

- for BigNumber, Number shown Float(53), Binary shown VARBINARY(MAX), InternetAddress shown UNKNOWN
- added testcase for Binary

[PDI-15934]-Table Output step generated DDL without data type (MS SQLServer)

---

.gitignore
core/src/org/pentaho/di/core/row/ValueMetaInterface.java
core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/org/pentaho/di/core/row/value/ValueMetaBigNumber.java
core/src/org/pentaho/di/core/row/value/ValueMetaDate.java
core/src/org/pentaho/di/core/row/value/ValueMetaInteger.java
core/src/org/pentaho/di/core/row/value/ValueMetaNumber.java
core/test-src/org/pentaho/di/core/row/ValueMetaTest.java

@pentaho/millenniumfalcon please review.
Moved Constructor lost in the middle of the code to the top of the class (after attributes)
Added some files/folders to the .gitignore and implemented a getFormatMask for each ValueMeta

[BACKLOG-12456] Fixed Date formatting mask mechanism 

---

assembly/package-res/samples/transformations/General - Load images and store into database table.ktr

Replaced "General - Load images and store into database table" transformation with the one attached by KC. Run to make sure new one works as expected.

[BACKLOG-11909] Sample transformation "General - Load images and store into database table.ktr" lost TableOutput step

---

engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java
engine/test-src/org/pentaho/di/trans/steps/transexecutor/TransExecutorUnitTest.java

Transformation executor was missing checks for disabled hops to output steps, added missing checks and tests.
@mkambol

[BACKLOG-11907] Sample transformation transformation-executor/trans-executor-parent.ktr fails

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteBigCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteLittleCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiBytePatternMatcher.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputDoubleLineEndTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java

- refactored processing csv data
- minor refactoring unit tests

[SP-3274][PDI-15922]-Missing data when using delimiters like "aa" in the CSV file

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteBigCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteLittleCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiBytePatternMatcher.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputDoubleLineEndTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java

- refactored processing csv data
- minor refactoring unit tests

[SP-3273][PDI-15922]-Missing data when using delimiters like "aa" in the CSV file

---

core/src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta.java
core/test-src/org/pentaho/di/core/database/MSSQLServerDatabaseMetaTest.java

- for BigNumber, Number shown Float(53), Binary shown VARBINARY(MAX), InternetAddress shown UNKNOWN
- added testcase for Binary

[SP-3307][PDI-15934]-Table Output step generated DDL without data type (MS SQLServer)

---

engine/src/org/pentaho/di/trans/steps/joinrows/JoinRows.java
engine/src/org/pentaho/di/trans/steps/joinrows/messages/messages_en_US.properties

[SP-3318][PDI-13561] Join Rows RowLevel Logging Fix

---

engine/src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFiles.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesIT.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesTest.java

find file in subfolder, relative to destination directory
add unit and integration tests
rename to camel case

[SP-3275][PDI-14334] Copy Files - overwrites files if subfolders used

---

engine/src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFiles.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesIT.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesTest.java

find file in subfolder, relative to destination directory
add unit and integration tests
rename to camel case

[SP-3276][PDI-14334] Copy Files - overwrites files if subfolders used

---

engine/src/org/pentaho/di/trans/steps/mapping/Mapping.java
engine/src/org/pentaho/di/trans/steps/mapping/MappingMeta.java
engine/src/org/pentaho/di/trans/steps/simplemapping/SimpleMapping.java
engine/test-src/org/pentaho/di/trans/steps/mapping/MappingUnitTest.java
engine/test-src/org/pentaho/di/trans/steps/simplemapping/SimpleMappingTest.java

-added setting flag in true ( in consistency with SimpleMapping )
-added correct processing this flag in dispose() ( in consistency with SimpleMapping )
-added removing from collection active transformation not only in case waiting sub transformation
@mbatchelor  Could you please merge it?

[SP-3277][PDI-13103] Flag wasStarted in MappingData never set to true

---

engine/src/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/org/pentaho/di/trans/messages/messages_en_US.properties
engine/src/org/pentaho/di/trans/messages/messages_it_IT.properties
engine/src/org/pentaho/di/trans/messages/messages_ja_JP.properties
engine/src/org/pentaho/di/trans/steps/mapping/MappingMeta.java
engine/src/org/pentaho/di/trans/steps/simplemapping/SimpleMappingMeta.java
engine/src/org/pentaho/di/trans/steps/singlethreader/SingleThreaderMeta.java
engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java

[CDA-91] As a Developer I can't invoke Jobs or Transformations from "Initial Transformation"
-fixed variable with class name for subclasses
-fixed message for exception loading sub transformation

[CDA-91] As a Developer I can't invoke Jobs or Transformations from "Initial Transformation"

---

engine/src/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/org/pentaho/di/trans/messages/messages_en_US.properties
engine/src/org/pentaho/di/trans/messages/messages_it_IT.properties
engine/src/org/pentaho/di/trans/messages/messages_ja_JP.properties
engine/src/org/pentaho/di/trans/steps/mapping/MappingMeta.java
engine/src/org/pentaho/di/trans/steps/simplemapping/SimpleMappingMeta.java
engine/src/org/pentaho/di/trans/steps/singlethreader/SingleThreaderMeta.java
engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java

[SP-3314][CDA-91] As a Developer I can't invoke Jobs or Transformations from "Initial Transformation"
-fixed variable with class name for subclasses
-fixed message for exception loading sub transformation

[SP-3314][CDA-91] As a Developer I can't invoke Jobs or Transformations from "Initial Transformation"

---

plugins/meta-inject-plugin/src/main/java/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java

...on "ETL Metadata Injection" step 
* Saving streamSourceStepname from UI when dialog is closed

[PDI-15989]   Problem saving "Streaming source step" and "Streaming target step" properties... 

---

engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java

Reverts pentaho/pentaho-kettle#3546

Revert "SP-3257 - Backport of PDI-15877 - Enclosure character is not removed from output stream"

---

engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java

Reverts pentaho/pentaho-kettle#3547

Revert "SP-3258 - Backport of PDI-15877 - Enclosure character is not removed from output stream"

---

pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/Execution.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/ExecutionManager.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/RemoteSource.java

* Restore CompletableFuture return type for submit()
* Make execution AutoClosable

Remote event stream API

---

engine/src/org/pentaho/di/repository/RepositoryExtended.java
engine/src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNames.java
plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
ui/src/org/pentaho/di/ui/repository/dialog/SelectDirectoryDialog.java
ui/src/org/pentaho/di/ui/repository/dialog/SelectObjectDialog.java
ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseController.java

[PDI-15928] - Get Repository Names step hangs when working with the

---

engine/src/org/pentaho/di/trans/Trans.java
engine/src/org/pentaho/di/trans/step/BaseStep.java
engine/src/org/pentaho/di/trans/step/RowHandler.java
engine/test-src/org/pentaho/di/trans/step/BaseStepTest.java

getRow/putRow/putError behavior within AEL Spark functions.

[BACKLOG-14877] Adding RowHandler to BaseStep, to allow overriding

---

ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java
ui/test-src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegateTest.java

[BACKLOG-14766] - Reopening transformation with logging turned on causes NPE in Spoon

---

ui/src/org/pentaho/di/ui/core/database/wizard/CreateDatabaseWizardPage2.java

[BACKLOG-14074] Database Connection Wizard: It's possible to skip Next and go to Finish without providing database name

---

engine/src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNames.java
engine/test-src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesTest.java
engine/test-src/org/pentaho/di/utils/TestUtils.java

Repository - added tests and behaviour for mask

[PDI-15928]Get Repository Names step hangs when working with the Pentaho

---

ui/src/org/pentaho/di/ui/spoon/SpoonSlave.java

@pamval, @mbatchelor, could you please take a look?

[PDI-13148] - NPE in Slave Server Monitor Tab

---

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforce/SalesforceConnection.java
plugins/salesforce/src/org/pentaho/di/trans/steps/salesforcedelete/SalesforceDeleteMeta.java

After switching from Axis to WSC - com.sforce.soap.partner.PartnerConnection.insert( SObject[] sfBuffer ) returns result for all sfBuffer's elements even if some of they are nulls.

[PDI-15900] Salesforce Insert throws error

---

engine/src/org/pentaho/di/trans/TransMeta.java

Reverts pentaho/pentaho-kettle#3348

Revert "[PDI-2286] Sort steps before saving to a file"

---

engine/test-src/org/pentaho/di/trans/step/StepMetaTest.java

Reverts pentaho/pentaho-kettle#3569

Revert "[TEST] coverage for StepMeta.fromXml"

---

engine/src/org/pentaho/di/trans/steps/nullif/NullIf.java
engine/test-src/org/pentaho/di/trans/steps/nullif/NullIfTest.java

- now it uses the format (conversion mask) from the meta data (previous step)

[PDI-14500]-Null if step does not use format when converting dates

---

ui/src/org/pentaho/di/ui/trans/steps/mapping/MappingDialog.java

[BACKLOG-12443] Mapping dialog size adjustment

---

core/src/org/pentaho/di/core/KettleClientEnvironment.java
engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java

Also adding ability to tailor the KettleClientEnvironment's list of plugins which are loaded.

[BACKLOG-14877] Propagating Trans failure back to Client.

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/org/pentaho/di/core/row/value/ValueMetaBigNumber.java
core/src/org/pentaho/di/core/row/value/ValueMetaDate.java
core/src/org/pentaho/di/core/row/value/ValueMetaInteger.java
core/src/org/pentaho/di/core/row/value/ValueMetaNumber.java
core/src/org/pentaho/di/core/row/value/ValueMetaTimestamp.java
core/test-src/org/pentaho/di/compatibility/ValueTest.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

@pentaho/millenniumfalcon please review.

[BACKLOG-14992] Fix to NPE when converting a String to Date

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/org/pentaho/di/core/row/value/ValueMetaTimestamp.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaStringTest.java

@pentaho/millenniumfalcon @TatsianaKasiankova please review
The second commit is a cleanup (removing deprecated Assert.* ) and it is the source of most of changed lines

[BACKLOG-14992] Fix to conversions from String when a mask isn't already set.

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java

@pentaho/millenniumfalcon please review. fix to enable QAT.

[BACKLOG-14992] Return default masks to public access

---

engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/Engine.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/ExecutionContext.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/ExecutionRequest.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/model/ActingPrincipal.java

Please review @CodeOnCoffee 
@pentaho/rogueone 
This is in conjunction with another PR: https://github.com/pentaho/pentaho-ee/pull/81

[BACKLOG-15160] first drop of passing pdi user to ael daemon

---

engine/src/org/pentaho/di/trans/steps/webservices/WebService.java
engine/test-src/org/pentaho/di/trans/steps/webservices/WebServiceTest.java

@mdamour1976 , @bmorrise  please review. 
Please, read BACKLOG-15326-related email before merge!

[BACKLOG-15326] - Unable to save output to local drive - add 301 HTTP code handling

---

engine/src/org/pentaho/di/trans/steps/nullif/NullIf.java
engine/test-src/org/pentaho/di/trans/steps/nullif/NullIfTest.java

- now it uses the format (conversion mask) from the meta data (previous step)

[SP-3379][PDI-14500]-Null if step does not use format when converting dates

---

engine/src/org/pentaho/di/trans/steps/nullif/NullIf.java
engine/test-src/org/pentaho/di/trans/steps/nullif/NullIfTest.java

- now it uses the format (conversion mask) from the meta data (previous step)

[SP-3378][PDI-14500]-Null if step does not use format when converting dates

---

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforce/SalesforceConnection.java
plugins/salesforce/src/org/pentaho/di/trans/steps/salesforcedelete/SalesforceDeleteMeta.java

[SP-3364] Backport of PDI-15900 - Salesforce Insert throws error (7.0 Suite)

---

plugins/pdi-pur-plugin/src/org/pentaho/di/ui/repository/pur/repositoryexplorer/controller/RepositoryLockController.java
plugins/pdi-pur-plugin/test/org/pentaho/di/ui/repository/pur/repositoryexplorer/controller/RepositoryLockControllerTest.java

added checking canUnlock in repository if it remote and Proxy
added test
fixed check style problems

[SP-3362][PDI-15976] Spoon v 7.0 cannot remove "Lock" from transformation/job

---

core/src/org/pentaho/di/core/fileinput/FileInputList.java
core/src/org/pentaho/di/core/vfs/KettleVFS.java
core/src/org/pentaho/di/core/vfs/SftpFileObjectWithWindowsSupport.java
core/src/org/pentaho/di/core/vfs/SftpFileSystemWindows.java
core/src/org/pentaho/di/core/vfs/SftpFileSystemWindowsProvider.java
core/test-src/org/pentaho/di/core/vfs/SftpFileObjectWithWindowsSupportTest.java

added sftp windows supporting
added tests

[SP-3356][PDI-14797] Get Filenames Step issue with VFS and WinSSHD

---

core/src/org/pentaho/di/core/fileinput/FileInputList.java
core/src/org/pentaho/di/core/vfs/KettleVFS.java
core/src/org/pentaho/di/core/vfs/SftpFileObjectWithWindowsSupport.java
core/src/org/pentaho/di/core/vfs/SftpFileSystemWindows.java
core/src/org/pentaho/di/core/vfs/SftpFileSystemWindowsProvider.java
core/test-src/org/pentaho/di/core/vfs/SftpFileObjectWithWindowsSupportTest.java

added sftp windows supporting
added tests

[SP-3355][PDI-14797] Get Filenames Step issue with VFS and WinSSHD

---

plugins/meta-inject-plugin/pom.xml
plugins/pom.xml
plugins/repositories-plugin/pom.xml
plugins/repositories-plugin/repositories-plugin-core/pom.xml

[ENGOPS-3024] update plugin poms to use 7.1-SNAPSHOT parents

---

engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/Execution.java

Properly logging exceptions and setting step status to stopped.

[BACKLOG-14877] Adding new method to close execution with an Exception.

---

pdi-engine/api/src/main/java/org/pentaho/di/engine/api/RowException.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/converter/RowConversionManager.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/events/BaseEvent.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/events/DataEvent.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/events/MetricsEvent.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/events/StatusEvent.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/model/Rows.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/ExecutionRequest.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/RemoteSource.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/reporting/Metrics.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/reporting/Status.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/reporting/Topic.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/model/ActingPrincipal.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/model/Configurable.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/model/Hop.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/model/Operation.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/model/Transformation.java

@CodeOnCoffee / @mkambol / @hudak

[BACKLOG-15386] Added serialVersionUID to all Serializable classes.

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java

[SP-3373][PDI-14390] Text file input throws NPE if skipping error rows and passing through incoming fieds

---

pdi-engine/api/src/main/java/org/pentaho/di/engine/api/HasConfig.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/model/MaterializedModelElement.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/model/Configurable.java

@ccaspanello @mkambol @pentaho-nbaker 
Needed for registered flatMapFunctions w/ SparkOperations

[BACKLOG-15549]Add defaults to HasConfig

---

ui/src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIDatabaseConnection.java
ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIDatabaseConnectionTest.java

- added verification modifiedDate != null

[PDI-15871]-Repository Explorer: Database Connections tab shows "Unable to initialize security tab" dialog

---

engine/src/org/pentaho/di/trans/steps/ldapinput/LdapProtocolFactory.java
engine/test-src/org/pentaho/di/trans/steps/ldapinput/LdapProtocolFactoryTest.java

-added resolving a variable for a protocol of LDAP step
-added a test

[PDI-16048] LDAP Input protocol not substituted

---

pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/Execution.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/ExecutionException.java

@hudak / @CodeOnCoffee / @mkambol / @rfellows

[BACKLOG-15249] Exception handling modifications so Spark App messages get sent to Spoon

---

engine/src/org/pentaho/di/trans/steps/rest/Rest.java
engine/test-src/org/pentaho/di/trans/steps/rest/RestTest.java

- added UriComponent.encode(...) for each parameter

[PDI-16045]-Rest Client step does not encode parameter list properly

---

pdi-engine/api/src/main/java/org/pentaho/di/engine/api/Engine.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/ExecutionContext.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/HasConfig.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/reporting/SubscriptionManager.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/model/Configurable.java

* Remove unnecessary Serialisation interfaces
* Remove unused type parameter

Cleanup Engine API

---

plugins/pdi-engine-configuration/ui/src/main/java/org/pentaho/di/engine/ui/RunConfigurationDialog.java

[BACKLOG-14903] UX updates for the run configuration dialog

---

core/src/org/pentaho/di/core/Const.java

* introduce new lettle compatibility property

[BACKLOG-15706]-HDP 25 - Hive with PMR job fails-Cannot instantiate class: org.osjava.sj.SimpleContextFactory

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java

[BACKLOG-15936] Fix slave server icon

---

engine/src/org/pentaho/di/trans/steps/rest/Rest.java
engine/test-src/org/pentaho/di/trans/steps/rest/RestTest.java

- added UriComponent.encode(...) for each parameter

[SP-3448][PDI-16045]-Rest Client step does not encode parameter list properly

---

engine/src/org/pentaho/di/trans/step/BaseStep.java
engine/src/org/pentaho/di/trans/step/RowHandler.java
engine/src/org/pentaho/di/trans/step/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/step/BaseStepTest.java

http://jira.pentaho.com/browse/BACKLOG-15953

[BACKLOG-15953] Adding getRowFrom/putRowTo to RowHandler

---

engine/src/org/pentaho/di/trans/steps/denormaliser/Denormaliser.java
engine/test-src/org/pentaho/di/trans/steps/denormaliser/DenormaliserAggregationsTest.java

[PDI-16017] Denormaliser step: Minimum Aggregation with multiple columns carries data across columns
- reworked fix PDI-9662. Method newGroup should not initialize result by default for MIN
[PDI-16015] Denormaliser step: KettleValueException on Minimum Aggregation only
- initialization code didn't have converting data

[SP-3377][PDI-16017] Denormaliser step: Minimum Aggregation with multiple columns carries data across columns

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

* Rethrowing a proper exception to be handled later
* Unit tests

[PDI-16136]   String to BigNumber conversion failure in Json Input step

---

engine/src/org/pentaho/di/trans/steps/pentahoreporting/PentahoReportingOutput.java
engine/src/org/pentaho/di/trans/steps/pentahoreporting/PentahoReportingOutputMeta.java
engine/src/org/pentaho/di/trans/steps/pentahoreporting/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/steps/pentahoreporting/PentahoReportingOutputLoadSaveTest.java
engine/test-src/org/pentaho/di/trans/steps/pentahoreporting/PentahoReportingOutputMetaLoadSaveTest.java
engine/test-src/org/pentaho/di/trans/steps/pentahoreporting/PentahoReportingOutputMetaTest.java
ui/src/org/pentaho/di/ui/trans/steps/pentahoreporting/PentahoReportingOutputDialog.java

- added new parameter "create parent folder" in dialog
- added processing new parameter
- fixed unit tests

[PDI-14571]-PDI Pentaho Reporting Output Sample does not generate pdf

---

engine/src/org/pentaho/di/trans/steps/ldapinput/LdapProtocolFactory.java
engine/test-src/org/pentaho/di/trans/steps/ldapinput/LdapProtocolFactoryTest.java

-added resolving a variable for a protocol of LDAP step
-added a test

[SP-3447][PDI-16048] LDAP Input protocol not substituted

---

plugins/pdi-engine-configuration/impl/pom.xml

Required along with this pull request
https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/115
https://github.com/pentaho/pentaho-karaf-assembly/pull/311
https://github.com/pentaho/pentaho-ee/pull/158

[BACKLOG-15902] Add features for Spark to server

---

pdi-engine/pom.xml

[CLEANUP] set parent pom version to 7.1-SNAPSHOT

---

pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/Execution.java

To support acquire/release of execution requests.

[BACKLOG-15249] Adding a Execution.releaseRequest to the AEL api

---

engine/src/org/pentaho/di/repository/kdr/KettleDatabaseRepository.java

[BACKLOG-15034] - When creating a Database Repository, an 'Invalid user credentials' error is thrown to the logs

---

engine/src/org/pentaho/di/base/AbstractMeta.java

https://github.com/pentaho/pdi-dataservice-server-plugin/pull/248 is dependent on this pull request.

[BACKLOG-15784] Increase performance of data services for DET

---

engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java

Master PR: https://github.com/pentaho/pentaho-kettle/pull/3799
7.1.0.0 PR: https://github.com/pentaho/pentaho-kettle/pull/3806
Jira Case: http://jira.pentaho.com/browse/BACKLOG-16118

[BACKLOG-16118] Fixed issue with field lengths in text input

---

pdi-engine/api/src/main/java/org/pentaho/di/engine/api/model/Row.java
pdi-engine/serializers/src/main/java/org/pentaho/pdi/engine/serializers/DataEventSerializer.java
pdi-engine/serializers/src/main/java/org/pentaho/pdi/engine/serializers/DeserializedRow.java
pdi-engine/serializers/src/test/java/org/pentaho/pdi/engine/serializers/DeserializedRowTest.java

Removing methods requiring metadata.
http://jira.pentaho.com/browse/BACKLOG-16027

[BACKLOG-16027] Slimming the Row api

---

plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/RunConfigurationManager.java
plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/pentaho/DefaultRunConfiguration.java
plugins/pdi-engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/RunConfigurationManagerTest.java

Master PR: https://github.com/pentaho/pentaho-kettle/pull/3809
7.1.0.0 PR: https://github.com/pentaho/pentaho-kettle/pull/3811

[BACKLOG-14903] Order run configurations alphabetically

---

assembly/ivy.xml

[BACKLOG-13032] groupId change for elastic & transitive fix in assembly

---

ui/src/org/pentaho/di/ui/spoon/trans/TransPerfDelegate.java

@pamval, @duarteteixeira, @mbatchelor, could you please take a look?

[PDI-14691] - Performance Graphs do not display in PDI 5.4

---

engine/src/org/pentaho/di/trans/ael/adapters/StepInterfaceEngineAdapter.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/model/Row.java
pdi-engine/serializers/src/main/java/org/pentaho/pdi/engine/serializers/DataEventSerializer.java
pdi-engine/serializers/src/main/java/org/pentaho/pdi/engine/serializers/DeserializedRow.java
pdi-engine/serializers/src/test/java/org/pentaho/pdi/engine/serializers/DeserializedRowTest.java

@dkincade @kcruzada 
Tested on master/QAT.
Will likely break the wingman build due to ordering-- pdi-engine needs to be built before kettle-engine.  Master build succeeded with no test failures.

Backlog 16027 7.1 - Slimming Row api

---

engine/src/org/pentaho/di/trans/ael/adapters/TransMetaConverter.java
engine/test-src/org/pentaho/di/trans/ael/adapters/TransMetaConverterTest.java

Remove steps following inactive input.
@mkambol

[BACKLOG-15685] As a Chris, I want to be able to disable steps when running on Spark

---

engine/src/org/pentaho/di/trans/ael/adapters/StepInterfaceEngineAdapter.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/model/Row.java
pdi-engine/serializers/src/main/java/org/pentaho/pdi/engine/serializers/DataEventSerializer.java
pdi-engine/serializers/src/main/java/org/pentaho/pdi/engine/serializers/DeserializedRow.java
pdi-engine/serializers/src/test/java/org/pentaho/pdi/engine/serializers/DeserializedRowTest.java

@dkincade, same as https://github.com/pentaho/pentaho-kettle/pull/3836 for 7.1.0.0

Backlog 16027 7.1.0.0

---

engine/src/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/test-src/org/pentaho/di/job/entries/job/JobEntryJobIT.java

- write logs to file from carte server

[PDI-14781] Empty log file gets created when job runs on carte server

---

plugins/repositories-plugin/repositories-plugin-core/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java
plugins/repositories-plugin/repositories-plugin-core/src/main/java/org/pentaho/di/ui/repo/RepositoryDialog.java
plugins/repositories-plugin/repositories-plugin-core/src/test/java/org/pentaho/di/ui/repo/RepositoryConnectControllerTest.java

Resending pull request due to the lost https://github.com/pentaho/pentaho-kettle/pull/3801.  Although Tim's pr was already merged these changes are absent in master (Possible because of a force push)

[PDI-14804] When creating a database repository connection in Spoon it's possible to create duplicate database connections

---

plugins/aggregate-rows/pom.xml
plugins/elasticsearch-bulk-insert/pom.xml
plugins/get-previous-row-field/pom.xml
plugins/gp-bulk-loader/pom.xml
plugins/meta-inject-plugin/pom.xml
plugins/pdi-engine-configuration/impl/src/test/resources/metastore_test/metastore/pentaho/Default Run Configuration/.type.xml
plugins/pdi-engine-configuration/impl/src/test/resources/metastore_test/metastore/pentaho/Spark Run Configuration/.type.xml
plugins/pdi-engine-configuration/pom.xml
plugins/pom.xml
plugins/repositories-plugin/pom.xml

[BACKLOG-13042] Mavenized get-previous-row-field

---

assembly/ivy.xml
plugins/aggregate-rows/aggregate-rows-core/pom.xml
plugins/aggregate-rows/assemblies/aggregate-rows-plugin/assembly/assembly.xml
plugins/aggregate-rows/assemblies/aggregate-rows-plugin/pom.xml
plugins/aggregate-rows/assemblies/pom.xml
plugins/aggregate-rows/pom.xml
plugins/elasticsearch-bulk-insert/assemblies/elasticsearch-bulk-insert-plugin/assembly/assembly.xml
plugins/elasticsearch-bulk-insert/assemblies/elasticsearch-bulk-insert-plugin/pom.xml
plugins/elasticsearch-bulk-insert/assemblies/pom.xml
plugins/elasticsearch-bulk-insert/elasticsearch-bulk-insert-core/pom.xml
plugins/elasticsearch-bulk-insert/pom.xml
plugins/get-previous-row-field/assemblies/plugin/pom.xml
plugins/get-previous-row-field/assemblies/plugin/src/assembly/assembly.xml
plugins/get-previous-row-field/assemblies/pom.xml
plugins/get-previous-row-field/core/pom.xml
plugins/get-previous-row-field/pom.xml
plugins/gp-bulk-loader/assemblies/gp-bulk-loader-plugin/pom.xml
plugins/gp-bulk-loader/assemblies/pom.xml
plugins/gp-bulk-loader/gp-bulk-loader-core/pom.xml
plugins/gp-bulk-loader/pom.xml
plugins/meta-inject-plugin/pom.xml
plugins/pdi-engine-configuration/api/pom.xml
plugins/pdi-engine-configuration/features/pom.xml
plugins/pdi-engine-configuration/features/src/main/feature/feature.xml
plugins/pdi-engine-configuration/impl/pom.xml
plugins/pdi-engine-configuration/pom.xml
plugins/pdi-engine-configuration/ui/pom.xml
plugins/repositories-plugin/assembly/pom.xml
plugins/repositories-plugin/pom.xml
plugins/repositories-plugin/repositories-plugin-core/pom.xml

@lgrill-pentaho @emartin-pentaho @e-cuellar @ViswesvarSekar

[ENGOPS-3148] groupId change for mavenized kettle plugins

---

engine/src/org/pentaho/di/trans/TransMeta.java
engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java
engine/test-src/org/pentaho/di/trans/TransMetaTest.java

[BACKLOG-16013] Activate parameters for Spark transformations

---

engine/src/org/pentaho/di/trans/TransMeta.java
engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java
engine/test-src/org/pentaho/di/trans/TransMetaTest.java

Backlog 16013 7.1

---

engine/src/org/pentaho/di/trans/TransMeta.java
engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java
engine/test-src/org/pentaho/di/trans/TransMetaTest.java

Backport of https://github.com/pentaho/pentaho-kettle/pull/3859

Backlog 16013 7.1.0.0

---

core/src/org/pentaho/di/core/extension/KettleExtensionPoint.java
engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/org/pentaho/di/job/entries/trans/messages/messages_en_US.properties
plugins/pdi-engine-configuration/api/src/main/java/org/pentaho/di/engine/configuration/api/RunConfigurationFactory.java
plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/EmbeddedRunConfigurationManager.java
plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/MetaStoreRunConfigurationFactory.java
plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/RunConfigurationManager.java
plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationRunExtensionPoint.java
plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationSaveExtensionPoint.java
plugins/pdi-engine-configuration/impl/src/main/resources/OSGI-INF/blueprint/beans.xml
plugins/pdi-engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationRunExtensionPointTest.java
ui/src/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialog.java

Master PR: https://github.com/pentaho/pentaho-kettle/pull/3861
7.1.0.0 PR: https://github.com/pentaho/pentaho-kettle/pull/3872

[BACKLOG-16242] Store run configurations in abstractmeta

---

assembly/ivy.xml

@dkincade @mdamour1976 please review

[BACKLOG-16413] - AEL is generally missing from pdi-ce

---

plugins/pdi-engine-configuration/ui/src/main/java/org/pentaho/di/engine/ui/RunConfigurationDialog.java
plugins/pdi-engine-configuration/ui/src/main/java/org/pentaho/di/engine/ui/RunConfigurationPopupMenuExtension.java
plugins/pdi-engine-configuration/ui/src/main/resources/org/pentaho/di/engine/ui/messages/messages_en_US.properties

Master PR: https://github.com/pentaho/pentaho-kettle/pull/3870
7.1.0.0 PR: https://github.com/pentaho/pentaho-kettle/pull/3879

[BACKLOG-16360] Add invalid characters check for run configurations

---

engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java
plugins/pdi-engine-configuration/ui/src/main/java/org/pentaho/di/engine/ui/RunConfigurationDialog.java

Master PR: https://github.com/pentaho/pentaho-kettle/pull/3882
7.1.0.0 PR: https://github.com/pentaho/pentaho-kettle/pull/3884

[BACKLOG-15590] Update missing server messaging

---

assembly/build.properties
assembly/build.xml

Includes refactored layout in the distribution and permission retention -- including eula-wrap config.

[BACKLOG-16377] AEL Client Assembly 

---

engine/src/org/pentaho/di/job/entries/checkdbconnection/JobEntryCheckDbConnections.java
engine/test-src/org/pentaho/di/job/entries/checkdbconnection/JobEntryCheckDbConnectionsTest.java

- changed the way calculating difference between times

[PDI-14906]-Check Db connections step timeout minutes calculated wrong

---

plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationImportExtensionPoint.java
plugins/pdi-engine-configuration/impl/src/main/resources/OSGI-INF/blueprint/beans.xml
plugins/pdi-engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationImportExtensionPointTest.java

Master PR: https://github.com/pentaho/pentaho-kettle/pull/3899
7.1.0.0 PR: https://github.com/pentaho/pentaho-kettle/pull/3901

[BACKLOG-16483] Import run configurations from jobs

---

ui/src/org/pentaho/di/ui/job/dialog/JobLoadProgressDialog.java
ui/src/org/pentaho/di/ui/trans/dialog/TransLoadProgressDialog.java

@pamval, @mbatchelor, could you please take a look?

[PDI-16177] - Progress Information screen doesn't show anything

---

core/src/org/pentaho/di/core/database/Database.java
core/src/org/pentaho/di/core/database/SqlScriptParser.java
core/test-src/org/pentaho/di/core/database/SqlScriptParserTest.java

[PDI-16224] Job/Transformation returns "ORA-00911: invalid character"error
-added correct processing backslash for Oracle DB

[PDI-16224] Job/Transformation returns "ORA-00911: invalid character"error

---

engine/src/org/pentaho/di/job/entries/checkdbconnection/JobEntryCheckDbConnections.java
engine/test-src/org/pentaho/di/job/entries/checkdbconnection/JobEntryCheckDbConnectionsTest.java

[SP-3556][PDI-14906]-Check Db connections step timeout minutes calculated wrong

---

engine/src/org/pentaho/di/trans/ael/adapters/TransMetaConverter.java
engine/test-src/org/pentaho/di/trans/ael/adapters/TransMetaConverterTest.java

[BACKLOG-16426] Steps following 2 disabled hops are executed in AEL mode

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

Commit open transactions after select statement to avoid locking of parallel sessions when using MySQL as repository database.

[SP-3564]Commit open transactions

---

engine/src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFiles.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesTest.java
ui/src/org/pentaho/di/ui/job/entries/copyfiles/JobEntryCopyFilesDialog.java

- fixed saving dialog
- added test for save/load

[PDI-14734]-Dialog's table discards input after losing focus

---

ivy.xml
plugins/kettle-gpload-plugin/ivy.xml
plugins/kettle-json-plugin/ivy.xml
plugins/kettle-xml-plugin/ivy.xml
plugins/salesforce/ivy.xml
ui/ivy.xml

[BACKLOG-12977] GAV change for kettle-engine-test

---

core/pom.xml
core/src/test/java/org/pentaho/di/core/database/SequenceMetaTest.java
core/src/test/java/org/pentaho/di/core/util/StringEvaluatorTest.java

[BACKLOG-12968] Pom tweaking and locale dependent test fix

---

plugins/aggregate-rows/aggregate-rows-core/pom.xml
plugins/elasticsearch-bulk-insert/assemblies/elasticsearch-bulk-insert-plugin/assembly/assembly.xml
plugins/elasticsearch-bulk-insert/elasticsearch-bulk-insert-core/pom.xml
plugins/googleanalytics/core/pom.xml
plugins/gp-bulk-loader/gp-bulk-loader-core/pom.xml
plugins/kettle-s3csvinput-plugin/core/pom.xml
plugins/kettle-s3csvinput-plugin/pom.xml
plugins/kettle-sap-plugin/core/pom.xml
plugins/kettle-sap-plugin/pom.xml
plugins/kettle-shapefilereader-plugin/core/pom.xml
plugins/kettle-shapefilereader-plugin/pom.xml
plugins/meta-inject-plugin/pom.xml

[BACKLOG-12977] more GAV fixes for engine test jar

---

engine/src/org/pentaho/di/trans/Trans.java
engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/ExecutionContext.java
pdi-engine/api/src/main/java/org/pentaho/di/engine/api/remote/Execution.java
ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java

[BACKLOG-16115] Add logic to stop transformation

---

core/ivy.xml

- exclude log4j dependency pull

[PDI-14764] Jaro algorithm glitch

---

pom.xml

[CLEANUP] separate modules into profiles

---

assemblies/pdi-ce/pom.xml
dbdialog/pom.xml
ui/pom.xml

[BACKLOG-12995] Leave swt as a compile dependency on modules

---

engine/src/test/java/org/pentaho/di/repository/filerep/KettleFileRepositoryTestBase.java
engine/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumTest.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

fixing Checksum tests failing sometimes due to some test pollution.
cleans some test created resources

[BACKLOG-12977] pentaho-kettle/engine some tests cleanup

---

engine/src/org/pentaho/di/job/entries/unzip/JobEntryUnZip.java
engine/test-src/org/pentaho/di/job/entries/unzip/JobEntryUnZipTest.java

[PDI-16222] Unzip File Job Entry - Move files After Extraction Failed
-moving and deleting correct fileObject

[PDI-16222] Unzip File Job Entry - Move files After Extraction Failed

---

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

[PDI-16265]-Text File Input: error handling line numbers are wrong

---

assemblies/pdi-ce/pom.xml
core/pom.xml
engine/pom.xml

[BACKLOG-12995] Updating dependency changes after rebase

---

assemblies/pdi-ce/pom.xml
assemblies/pom.xml
core/pom.xml
dbdialog/pom.xml
engine/pom.xml
integration/pom.xml
pdi-engine/api/pom.xml
pdi-engine/pom.xml
pdi-engine/serializers/pom.xml
pom.xml
ui/pom.xml

[BACKLOG-12995] Consolidating dependencies and gav's

---

plugins/file-open-save-plugin/impl/core/src/main/javascript/app/components/files/files.component.js
plugins/file-open-save-plugin/impl/core/src/main/javascript/app/components/files/files.html

@bmorrise @e-cuellar 
For sorting feature.
Please review. :)

[BACKLOG-16428] Adding sorting feature for 'Name' column

---

plugins/pom.xml

[CLEANUP] separate plugin modules into profiles

---

plugins/file-open-save-plugin/impl/core/src/main/javascript/app/components/files/files.component.js
plugins/file-open-save-plugin/impl/core/src/main/javascript/app/components/files/files.css
plugins/file-open-save-plugin/impl/core/src/main/javascript/app/components/files/files.html

Makes table scrollable
@bmorrise @e-cuellar  :)

[BACKLOG-16428] Implementation for scrollable files results table

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

[PDI-7090] - Only one user can make changes in a repository at any time. (Database Repository is locked)
Fixed an additional problem. When user editing or create slave server via toolbar it locks database.
This commit uses approach from base commit https://github.com/pentaho/pentaho-kettle/pull/3857/commits/befadee3293dd4f8f3c5999dd1e345f56b4cdabd

[PDI-7090] - Only one user can make changes in a repository at any time. (Database Repository is locked)

---

plugins/pdi-engine-configuration/api/pom.xml
plugins/pdi-engine-configuration/assemblies/feature/pom.xml
plugins/pdi-engine-configuration/assemblies/feature/src/main/feature/feature.xml
plugins/pdi-engine-configuration/assemblies/pom.xml
plugins/pdi-engine-configuration/impl/pom.xml
plugins/pdi-engine-configuration/pom.xml
plugins/pdi-engine-configuration/ui/pom.xml

[BACKLOG-15836] Mavenize pdi-engine-configuration: review

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

Reverts pentaho/pentaho-kettle#4030

Revert "[SP-3564][PDI-7090] - Only one user can make changes in a repository at any time. (Database Repository is locked)"

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

Reverts pentaho/pentaho-kettle#4029

Revert "[SP-3565] Backport of PDI-7090 - Only one user can make changes in a repository at any time. (Database Repository is locked) (6.1 Suite)."

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

Reverts pentaho/pentaho-kettle#3951

Revert "[SP-3564]Commit open transactions"

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

Reverts pentaho/pentaho-kettle#3952

Revert "[SP-3565]Commit open transactions"

---

assemblies/pdi-ce/pom.xml
engine/pom.xml
plugins/pdi-pur-plugin/assemblies/plugin/pom.xml
plugins/pdi-pur-plugin/core/pom.xml
pom.xml

[CLEANUP] Cleanup versions to match version.properties

---

plugins/kettle-json-plugin/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInputField.java
plugins/kettle-json-plugin/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/JsonInputMetaTest.java

- trim type now sets.
- line separators in test were changed to the system default.

[PDI-16312] JSON Input step ignores the trim type

---

plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/EmbeddedRunConfigurationManager.java
plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/MetaStoreRunConfigurationFactory.java
plugins/pdi-engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/RunConfigurationManagerTest.java

Reverts pentaho/pentaho-kettle#4064

Revert "[BACKLOG-17014]  Provide key driven Mulit-provider MetastoreLocator"

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

This reverts commit 25b5b63bf472151d73ab126a581e35783bc27b60.

Revert "[SP-3564]Commit open transactions after select statement to avoid locking of parallel sessions when using MySQL as repository database."

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

This reverts commit 85cd2bc0d8ee07ec437e53e8d877fbaa7e7ba758.

Revert "[SP-3565]Commit open transactions after select statement to avoid locking of parallel sessions when using MySQL as repository database."

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java
ui/src/org/pentaho/di/ui/spoon/SWTGC.java

[PDI-7090]-Only one user can make changes in a repository at any time (Database Repository is locked)

---

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

[SP-3626][PDI-16265]-Text File Input: error handling line numbers are wrong

---

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

[SP-3627][PDI-16265]-Text File Input: error handling line numbers are wrong

---

engine/src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFiles.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesTest.java
ui/src/org/pentaho/di/ui/job/entries/copyfiles/JobEntryCopyFilesDialog.java

- fixed saving dialog
- added test for save/load

[SP-3601][PDI-14734]-Dialog's table discards input after losing focus

---

plugins/pdi-pur-plugin/ivy.xml

[SP-3571][PPP-3742]-Use of vulnerable component gwt-servlet-2.0.3.jar CVE-2012-4563

---

engine/src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFiles.java
engine/test-src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesTest.java
ui/src/org/pentaho/di/ui/job/entries/copyfiles/JobEntryCopyFilesDialog.java

- fixed saving dialog
- added test for save/load

[SP-3600][PDI-14734]-Dialog's table discards input after losing focus

---

core/src/org/pentaho/di/core/logging/LogChannel.java
core/src/org/pentaho/di/core/logging/LogChannelFileWriterBuffer.java
core/src/org/pentaho/di/core/logging/LoggingRegistry.java
core/test-src/org/pentaho/di/core/logging/LogChannelFileWriterBufferTest.java
core/test-src/org/pentaho/di/core/logging/LoggingRegistryTest.java
engine/src/org/pentaho/di/core/logging/LogChannelFileWriter.java
engine/src/org/pentaho/di/www/CarteSingleton.java
engine/test-src/org/pentaho/di/core/logging/LogChannelFileWriterTest.java

[SP-3586] Backport of PDI-15982 - Incomplete/Missing logs when Main Job with sub jobs are scheduled (7.1 Suite)

---

core/src/org/pentaho/di/core/logging/LogChannel.java
core/src/org/pentaho/di/core/logging/LogChannelFileWriterBuffer.java
core/src/org/pentaho/di/core/logging/LoggingRegistry.java
core/test-src/org/pentaho/di/core/logging/LogChannelFileWriterBufferTest.java
core/test-src/org/pentaho/di/core/logging/LoggingRegistryTest.java
engine/src/org/pentaho/di/core/logging/LogChannelFileWriter.java
engine/src/org/pentaho/di/www/CarteSingleton.java
engine/test-src/org/pentaho/di/core/logging/LogChannelFileWriterTest.java

[SP-3587] Backport of PDI-15982 - Incomplete/Missing logs when Main Job with sub jobs are scheduled (6.1 Suite)

---

plugins/json/core/pom.xml
plugins/pom.xml
plugins/pur/core/pom.xml
plugins/salesforce/pom.xml

[CLEANUP] Setting plugins to run tests with reuseForks=false

---

plugins/repositories/core/src/main/resources-filtered/META-INF/js/require.json

@marcoslarsen @graimundo 
@tmcsantos had missed out that curly bracket. Tested locally and the repo window works as intended. This should fix the DET issue also.

[BACKLOG-17471] Fixes repository window showing up blank

---

plugins/file-open-save/core/src/main/javascript/app/app.css
plugins/file-open-save/core/src/main/javascript/app/components/card/card.css

Fixes for #7, 10, 21
@bmorrise @e-cuellar

[BACKLOG-15718] card line height and disable button cursor fixes

---

engine/src/main/java/org/pentaho/di/kitchen/Kitchen.java

- All possible options are covered now

[PDI-16221] "file" option of Kitchen and Pan do not work in the file system

---

ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java
ui/src/test/java/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegateTest.java

[PDI-16339]--Saving a job with a duplicate name makes PDI work inconsistently

---

plugins/repositories/core/src/main/resources-filtered/web/index.html

[CLEANUP] Replace smart quotes in html tag

---

engine/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSum.java
engine/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumTest.java

- checksum calculates on native data types
- added tests

[PDI-9323] dealing with decimals in checksum, comparisons etc not according to value

---

core/src/main/java/org/pentaho/di/core/Condition.java
core/src/test/java/org/pentaho/di/core/ConditionTest.java

- the extra restrictions were removed - now the field positions updates every time

[PDI-13227] join rows step - after changing the steps on incoming hops, step gets into undefined / not working state

---

ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/datagrid/DataGridDialog.java

[PDI-9388] Deleting a column from the Datagrid step moves column names as heading for wrong data
added synchronization between Fields and Data tables

[PDI-9388] Deleting a column from the Datagrid step moves column names as heading for wrong data

---

ui/src/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java
ui/test-src/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegateTest.java

[SP-3695][PDI-16339]--Saving a job with a duplicate name makes PDI work inconsistently

---

plugins/file-open-save/core/src/main/javascript/app/app.css

[BACKLOG-15721] Arrow cursor for disabled buttons

---

plugins/file-open-save/core/src/main/javascript/app/components/breadcrumb/breadcrumb.component.js
plugins/file-open-save/core/src/main/javascript/app/components/breadcrumb/breadcrumb.css
plugins/file-open-save/core/src/main/javascript/app/components/breadcrumb/breadcrumb.html

[BACKLOG-15721] Truncate long breadcrumb items

---

plugins/file-open-save/core/src/main/javascript/app/app.component.js
plugins/file-open-save/core/src/main/javascript/app/app.css
plugins/file-open-save/core/src/main/javascript/app/app.html
plugins/file-open-save/core/src/main/javascript/app/app.module.js
plugins/file-open-save/core/src/main/javascript/app/components/files/files.component.js
plugins/file-open-save/core/src/main/javascript/app/shared/directives/edit.directive.js
plugins/file-open-save/core/src/main/javascript/app/shared/directives/key.directive.js

[BACKLOG-15721] Allow hitting enter to save/open

---

plugins/file-open-save/core/src/main/javascript/app/components/breadcrumb/breadcrumb.component.js
plugins/file-open-save/core/src/main/javascript/app/components/folder/folder.component.js

[BACKLOG-15721] small fix for folder area scrolling

---

plugins/file-open-save/core/src/main/javascript/app/components/breadcrumb/breadcrumb.css
plugins/file-open-save/core/src/main/javascript/app/components/breadcrumb/breadcrumb.html

[BACKLOG-15721] breadcrumb flyout not showing

---

ui/src/main/java/org/pentaho/di/ui/core/PropsUI.java

[BACKLOG-15718] Fix for recently opened files

---

plugins/file-open-save/core/src/main/javascript/app/app.css
plugins/file-open-save/core/src/main/javascript/app/app.html

[BACKLOG-15721] Disallow text selection in tree

---

plugins/file-open-save/core/src/main/javascript/app/app.component.js
plugins/file-open-save/core/src/main/javascript/app/app.css
plugins/file-open-save/core/src/main/javascript/app/shared/directives/edit.directive.js

[BACKLOG-15721] Update for keyup for rename

---

plugins/file-open-save/core/src/main/javascript/app/app.component.js
plugins/file-open-save/core/src/main/javascript/app/components/error/error.css

[BACKLOG-15721] Fix for aligning folders

---

engine/src/main/java/org/pentaho/di/trans/steps/insertupdate/InsertUpdate.java
engine/src/test/java/org/pentaho/di/trans/steps/insertupdate/InsertUpdateMetaTest.java

-added returning false in error case

[PDI-14346] Error handling in Insert/Update from sub transformation

---

engine/src/main/java/org/pentaho/di/repository/IUser.java
engine/src/main/java/org/pentaho/di/repository/UserInfo.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java
ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseController.java
ui/src/test/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseControllerTest.java

[PDI-16258] Hidden folders show for business user "Suzy" from Spoon
only admins can see hidden files in pentaho repository via spoon explorer
safe way without impacting on PDI Plugins and custom plugins

[PDI-16258] Hidden folders show for business user "Suzy" from Spoon

---

plugins/file-open-save/core/src/main/java/org/pentaho/repo/extension/RepositoryOpenSaveExtensionPoint.java

[BACKLOG-15718] Fix for recently opened file directory

---

engine/src/main/java/org/pentaho/di/repository/RepositorySecurityProvider.java
plugins/pur/core/src/main/java/org/pentaho/di/ui/repository/EESpoonPlugin.java
plugins/pur/core/src/main/java/org/pentaho/di/ui/repository/pur/services/IAbsSecurityProvider.java
plugins/pur/core/src/test/java/org/pentaho/di/ui/repository/EESpoonPluginTest.java

Repository we see the following error on console "Perspective with
schedulerPerspective is not found"

[BACKLOG-16610] - [PDI CE] - In some operation when connect to Pentaho

---

plugins/file-open-save/core/src/main/javascript/app/components/files/files.component.js
plugins/file-open-save/core/src/main/javascript/app/components/files/files.css
plugins/file-open-save/core/src/main/javascript/app/components/files/files.html
plugins/file-open-save/core/src/main/javascript/app/components/loading/loading.component.js
plugins/file-open-save/core/src/main/resources/i18n/file-open-save/messages_en.properties

[BACKLOG-15721] Light cleanup and localization of files headers

---

plugins/file-open-save/core/src/main/javascript/app/components/breadcrumb/breadcrumb.component.js
plugins/file-open-save/core/src/main/javascript/app/components/folder/folder.component.js
plugins/file-open-save/core/src/main/javascript/app/components/folder/folder.html
plugins/file-open-save/core/src/main/javascript/app/components/utils.js

[BACKLOG-15721] Fix for folder horizontal scrolling issue

---

plugins/file-open-save/core/src/main/javascript/app/components/folder/folder.html

[BACKLOG-15721] small fix for folder width

---

ui/src/main/java/org/pentaho/di/ui/core/widget/ColumnInfo.java
ui/src/main/java/org/pentaho/di/ui/core/widget/ColumnsResizer.java
ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java

TableView: allow disabling automatic column expansion for contents
ColumnsResizer: account for vscrollbar when resizing, option to refit
after manual column resize

[BACKLOG-17671] TableView column resize

---

engine/src/main/java/org/pentaho/di/www/RunTransServlet.java
engine/src/test/java/org/pentaho/di/www/RunTransServletTest.java

clearing parameters was removed
@pamval Could you please review and merge it?

[PDI-16422] runTrans web service does not apply transformation parameters

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

- added prompt the user to save the files

[PDI-16416]-Disconnect from a repository does not prompt the user to save the files before disconnect

---

core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
core/src/test/java/org/pentaho/di/core/database/DatabaseMetaTest.java
ui/src/main/java/org/pentaho/di/ui/core/database/wizard/CreateDatabaseWizardPage1.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java

- fixed, now it trimmed before storing and checked trimmed values

[PDI-16365]-Spaces in connection name can cause unexpected behavior

---

plugins/file-open-save/core/src/main/javascript/app/app.component.js
plugins/file-open-save/core/src/main/javascript/app/app.html
plugins/file-open-save/core/src/main/javascript/app/components/loading/loading.component.js
plugins/file-open-save/core/src/main/javascript/app/components/loading/loading.html

@e-cuellar 
Please review/merge

[BACKLOG-18139] Tooltip visible while Open thin dialog

---

plugins/file-open-save/core/src/main/resources/i18n/file-open-save/messages_en.properties

@e-cuellar 
please review/merge

[BACKLOG-18157] Fix casing for the word delete

---

plugins/file-open-save/core/src/main/javascript/app/app.component.js

[BACKLOG-18136] Accessing recent files that have been deleted

---

engine/pom.xml

@pentaho/rogueone @pentaho/rebelalliance @pamval 
Driver version upgrade. please review.

[BACKLOG-17345] Upgrade Postgres JDBC Driver version to 42.1.1

---

plugins/file-open-save/assemblies/feature/src/main/feature/feature.xml
plugins/file-open-save/pom.xml

[BACKLOG-18159] Enable new file open/save for CE

---

engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/job/JobMeta.java
engine/src/main/java/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFiles.java
engine/src/main/java/org/pentaho/di/job/entries/createfile/JobEntryCreateFile.java
engine/src/main/java/org/pentaho/di/job/entries/createfolder/JobEntryCreateFolder.java
engine/src/main/java/org/pentaho/di/job/entries/deletefile/JobEntryDeleteFile.java
engine/src/main/java/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFiles.java
engine/src/main/java/org/pentaho/di/job/entries/deletefolders/JobEntryDeleteFolders.java
engine/src/main/java/org/pentaho/di/job/entries/movefiles/JobEntryMoveFiles.java
engine/src/main/java/org/pentaho/di/job/entries/waitforfile/JobEntryWaitForFile.java
engine/src/main/java/org/pentaho/di/job/entry/JobEntryCopy.java
engine/src/main/java/org/pentaho/di/job/entry/JobEntryInterface.java
engine/src/test/java/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesTest.java
engine/src/test/java/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFilesTest.java

The infrastructure for jobs and following job Steps are implemented with this PR
Delete Files
Delete Folders
Move Files
Copy Files
Wait For File
Create a Folder
Delete File
Create File

[BACKLOG-17016] Implement EmbeddedNamedClusters on Job Steps:

---

plugins/file-open-save/core/src/main/javascript/app/shared/directives/focus.directive.js

[BACKLOG-18075] Fix for input box focus

---

plugins/file-open-save/core/src/main/javascript/app/shared/directives/focus.directive.js

[BACKLOG-18075] Fixed issue with save name highlight

---

plugins/file-open-save/core/src/main/javascript/app/app.component.js
plugins/file-open-save/core/src/main/javascript/app/app.html
plugins/file-open-save/core/src/main/javascript/app/components/files/files.component.js

[BACKLOG-18152] Fixed issue with create folder permissions

---

engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java

- applied fix (https://github.com/pentaho/pentaho-kettle/pull/4255), added unit test

[PDI-16430]-The PostgreSQL bulk loader" truncate action exists an error

---

plugins/file-open-save/core/src/main/javascript/app/shared/directives/focus.directive.js

[BACKLOG-18075] Check for empty values before setting selection

---

engine/src/main/java/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
engine/src/test/resources/org/pentaho/di/trans/steps/csvinput/files/column_name_with_spaces.csv

@bmorrise , @pamval please review.

[BACKLOG-18365] - Second column reading as all null values for the attached CSV and KTR

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java

-added prompt the user to save the files

[SP-3723][PDI-16416]-Disconnect from a repository does not prompt the user to save the files before disconnect

---

core/src/org/pentaho/di/core/Condition.java
core/test-src/org/pentaho/di/core/ConditionTest.java

[SP-3701] Backport of PDI-13227 - join rows step - after changing the steps on incoming hops, step gets into undefined / not working state (6.1 Suite)

---

core/src/org/pentaho/di/core/Condition.java
core/test-src/org/pentaho/di/core/ConditionTest.java

[SP-3700] Backport of PDI-13227 - join rows step - after changing the steps on incoming hops, step gets into undefined / not working state (7.1 Suite)

---

engine/src/org/pentaho/di/trans/steps/insertupdate/InsertUpdate.java
engine/test-src/org/pentaho/di/www/RunTransServletTest.java

[SP-3711][PDI-14346] Error handling in Insert/Update from sub transformation
-added returning false in error case

[SP-3711][PDI-14346] Error handling in Insert/Update from sub transformation

---

engine/src/org/pentaho/di/trans/steps/insertupdate/InsertUpdate.java
engine/test-src/org/pentaho/di/trans/steps/insertupdate/InsertUpdateMetaTest.java

[SP-3710][PDI-14346] Error handling in Insert/Update from sub transformation
-added returning false in error case

[SP-3710][PDI-14346] Error handling in Insert/Update from sub transformation

---

ui/src/org/pentaho/di/ui/core/widget/TableView.java
ui/src/org/pentaho/di/ui/trans/steps/datagrid/DataGridDialog.java

[SP-3709][PDI-9388] Deleting a column from the Datagrid step moves column names as heading for wrong data
added synchronization between Fields and Data tables

[SP-3709][PDI-9388] Deleting a column from the Datagrid step moves column names as heading for wrong data

---

plugins/file-open-save/core/src/main/resources-filtered/app/index.html

[BACKLOG-17812] Disable right click in Open/Save

---

engine/src/org/pentaho/di/www/RunTransServlet.java
engine/test-src/org/pentaho/di/www/RunTransServletTest.java

[SP-3727][PDI-16422] runTrans web service does not apply transformation parameters
clearing parameters was removed

[SP-3727][PDI-16422] runTrans web service does not apply transformation parameters

---

engine/src/org/pentaho/di/core/injection/AfterInjection.java
engine/src/org/pentaho/di/core/injection/bean/BeanInjector.java
engine/src/org/pentaho/di/trans/steps/insertupdate/InsertUpdate.java
engine/src/org/pentaho/di/trans/steps/insertupdate/InsertUpdateMeta.java
engine/src/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderMeta.java
engine/src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMeta.java
engine/src/org/pentaho/di/trans/steps/streamlookup/StreamLookupMeta.java
engine/test-src/org/pentaho/di/trans/steps/insertupdate/InsertUpdateMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java
engine/test-src/org/pentaho/di/trans/steps/streamlookup/StreamLookupMetaTest.java
plugins/meta-inject-plugin/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInject.java

Reverts pentaho/pentaho-kettle#4343

Revert "Revert "[SP3754][PDI-16472] Oracle bulk loader is not working with metadata injection (ArrayIndexOutOfBoundsException)""

---

plugins/file-open-save/core/src/main/java/org/pentaho/repo/dialog/RepositoryOpenSaveDialog.java
plugins/file-open-save/core/src/main/javascript/app/app.html
plugins/file-open-save/core/src/main/javascript/app/components/card/card.css
plugins/file-open-save/core/src/main/javascript/app/components/folder/folder.html
plugins/file-open-save/core/src/main/javascript/app/shared/directives/resize/resize.module.js
plugins/file-open-save/core/src/main/javascript/app/shared/directives/resize/resizeCards.directive.js
plugins/file-open-save/core/src/main/javascript/app/shared/directives/resize/resizeFiles.directive.js

@bmorrise 
Please review/merge.

[BACKLOG-18371] Some resizing fixes

---

plugins/file-open-save/core/src/main/javascript/app/app.css
plugins/file-open-save/core/src/main/javascript/app/app.html
plugins/file-open-save/core/src/main/javascript/app/shared/directives/resize/resizeCards.directive.js

[BACKLOG-18371] Some more resizing fixes

---

plugins/file-open-save/core/src/main/java/org/pentaho/repo/extension/RepositoryOpenSaveExtensionPoint.java
plugins/file-open-save/core/src/main/javascript/app/components/folder/folder.html
plugins/file-open-save/core/src/main/javascript/app/shared/directives/resize/resizeFolders.directive.js

[BACKLOG-18371] Fix for folder x-scrolling and spacing below buttons

---

ui/src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIRepositoryDirectory.java
ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIRepositoryDirectoryTest.java

[SP-3730][PDI-16258] Hidden folders show for business user "Suzy" from Spoon
fixing showing hidden files after renaming, moving and deleting (refresh)

[SP-3730][PDI-16258] Hidden folders show for business user "Suzy" from Spoon

---

engine/src/main/java/org/pentaho/di/trans/ael/adapters/TransMetaConverter.java
engine/src/test/java/org/pentaho/di/trans/ael/adapters/TransMetaConverterTest.java

- Only resolve hc url with a cluster information that is defined.

[BACKLOG-18592] - Search an replace all hadoop cluster url to the file system url

---

core/src/main/java/org/pentaho/di/core/database/Database.java

- added the use of connection properties

[PDI-16323] Ability to publish data source over SSL to the BA server

---

assemblies/pdi-ce/pom.xml
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/spark/SparkRunConfiguration.java
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/spark/SparkRunConfigurationExecutor.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/spark/SparkRunConfigurationExecutorTest.java

No longer included in the assembly, in favor
of the websocket daemon.

[BACKLOG-18537] Removing the AEL RSA daemon

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/database/DatabaseUnitTest.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
engine/src/main/java/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java
engine/src/test/java/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java

-there was deleted setting wrong type

[PDI-14721] Problem with MySQL and BLOBs - ValueMetaInterface.TYPE_BINARY is being set to ValueMetaInterface.STRING

---

engine-ext/api/src/main/java/org/pentaho/di/engine/model/ActingPrincipal.java
engine-ext/api/src/test/java/org/pentaho/di/engine/model/ActingPrincipalTest.java
engine/src/main/java/org/pentaho/di/trans/ael/websocket/TransWebSocketEngineAdapter.java

Adding an ANONYMOUS ActingPrincipal to allow
easier identification of unknown principal,
as opposed to searching for "anonymous".

[BACKLOG-18541] Proxy user support

---

core/src/main/java/org/pentaho/di/core/vfs/AliasedFileObject.java

[BACKLOG-17900] - Implement read/write Parquet format functionality in PDI steps via Shim API - resolve Hadoop cluster file paths

---

assemblies/pdi-ce/pom.xml

[BACKLOG-18537] Removing the RSA daemon from the assembly.

---

engine/src/main/java/org/pentaho/di/trans/ael/adapters/TransMetaConverter.java
engine/src/main/java/org/pentaho/di/workarounds/ResolvableResource.java
engine/src/test/java/org/pentaho/di/trans/ael/adapters/TransMetaConverterTest.java

[BACKLOG-17900] - Implement read/write Parquet format functionality in PDI steps via Shim API - resolve Hadoop cluster file paths for AEL

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

[PDI-16455] Problem when comparing binary values
-fixed comparing binary values. Fix is based on PR https://github.com/pentaho/pentaho-kettle/pull/4026 by GavinHacker
- fixed merge conflict, added test

[PDI-16455] Problem when comparing binary values

---

plugins/file-open-save/core/src/main/javascript/app/app.component.js
plugins/file-open-save/core/src/main/javascript/app/app.html
plugins/file-open-save/core/src/main/javascript/app/components/files/files.component.js
plugins/file-open-save/core/src/main/javascript/app/shared/directives/scrollToFolder.directive.js

[BACKLOG-18720] Delete icon in thin Repository Save dialog

---

plugins/file-open-save/core/pom.xml

[BACKLOG-18159] Restoring removed tag in pom.xml

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java
engine/test-src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java

[SP-3776][PDI-14721] Problem with MySQL and BLOBs - ValueMetaInterface.TYPE_BINARY is being set to ValueMetaInterface.STRING
-there was deleted setting wrong type

[SP-3776][PDI-14721] Problem with MySQL and BLOBs - ValueMetaInterface.TYPE_BINARY is being set to ValueMetaInterface.STRING

---

core/src/org/pentaho/di/core/database/Database.java

[SP-3757] Backport of PDI-16323 - Ability to publish data source over SSL to the BA server (7.1 Suite)

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java
engine/test-src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java

[SP-3775][PDI-14721] Problem with MySQL and BLOBs - ValueMetaInterface.TYPE_BINARY is being set to ValueMetaInterface.STRING
-there was deleted setting wrong type

[SP-3775][PDI-14721] Problem with MySQL and BLOBs - ValueMetaInterface.TYPE_BINARY is being set to ValueMetaInterface.STRING

---

engine/src/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/test-src/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java

[SP-3804][PDI-16430]-The PostgreSQL bulk loader" truncate action exists an error

---

plugins/file-open-save/core/src/main/java/org/pentaho/repo/controller/RepositoryBrowserController.java

[BACKLOG-19068] small fix to cover folders that begin with same prefix

---

ui/src/main/java/org/pentaho/di/ui/trans/step/BaseStepDialog.java

[BACKLOG-18970] - Parquet Output - Add new options - Date/Time Stamp & File extension - fix option tab controls

---

assemblies/pdi-ce/src/main/resources/classes/log4j.xml

@VasilinaTerehova please take a view and merge

[BACKLOG-16494] - Ranger for YARN: job freezes if policy for current user disabled or not exist

---

plugins/file-open-save/core/src/main/javascript/app/components/error/error.component.js
plugins/file-open-save/core/src/main/javascript/app/components/files/files.component.js
plugins/file-open-save/core/src/main/resources/i18n/file-open-save/messages_en.properties

[BACKLOG-19090] added error message for renaming folder with open file

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

Reverts pentaho/pentaho-kettle#4176

Revert "[PDI-14442]-PDI Import scripts are executed in parallel by multiple users"

---

.gitignore
engine/src/main/java/org/pentaho/di/trans/steps/regexeval/RegexEvalMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClassMeta.java

@rmansoor @tkafalas @mbatchelor, please take a look

BACKLOG-19141 - Fixed serialization of UserDefinedJavaClass and RegExEval to NOT output CDATA tags in ktr XML

---

engine/src/main/java/org/pentaho/di/trans/steps/update/UpdateMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/update/UpdateMetaTest.java

[PDI-16501]-Update step: The row in "The key(s) to look up the value(s)" is missing after exporting the repository.

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

[PDI-16510]-Job entries are not sorted alphabetically within their functional groupings

---

ui/src/org/pentaho/di/ui/job/entries/job/JobEntryJobDialog.java

[PDI-16503]-Once the "server" environment type is selected for a job entry of a job it cannot be changed back to "local"

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/mapping/MappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/simplemapping/SimpleMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/singlethreader/SingleThreaderMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
engine/src/main/resources/org/pentaho/di/trans/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/StepWithMappingMetaTest.java
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java

Reverts pentaho/pentaho-kettle#4457

Revert "[PDI-15891]-Problem running a zipped file with Pan.bat"

---

assemblies/pdi-ce/src/main/resources-filtered/docs/English/welcome/index.html

@pentaho/millenniumfalcon @pentaho/2-1b please review

[BACKLOG-19262] Updated direct references to mindtouch links

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java
plugins/pur/core/src/main/resources/org/pentaho/di/repository/pur/messages/messages_en_US.properties

Resend pull-request of the reverted https://github.com/pentaho/pentaho-kettle/pull/4176

[PDI-14442]-PDI Import scripts are executed in parallel by multiple users

---

ui/src/main/java/org/pentaho/di/ui/trans/step/BaseStepDialog.java

[BACKLOG-19241] - Parquet output get fields dialog fixes

---

plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/abort/Abort.java

Reverts pentaho/pentaho-kettle#4536

[BACKLOG-19565] Revert - stopping in abort on a separate thread

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java

[SP-3826][PDI-16510]-Job entries are not sorted alphabetically within their functional groupings

---

core/src/org/pentaho/di/core/database/DatabaseMeta.java
core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java
ui/src/org/pentaho/di/ui/core/database/wizard/CreateDatabaseWizardPage1.java
ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsController.java
ui/src/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java
ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsControllerTest.java

-fixed, now it trimmed before storing and checked trimmed values

[SP-3735][PDI-16365]-Spaces in connection name can cause unexpected behavior

---

ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java

[BACKLOG-19491] - Parquet Input/output is sorting empty lines and theirs values - remove empty lines before sorting

---

plugins/file-open-save/core/src/main/javascript/app/app.component.js

Master PR: https://github.com/pentaho/pentaho-kettle/pull/4533
8.0.0.0 PR: https://github.com/pentaho/pentaho-kettle/pull/4562

[BACKLOG-19516] Fix for deleting child folders

---

plugins/repositories/core/src/main/resources-filtered/web/pentaho-repository-connect.html
plugins/repositories/core/src/main/resources/web/css/style.css
plugins/repositories/core/src/main/resources/web/lang/messages_en.properties

[BACKLOG-19684] Update the PDI respository login screen

---

ui/src/main/java/org/pentaho/di/ui/trans/step/BaseStepDialog.java

@dkincade , @kcruzada please review.
Master PR: https://github.com/pentaho/pentaho-kettle/pull/4531

[BACKLOG-19241] - Parquet output get fields dialog fixes (#4531)

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/messages/messages_en_US.properties

Depends on https://github.com/pentaho/pentaho-platform/pull/3916

[SP-3843][PDI-14442]-PDI Import scripts are executed in parallel by multiple users

---

engine/src/it/java/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFilesIT.java

BACKLOG-19752 - Fixed failing PDI Integration Tests

---

plugins/file-open-save/core/src/main/javascript/app/components/error/error.component.js

[BACKLOG-18129] fix for no space after job when overwriting file

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/test/java/org/pentaho/di/core/ConstTest.java

[PDI-16573]-In Calculator step, "Remove CR/LF" function does not work

---

plugins/file-open-save/core/src/main/javascript/app/components/error/error.component.js
plugins/file-open-save/core/src/main/javascript/app/components/error/error.css
plugins/file-open-save/core/src/main/javascript/app/components/error/error.html

[BACKLOG-18129] fix for text wrapping in linux

---

engine/src/it/java/org/pentaho/di/job/entries/job/JobEntryJobIT.java
engine/src/it/java/org/pentaho/di/job/entries/zipfile/JobEntryZipFileIT.java

BACKLOG-19752 - Fixed failing tests in JobEntryJobIT and JobEntryZipFileIT

---

engine/src/main/java/org/pentaho/di/trans/steps/replacestring/ReplaceString.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java

@bmorrise , @mbatchelor, @mchen-len-son  please review.

[PDI-16590] - Replace in String: Step processes regular expression even when "Use Regex" option set to N

---

engine/src/main/java/org/pentaho/di/trans/steps/replacestring/ReplaceString.java
engine/src/main/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringData.java
engine/src/main/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringMetaInjectionTest.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/replacestring/ReplaceStringDialog.java

[PDI-16593]-PDI Replace in string : In case of double-byte characters, case sensitive option does not work

---

engine/src/main/java/org/pentaho/di/imp/Import.java
engine/src/main/resources/org/pentaho/di/imp/messages/messages_en_US.properties

[PDI-16591] Able to import Job/Trans to /<root>
-disallow import in root directory via the import tool

[PDI-16591] Able to import Job/Trans to /<root>

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtilsTest.java

[PDI-16579] Text File Input Not Recognized Escaped Characters At End of String
-added supporting escaped escape
@bmorrise Could you please review and merge it?

[PDI-16579] Text File Input Not Recognized Escaped Characters At End of String

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositoryConnectorTest.java

[PDI-16535]-Errors creating transformations and jobs when the user connects to Pentaho Repository using a different case of the user name created

---

engine/src/main/java/org/pentaho/di/core/EngineMetaInterface.java
engine/src/test/java/org/pentaho/di/base/AbstractMetaTest.java
ui/src/main/java/org/pentaho/di/ui/spoon/SpoonSlave.java

[PDI-16684] Every click on the PDI UI sending a request to the Pentaho Server
added default implementation, removed stubs

[PDI-16684] Every click on the PDI UI sending a request to the Pentaho Server

---

engine/src/test/java/org/pentaho/di/concurrency/BaseStepConcurrencyTest.java

[PDI-8934] BaseStep rowListeners - Thread Safety Issue

---

plugins/file-open-save/core/src/main/resources-filtered/app/index.html
plugins/repositories/core/src/main/resources-filtered/web/index.html

[BACKLOG-19912] changed call to require-init to webcontext

---

core/src/org/pentaho/di/core/Const.java
core/test-src/org/pentaho/di/core/ConstTest.java

[SP-3890][PDI-16573]-In Calculator step, "Remove CR/LF" function does  not work

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/test/java/org/pentaho/di/core/ConstTest.java

[SP-3891][PDI-16573]-In Calculator step, "Remove CR/LF" function does not work

---

engine/src/org/pentaho/di/trans/steps/replacestring/ReplaceString.java
engine/src/org/pentaho/di/trans/steps/replacestring/ReplaceStringData.java
engine/src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMeta.java
engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMetaInjectionTest.java
engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java
ui/src/org/pentaho/di/ui/trans/steps/replacestring/ReplaceStringDialog.java

[SP-3896][PDI-16593]-PDI Replace in string : In case of double-byte characters,case sensitive option does not work

---

engine/src/main/java/org/pentaho/di/trans/steps/replacestring/ReplaceString.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java

@mchen-len-son, @stepanovdg please review

[SP-3899] - Backport of PDI-16590 - Replace in String: Step processes  regular expression even when "Use Regex" option set to N (8.0 Suite)

---

.gitignore
engine/src/main/java/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesMod.java

@ccaspanello @baudekin @francisco-guilherme

BACKLOG-20096 - Fixed error with JavaScript failing when run in AEL / Spark.

---

engine/src/main/java/org/pentaho/di/trans/streaming/README.md
engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStep.java
engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMeta.java
engine/src/main/java/org/pentaho/di/trans/streaming/common/FixedTimeStreamWindow.java
engine/src/main/resources/org/pentaho/di/trans/streaming/common/messages_en_US.properties
plugins/file-stream/src/main/java/org/pentaho/di/trans/step/filestream/FileStream.java
plugins/file-stream/src/main/java/org/pentaho/di/trans/step/filestream/FileStreamMeta.java

Defensive null checks, and variable subitution for
FileStream parameters.

[BACKLOG-17271] Minor cleanup.

---

plugins/meta-inject/pom.xml
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInject.java
plugins/meta-inject/src/test/java/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java

[BACKLOG-19596] Auto-save generated meta injection ktrs in the repo, when connected

---

assemblies/pdi-ce/src/main/resources/samples/transformations/meta-inject/use_metainject_step.ktr

- mapping has been fixed in use_metainject_step.ktr

[PDI-16660] Metadata Injection Sample is broken

---

engine/src/main/java/org/pentaho/di/trans/streaming/common/BlockingQueueStreamSource.java
engine/src/main/resources/org/pentaho/di/trans/streaming/common/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/streaming/common/BlockingQueueStreamSourceTest.java

Tightened up thread handling in the BlockingQueueStreamSource.

[BACKLOG-20210] MQTT- create PDI Consumer Step

---

ui/src/org/pentaho/di/ui/trans/steps/multimerge/MultiMergeJoinDialog.java

after repository export/import (7.1 Suite)

[SP-3964]-[PDI-16623] - Unable to open dialog for Multiway Merge Join

---

engine/src/org/pentaho/di/cluster/SlaveServer.java

@mchen-len-son, could you please take a look?

[SP-3968] - additional PR regression fixing

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStream.java
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamData.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamTest.java

What was done:
1) changed unit test

[PDI-16527] - XML Input Stream step re-writes data in fields from previous  steps

---

engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputStep.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

@bmorrise, @mchen-len-son please review

[PDI-16697] - Error reading file in Text File Input step causes trans formation to fail when "Skip error files?" and error handling is enabled

---

plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforceinput/SalesforceInput.java
plugins/salesforce/core/src/main/java/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java
plugins/salesforce/core/src/test/java/org/pentaho/di/trans/steps/salesforceinput/SalesforceInputTest.java

[PDI-16685] Salesforce Document Table Insert or Update - Base64 field
- added correcting detecting a binary field in a Salesforce Input step
- added correcting reading a binary data
@bmorrise Could you please review and merge it?

[PDI-16685] Salesforce Document Table Insert or Update - Base64 field

---

engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInput.java

- fix for the found regression

[PDI-14296] Load File Content in Memory corrupts data read from binary files

---

engine/src/org/pentaho/di/trans/steps/loadfileinput/LoadFileInput.java

- fix for the found regression

[SP-4001] Backport of PDI-14296 - Load File Content in Memory corrupts data read from binary files (7.1 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInput.java

- fix for the found regression

[SP-4002] Backport of PDI-14296 - Load File Content in Memory corrupts data read from binary files (8.0 Suite)

---

plugins/s3csvinput/pom.xml

Associated with:
https://github.com/pentaho/pentaho-s3-vfs/pull/30
https://github.com/pentaho/big-data-plugin/pull/1234

[BACKLOG-20908] Upgrade jets3t to version 0.9.4

---

plugins/salesforce/core/src/main/java/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java

[PDI-16805] Salesforce Input doesn't get the transformation status 'changed'
- added status 'changed' when button 'Get fields' is pressed

[PDI-16805] Salesforce Input doesn't get the transformation status 'changed'

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java

[PDI-16790]-Miscalculation with big number data type in calculator step

---

dbdialog/pom.xml
plugins/lucid-db-bulk-loader/build.properties
plugins/pur/core/pom.xml
plugins/ssh2/build.properties
plugins/star-modeler/build.properties
plugins/star-modeler/ivy.xml
pom.xml
ui/pom.xml

@pentaho/2-1b 
Depends on https://github.com/pentaho/pentaho-commons-xul/pull/143

[BACKLOG-20423] Update downstreams

---

assemblies/pdi-ce/pom.xml
engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMeta.java
engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMetaTest.java

Move retrieving the Resource Dependencies to Base Stream Meta.
Put libraries in the appropriate spots for AEL/Spark.

[BACKLOG-20859] Run MQTT Step in AEL/Spark

---

plugins/star-modeler/ivy.xml

@pentaho/2-1b gav change
for pentaho/pentaho-metadata/pull/186

[BACKLOG-13306] GAV change

---

core/src/main/java/org/pentaho/di/core/encryption/TwoWayPasswordEncoderPluginType.java
core/src/main/java/org/pentaho/di/core/extension/ExtensionPointPluginType.java
core/src/main/java/org/pentaho/di/core/logging/LoggingPluginType.java
core/src/main/java/org/pentaho/di/core/plugins/BasePluginType.java
core/src/main/java/org/pentaho/di/core/plugins/DatabasePluginType.java
core/src/main/java/org/pentaho/di/core/plugins/PluginRegistryPluginType.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaPluginType.java
core/src/test/java/org/pentaho/di/core/plugins/BasePluginTypeTest.java
engine/src/main/java/org/pentaho/di/core/auth/AuthenticationProviderPluginType.java
engine/src/main/java/org/pentaho/di/core/compress/CompressionPluginType.java
engine/src/main/java/org/pentaho/di/core/plugins/CartePluginType.java
engine/src/main/java/org/pentaho/di/core/plugins/EnginePluginType.java
engine/src/main/java/org/pentaho/di/core/plugins/ImportRulePluginType.java
engine/src/main/java/org/pentaho/di/core/plugins/JobEntryPluginType.java
engine/src/main/java/org/pentaho/di/core/plugins/KettleLifecyclePluginType.java
engine/src/main/java/org/pentaho/di/core/plugins/PartitionerPluginType.java
engine/src/main/java/org/pentaho/di/core/plugins/RepositoryPluginType.java
engine/src/main/java/org/pentaho/di/core/plugins/StepPluginType.java

- The implementation of the registerNatives() method has been moved to the BasePluginType class
- New parameters for correct work of registerNatives() method have been added in inheritors of BasePluginType class

[PDI-16269] registerNatives() method fails to close streams

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmloutput/XMLOutput.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmloutput/XMLOutputTest.java

[PDI-16769]-XML Output locks the file so it cannot be deleted in next step

---

plugins/s3csvinput/core/pom.xml
plugins/s3csvinput/core/src/main/java/org/pentaho/di/trans/steps/s3csvinput/S3CsvInput.java
plugins/s3csvinput/core/src/main/java/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputData.java
plugins/s3csvinput/core/src/main/java/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputDialog.java
plugins/s3csvinput/core/src/main/java/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta.java
plugins/s3csvinput/core/src/main/java/org/pentaho/di/trans/steps/s3csvinput/S3ObjectsProvider.java
plugins/s3csvinput/core/src/main/resources/org/pentaho/di/trans/steps/s3csvinput/messages/messages_en_US.properties
plugins/s3csvinput/core/src/test/java/org/pentaho/di/trans/steps/s3csvinput/S3ObjectsProviderTest.java

[PDI-16813]: Request Error: Invalid class name: org.jets3t.service.utils.RestUtils$ConnManagerFactory when connecting to Amazon S3 bucket in PDI 8.0

---

engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMeta.java
engine/src/main/resources/org/pentaho/di/trans/streaming/common/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMetaTest.java

Reverts pentaho/pentaho-kettle#4834

Revert "[BACKLOG-21055] - open referenced trans for streaming steps"

---

core/src/main/java/org/pentaho/di/core/row/RowMeta.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/test/java/org/pentaho/di/trans/TransMetaTest.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/job/JobGraph.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java
ui/src/main/java/org/pentaho/di/ui/trans/dialog/TransHopDialog.java

6a5370073ab9d4b6f18f36abce89d9f0302bdefc 30fc3fc338d3f9d89a5444c802c8106e8de3216a 6cf0f2eff9fa762a51ea9bd72672cfbc2521dd0d

[CLEANUP] Reverts commits

---

core/src/main/java/org/pentaho/di/core/util/EncodeUtil.java
core/src/test/java/org/pentaho/di/core/util/EncodeUtilTest.java
engine-ext/api/pom.xml
engine-ext/api/src/main/java/org/pentaho/di/engine/api/remote/MessageDecoder.java
engine-ext/api/src/main/java/org/pentaho/di/engine/api/remote/MessageEncoder.java

@ccaspanello @flbrino @baudekin

BACKLOG-21021 - reduced AEL WebSocket message sizes by gziping Message objects.  Reduced by 80%

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStream.java
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamData.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamTest.java

steps
What was done:
1) changed ubit test

[SP-4043][PDI-16527] - XML Input Stream step re-writes data in fields from previous

---

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinput/SalesforceInput.java
plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinput/SalesforceInputTest.java

[Sp-4048][PDI-16685] Salesforce Document Table Insert or Update - Base64 field
- added correcting detecting a binary field in a Salesforce Input step
- added correcting reading a binary data

[Sp-4048][PDI-16685] Salesforce Document Table Insert or Update - Base64 field

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java

[SP-4064][PDI-16790]-Miscalculation with big number data type in calculator step

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmloutput/XMLOutput.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmloutput/XMLOutputTest.java

[SP-4088][PDI-16769]-XML Output locks the file so it cannot be deleted in next step

---

core/src/org/pentaho/di/core/row/ValueDataUtil.java
core/test-src/org/pentaho/di/core/row/ValueDateUtilTest.java

[SP-4063][PDI-16790]-Miscalculation with big number data type in calculator step

---

plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmloutput/XMLOutput.java
plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/xmloutput/XMLOutputTest.java

[SP-4087][PDI-16769]-XML Output locks the file so it cannot be deleted in next step

---

plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java

- added status 'changed' when button 'Get fields' is pressed
- added status 'changed' for checkboxes of tab Content if they are changed

[SP-4065][PDI-16805] Salesforce Input doesn't get the transformation status 'changed'

---

ui/src/main/java/org/pentaho/di/ui/core/widget/StyledTextComp.java

UXD has asked that we place the "variable support" icon ABOVE the splunk query text area within the  Splunk Input Step, rather to the right of it, and in its current form, the `StyledTextComp` does not support this, due to the fact that images cannot be placed above the text component when the `ControlDecoration` wrapper is used. I discussed this with @ddiroma and he approves of this approach.
@pentaho/r2d2

[BACKLOG-21096] Add ability to place the 'variable support' icon above StyledTextComp'

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/SimpleMessageDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/dialog/TransPreviewProgressDialog.java

...row preview progress from the caller and a SimpleMessageDialog
@pentaho/r2d2

[BACKLOG-21096] Adding ability to control error dialogs related to

---

dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java

-changed from 5 empty patameters to 15 by default

[PDI-16678]-database connection > option section - can't add more than 4 parameters

---

engine/src/main/resources/org/pentaho/di/trans/step/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/core/ConstUI.java
ui/src/main/java/org/pentaho/di/ui/trans/step/common/CommonStepDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/step/common/CommonStepMeta.java

[BACKLOG-21097] Added common step dialog components in preparation for BACKLOG-21097

---

ui/src/main/java/org/pentaho/di/ui/core/ConstUI.java
ui/src/main/java/org/pentaho/di/ui/core/widget/StyledTextComp.java
ui/src/main/java/org/pentaho/di/ui/trans/step/common/CommonStepDialog.java

[BACKLOG-21368] Fixing minor UI issues with the Splunk Input and Output steps

---

assemblies/lib/pom.xml
engine/pom.xml

@pentaho/2-1b 
Depends on https://github.com/pentaho/pentaho-registry/pull/11

[BACKLOG-13943] Downstream updates

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStream.java
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamData.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamTest.java

What was done:
1) changed unit test

[PDI-16527] - XML Input Stream step re-writes data in fields from previous steps

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStream.java
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamData.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamTest.java

What was done:
1) changed ubit test

[SP-4043][PDI-16527] - XML Input Stream step re-writes data in fields from previous steps

---

engine/src/main/java/org/pentaho/di/trans/steps/mappingoutput/MappingOutputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/mapping/MappingOutputMetaIT.java

[PDI-16382]-Select Values Step Throws Errors when multiple fields with

---

engine-ext/api/pom.xml
engine-ext/api/src/main/java/org/pentaho/di/engine/api/remote/EncodeUtil.java
engine-ext/api/src/main/java/org/pentaho/di/engine/api/remote/MessageDecoder.java
engine-ext/api/src/main/java/org/pentaho/di/engine/api/remote/MessageEncoder.java
engine-ext/api/src/test/java/org/pentaho/di/engine/api/remote/EncodeUtilTest.java

@pentaho-jrice / @baudekin / @flbrino / @apreto

[BACKLOG-21021] Removed circular dependency

---

plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStream.java
plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamData.java
plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamTest.java

What was done:
1) changed unit test

[SP-4042][PDI-16527] - XML Input Stream step re-writes data in fields from previous steps

---

engine/src/main/java/org/pentaho/di/trans/step/BaseStep.java
engine/src/test/java/org/pentaho/di/trans/step/BaseStepTest.java

[PDI-16653] - Safe Mode does not error out like it is supposed to in 7.1

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java

[BACKLOG-20802] Fix null pointer exception

---

assemblies/lib/pom.xml

@pentaho/2-1b  Aligning dependencies for pdi-ee

[BACKLOG-16972] pdi-ee mavenization cleanup

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java
plugins/pur/core/src/main/resources/org/pentaho/di/repository/pur/messages/messages_en_US.properties

@ddiroma, @mbatchelor, @pamval, could you please take a look?

[BACKLOG-20667] - Logging PurRepositoryConnector in appropriate way

---

engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMeta.java
engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMetaTest.java

BaseStreamMeta xml serialization will now use a group tag
if the attribute is part of a injection group.
This will be used to bucket SSL properties under a <SSL> tag.
https://jira.pentaho.com/browse/BACKLOG-21243

[BACKLOG-21243] MQTT Consumer - SSL

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/main/java/org/pentaho/di/trans/steps/calculator/Calculator.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java
engine/src/test/java/org/pentaho/di/trans/steps/calculator/CalculatorUnitTest.java

- fixed. now source values convert to the target data type before calculation

[PDI-16891]-Incorrect remainder in division of numbers in Calculator step

---

assemblies/lib/pom.xml

@pentaho/x-wing 
Depends on https://github.com/pentaho/pentaho-commons-database/pull/149

[BACKLOG-20414] pentaho-commons-database downstream update

---

engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java

[PDI-16927]: PostgreSQL Bulk Loader : "DB Name Override" option is not working as expected.

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java
engine/src/test/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheetTest.java

- support of inline strings was added
- test was added

[PDI-16910] Excel Input does not work when reading from an XLSX created by the MSSQL report

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
core/src/main/java/org/pentaho/di/core/util/PentahoJaroWinklerDistance.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java

[PDI-16904]-Calculator step : The result of Jaro similitude and JaroWinkler similitude formula's are showing incorrect values.

---

plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/pentaho/DefaultRunConfigurationExecutor.java
plugins/pdi-engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/pentaho/DefaultRunConfigurationExecutorTest.java

fixing the issue with remote execution

[BACKLOG-21573] Fix for sending resources to server

---

plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/pentaho/DefaultRunConfigurationExecutor.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/pentaho/DefaultRunConfigurationExecutorTest.java

[Sp-4177]-Backport of BACKLOG-21573 - Kafka - When creating a slave server connection to run the Kafka consumer Ktr it is finishing with errors

---

engine/src/main/java/org/pentaho/di/www/BaseCartePlugin.java
engine/src/main/java/org/pentaho/di/www/CarteServlet.java
engine/src/main/java/org/pentaho/di/www/GetRootServlet.java
engine/src/main/java/org/pentaho/di/www/NextSequenceValueServlet.java
engine/src/test/java/org/pentaho/di/www/GetRootServletTest.java

Linked with https://github.com/pentaho/pentaho-platform-ee/pull/1247 https://github.com/pentaho/pentaho-platform/pull/4052

[BISERVER-13757]-404 error handling for pentaho/getImage?image=... call

---

dbdialog/src/org/pentaho/ui/database/event/DataHandler.java

[SP-4116][PDI-16678]-database connection > option section - can't add more than 4 parameters

---

dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java

-changed from 5 empty patameters to 15 by default

[SP-4117][PDI-16678]-database connection > option section - can't add more than 4 parameters

---

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsert.java
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsertTest.java

[SP-4089][PDI-16857] External Id doesn't work in the step Salesforce upsert.
- fixed sending Foreign key for Salesforce upsert step

[SP-4089][PDI-16857] External Id doesn't work in the step Salesforce upsert.

---

core/pom.xml
core/src/main/java/org/pentaho/di/core/logging/LogMessage.java
core/src/main/java/org/pentaho/di/core/util/StringUtil.java
core/src/test/java/org/pentaho/di/core/logging/LogMessageTest.java
core/src/test/java/org/pentaho/di/core/util/StringUtilTest.java
core/src/test/java/org/pentaho/di/core/xml/XMLFormatterTest.java
engine/pom.xml
engine/src/main/java/org/pentaho/di/job/JobExecutionConfiguration.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/org/pentaho/di/job/entries/trans/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMetaTest.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java
plugins/pur/core/src/main/resources/org/pentaho/di/repository/pur/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialog.java

Additionally, I fixed a few unrelated unit tests that were failing on my windows box - replacing the xml comparison with an approach that is platform independent.
@pentaho/r2d2

[BACKLOG-21756] Handling of 'Trans Job Entry > Transformation' field

---

ui/src/main/resources/org/pentaho/di/ui/trans/step/messages/messages_en_US.properties

[CLEANUP] Missing colon.

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java
ui/src/main/java/org/pentaho/di/ui/trans/dialog/TransHopDialog.java

- added cache invalidation on changing trans hop`s state

[PDI-16818] Improvements to RowMeta have slowed down again in 7.x+

---

assemblies/lib/pom.xml
assemblies/static/src/main/resources/classes/log4j.xml
core/src/main/java/org/pentaho/di/core/logging/Slf4jLoggingEventListener.java
core/src/test/java/org/pentaho/di/core/logging/Slf4jLoggingEventListenerTest.java

- Map PDI log level to log4j threshold.
- Update format of the log entry.

[BACKLOG-21882] - Enable pdi log to roll to next day.

---

plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationInjectExtensionPoint.java

@VasilinaTerehova please take a view and merge

[BACKLOG-21581]-Yarn job fails to run remotely on Pentaho server

---

engine/pom.xml
engine/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java
engine/src/main/java/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
engine/src/test/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheetTest.java
engine/src/test/java/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep_StyleFormatTest.java
plugins/json/core/pom.xml
plugins/xml/pom.xml

@duarteteixeira @pamval @mbatchelor @bmorrise

[PPP-4019] Use of vulnerable component Apache POI 3.15 CVE-2017-12626

---

core/src/main/java/org/pentaho/di/core/row/RowMeta.java
core/src/test/java/org/pentaho/di/core/row/RowMetaTest.java

- fixed. changed Arrays.hashCode->Arrays.deepHashCode

[PDI-16562]-Comparison of Binary fields of same length and value fails

---

core/src/main/resources/org/pentaho/di/i18n/messages/messages_en_US.properties
engine/src/main/java/org/pentaho/di/core/LastUsedFile.java
plugins/file-open-save/core/src/main/javascript/app/components/error/error.component.js
plugins/file-open-save/core/src/main/resources/i18n/file-open-save/messages_en.properties
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties
ui/src/test/java/org/pentaho/di/ui/spoon/SpoonTest.java

[BACKLOG-18455] Handing of missing recent files: updates based on UX vision and minor fixes

---

core/src/main/java/org/pentaho/di/core/util/EnvUtil.java
core/src/test/java/org/pentaho/di/core/util/EnvUtilTest.java
engine/src/test/java/org/pentaho/di/trans/LoadSaveTester.java
engine/src/test/java/org/pentaho/di/trans/steps/loadsave/LoadSaveTester.java

[BACKLOG-16710] - fixes EnvUtil for locales with variants.

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/main/resources/org/pentaho/di/job/entries/trans/messages/messages_en_US.properties
engine/src/main/resources/org/pentaho/di/trans/messages/messages_en_US.properties
plugins/pur/core/src/main/resources/org/pentaho/di/repository/pur/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/spoon/JobFileListener.java

[BACKLOG-21756] Additional log changes and minor fixes

---

engine/src/main/java/org/pentaho/di/trans/TransMeta.java

- getPrevSteps should also be using step meta cache keys

[BACKLOG-22072] DET / DataServices not working with Stream Lookup step

---

core/src/main/java/org/pentaho/di/core/util/StringUtil.java
core/src/test/java/org/pentaho/di/core/util/StringUtilTest.java
engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputMeta.java
plugins/json/core/pom.xml
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzer.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerPluginLifecycleListener.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputExternalResourceConsumer.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerTest.java

[BACKLOG-21736] Adding a data-lineage analyzer for the JSON Input step

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

- partial backport of BACKLOG-18754

[SP-4104] Backport of PDI-16804 - DET charts can show no data, when it should show data (7.1 Suite)

---

plugins/streaming/impls/jms/pom.xml
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsConsumer.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsDelegate.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsStreamSource.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsConsumerDialog.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/JmsStreamSourceTest.java

Plus fieldname meta for message / destination.

[BACKLOG-21800] JMS Consumer - Support for receive timeout

---

integration/pom.xml
integration/src/it/java/org/pentaho/test/util/FieldAccessorUtl.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/test/java/org/pentaho/di/ui/spoon/SpoonTest.java

Also fixed an unrelated failing unit test
@pentaho/r2d2

[BACKLOG-22284] Unable to open file through 'File > Open URL' menu

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
core/src/main/java/org/pentaho/di/core/util/PentahoJaroWinklerDistance.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java

[SP-4184][PDI-16904]-Calculator step : The result of Jaro similitude and JaroWinkler similitude formula's are showing incorrect values.

---

core/src/main/java/org/pentaho/di/core/row/RowMeta.java
core/src/test/java/org/pentaho/di/core/row/RowMetaTest.java

- fixed. changed Arrays.hashCode->Arrays.deepHashCode

[SP-4207][PDI-16562]-Comparison of Binary fields of same length and value fails

---

core/src/org/pentaho/di/core/row/RowMeta.java
core/test-src/org/pentaho/di/core/row/RowMetaTest.java

- fixed. changed Arrays.hashCode->Arrays.deepHashCode

[SP-4208][PDI-16562]-Comparison of Binary fields of same length and value fails

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java
engine/src/test/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheetTest.java

[SP-4182] Backport of PDI-16910 - Excel Input does not work when reading from an XLSX created by the MSSQL report (8.0 Suite)

---

core/src/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/org/pentaho/di/trans/steps/calculator/Calculator.java
engine/test-src/org/pentaho/di/core/row/ValueDataUtilTest.java
engine/test-src/org/pentaho/di/trans/steps/calculator/CalculatorUnitTest.java

- fixed. now source values convert to the target data type before
calculation

[SP-4193][PDI-16891]-Incorrect remainder in division of numbers in Calculator step

---

core/src/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/org/pentaho/di/trans/steps/calculator/Calculator.java
engine/test-src/org/pentaho/di/core/row/ValueDataUtilTest.java
engine/test-src/org/pentaho/di/trans/steps/calculator/CalculatorUnitTest.java

Reverts pentaho/pentaho-kettle#5120
Oddly, the PR showed that tests had passed, but upon merging, it shows checkstyle violations. Please resubmit PR and fix checkstyle.

Revert "[SP-4193][PDI-16891]-Incorrect remainder in division of numbers in Calculator step"

---

engine/src/main/java/org/pentaho/di/core/changed/ChangedFlag.java
engine/src/test/java/org/pentaho/di/base/AbstractMetaTest.java

-changed according Marc Batchelor comment

[PDI-17077]-Erroneous Synchronization in ChangedFlag.java

---

engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputFiles.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMetaTest.java

option "Run resulting transformation" is unchecked

[PDI-16986] - Metadata Injection: Get "index out of bound" error when

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducer.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducerMeta.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsProducerDialog.java
plugins/streaming/impls/jms/src/main/resources/JMSP.svg
plugins/streaming/impls/jms/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugins/streaming/impls/jms/src/main/resources/org/pentaho/di/trans/step/jms/messages/messages_en_US.properties

[BACKLOG-21859] Implement JMS Producer for IBM MQ - UI and function

[BACKLOG-21859] Implement JMS Producer for IBM MQ - UI and function

---

engine/src/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java
engine/test-src/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheetTest.java

[SP-4181] Backport of PDI-16910 - Excel Input does not work when reading from an XLSX created by the MSSQL report (7.1 Suite)

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/main/java/org/pentaho/di/trans/steps/calculator/Calculator.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java
engine/src/test/java/org/pentaho/di/trans/steps/calculator/CalculatorUnitTest.java

- fixed. now source values convert to the target data type before calculation

[SP-4194][PDI-16891]-Incorrect remainder in division of numbers in Calculator step

---

ui/src/main/java/org/pentaho/di/core/dnd/DragAndDropContainer.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonTreeDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java
ui/src/test/java/org/pentaho/di/core/dnd/DragAndDropContainerTest.java
ui/src/test/java/org/pentaho/di/ui/spoon/delegates/SpoonTreeDelegateTest.java

Please review and merge if OK.
@bmorrise @pamval @mbatchelor @duarteteixeira

[PDI-17076] AvroOutput step clashes with Marketplace AvroOutput

---

core/src/org/pentaho/di/core/row/ValueDataUtil.java
core/src/org/pentaho/di/core/util/PentahoJaroWinklerDistance.java
engine/test-src/org/pentaho/di/core/row/ValueDataUtilTest.java

[SP-4183][PDI-16904]-Calculator step : The result of Jaro similitude and JaroWinkler similitude formula's are showing incorrect values.

---

engine/src/org/pentaho/di/core/logging/BaseLogTable.java

[SP-4228][PDI-16858] Log connection is set to 'live_logging_info' on Transformation and Job logging

---

engine/src/main/java/org/pentaho/di/core/logging/BaseLogTable.java

[SP-4229][PDI-16858] Log connection is set to 'live_logging_info' on Transformation and Job logging

---

ui/src/main/java/org/pentaho/di/ui/core/widget/ComboVar.java
ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java

[BACKLOG-22283] Revert to functionality where table comboVars show variable icon in cell when selected and not outside of table

[BACKLOG-22283] Revert to functionality where table comboVars show variable icon in cell when selected and not outside of table

---

core/src/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/org/pentaho/di/trans/steps/calculator/Calculator.java
engine/test-src/org/pentaho/di/core/row/ValueDataUtilTest.java
engine/test-src/org/pentaho/di/trans/steps/calculator/CalculatorUnitTest.java

- fixed. now source values convert to the target data type before calculation.

[SP-4193][PDI-16891]-Incorrect remainder in division of numbers in Calculator step 

---

engine/src/main/java/org/pentaho/di/cluster/SlaveServer.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/www/GetTransStatusServlet.java
engine/src/main/java/org/pentaho/di/www/SlaveServerTransStatus.java
engine/src/test/java/org/pentaho/di/www/SlaveServerTransStatusTest.java

[SP-4253][PDI-17061] 'Get rows from result' step does not pass rows when a transformation is executed on a remote carte server

---

core/src/main/java/org/pentaho/di/core/RowMetaAndData.java

Reverts pentaho/pentaho-kettle#5166

Revert "[BACKLOG-21321] Avro Streaming enhancments ( pass fields from prior s…"

---

core/src/main/java/org/pentaho/di/core/RowMetaAndData.java

Reverts pentaho/pentaho-kettle#5169

[BACKLOG-21321] Avro Streaming enhancements 

---

engine/src/org/pentaho/di/cluster/SlaveServer.java
engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/org/pentaho/di/www/GetTransStatusServlet.java
engine/src/org/pentaho/di/www/SlaveServerTransStatus.java
engine/src/org/pentaho/di/www/cache/CachedItem.java
engine/src/org/pentaho/di/www/cache/CarteStatusCache.java
engine/test-src/org/pentaho/di/www/SlaveServerTransStatusTest.java

[SP-4252][PDI-17061] 'Get rows from result' step does not pass rows when a transformation is executed on a remote carte server

---

plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSumMeta.java

Fix for dialog type descriptions

[BACKLOG-22182] Checksum Decouple

---

engine/src/main/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariables.java
engine/src/test/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java

does not reset variables or parameters with every execution

revert [SP-4164][PDI-16387] Running a Job for Every Input Row, sub job

---

engine/src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariables.java
engine/test-src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java

does not reset variables or parameters with every execution

revert [SP-4165][PDI-16387] Running a Job for Every Input Row, sub job

---

engine/src/main/java/org/pentaho/di/core/util/serialization/ConfigHelper.java
engine/src/test/java/org/pentaho/di/core/util/serialization/ConfigHelperTest.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducer.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducerMeta.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsProducerDialog.java
plugins/streaming/impls/jms/src/main/resources/org/pentaho/di/trans/step/jms/messages/messages_en_US.properties
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/context/ActiveMQProviderTest.java
plugins/streaming/impls/jms/src/test/resources/amq-producer.ktr
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMeta.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMeta.java

[BACKLOG-22165] JMS Producer add user defined properties tab and table

[BACKLOG-22165] JMS Producer add user defined properties tab and table

---

engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileOutputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/file/BaseFileOutputMetaTest.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/JsonOutput.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/JsonOutputMeta.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzer.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzerPluginLifecycleListener.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputExternalResourceConsumer.java
plugins/json/core/src/main/java/org/pentaho/di/ui/trans/steps/jsonoutput/JsonOutputDialog.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerTest.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzerTest.java

In addition to adding the analyzer, some re-factoring was done to pull common functionality into a base class, to allow further expansion of the new features to other output steps.
@pentaho/r2d2

[BACKLOG-21738] Adding a data-lineage analyzer for the JSON Output step

---

engine/src/main/java/org/pentaho/di/trans/step/BaseStep.java

- replaced synchronized with read write locks

[PDI-16921] Concurrent access to outputRowSets in Mapping Init

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducerMeta.java

[BACKLOG-22165] Removing sorting of JmsProducer properties

[BACKLOG-22165] Removing sorting of JmsProducer properties

---

plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerTest.java

related PR: https://github.com/pentaho/pentaho-metaverse/pull/459
@pentaho/r2d2

[BACKLOG-21738][CLEANUP][TEST] Additional minor changes and added unit tests

---

engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMeta.java
engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMetaTest.java

sub step needed env substitution in the getFields() method.
https://jira.pentaho.com/browse/BACKLOG-22575

[BACKLOG-22575]JMS- No data in Preview when param in "Ret fields from"

---

plugins/repositories/core/src/main/javascript/app/components/shared/connect/connect.component.js

[BACKLOG-22273] Remove admin as default

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducer.java

[BACKLOG-22165 Added debug logging of JmsProducer properties

[BACKLOG-22165 Added debug logging of JmsProducer properties

---

engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/test/java/org/pentaho/di/trans/TransMetaTest.java

Related PR: https://github.com/pentaho/pentaho-metaverse/pull/460
@pentaho/r2d2

[BACKLOG-22731] Fix Stream Lookup analyzer and failing integration test

---

plugins/file-open-save/core/src/main/javascript/app/app.css
plugins/file-open-save/core/src/main/javascript/app/app.html

[BACKLOG-22758] Thin Save dialog missing "New folder" control

---

engine/src/main/java/org/pentaho/di/core/util/serialization/StepMetaProps.java
engine/src/test/java/org/pentaho/di/core/util/serialization/StepMetaPropsTest.java

Formerly the @Sensitive annotation only applied to top level
attributes, not those within an @InjectionDeep property.
https://jira.pentaho.com/browse/BACKLOG-22766

[BACKLOG-22766] Applying encryption to nested attributes in meta

---

engine/src/main/java/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/BOMDetector.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java

[PDI-17113]-CSV input step with UTF-8 encoding still reads BOM as data

---

core/src/main/java/org/pentaho/di/core/plugins/KettleURLClassLoader.java
core/src/main/resources/org/pentaho/di/core/plugins/messages/messages_en_US.properties

Reverts pentaho/pentaho-kettle#5137

Revert "[SP-4170] - Backport of PDI-16884 - Cassandra Output step does not wo…"

---

assemblies/static/src/main/resources/spoon.sh

[BACKLOG-22728] - DET - Segmentation Fault while using Select filter on Ubuntu

---

engine/src/main/java/org/pentaho/di/job/Job.java

[BACKLOG-22837] Fix for ConcurrentModificationException in job with multiple job or transformation entries

---

core/src/main/java/org/pentaho/di/core/row/ValueMetaInterface.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaStringTest.java
ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java

[BACKLOG-21186] Fixed sorting step metrics

[BACKLOG-21186] Fixed sorting step metrics

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/LazyUnifiedRepositoryDirectory.java
ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseController.java
ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/model/UIRepositoryDirectory.java
ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/model/UIRepositoryObject.java
ui/src/main/resources/org/pentaho/di/ui/repository/repositoryexplorer/xul/explorer-layout.xul
ui/src/test/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseControllerTest.java
ui/src/test/java/org/pentaho/di/ui/repository/repositoryexplorer/model/UIRepositoryDirectoryTest.java

https://github.com/pentaho/pentaho-commons-xul/pull/147

[BACKLOG-22287] Lazy loading of folders in Repository Explorer

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java
engine/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxUtil.java
engine/src/test/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheetTest.java

[PDI-17110]: Excel Input cannot process Cognos generated Excel report

---

engine/src/main/java/org/pentaho/di/www/cache/CarteStatusCache.java

Use daemon threads to avoid blocking shutdown. Switching the thread launched to be daemon otherwise it blocks the pentaho server shutdown. Also naming the thread created with class name to make tracking of threads easy
Testing : tested with QAT-352. Replaced kettle-engine jar and verified that the server stops and process goes away.
@pentaho/rogueone @pamval @kcruzada @dkincade

BACKLOG-22955 : Create daemon threads for CarteStatusCache

---

engine/src/main/java/org/pentaho/di/www/cache/CarteStatusCache.java

Cherry picked fix for 8.1.0.0 Branch. Use daemon threads to avoid blocking shutdown. 
This fix is for BACKLOG-22955 - Pentaho Server fails to stop after it’s been used to run a transformation    
Won’t Hold Code Freeze - Not a regression occurs in 8.0.  This should be investigated further to see if something can be done.
master PR : https://github.com/pentaho/pentaho-kettle/pull/5293
@pentaho/rogueone @kcruzada @dkincade @pamval

BACKLOG-22955 : 8.1.0.0 - Create daemon threads for CarteStatusCache (#5293)

---

engine/src/main/java/org/pentaho/di/www/cache/CarteStatusCache.java

Cherry picked fix for 8.1 Branch. Use daemon threads to avoid blocking shutdown. 
This fix is for BACKLOG-22955 - Pentaho Server fails to stop after it’s been used to run a transformation    
Won’t Hold Code Freeze - Not a regression occurs in 8.0.  This should be investigated further to see if something can be done.
master PR : https://github.com/pentaho/pentaho-kettle/pull/5293
@pentaho/rogueone @kcruzada @dkincade @pamval

BACKLOG-22955 : 8.1 branch Create daemon threads for CarteStatusCache (#5293)

---

engine/src/main/resources/org/pentaho/di/job/entries/special/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/job/entries/special/JobEntrySpecialDialog.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java

[PDI-16229]-Dummy job entry can not be opened/renamed.

---

engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputStep.java
engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputStepData.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

[PDI-17117]-"Text file input" step picks up the last file in order when supplies with 2 files of same names

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index.html

[BACKLOG-23018] Update references to pentaho.com

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsConsumerMeta.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducerMeta.java

…ep, JMS Producer step, Amazon EMR Job Executor entry, and Amazon Hive Job entry

Help Links need to be created for the JMS Consumer step, JMS Producer step, Amazon EMR Job Executor entry, and Amazon Hive Job entry 

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsConsumerMeta.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducerMeta.java

…ep, JMS Producer step, Amazon EMR Job Executor entry, and Amazon Hive Job entry

Help Links need to be created for the JMS Consumer step, JMS Producer step, Amazon EMR Job Executor entry, and Amazon Hive Job entry

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/ShowHelpDialog.java

Fixes a compilation issue with the big-data-plugin repository.

[BACKLOG-22112] Improvements to documentation dialog in PDI (#5318)

---

plugins/json/core/pom.xml

@emartin-pentaho @pentaho-amessier

[CLEANUP] fix metaverse version prop

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaString.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java
ui/src/test/java/org/pentaho/di/ui/spoon/trans/TransGridDelegateTest.java

[BACKLOG-22898] Implement step metrics sub step sorting

[BACKLOG-22898] Implement step metrics sub step sorting

---

plugins/openerp/core/src/main/java/org/pentaho/di/openerp/core/OpenERPHelper.java

[BACKLOG-22406] copyright correction

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java

- added configurable parameter of max length of tab

[PDI-16890]-UI Glitch on tab name

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/test/java/org/pentaho/di/trans/StepWithMappingMetaTest.java

[PDI-17119] Mapping (sub transformation) step : Using variables/parameters in the parent transformation to resolve the sub-transformation name
- added resolving a child file name via a parent space

[PDI-17119] Mapping (sub transformation) step : Using variables/parameters in the parent transformation to resolve the sub-transformation name

---

engine/src/main/java/org/pentaho/di/trans/steps/httppost/HTTPPOST.java

[PDI-17108] HTTP Post step fails Digest Based Authentication

---

engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputStep.java
engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputStepData.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

[SP-4327][PDI-17117]-"Text file input" step picks up the last file in order when supplies with 2 files of same names

---

engine/src/main/resources/org/pentaho/di/job/entries/special/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/job/entries/special/JobEntrySpecialDialog.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java

[SP-4322][PDI-16229]-Dummy job entry can not be opened/renamed.

---

engine/src/org/pentaho/di/job/entries/special/messages/messages_en_US.properties
ui/src/org/pentaho/di/ui/job/entries/special/JobEntrySpecialDialog.java
ui/src/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java

[SP-4321][PDI-16229]-Dummy job entry can not be opened/renamed.

---

core/src/org/pentaho/di/core/Const.java
engine/src/kettle-variables.xml
ui/src/org/pentaho/di/ui/spoon/delegates/SpoonDelegate.java
ui/src/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java
ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java

-added configurable parameter of max length of tab

[SP-4339][PDI-16890]-UI Glitch on tab name

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java

- added configurable parameter of max length of tab

[SP-4340][PDI-16890]-UI Glitch on tab name

---

engine/src/main/java/org/pentaho/di/trans/steps/setvaluefield/SetValueField.java
engine/src/main/java/org/pentaho/di/trans/steps/setvaluefield/SetValueFieldMeta.java
engine/src/main/resources/org/pentaho/di/trans/steps/setvaluefield/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/steps/setvaluefield/SetValueFieldMetaInjectionTest.java

[BACKLOG-23396] Adds metadata injection to Set Field Value step

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties

https://jira.pentaho.com/browse/BACKLOG-23011

[BACKLOG-23011] Prevent force stop after a safe stop has been started

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties

To reduce code footprint and allow for consistent changes if needed.

[CLEANUP]  Extracting calls to pop a message dialog in TransGraph

---

ui/src/main/java/org/pentaho/di/ui/core/WidgetUtils.java

https://jira.pentaho.com/browse/BACKLOG-23645

[BACKLOG-23645] Static helper methods for creating fields drop down.

---

plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerDialog.java

Ux tweaks, plus adding hooks to set meta changed state.
https://jira.pentaho.com/browse/BACKLOG-23645

[BACKLOG-23645] MQTT Prod - support for fields in topic

---

plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerDialog.java

https://jira.pentaho.com/browse/BACKLOG-23645

[BACKLOG-23645] MQTT Prod - Ux tweaks to improve appearance in Win10

---

plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerDialog.java

https://jira.pentaho.com/browse/BACKLOG-23645

[BACKLOG-23645] Hopefully final UI tweak.

---

engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java

Changed to LinkedHashMap to ensure insert order
@pentaho-lmartins @pamval @bmorrise @mbatchelor

[PDI-17377] Trans Executor mixes parameter values

---

engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/test/java/org/pentaho/di/trans/TransTest.java

Non-input steps could formerly be marked as input steps, causing
early termination during "stop input processing".
https://jira.pentaho.com/browse/BACKLOG-24266

[BACKLOG-24266] Correcting issue with safe stop

---

plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java

Reverts pentaho/pentaho-kettle#5535

Revert "[SP-4402] Backport of PDI-17203 - XML Output step: Null pointer exception when processing fields with null values (8.1 Suite)"

---

engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java

@pentaho-lmartins @ricardosilva88 @cravobranco

[SP-4397] Backport of PDI-17377 - Trans Executor mixes parameter values (8.1 Suite)

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java

[BACKLOG-24014] Remove step metrics error logging for a valid single empty row ktr

[BACKLOG-24014] Remove step metrics error logging for a valid single empty row ktr

---

core/src/main/java/org/pentaho/di/core/row/ValueMetaInterface.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaInternetAddress.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaInternetAddressTest.java
engine/src/main/java/org/pentaho/di/trans/steps/sort/SortRows.java

[PDI-17270] Sort rows : Cannot sort Internet Address Types

---

core/src/main/java/org/pentaho/di/core/row/ValueMetaInterface.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaInternetAddress.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaInternetAddressTest.java
engine/src/main/java/org/pentaho/di/trans/steps/sort/SortRows.java

[BACKLOG-24579] First check-in of Dataflow prototype

---

assemblies/static/src/main/resources-filtered/Data Integration.app/Contents/Info.plist

[PDI-16499] - Version is not properly set on 'Data Integration.app'

---

core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java
engine-ext/api/pom.xml
engine-ext/pom.xml
engine/src/main/java/org/pentaho/di/trans/TransSupplier.java
engine/src/main/java/org/pentaho/di/trans/ael/adapters/DataflowEngineAdapter.java
engine/src/main/java/org/pentaho/di/trans/ael/adapters/DataflowRunner.java
engine/src/main/java/org/pentaho/di/trans/ael/adapters/TestLogger.java
engine/src/test/java/org/pentaho/di/trans/TransSupplierTest.java
engine/src/test/java/org/pentaho/di/trans/ael/adapters/DataflowRunnerTest.java
engine/src/test/resources/log4j.xml
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/EmbeddedRunConfigurationManager.java
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/dataflow/DataflowRunConfiguration.java
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/dataflow/DataflowRunConfigurationExecutor.java
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/dataflow/DataflowRunConfigurationProvider.java
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/dataflow/DataflowRunConfigurationUI.java
plugins/engine-configuration/impl/src/main/resources/OSGI-INF/blueprint/beans.xml

[BACKLOG-24579] First checkin of Dataflow prototype

---

engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileOutputMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMetaInjectionTest.java

Minor refactoring to take advantage of a pre-existing base class and it's common functionality.

[BACKLOG-24279][BACKLOG-24281] Data lineage analyzers for the Hadoop input and output steps

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsConsumerMeta.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsDelegate.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducerMeta.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/context/WebsphereMQProvider.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/ConnectionForm.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsConsumerDialog.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsDialogSecurityLayout.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsProducerDialog.java
plugins/streaming/impls/jms/src/main/resources/org/pentaho/di/trans/step/jms/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/core/widget/CheckBoxTableCombo.java

Implement SSL on for IBM MQ JMS steps; add new gui widget to enable more uniform SSL controls on other steps.

[BACKLOG-22976] 

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/ConnectionForm.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsConsumerDialog.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsDialogSecurityLayout.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsProducerDialog.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerDialog.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerDialog.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MqttDialogSecurityLayout.java
ui/src/main/java/org/pentaho/di/ui/core/widget/AuthComposite.java

[BACKLOG-23000] Amqp implement authentication - create an authentication composite and refactor mqtt and jms to use it

[BACKLOG-23000] Amqp implement authentication - create an authentication composite and refactor mqtt and jms to use it

---

engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java

[PDI-17427] Job Executor Step doesn't read fields correctly

---

plugins/pur/core/src/main/java/com/pentaho/di/purge/UnifiedRepositoryPurgeService.java
plugins/pur/core/src/test/java/com/pentaho/di/purge/UnifiedRepositoryPurgeServiceTest.java

To be merged with https://github.com/pentaho/pentaho-platform/pull/4200

[BACKLOG-24621] - Refactor DTOs

---

plugins/json/assemblies/feature/pom.xml
plugins/json/assemblies/pom.xml
plugins/json/core/pom.xml
plugins/json/pom.xml

[BACKLOG-24588] revert artifact rename

---

assemblies/plugins/pom.xml

@emartin-pentaho 
@pentaho-amessier

remove json-plugin from assembly

---

assemblies/static/src/main/resources-filtered/Data Integration.app/Contents/Info.plist

Reverts pentaho/pentaho-kettle#5664
Note: Don't foget to upadte JIRA case for this one - https://jira.pentaho.com/browse/SP-4508

Revert "[SP-4508] - Backport of PDI-16499 - Version is not properly set on "D…"

---

engine/src/main/java/org/pentaho/di/trans/step/StepMetaInterface.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/joinrows/JoinRowsMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/joinrows/JoinRowsMetaTest.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/test/java/org/pentaho/di/ui/spoon/SpoonTest.java

Reverts pentaho/pentaho-kettle#5679
Reverting the revert.... @cravobranco

Revert "Revert "[SP-4455] Backport of PDI-17024 - Step name called "User Defi…"

---

assemblies/static/src/main/resources-filtered/Data Integration.app/Contents/Info.plist

Reverts pentaho/pentaho-kettle#5680
Reverting the revert... @cravobranco

Revert "Revert "[SP-4508] - Backport of PDI-16499 - Version is not properly set on "D…""

---

engine/src/main/java/org/pentaho/di/trans/steps/mappingoutput/MappingOutputMeta.java

Reverts pentaho/pentaho-kettle#5675
Reverting the revert... @cravobranco

Revert "Revert "[SP-4442] - Backport of PDI-17378 - Different column renaming…"

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java

Fixes regression when a job was created locally and later uploaded to a repository.
@ccaspanello @pamval @bmorrise

[PDI-17278] Repository Job Fails Using Variable to Run Local Job

---

plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java
plugins/meta-inject/src/main/resources/OSGI-INF/blueprint/pentaho-metainject-pdi-blueprint.xml

(part 2 of ) Reverts https://github.com/pentaho/pentaho-kettle/pull/5712
Re-adding 
- `blueprint.xml`
- `MetaInjectDialog.java`
which were missed out from the original revert PR ( https://github.com/pentaho/pentaho-kettle/pull/5713 )
@pentaho/rogueone @kurtwalker @mdamour1976 @tmcsantos @hbfernandes

Revert [BACKLOG-25015] Meta-inject - Move step to Kettle plugin system

---

ui/src/org/pentaho/di/ui/core/dialog/license/license.txt

[SP-4505] - Backport of PDI-17489 - Copyright info on PDI not okay

---

ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseController.java

I can't see how a test case can be written here with all this SWT stuff and all the event handlers firing.
I mean, a test case that will test anything meaningful.
@pamval @mbatchelor @bmorrise

[PDI-17283] After upgrade to 8.1. versioning not active

---

plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducer.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSourceTest.java

[BACKLOG-23916] Use UTF-8 charset for streaming step message to byte conversion

[BACKLOG-23916] Use UTF-8 charset for streaming step message to byte conversion

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzer.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzer.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerTest.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzerTest.java

Additionally, performed some cleanup of unnecessary File sub-types
Related PRs:
https://github.com/pentaho/pentaho-metaverse/pull/482
https://github.com/pentaho/big-data-plugin/pull/1493
https://github.com/pentaho-es/pdi-igc-lineage-plugin/pull/3

[BACKLOG-25105] Adding HDFS input/output resources

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/EnterStringDialog.java

@ricardosilva88 @pentaho-lmartins

[PMD-1077] CLONE - Able to Publish a model with no domain name

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMetaTest.java

Also making the related unit test more robust to catch this specific bug

[BACKLOG-25556] Fix for text file output filename handing

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java

Reverts pentaho/pentaho-kettle#5762

Revert "[SP-4608] Fix for text file output filename handing"

---

engine/src/it/java/org/pentaho/di/trans/steps/http/HTTPIT.java

Cherry pick of #5766 to 8.1 branch.
@cravobranco

[CLEANUP] Fixes integration tests in HTTPIT.java

---

plugins/get-fields/core/src/main/javascript/app/app.component.js

[BACKLOG-25665] fix for search error string

---

engine/src/main/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariables.java
engine/src/test/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java

[PDI-17536] - SetVariable in job to blank returns in null error

---

plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositoryStressTest.java

Fixing test bug report by @ppatricio

[BISERVER-13923] Concurrency issue with importing files

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzer.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzer.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerTest.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzerTest.java

[SP-4635] Backport of BACKLOG-25105 - IGC Plugin - HDFS1 to HDFS2- No resource asset is displayed (8.1 Suite)

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/EnterStringDialog.java

Merge before: https://github.com/pentaho/pentaho-metadata-editor/pull/133
@bantonio82 @ssamora

[SP-4643] Backport of PMD-1077 - CLONE - Able to Publish a model with no domain name (8.1 Suite)

---

plugins/meta-inject/pom.xml
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInject.java
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java
plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java
plugins/meta-inject/src/main/resources/OSGI-INF/blueprint/pentaho-metainject-pdi-blueprint.xml
plugins/meta-inject/src/test/java/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java

Realtes PRs:
https://github.com/pentaho/pentaho-metaverse/pull/501
https://github.com/pentaho-es/pdi-igc-lineage-plugin/pull/23

[BACKLOG-24282] Adding custom analyzer to MDI step (meta-inject)

---

core/pom.xml
engine/pom.xml
plugins/xml/core/pom.xml
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataData.java
pom.xml

This is one of a series of PRs. See pentaho/maven-parent-poms#70 for the complete list and more details. **Do not merge until further notice!**
@graimundo

[PPP-4182] Use of vulnerable component dom4j-1.6.1.jar  CVE-2018-1000632

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java

Reverts pentaho/pentaho-kettle#5853

Revert "Revert "[SP-4602] Backport of PDI-17375 - Get Data from XML issue wit…"

---

assemblies/client/pom.xml
assemblies/core/lib/pom.xml
assemblies/lib/pom.xml

Backlog 26037

---

plugins/get-fields/core/src/main/resources/i18n/get-fields/messages.properties
plugins/get-fields/core/src/main/resources/i18n/get-fields/messages_en.properties
plugins/json/core/src/main/resources/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties

[BACKLOG-25918] Small fix per UX

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputData.java

[BACKLOG-24582] - Updated FileStreamMap logic

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/test/java/org/pentaho/di/core/ConstTest.java
engine/src/main/java/org/pentaho/di/trans/steps/excelinput/ExcelInput.java
engine/src/test/java/org/pentaho/di/trans/steps/excelinput/ExcelInputContentParsingTest.java

PDI-17586 - Excel Input Step can't use VFS

---

plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java

This is to improve the presentation of mappings within the IGC plugin

[BACKLOG-24282] Minor changes to the handling of MDI mappings in data lineage

---

engine/src/main/java/org/pentaho/di/trans/steps/mapping/MappingMeta.java

Minot changes needed to allow the Mapping Analyzer to be added within the pentaho-metaverse-core project

[BACKLOG-21741] Creating a data-lineage analyzer for the Mapping (sub-transformation) step

---

plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java

Reverts pentaho/pentaho-kettle#5933

Revert "[SP-4519] Backport of BACKLOG-24282 - Minor fix to the MDI analyzer -…"

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index.html
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties

[BACKLOG-26373] Update and Validate In-Product Links

---

engine/src/main/java/org/pentaho/di/trans/steps/singlethreader/SingleThreaderMeta.java

Reverts pentaho/pentaho-kettle#5932

Revert "[SP-4733] Backport of BACKLOG-25980 - Adding custom step analyzer for…"

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index.html
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties

@kcruzada @pvale @jlien @pentaho-svigneri 
Master PR: https://github.com/pentaho/pentaho-kettle/pull/5941

[BACKLOG-26373] Update and Validate In-Product Links (#5941)

---

plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java

Reverts pentaho/pentaho-kettle#5931

Revert "[SP-4638][CLEANUP] Backport of BACKLOG-21741 - Creating a data-lineag…"

---

plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java

Reverts pentaho/pentaho-kettle#5929

Revert "[SP-4519] Backport of BACKLOG-24282 - Minor changes to the handling o…"

---

plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducer.java
plugins/streaming/impls/mqtt/src/main/resources/org/pentaho/di/trans/step/mqtt/messages/messages_en_US.properties

stopped or disposed.
https://jira.pentaho.com/browse/BACKLOG-26377

[BACKLOG-26377] Deferring close of mqtt client until trans is

---

engine/src/main/java/org/pentaho/di/core/util/serialization/BaseSerializingMeta.java

Was failing when parentStepMeta was not defined.  The new
strategy directly creates a new stepmetainterface via the plugin
registry.
https://jira.pentaho.com/browse/BACKLOG-26211

[BACKLOG-26211] One more pass at withVariables.

---

plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java

Reverts pentaho/pentaho-kettle#5991

Revert "[BACKLOG-26444] Adding some missing input links to the mdi analyzer"

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/analyzer/JmsConsumerAnalyzer.java

@kcruzada @pvale @jlien @svigneri

[BACKLOG-26047] JMS Consumer Step Analyzer changes

---

ui/src/test/java/org/pentaho/di/core/dnd/DragAndDropContainerTest.java

Completing the #5949 PR ( which was closed )
- contains the #5949 fix
- the required import was added
- fix replicated for entire test class
@pentaho/tatooine

[PDI-17699] DragAndDropContainerTest fail on Windows

---

plugins/file-open-save/core/pom.xml
plugins/file-open-save/pom.xml
plugins/get-fields/core/pom.xml
plugins/get-fields/pom.xml

@pentaho/millenniumfalcon @pentaho/x-wing please review

[BACKLOG-22832] Upgrade require.js and r.js to version 2.3.6

---

engine/src/main/java/org/pentaho/di/trans/ael/websocket/TransWebSocketEngineAdapter.java

I couldn't figure a way to unit test this change.  open to suggestions.

[BACKLOG-25678] - all steps are stopped if a Trans fails

---

core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/MariaDBDatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/MySQLDatabaseMeta.java
core/src/test/java/org/pentaho/di/core/database/DatabaseMetaSupportsSchemasTest.java
core/src/test/java/org/pentaho/di/core/database/MariaDBDatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/MySQLDatabaseMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java

@mbatchelor @bmorrise @pentaho/tatooine Please review and merge.

[PDI-17673] PDI logging UI (trash can) fails to clear log table.

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java

@pentaho/tatooine  
@mbatchelor

[PDI-17478] Can't use directory path variables on Get data from XML step

---

core/pom.xml

This is a series of PRs, please see pentaho/maven-parent-poms#82 for full list.
@ssamora

[PPP-4226] Use of vulnerable component commons-compress  CVE-2018-11771

---

plugins/repositories/core/src/main/java/org/pentaho/di/ui/repo/controller/RepositoryConnectController.java

@pentaho/tatooine @pentaho-lmartins  
@mbatchelor @mkambol

[PDI-17701] Repository manager window - Check box

---

core/pom.xml

[ENGOPS-4746] upgrade simple-jndi to 1.0.2

---

engine/src/main/java/org/pentaho/di/www/GetStatusServlet.java
engine/src/main/resources/org/pentaho/di/www/messages/messages_en_US.properties

[BACKLOG-26272] fix for pause icon not working correctly

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/ExcelInput.java

@pentaho-lmartins @pedrofvteixeira

[PDI-17765] Microsoft Excel Input step - Limit option works incorrectly

---

engine/src/main/java/org/pentaho/di/job/entry/JobEntryCopy.java
engine/src/test/java/org/pentaho/di/job/entry/JobEntryCopyTest.java

@pentaho-lmartins @pedrofvteixeira

[PDI-17764] Checkpoints dropped from Job on Export to XML

---

engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/test/java/org/pentaho/di/job/JobTest.java

@mbatchelor @pentaho-lmartins @ppatricio

[PDI-17744] Start job entry doesn't repeat in sub-job

---

assemblies/static/src/main/resources-filtered/Data Integration.app/Contents/Info.plist

@pentaho/tatooine you know what to do...

[BACKLOG-26968] Update copyright versions to 2019

---

ui/src/main/java/org/pentaho/di/ui/xul/KettleDialog.java

[BACKLOG-26961] avoid extra windows from missing xul parent component

---

assemblies/static/src/main/resources-filtered/Data Integration.app/Contents/Info.plist

[SP-4856] Backport of BACKLOG-26968 - Update copyright versions to 2019

---

assembly/package-res/Data Integration.app/Contents/Info.plist

[SP-4857] Backport of BACKLOG-26968 - Update copyright versions to 2019

---

assemblies/static/src/main/resources/README.txt

[PPP-4312] .TXT files content are outdated (Report Designer and PDI)

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/ShowHelpDialog.java

@pentaho/kashyyyk and @NJtwentyone please review

[FIX] Remove unused variable

---

plugins/streaming/impls/mqtt/pom.xml
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMeta.java
plugins/streaming/impls/mqtt/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugins/streaming/pom.xml

Added metaverse annotations to producer meta and wired up
the AnnotationDrivenStepMetaAnalyzer in blueprint.
https://jira.pentaho.com/browse/BACKLOG-26922

[BACKLOG-26922] MQTT Producer - Implement Kettle Lineage

---

plugins/repositories/core/src/main/javascript/app/components/other/other.component.js

Reverts pentaho/pentaho-kettle#6233

Revert "[SP-4898] Backport of PDI-17848 - Repository Manager - Close button n…"

---

assemblies/client/pom.xml
assemblies/client/src/assembly/assembly.xml
assemblies/core/client/pom.xml
assemblies/core/client/src/assembly/assembly.xml
assemblies/core/static/src/main/resources/spoon.sh
assemblies/static/src/main/resources/spoon.sh

Reverts pentaho/pentaho-kettle#6245

Revert "[BACKLOG-26964] - Linux SWT lib upgrade"

---

plugins/file-open-save/pom.xml
plugins/get-fields/pom.xml
plugins/repositories/core/pom.xml

[BACKLOG-27567] Centralize org.osgi dependencies management
