plugins/repositories/core/pom.xml

[BACKLOG-27569] Centralize pax-web dependency management

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
plugins/engine-configuration/impl/pom.xml

[BACKLOG-27575] Remove Felix Main dependency

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmloutput/XMLField.java
plugins/xml/core/src/main/java/org/pentaho/di/ui/trans/steps/xmloutput/XMLOutputDialog.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmloutput/XMLOutputTest.java

@pentaho-lmartins @bantonio82 @pentaho/tatooine

[SP-4902] Backport of PDI-15575 - XML Output Step - should allow developers to save and edit when step configuraton is incomplete (8.2 Suite)

---

assemblies/lib/pom.xml

[BACKLOG-27567] Added missing OSGi core dependency

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/EnterStringDialog.java

@pentaho-lmartins @bantonio82 please review

[SP-4903] [PDI-17617] - Fixed: Step copies : Buttons missing

---

core/src/main/java/org/pentaho/di/core/database/Database.java

@pentaho-lmartins @pentaho/tatooine

[PDI-17792] Get Table Names step throws java.lang.NullPointerException

---

engine/src/main/java/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputDoubleLineEndTest.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputEnclosureTest.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputMultiCharDelimiterTest.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputRowNumberTest.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputUnitTestBase.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/PDI_15270_Test.java

@pentaho/tatooine @pentaho-lmartins
There was much duplicate code on the unit tests, so I pushed some to the base class.
There're 13 unit test classes, someone should look into them as it seems that there're tests that are duplicated... sometime... :-)

[PDI-17831] .csv read from CSV Input step is locked in Carte's JVM

---

assemblies/lib/pom.xml

[BACKLOG-27577] Add missing karaf main lib to assembly

---

ui/src/main/resources/org/pentaho/di/ui/trans/step/messages/messages_en_US.properties

[BACKLOG-27867] Change field label for parallelism setting on streaming

---

plugins/file-open-save/assemblies/feature/src/main/feature/feature.xml
plugins/file-open-save/pom.xml
plugins/get-fields/assemblies/feature/src/main/feature/feature.xml
plugins/get-fields/pom.xml

Needs [pentaho/maven-parent-poms#109](https://github.com/pentaho/maven-parent-poms/pull/109).
@graimundo

[BACKLOG-27565] Centralize CXF dependency version

---

core/pom.xml
core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/main/resources/org/pentaho/di/core/vfs/providers.xml
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
plugins/google-analytics/core/pom.xml
plugins/gpload/pom.xml
plugins/json/core/pom.xml
plugins/openerp/pom.xml
plugins/pentaho-googledrive-vfs/core/pom.xml
plugins/repositories/core/pom.xml
pom.xml

Reverts pentaho/pentaho-kettle#6316

Revert "[PDI-17775] Process Files step no longer supports HTTP scheme"

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
core/pom.xml
plugins/google-analytics/core/pom.xml
plugins/json/assemblies/plugin/pom.xml
plugins/json/core/pom.xml
plugins/pur/core/pom.xml
plugins/pur/repository-proxy/pom.xml
plugins/streaming/impls/mqtt/pom.xml

Needs https://github.com/pentaho/maven-parent-poms/pull/111.
@graimundo

[BACKLOG-27565] Centralize SLF4J dependency

---

plugins/s3csvinput/core/pom.xml
plugins/s3csvinput/pom.xml

This is a series of PRs to update the version of AWS Java SDK across all repositories.
See: https://github.com/pentaho/maven-parent-poms/pull/114
@pentaho/tatooine @ssamora

[PDI-17867] Fixes not closing connections leading to timeouts

---

ui/src/main/java/org/pentaho/di/ui/core/widget/LabeledControl.java

Handles common pattern of a series of textvars/combovars/etc, one on top
of the next, each with a label.  Also handles re-laying out controls
when one or more is hidden.

[BACKLOG-27028] Control to simplify creation/layout of labeled controls

---

plugins/get-fields/core/src/main/resources-filtered/OSGI-INF/blueprint/blueprint.xml

@dcleao please review. I think you've missed this one.

[BACKLOG-27098] Remove unneeded whiteboard ResourceMapping

---

assemblies/samples/src/main/resources/transformations/files/jsonfile.js

Fixing invalid JSON in sample @pentaho/r2d2

PDI-18003 - Fixing invalid JSON

---

ui/src/main/java/org/pentaho/di/ui/core/widget/VFSFileSelection.java

[BACKLOG-28179] Add an option to control what kind of files can be

---

core/src/main/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMeta.java
dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java
dbdialog/src/main/resources/org/pentaho/ui/database/databasedialog.properties
dbdialog/src/main/resources/org/pentaho/ui/database/snowflakehv_native.xul
ui/src/main/java/org/pentaho/di/ui/core/database/dialog/DataOverrideHandler.java

Consistent with the commons-db dialect:
https://github.com/pentaho/pentaho-commons-database/pull/165
https://jira.pentaho.com/browse/BACKLOG-28164

[BACKLOG-28164]  Adding Warehouse as a main option for Snowflake

---

ui/src/org/pentaho/di/ui/core/dialog/Splash.java

[SP-4986] - Backport of PDI-14160

---

plugins/connections/assemblies/feature/src/main/feature/feature.xml

[BACKLOG-27714] Use inherited cxf version

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/Splash.java

[SP-4987] Backport of PDI-14160

---

engine/src/main/java/org/pentaho/di/trans/steps/infobrightoutput/InfobrightLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/terafast/TeraFast.java
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_en_US.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_es_AR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_fr_FR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_it_IT.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_ja_JP.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_ko_KR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_en_US.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_fr_FR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_it_IT.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_ja_JP.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_ko_KR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_en_US.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_fr_FR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_it_IT.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_ja_JP.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_ko_KR.properties
engine/src/test/java/org/pentaho/di/trans/steps/infobrightoutput/InfobrightLoaderTest.java
engine/src/test/java/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseTest.java
engine/src/test/java/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoaderTest.java
engine/src/test/java/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java
engine/src/test/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java
engine/src/test/java/org/pentaho/di/trans/steps/terafast/TeraFastTest.java

@pentaho/tatooine @pentaho-lmartins @bantonio82

[SP-4974] Backport of PDI-17481 - Some steps of Bulk loading return NPE if previous steps have no rows (8.2 Suite)

---

engine/src/org/pentaho/di/trans/steps/infobrightoutput/InfobrightLoader.java
engine/src/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_en_US.properties
engine/src/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_es_AR.properties
engine/src/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_fr_FR.properties
engine/src/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_it_IT.properties
engine/src/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_ja_JP.properties
engine/src/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_ko_KR.properties
engine/src/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseLoader.java
engine/src/org/pentaho/di/trans/steps/ivwloader/messages/messages_en_US.properties
engine/src/org/pentaho/di/trans/steps/ivwloader/messages/messages_fr_FR.properties
engine/src/org/pentaho/di/trans/steps/ivwloader/messages/messages_it_IT.properties
engine/src/org/pentaho/di/trans/steps/ivwloader/messages/messages_ja_JP.properties
engine/src/org/pentaho/di/trans/steps/ivwloader/messages/messages_ko_KR.properties
engine/src/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoader.java
engine/src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoader.java
engine/src/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/src/org/pentaho/di/trans/steps/terafast/TeraFast.java
engine/src/org/pentaho/di/trans/steps/terafast/messages/messages_en_US.properties
engine/src/org/pentaho/di/trans/steps/terafast/messages/messages_fr_FR.properties
engine/src/org/pentaho/di/trans/steps/terafast/messages/messages_it_IT.properties
engine/src/org/pentaho/di/trans/steps/terafast/messages/messages_ja_JP.properties
engine/src/org/pentaho/di/trans/steps/terafast/messages/messages_ko_KR.properties
engine/test-src/org/pentaho/di/trans/steps/infobrightoutput/InfobrightLoaderTest.java
engine/test-src/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseTest.java
engine/test-src/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoaderTest.java
engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java
engine/test-src/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java
engine/test-src/org/pentaho/di/trans/steps/terafast/TeraFastTest.java

@pentaho/tatooine @pentaho-lmartins @bantonio82

[SP-4973] Backport of PDI-17481 - Some steps of Bulk loading return NPE if previous steps have no rows (7.1 Suite)

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStep.java
engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMeta.java
engine/src/main/java/org/pentaho/di/trans/streaming/common/BlockingQueueStreamSource.java
engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMetaTest.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerDialog.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducer.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSourceTest.java
plugins/streaming/impls/mqtt/src/test/resources/ProduceFourBinaryRows.ktr

[BACKLOG-28319] - implementing binary messages for mqtt producer

[BACKLOG-28318] - implementing binary messages for mqtt consumer

---

ui/src/main/java/org/pentaho/di/ui/core/widget/LabeledControl.java

Adding ability to attach a LabeledControl to the top of a container.
https://jira.pentaho.com/browse/BACKLOG-28332

[BACKLOG-28332] Update UX layout for Redshift Copy dialog

---

ui/src/main/java/org/pentaho/di/ui/core/widget/LabeledControl.java

https://jira.pentaho.com/browse/BACKLOG-28332

[BACKLOG-28332] Setting 15 px spacing between LabeledControls

---

core/src/org/pentaho/di/core/row/RowMeta.java

@pentaho-lmartins please review

[SP-4947] - Fixed missing error message in Abort step

---

core/src/org/pentaho/di/core/row/RowMeta.java

Reverts pentaho/pentaho-kettle#6413

Revert "[SP-4947] - Fixed missing error message in Abort step"

---

engine/src/main/java/org/pentaho/di/base/AbstractBaseCommandExecutor.java
engine/src/main/java/org/pentaho/di/base/IParams.java
engine/src/main/java/org/pentaho/di/base/KettleConstants.java
engine/src/main/java/org/pentaho/di/base/Params.java
engine/src/main/java/org/pentaho/di/kitchen/JobParams.java
engine/src/main/java/org/pentaho/di/pan/Pan.java
engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java
engine/src/main/java/org/pentaho/di/pan/TransParams.java
engine/src/test/java/org/pentaho/di/pan/PanCommandExecutorTest.java

Reverts pentaho/pentaho-kettle#6420

Revert "[BACKLOG-28227] Expanded Pan functionality to accept and execute a BA…"

---

engine/src/main/java/org/pentaho/di/base/AbstractBaseCommandExecutor.java
engine/src/main/java/org/pentaho/di/base/IParams.java
engine/src/main/java/org/pentaho/di/base/KettleConstants.java
engine/src/main/java/org/pentaho/di/base/Params.java
engine/src/main/java/org/pentaho/di/kitchen/JobParams.java
engine/src/main/java/org/pentaho/di/pan/Pan.java
engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java
engine/src/main/java/org/pentaho/di/pan/TransParams.java
engine/src/test/java/org/pentaho/di/pan/PanCommandExecutorTest.java

Reverts pentaho/pentaho-kettle#6423
Original PR: pentaho/pentaho-kettle#6420
https://github.com/pentaho/pentaho-ee/pull/2010 needs to be merged together with this

Revert "Revert "[BACKLOG-28227] Expanded Pan functionality to accept and execute a BA…""

---

engine/src/main/java/org/pentaho/di/repository/RepositoryConnectionUtils.java
engine/src/main/resources/org/pentaho/di/repository/messages/messages_en_US.properties

repository and adding it as utility so it can be reused

[BACKLOG-28507] Refactored the PdiAction code that is making a connetion to

---

engine/src/main/resources/org/pentaho/di/trans/steps/stringcut/messages/messages_en_US.properties

* Updated messages after UX review.
@pentaho/bb-8 please review.

[BACKLOG-24067] Updated messages after UX review

---

engine/src/main/java/org/pentaho/di/repository/RepositoryConnectionUtils.java

- Replaced the ActionExecutionException with KettleException

[CLEANUP]  Fixed the javadoc comments

---

ui/src/main/java/org/pentaho/di/ui/core/widget/LabeledControl.java

Making LabeledControl.Series more flexible, to allow multi-column
layout of controls.  Used by redshift bulk load in showing/hiding
controls appropriate to a format type.
https://jira.pentaho.com/browse/BACKLOG-28310

[BACKLOG-28310] Redshift - Text option for removing quotes

---

core/src/main/java/org/pentaho/di/core/database/RedshiftDatabaseMeta.java
dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java
dbdialog/src/main/resources/org/pentaho/ui/database/databasedialog.properties
ui/src/main/java/org/pentaho/di/ui/core/database/dialog/XulDatabaseDialog.java

getConnectionSpecificInfo and setConnectionSpecificInfo. Provide ability
for plugins to update db dialog.

[BACKLOG-28369] Update DataHandler to allow subclasses to extend

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/databaselookup/DatabaseLookupDialog.java

@pentaho/tatooine @pentaho-lmartins @wseyler

[PDI-17604] - 'Database lookup' step gets unusable with too many fields

---

assemblies/samples/src/main/resources/transformations/Check if a column exists - Basic example.ktr

[BACKLOG-28271] - Updating sample to use correct database

---

engine/src/main/java/org/pentaho/di/trans/steps/csvinput/CsvInputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputMetaTest.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/csvinput/CsvInputDialog.java

@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-17655] Added methods to trim the text from the UI side and the Backend. One side for new work, one side for running previously made transformations.
* [PDI-17655] Added test method to verify trimming of text.

[PDI-17655] CSV Input Step - Data conversion issue ‘Cant convert string to integer’

---

engine/src/main/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkDataOutput.java
engine/src/main/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkDataOutputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderTest.java

[SP-5039] Backport of PDI-15207 - Oracle Bulk Loader don't parse internal variable (8.2 Suite)

---

engine/src/org/pentaho/di/trans/steps/orabulkloader/OraBulkDataOutput.java
engine/src/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoader.java
engine/test-src/org/pentaho/di/trans/steps/orabulkloader/OraBulkDataOutputTest.java
engine/test-src/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderTest.java

[SP-5038] Backport of PDI-15207 - Oracle Bulk Loader don't parse internal variable (7.1 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/csvinput/CsvInputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputMetaTest.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/csvinput/CsvInputDialog.java

Reverts pentaho/pentaho-kettle#6468

Revert "[PDI-17655] CSV Input Step - Data conversion issue ‘Cant convert string to integer’"

---

plugins/file-open-save-new/core/src/main/javascript/app/app.css

Master PR: https://github.com/pentaho/pentaho-kettle/pull/6538
8.3 PR: https://github.com/pentaho/pentaho-kettle/pull/6540
8.3.0.0 PR: https://github.com/pentaho/pentaho-kettle/pull/6539

[BACKLOG-29160] Fix for open save on linux

---

core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
core/src/main/java/org/pentaho/di/connections/vfs/VFSHelper.java
core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/test/java/org/pentaho/di/connections/ConnectionManagerTest.java

Master: https://github.com/pentaho/pentaho-kettle/pull/6553
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6554
8.3: https://github.com/pentaho/pentaho-kettle/pull/6555

[BACKLOG-29223] Fix for ConnectionManager when connection is null

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/context/ActiveMQProvider.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/context/WebsphereMQProvider.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/context/ActiveMQProviderTest.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/context/WebsphereMQProviderTest.java

This commit is a cherry-pick from master b4f91636f.

[BACKLOG-29207] Mask all passwords in debug output.

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java

Master: https://github.com/pentaho/pentaho-kettle/pull/6558
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6561
8.3: https://github.com/pentaho/pentaho-kettle/pull/6562

[PDI-16490] Fix for using kettle.properties for data formats

---

assemblies/static/src/main/resources/ui/menubar.xul
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

Master: https://github.com/pentaho/pentaho-kettle/pull/6589
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6592
8.3: https://github.com/pentaho/pentaho-kettle/pull/6593

[BACKLOG-29277] Disable file menu options in PDI for new VFS browser

---

core/src/main/java/org/pentaho/di/core/database/Database.java
engine/src/main/java/org/pentaho/di/trans/steps/gettablenames/GetTableNames.java
engine/src/test/java/org/pentaho/di/trans/steps/gettablenames/GetTableNamesTest.java

Reverts pentaho/pentaho-kettle#6597

Revert "[PDI-18084] Revert original work and fixed bug in non JDBC Meta fallback"

---

core/src/main/java/org/pentaho/di/core/database/Database.java

[PDI-18084] Fixed bug in non JDBC Meta fallback

---

plugins/file-open-save/core/src/main/javascript/app/components/folder/folder.component.js

Master: https://github.com/pentaho/pentaho-kettle/pull/6602
8.3: https://github.com/pentaho/pentaho-kettle/pull/6615
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6616

[PDI-18122] Fix for file search in spoon

---

core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/test/java/org/pentaho/di/core/vfs/KettleVFSTest.java
engine/src/main/java/org/pentaho/di/trans/step/StepMeta.java

PR with a "wait for provider" solution in KettleVFS:
1-added a wait for provider mechanism
2-check for big data providers, that were wrongly defined as relativePathFilenames
There was also a problem with some trans executions, that required a change in StepMeta following the https://github.com/pentaho/pentaho-kettle/pull/6091 approach.
For 7.1 we have to backport the https://github.com/pentaho/pentaho-kettle/pull/6091 first to use this fix.
@mkambol

[PPP-4374] Random issues with Karaf - Race Condition

---

assemblies/samples/src/main/resources/jobs/Slowly Changing Dimension/create - populate - update slowly changing dimension.kjb

[BACKLOG-29336] Updated sample to account for Sample DB user change.

---

core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/test/java/org/pentaho/di/core/vfs/KettleVFSTest.java
engine/src/main/java/org/pentaho/di/trans/step/StepMeta.java

cherry-pick of https://github.com/Pentaho/pentaho-kettle/commit/bfccc92c4385064d5ef1cb5cac39f22e47cf9799
@bantonio82

[PPP-4374] Random issues with Karaf - Race Condition (#6594)

---

engine/src/main/java/org/pentaho/di/www/GetJobStatusServlet.java
engine/src/main/java/org/pentaho/di/www/GetStatusServlet.java
engine/src/main/java/org/pentaho/di/www/GetTransStatusServlet.java
engine/src/main/java/org/pentaho/di/www/StatusServletUtils.java

[SP-5069] Adding Backport of logic for PDI-17863 and PDI-18039

---

engine/src/org/pentaho/di/www/ExecuteJobServlet.java
plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositoryConnector.java

Reverts pentaho/pentaho-kettle#6629

Revert "[SP-5078] Backport of PDI-18081 - The /kettle/executeJob REST API cal…"

---

plugins/connections/ui/src/main/javascript/app/components/summary/summary.css
plugins/connections/ui/src/main/javascript/app/components/summary/summary.html

Master: https://github.com/pentaho/pentaho-kettle/pull/6631
8.3: https://github.com/pentaho/pentaho-kettle/pull/6645
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6646

[BACKLOG-29275] Fix for overlapping fields

---

plugins/connections/ui/src/main/javascript/app/components/creating/creating.component.js
plugins/connections/ui/src/main/javascript/app/components/failure/failure.component.js
plugins/connections/ui/src/main/javascript/app/components/success/success.component.js
plugins/connections/ui/src/main/resources/i18n/connections/messages.properties
plugins/connections/ui/src/main/resources/i18n/connections/messages_en.properties

Master: https://github.com/pentaho/pentaho-kettle/pull/6651
8.3: https://github.com/pentaho/pentaho-kettle/pull/6654
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6655

[BACKLOG-29387] Able to save VFS connection without valid credentials

---

plugins/connections/ui/src/main/java/org/pentaho/di/connections/ui/endpoints/ConnectionEndpoints.java
plugins/connections/ui/src/main/resources/org/pentaho/di/connections/ui/dialog/messages/messages_en_US.properties

Master: https://github.com/pentaho/pentaho-kettle/pull/6666
8.3: https://github.com/pentaho/pentaho-kettle/pull/6667
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6668

[BACKLOG-29386] Add help link for VFS connections

---

plugins/file-open-save/core/src/main/java/org/pentaho/repo/controller/RepositoryBrowserController.java

Master: https://github.com/pentaho/pentaho-kettle/pull/6617
8.3: https://github.com/pentaho/pentaho-kettle/pull/6675
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6676

[PDI-18113] Fix for showing hidden files/folders for admin in search

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index.html

[BACKLOG-29422] Update and Validate In-Product Links in 8.3

---

plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/abort/AbortMeta.java
plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSumMeta.java
plugins/core/ui/src/main/java/org/pentaho/di/ui/trans/steps/abort/AbortDialog.java
plugins/core/ui/src/main/java/org/pentaho/di/ui/trans/steps/checksum/CheckSumDialog.java
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java
plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java
plugins/meta-inject/src/main/resources/OSGI-INF/blueprint/pentaho-metainject-pdi-blueprint.xml

Master PR: https://github.com/pentaho/pentaho-kettle/pull/6688
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6698
@kcruzada @dkincade

[BACKLOG-29422] more updated doc links for 8.3

---

plugins/file-open-save/core/src/main/javascript/app/components/folder/folder.component.js

@LeonardoCoelho71950 @smmribeiro @pentaho/tatooine
8.2: #6697
8.2.0.7: https://github.com/pentaho/pentaho-kettle/pull/6702

[SP-5114] Backport of PDI-18112 - Repository Thin dialog - Unable to open file using Search functionality (8.2 Suite)

---

plugins/file-open-save/core/src/main/java/org/pentaho/repo/controller/RepositoryBrowserController.java

@LeonardoCoelho71950 @smmribeiro @pentaho/tatooine
8.2: #6699
8.2.0.7: #6701

[SP-5115] Backport of PDI-18113 - Repository Thin dialog - Hidden Files are not listed on Search results (8.2 Suite)

---

ui/src/main/java/org/pentaho/di/ui/core/widget/WidgetBuilder.java
ui/src/main/java/org/pentaho/di/ui/job/entry/JobEntryDialog.java

Adding common UI controls to be shared across multiple plugins.

[BACKLOG-29210] Snowflake DW Manager.

---

engine/src/main/resources/kettle-variables.xml

@pentaho-lmartins @pentaho/tatooine

[PDI-16846] kettle.properties dialog box in PDI has swapped descriptions

---

assemblies/samples/src/main/resources/transformations/Get File Names - Change short filename.ktr
assemblies/samples/src/main/resources/transformations/Get File Names - Remove extension.ktr

@pentaho-lmartins @pentaho/tatooine

[PDI-18033] PDI sample Get File Names - Remove extention.ktr misspelled

---

ui/src/main/java/org/pentaho/di/ui/trans/step/common/GetFieldsCapableStepDialog.java
ui/src/test/java/org/pentaho/di/ui/trans/step/common/GetFieldsCapableStepDialogTest.java

[SP-5154] - Backport of PDI-18134 - Wrong error message in CSV input step with invalid filename/path (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/mail/Mail.java
engine/src/test/java/org/pentaho/di/trans/steps/mail/MailTest.java

@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950

[SP-5140] Backport of PDI-13333 - Send Mail Step does not handle multi-byte characters file attachment. (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/plugins/BasePluginType.java
core/src/test/java/org/pentaho/di/core/plugins/BasePluginTypeTest.java

@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950

[SP-5133] Backport of PDI-17862 - Spoon - Scan of plugin jars at startup does not handle exceptions gracefully (8.3 Suite)

---

core/src/org/pentaho/di/core/plugins/BasePluginType.java
core/test-src/org/pentaho/di/core/plugins/BasePluginTypeTest.java

@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950

[SP-5132] Backport of PDI-17862 - Spoon - Scan of plugin jars at startup does not handle exceptions gracefully (7.1 Suite)

---

engine/ivy.xml
engine/src/org/pentaho/di/trans/steps/mail/Mail.java
engine/test-src/org/pentaho/di/trans/steps/mail/MailTest.java
engine/test-src/org/pentaho/di/trans/steps/mailinput/ParseMailInputTest.java

@pentaho/tatooine @pentaho-lmartins @LeonardoCoelho71950

[SP-5139] Backport of PDI-13333 - Send Mail Step does not handle multi-byte characters file attachment. (7.1 Suite)

---

ui/src/main/java/org/pentaho/di/ui/spoon/partition/PartitionMethodSelector.java
ui/src/main/resources/org/pentaho/di/ui/spoon/partition/messages/messages_en_US.properties

@ddiroma @kurtwalker please review

 [PDI-15164] Fixed spelling of the Partitioning Method dialog header

---

assemblies/client/pom.xml
assemblies/core/client/pom.xml

Don't merge this one until https://github.com/pentaho/pentaho-karaf-assembly/pull/549 is merged and artifacts are deployed on Nexus
CC: @Pancho7

[BACKLOG-29565] - PDI-CE Assembly - Migrating from deprecated old style

---

assemblies/lib/pom.xml

@pentaho/millenniumfalcon, @graimundo please review.

[BACKLOG-29696] Add missing dependency to PDI Client

---

assemblies/client/pom.xml
assemblies/core/client/pom.xml

cc: @Pancho7
!! This is NOT the first to be merged !!
Merging order:
1 - https://github.com/pentaho/pentaho-karaf-assembly/pull/557
2 - https://github.com/pentaho/pentaho-karaf-ee-assembly/pull/234
3 - https://github.com/pentaho/pentaho-kettle/pull/6778
4 - https://github.com/pentaho/pdi-assemblies-ee/pull/4

[BACKLOG-29710] - PDI-EE Assembly - Migrating from deprecated old style

---

core/src/org/pentaho/di/core/logging/SimpleLoggingObject.java
engine/src/org/pentaho/di/www/BaseJobServlet.java

Reverts pentaho/pentaho-kettle#6760
@RPAraujo @pentaho-lmartins

Revert "[SP-5175] Backport of PDI-18148 - java.lang.NullPointerException is t…"

---

ui/src/org/pentaho/di/ui/core/widget/ConditionEditor.java

This reverts commit 72a14cba26f2fcc9115782b407906f83711a7d60.

Revert "[SP-5190] - Back port of PDI-17657 to 7.1"

---

engine/pom.xml
engine/src/main/java/org/pentaho/di/repository/KettleAuthenticationException.java
engine/src/main/java/org/pentaho/di/repository/KettleRepositoryNotFoundException.java
engine/src/main/java/org/pentaho/di/www/ExecuteJobServlet.java
engine/src/main/resources/org/pentaho/di/www/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/www/ExecuteJobServletTest.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/UnifiedRepositoryInvocationHandler.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/UnifiedRepositoryInvocationHandlerTest.java

I will squash all commits and properly rename them after merge-master review. Nevertheless, I believe the review will be easier this way.
@RPAraujo @bcostahitachivantara

[SP-5194] Backport of PDI-17005 - Issues with Carte Jobs API executeJob endpoint in Pentaho REST API (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMeta.java

SP-5218 Backport of PSW-270 - JDBC Password is shown in clear text in PSW when connecting to SnowFlake and in debug mode (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/test/java/org/pentaho/di/core/vfs/KettleVFSTest.java
engine/src/test/java/org/pentaho/di/job/entries/unzip/JobEntryUnZipTest.java

Reverts pentaho/pentaho-kettle#6820

Revert "[PDI-18211] JSON Input Step Performance Degradation in 8.3"

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
plugins/log4j/core/pom.xml

@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-17794] Removed version references due to maven-parent-poms controlling that aspect
* [PDI-17794] Removed the version information for apache-log4j-extras, allowing top-level maven-parent-poms to handle it
This pull request is part of a series of pull requests:
- https://github.com/pentaho/maven-parent-poms/pull/137
- https://github.com/pentaho/adaptive-execution-layer/pull/3
- https://github.com/pentaho/big-data-plugin/pull/1682
- https://github.com/webdetails/cdf/pull/1075
- https://github.com/pentaho/commons-ee/pull/1
- https://github.com/webdetails/cpf/pull/144
- https://github.com/webdetails/cpk/pull/82
- https://github.com/pentaho/data-access/pull/1060
- https://github.com/pentaho/maven-project-archetypes/pull/16
- …

[PDI-17794] Warnings in Spoon console due to wrong version of log4j

---

core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/test/java/org/pentaho/di/core/vfs/KettleVFSTest.java

The PPP-4374 case ( #6641 ) popped up some invalid getObject calls. For instance, it looks like kettleAnalyzerUtil.java (pentaho-metaverse) calls KettleVFS and then saves the result as resource even if it is not a valid file path, so we should be validating if we really want to request a "getFileObject" from a whole json string as argument, and not just validating if it is empty:
https://github.com/pentaho/pentaho-metaverse/blob/master/api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java#L156
At the same time KettleVFS should also be prepared to deal with this. And we have more cases where this also happen. A first approach was made in here (https://github.com/pentaho/pentaho-kettle/pull/6820) but the URI validation added, which is the recommend validation …

[PDI-18211] JSON Input Step Performance Degradation in 8.3

---

engine/src/main/java/org/pentaho/di/trans/steps/replacestring/ReplaceString.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringProcessRowNoUnicodeTest.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringProcessRowUnicodeTest.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java

I've added two test classes with a total of 130 unit tests that cover a few scenarios for all possible combinations of "Use ReGex"/"Case sensitive"/"Whole word"/"Is Unicode" values.
@pentaho/tatooine @ppatricio

[BACKLOG-30125] PDI Replace in string step not removing file extension

---

engine/src/main/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderTest.java
plugins/gpload/core/src/main/java/org/pentaho/di/trans/steps/gpload/GPLoad.java
plugins/gpload/core/src/test/java/org/pentaho/di/trans/steps/gpload/GPLoadTest.java

@bcostahitachivantara @RPAraujo
Part of a set of PRs:
- https://github.com/pentaho/pentaho-kettle/pull/6835
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/50

[SP-5225] Backport of PDI-18073 - Bulk Loading steps returning NPE if previous steps does not have rows (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/database/Database.java
engine/src/main/java/org/pentaho/di/core/util/AsyncDatabaseAction.java
engine/src/test/java/org/pentaho/di/core/util/AsyncDatabaseActionTest.java
ui/src/main/java/org/pentaho/di/ui/core/widget/WidgetBuilder.java

from Redshift Bulk Load, Snowflake Bulk Load, and Snowflake WH manager.
As part of this, made core.database.Database implement Closeable
such that it can be used in a try-with-resources.  .close() just
calls .disconnect, which handles all statement and connection closing.
This commit also moves the WidgetBulder class out of the snowflake
bulk load proj.

[CLEANUP] Extracting/refactoring duplicated async db logic

---

assemblies/lib/pom.xml
core/src/main/java/org/pentaho/di/core/plugins/PluginInterface.java
core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java
plugins/meta-inject/pom.xml

Reverts pentaho/pentaho-kettle#6880

Revert "[BACKLOG-19907] - Migrate the shims to Karaf bundles."

---

assemblies/lib/pom.xml
core/src/main/java/org/pentaho/di/core/plugins/PluginInterface.java
core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java
plugins/meta-inject/pom.xml

[BACKLOG-19907] - Migrate the shims to Karaf bundles.

[BACKLOG-19907] - Migrate the shims to Karaf bundles.

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/test/java/org/pentaho/di/job/entries/trans/JobEntryTransTest.java

Revert '[PDI-18227] Nulls do not initialize variables when passed

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/test/java/org/pentaho/di/job/entries/trans/JobEntryTransTest.java

Reverts pentaho/pentaho-kettle#6864

Revert "[SP-5248] Backport of PDI-18227 - Nulls do not initialize variables w…"

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

@pentaho/tatooine @ppatricio @pentaho-lmartins 
* [PDI-18283] Changing order of JSON path resolution to before the Json Fast Reader is initialized.
* [PDI-18283] Adding test to show the path resolution works once you add the PARAM
* [PDI-18283] Updating licenses

[PDI-18283] JSON Input : Illegal character error when trying to pass Parameters/Variables to the Fields tab.

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/PropertiesComboDialog.java

* Allow the use of parameters on the value column.

[BACKLOG-31476] - Step Tuning Variable Support (Value Only)

---

plugins/shapefilereader/core/src/main/java/org/pentaho/di/shapefilereader/ShapeFileReader.java
plugins/shapefilereader/core/src/main/java/org/pentaho/di/shapefilereader/ShapeFileReaderMeta.java
plugins/shapefilereader/core/src/main/java/org/pentaho/di/ui/shapefilereader/ShapeFileReaderDialog.java
plugins/shapefilereader/core/src/main/java/org/pentaho/gis/shapefiles/ShapeFile.java
plugins/shapefilereader/core/src/main/resources/org/pentaho/di/shapefilereader/messages/messages_en_US.properties

@pentaho/tatooine @pentaho-lmartins

[PDI-18330] - Character corruption in the [ESRI Shapefile Reader] step

---

core/src/main/java/org/pentaho/di/cluster/SlaveConnectionManager.java
core/src/main/java/org/pentaho/di/compatibility/Value.java
core/src/main/java/org/pentaho/di/core/Const.java

name, closing possible vulnerability with client SSL.

[CLEANUP] - supressing sonar violations for fields with PASSWORD in the

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

[SP-5277] Backport of PDI-18283 - JSON Input : Illegal character error when trying to pass Parameters/Variables to the Fields tab. (8.3 Suite)

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/FieldsTab.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsConsumerDialog.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/step/BaseStreamingDialog.java

the parent streaming dialog class

[BACKLOG-31578] - pulling logic for determining sub-trans fields up to

---

plugins/shapefilereader/core/pom.xml
plugins/shapefilereader/core/src/main/java/org/pentaho/di/shapefilereader/ShapeFileReader.java
plugins/shapefilereader/core/src/main/java/org/pentaho/di/ui/shapefilereader/ShapeFileReaderDialog.java
plugins/shapefilereader/core/src/test/java/org/pentaho/di/shapefilereader/ShapeFileReaderTest.java

@pentaho/tatooine @pentaho-lmartins

PDI-18335 - The output data of "ESRI Shapefile Reader" step are different from the preview data.

---

core/src/main/java/org/pentaho/di/core/database/BaseDatabaseMeta.java
core/src/main/java/org/pentaho/di/core/encryption/Encr.java
core/src/main/java/org/pentaho/di/core/encryption/KettleTwoWayPasswordEncoder.java
core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java
core/src/main/java/org/pentaho/di/core/xml/XMLParserFactoryProducer.java
core/src/main/java/org/pentaho/di/metastore/MetaStoreConst.java
core/src/test/java/org/pentaho/di/core/xml/XMLParserFactoryProducerTest.java
core/src/test/java/org/pentaho/di/core/xml/XMLUtilsTest.java
engine/src/main/java/org/pentaho/di/repository/kdr/KettleDatabaseRepositoryBase.java
engine/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java
engine/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiWorkbook.java
engine/src/main/java/org/pentaho/di/trans/steps/olapinput/OlapInputMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/tableinput/TableInputMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/webservices/WebService.java
engine/src/main/java/org/pentaho/di/www/SslConfiguration.java

suppressing password-in-field warnings
using secure XML parsing in Excel Input, Table Input, and Web Service Locator steps

[CLEANUP] - addressing sonar violations

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java

Default MathContext is UNLIMITED.

[BACKLOG-31920] NPE when using Big Number in Calculator step

---

plugins/shapefilereader/core/src/main/java/org/pentaho/di/shapefilereader/ShapeFileReader.java
plugins/shapefilereader/core/src/main/java/org/pentaho/di/shapefilereader/ShapeFileReaderMeta.java

[CLEANUP] fixes checkstyle issues

---

assemblies/static/src/main/resources/ui/menubar.xul

[BACKLOG-30774] Update menu with new open/save dialog

---

engine/src/main/java/org/pentaho/di/core/util/serialization/MetaXmlSerializer.java
engine/src/main/java/org/pentaho/di/trans/steps/ldapinput/store/TrustAlwaysManager.java
engine/src/main/java/org/pentaho/di/trans/steps/webservices/WebService.java

using secure xml transformer
suppressing warnings in TrustAlwaysManager

[CLEANUP] addressing sonar violations

---

plugins/shapefilereader/core/pom.xml
plugins/shapefilereader/core/src/main/java/org/pentaho/di/shapefilereader/ShapeFileReader.java
plugins/shapefilereader/core/src/main/java/org/pentaho/di/ui/shapefilereader/ShapeFileReaderDialog.java
plugins/shapefilereader/core/src/test/java/org/pentaho/di/shapefilereader/ShapeFileReaderTest.java

Cherry-pick of:
- 61d2cbfd18ea44a23433340bdeb911fccba5f077
- 65a667a8ed51af5833b4d70268ecec518ec1f499 
- 6dd92965feb1a3f5a6368e7ce494b5c4393c5a5a
- c8ce50b53a80e9d0d601189689e816bb0f3b934d
@smmribeiro @gryphendowre

[SP-5304] - Backport of PDI-18335 - The output data of "ESRI Shapefile Reader" step are different from the preview data. (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/www/AddJobServlet.java
engine/src/main/java/org/pentaho/di/www/AddTransServlet.java
engine/src/main/java/org/pentaho/di/www/GetStatusServlet.java
engine/src/main/java/org/pentaho/di/www/StatusServletUtils.java

Sanitizing content derived from user input w/ Encode.forHtml.

[CLEANUP]  Addresses a handful of javasecurity:S5131 violations

---

dbdialog/src/main/resources/org/pentaho/ui/database/impala_native.xul

[BACKLOG-32219] Adding changes to support hadoop cluster field in database connection
Hey @angel-ramoscardona, @jgminder, @peterrinehart: Could you please take a look at this pull request? Thanks!

Impala Connection - Update UI for Named Cluster

---

engine/src/main/java/org/pentaho/di/job/entries/simpleeval/JobEntrySimpleEval.java

Since the variable can be a parameter, we need to use the VariableSpace.
@pentaho/tatooine @pentaho-lmartins @ppatricio

[PDI-18437] Simple Evaluation is true when string compared to NULL

---

plugins/pur/core/pom.xml

Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/501494191976ae9e7c7824266a238844442f65ab

[SP-5323] Backport of PPP-4447 - Use of vulnerable component - Tika Core 1.1x (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/test/java/org/pentaho/di/job/entries/job/JobEntryJobTest.java

Merge Masters: @pentaho-lmartins  and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/534670c21cf286cb291e1ba2f38949821e8a30a7

[SP-5325] Backport of PDI-18426 - Runtime parameter values for database logging are not passed to the Next level Jobs from the Main Job (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/kitchen/Kitchen.java
engine/src/main/java/org/pentaho/di/pan/Pan.java

Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/ab5d1cbb7c4dc38317383461ea565a2977bdee8c

[SP-5329] Backport of PDI-18228 - Pan bad read of Data Grid Step (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/test/java/org/pentaho/di/trans/TransTest.java

Merge Masters: @pentaho-lmartins  and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/392454f5eb5c3a03aef23c7a5a3350353f96d0d3

[SP-5324] Backport of PDI-18214 - If SQL fails in transformations ran on the Pentaho Server, the database connections are not closed. (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
engine/src/main/java/org/pentaho/di/job/entry/JobEntryBase.java
engine/src/test/java/org/pentaho/di/job/entry/JobEntryBaseTest.java

Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/8422c706cf37856c6cfa62d235703f6056dbdb12

[SP-5334] Backport of PDI-18396 - Job 'ZIP File' step generates wrong file path if period/dot in parent folder name (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/reservoirsampling/ReservoirSampling.java

Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/67c3d4a0c5df77eb908290ac762814324d1869c1

[SP-5336] Backport of PDI-18431 - Seed in Reservoir sampling step only using default parameters values (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/simpleeval/JobEntrySimpleEval.java

Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/d35c9d2ab8d890e1dd76325211434d6ad32410ae

[SP-5337] Backport of PDI-18437 - Simple Evaluation is "true" when string compared to NULL (8.3 Suite)

---

engine/src/main/resources/org/pentaho/libformula/editor/function/functions.xml
engine/src/main/resources/org/pentaho/libformula/editor/function/messages/messages_en_US.properties

Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/7543145b3bcf7205067bb0276c2d67cc40a61aa0

[SP-5338] Backport of PDI-17726 - Formula Editor Bug - Step Reports Error for 'MINUTE()', 'SECOND()' - works anyway, formula valid (8.3 Suite)

---

ui/src/main/java/org/pentaho/di/ui/spoon/partition/PartitionMethodSelector.java

@ssamora @pentaho-lmartins 
@dkincade 
Just to fix a Sonar code smell.

[PDI-15164] Partitioning Method Dialog- misspelling

---

ui/src/org/pentaho/di/ui/spoon/trans/TransPreviewDelegate.java

@ppatricio 
cherry-pick of 9bffc80202faa9102786c765c45a3e066c312073

[SP-5318] Backport of BACKLOG-22742

---

ui/src/main/java/org/pentaho/di/ui/spoon/partition/PartitionMethodSelector.java
ui/src/main/resources/org/pentaho/di/ui/spoon/partition/messages/messages_en_US.properties

Merge Masters: @pentaho-lmartins  and @smmribeiro
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/31cf5d95746011f599a871de6b3929589dd3a999
* https://github.com/Pentaho/pentaho-kettle/commit/4141f1f06f15df86c24b32453125ae4869044c89

[SP-5319] Backport of PDI-15164 - Partitioning Method Dialog- misspelling (8.3 Suite)

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileInputDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/textfileinput/TextFileInputDialog.java

PDI-12899 Text File Input - Disabled "Allow breaks in enclosed fields"

---

engine/src/main/java/org/pentaho/di/trans/steps/denormaliser/DenormaliserMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/denormaliser/DenormalizerMetaTest.java

Fixed and added unit test. The Denormaliser also did not honor:
-Grouping Symbol
-Decimal Symbol
-Currency Symbol

[PDI-17738] Row Denormaliser doesn't honor formats

---

engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java

Boolean values are stored as same as Integer values.
JIRA: https://jira.pentaho.com/browse/PDI-7339

[PDI-7339] PGBulkLoader: Store boolean values

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/DatabaseDelegate.java

[BISERVER-14355] - The JDBC connection pooling properties aren't getting mirrored from Pentaho (Merged) Server <=> Spoon

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransPreviewDelegate.java

Merge Masters: @ppatricio and @bcostahitachivantara
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/ee21fbe5d109118b2268bf423987389183329c10

[SP-5353] Backport of PDI-18091 - Preview data for Transformation Executor step shows conversion error when using parameters (8.3 Suite)

---

engine/src/main/resources/org/pentaho/di/trans/steps/tableoutput/messages/messages_en_US.properties

Merge Masters: @ppatricio and @bcostahitachivantara
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/d30f343175a89b6ae03ad1ab6c9f97b8d914dff8

[SP-5346] Backport of PDI-18257 - Metadata Injection configuration error on Table Output step (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java

[BACKLOG-31152] Make shim driver dir parameter visible to other

---

engine/src/main/java/org/pentaho/di/trans/steps/denormaliser/DenormaliserMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/denormaliser/DenormalizerMetaTest.java

Merge Masters: @ppatricio and @bcostahitachivantara
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/252ddf75cf783a743bd9b68b28888d0b094ef6a1

[SP-5363] Backport of PDI-17738 - Row Denormaliser step ignores number format (8.3 Suite)

---

plugins/connections/ui/src/main/resources/org/pentaho/di/connections/ui/dialog/messages/messages_en_US.properties

[BACKLOG-33146] Change to VFS browser help url

---

plugins/file-open-save-new/core/src/main/javascript/app/components/files/files.html

Reverts pentaho/pentaho-kettle#7208

Revert "[BACKLOG-33183] Disable copy/cut/paste"

---

plugins/file-open-save-new/core/src/main/javascript/app/components/filecontrols/filecontrols.component.js
plugins/file-open-save-new/core/src/main/javascript/app/components/filecontrols/filecontrols.html
plugins/file-open-save-new/core/src/main/resources/i18n/file-open-save-new/messages.properties
plugins/file-open-save-new/core/src/main/resources/i18n/file-open-save-new/messages_en.properties

[BACKLOG-32939] Tooltips are missing from icons in VFS browser

---

plugins/repositories/core/src/main/javascript/app/components/shared/error/error.component.js

- accessing jquery library via "jQuery" instead of alias "$"

[BACKLOG-33234] Repository Plugin Connect UI is broken

---

core/src/test/java/org/pentaho/di/core/row/value/timestamp/SimpleTimestampFormatTest.java

[TEST] Fixing SimpleTimestampFormatTest.testParseMultiThread()

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransPreviewDelegate.java

@pentaho-lmartins @pentaho/tatooine

[PDI-17471] Preview Dialog has sporadic behavior and no error logging

---

dbdialog/src/main/resources/org/pentaho/ui/database/databasedialog.xul

Increasing default height of the dbdialog.
https://jira.pentaho.com/browse/PDI-18589

[PDI-18589] PRD-dbdialog, some fields not visible in Ubuntu

---

dbdialog/src/main/resources/org/pentaho/ui/database/databasedialog.xul

More vertical pixels!
https://jira.pentaho.com/browse/PDI-18589

[PDI-18589] PRD -Redshift db conn, some fields not visible in Ubuntu

---

core/src/test/java/org/pentaho/di/core/row/RowMetaTest.java
core/src/test/java/org/pentaho/di/core/row/ValueMetaAndDataTest.java
core/src/test/java/org/pentaho/di/core/row/value/timestamp/SimpleTimestampFormatTest.java

Some tests set sys props, which can mess up other
tests which expect certain props.
Also did some minor cleanup.

[TEST] Fixing tests which fail depending on ordering

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaTimestamp.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaTimestampTest.java
engine/src/main/resources/kettle-variables.xml

Rebased https://github.com/pentaho/pentaho-kettle/pull/7007 from @LeonardoCoelho71950 .
@ssamora

[PDI-18369] Converting Integer to Timestamp type using Select values step results in incorrect date

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/mapping/MappingDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/simplemapping/SimpleMappingDialog.java
ui/src/main/java/org/pentaho/di/ui/util/MappingUtil.java
ui/src/test/java/org/pentaho/di/ui/util/MappingUtilTest.java

@pentaho/tatooine @pentaho-lmartins

[PDI-18405] Subtransformation Mapping not Loading in Editor

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/org/pentaho/di/job/entries/trans/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialog.java

remote transformation finishes running.

[PDI-18578] Give users the option to not send result data rows when a

---

plugins/file-open-save-new/core/src/main/javascript/app/components/folder/folder.component.js

[PDI-18612] fix for VFS browser file sorting

---

engine/src/test/java/org/pentaho/di/core/util/AsyncDatabaseActionTest.java
engine/src/test/java/org/pentaho/di/job/entries/evaluatetablecontent/JobEntryEvalTableContentTest.java

Setting values that could be modified elsewhere.

[TEST] Fixes for sporadically breaking tests.

---

plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerDialog.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerMeta.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java
plugins/streaming/impls/mqtt/src/main/resources/org/pentaho/di/trans/step/mqtt/messages/messages_en_US.properties

Reverts pentaho/pentaho-kettle#7254

Revert "[PDI-18501] MQTT Client Step to Include "Client ID" to Allow Persistent Connections"

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/org/pentaho/di/job/entries/trans/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialog.java

Reverts pentaho/pentaho-kettle#7256

Revert "[PDI-18578] Give users the option to not send result data rows when a"

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/ArgumentsDialog.java
ui/src/main/java/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java

[PDI-17609] - Run Options dialog doesn't scale

---

plugins/file-open-save-new/core/src/main/javascript/app/services/folder.service.js
plugins/file-open-save-new/core/src/main/javascript/app/services/providers/vfs.service.js

- propogate error message back to app.component.js

[PDI-18608] When AWS token has expires using VFS Browser no indication

---

core/src/main/java/org/pentaho/di/core/osgi/api/NamedClusterOsgi.java

* [BAD-1907] Updating license headers

[BAD-1907] Plain text password is stored in the shim configuration files

---

dbdialog/src/main/resources/org/pentaho/ui/database/databasedialog.xul

Cherry-pick of:
https://github.com/pentaho/pentaho-kettle/pull/7231
https://github.com/pentaho/pentaho-kettle/pull/7236

[SP-5417] Backport of PDI-18589 - PRD - When creating a Redshift database connection, some fields are not visible. Ubuntu only (9.0 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/repository/RepositoryImporter.java

Merge Masters: @ssamora 
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/0b664b8e4bc5787afbf28efa5e15630ebf044972

[SP-5404] Backport of PDI-18461 - A subjob's directory will be incorrect when imported into Spoon to a different directory (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/repository/RepositoryImporter.java

Merge Masters: @ssamora
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/0b664b8e4bc5787afbf28efa5e15630ebf044972

[SP-5405] Backport of PDI-18461 - A subjob's directory will be incorrect when imported into Spoon to a different directory (9.0 Suite)

---

core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/main/java/org/pentaho/di/core/database/DatabaseFactory.java
core/src/main/java/org/pentaho/di/core/database/DatabaseTestResults.java
core/src/main/resources/org/pentaho/di/core/database/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/core/database/dialog/DataOverrideHandler.java

[BACKLOG-28778] Adding changes to show custom dialog on error or success
[BACKLOG-28778] Capturing specific SQL Exception and setting message for user
[BACKLOG-28778] Moving exception text to properties file
[BACKLOG-28778] Changing connection message to be more generic
[BACKLOG-28778] Exception message grammar tweaks

[BACKLOG-28778] Connection Dialog - No suitable Driver error when Host Name has a special character

---

core/src/main/java/org/pentaho/di/cluster/HttpUtil.java
core/src/main/java/org/pentaho/di/core/injection/DefaultInjectionTypeConverter.java
core/src/main/java/org/pentaho/di/core/injection/InjectionTypeConverter.java
core/src/main/java/org/pentaho/di/core/row/SpeedTest.java
core/src/main/java/org/pentaho/di/core/util/SocketUtil.java
core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java

* HttpUtil
* DefaultInjectionTypeConverter
* InjectionTypeConverter
* SpeedTest
* SocketUtil
* XMLHandler

[CLEANUP] Cleanup Sonar issues

---

core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/test/java/org/pentaho/di/core/vfs/KettleVFSTest.java

Reverts pentaho/pentaho-kettle#7315

Revert "[SP-5445] Backport of PDI-18630 - VFS Process files Copy operation fa…"

---

engine/src/main/java/org/pentaho/di/job/JobMeta.java

to problems with resolving paths in nested job steps.

[PDI-18621] Setting internal directory variables from the parent leads

---

core/pom.xml
core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/main/resources/org/pentaho/di/core/vfs/providers.xml
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
plugins/google-analytics/core/pom.xml
plugins/gpload/pom.xml
plugins/json/core/pom.xml
plugins/openerp/pom.xml
plugins/pentaho-googledrive-vfs/core/pom.xml
plugins/repositories/core/pom.xml

This reverts commit 1da612ecfe40d087a8b5c93cff577d92f263db7b, reversing
changes made to 126227e8c8b5793bbcd3e3f775a43a398cbbf868.
This Revert PR is part of a series:
- https://github.com/pentaho/maven-parent-poms/pull/229
- https://github.com/pentaho/apache-vfs-browser/pull/62
- https://github.com/pentaho/big-data-plugin/pull/2040
- https://github.com/webdetails/cpk/pull/87
- https://github.com/pentaho/data-access/pull/1091
- https://github.com/pentaho/mondrian/pull/1202
- https://github.com/pentaho/pdi-jms-plugin/pull/76
- https://github.com/pentaho/pdi-platform-utils-plugin/pull/104
- https://github.com/pentaho/pdi-plugins-ee/pull/174
- https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/84
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/53
- …

Revert "Merge pull request #7313 from gryphendowre/SP-5370"

---

core/src/main/java/org/pentaho/di/core/osgi/api/NamedClusterOsgi.java

This reverts commit 873b2faadbf6c9e24691cbc4fa11ceef1527a363, reversing
changes made to 86c363365aac4d0cbefb482f3df1454b31d2f4d0.
PR is a set of Revert PRs:
- https://github.com/pentaho/pentaho-hadoop-shims/pull/1125
- https://github.com/pentaho/pentaho-yarn-kettle-plugin/pull/404
- https://github.com/pentaho/big-data-plugin/pull/2041
- https://github.com/pentaho/pentaho-big-data-ee/pull/445
- https://github.com/pentaho/pentaho-kettle/pull/7336

Revert "Merge pull request #7288 from gryphendowre/SP-5422"

---

engine/src/main/java/org/pentaho/di/core/compress/zip/ZIPCompressionInputStream.java
engine/src/main/java/org/pentaho/di/core/util/FileUtil.java
engine/src/main/java/org/pentaho/di/core/util/JavaScriptUtils.java
engine/src/main/java/org/pentaho/di/core/util/PluginPropertyHandler.java
engine/src/main/java/org/pentaho/di/job/JobHopMeta.java

Cleanup for the following files:
- ZIPCompressionInputStream
- FileUtil
- JavaScriptUtils
- PluginPropertyHandler
- JobHopMeta

[CLEANUP] Sonar Cleanup

---

core/src/main/java/org/pentaho/di/core/database/Database.java

Reverts pentaho/pentaho-kettle#7349

Revert "[PDI-18555] Added logic to handle NULL in row level log timeout"

---

engine/src/main/java/org/pentaho/di/core/logging/BaseLogTable.java

Reverts pentaho/pentaho-kettle#7354

Revert "[PDI-18555] Added logic to omit disabled log fields from ktrs and kjbs"

---

plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationSaveExtensionPoint.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationSaveExtensionPointTest.java

Reverts pentaho/pentaho-kettle#7351

Revert "[PDI-18665] NPE when editing job or transformation job entries at job…"

---

ui/src/main/java/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java

[PDI-17609] Run Options dialog doesn't scale

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java
engine/src/main/java/org/pentaho/di/trans/steps/rest/StringMessageBodyWriter.java
engine/src/test/java/org/pentaho/di/trans/steps/rest/RestTest.java
engine/src/test/java/org/pentaho/di/trans/steps/rest/StringMessageBodyWriterTest.java

@ssamora 
@ppatricio 
@smmribeiro

[SP-5396] - Backport of PDI-17423 - PDI REST Client Not Sending Content-Length(setting chunked) (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java
engine/src/main/java/org/pentaho/di/trans/steps/rest/StringMessageBodyWriter.java
engine/src/test/java/org/pentaho/di/trans/steps/rest/RestTest.java
engine/src/test/java/org/pentaho/di/trans/steps/rest/StringMessageBodyWriterTest.java

@ssamora 
@ppatricio 
@smmribeiro

[SP-5397] - Backport of PDI-17423 - PDI REST Client Not Sending Content-Length(setting chunked) (9.0 Suite)

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/transexecutor/TransExecutorDialog.java

[SP-5562] Backport of PDI-18498 - Transformation executor error passing transformation name with path in parameter (9.0 Suite)

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/transexecutor/TransExecutorDialog.java

[SP-5561] Backport of PDI-18498 - Transformation executor error passing transformation name with path in parameter (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/databaselookup/DefaultCache.java
engine/src/test/java/org/pentaho/di/trans/steps/databaselookup/DefaultCacheTest.java

cherry-pick of 3ac8ec5 and 9fcfb00
@pentaho-lmartins @bcostahitachivantara @smmribeiro @ppatricio

[SP-5564] Backport of PDI-18547 - DB lookup Step retrieves the last row when "Load All Data" option is enabled. (9.0 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/databaselookup/DefaultCache.java
engine/src/test/java/org/pentaho/di/trans/steps/databaselookup/DefaultCacheTest.java

cherry-pick of 3ac8ec5 and 9fcfb00
@pentaho-lmartins @bcostahitachivantara @smmribeiro @ppatricio

[SP-5563] Backport of PDI-18547 - DB lookup Step retrieves the last row when "Load All Data" option is enabled. (8.3 Suite)

---

assemblies/static/pom.xml
assemblies/static/src/main/resources-filtered/Encr.bat
assemblies/static/src/main/resources-filtered/encr.sh
core/pom.xml
core/src/test/resources/kettle-password-encoder-plugins.xml
plugins/connections/ui/pom.xml
plugins/repositories/core/pom.xml
plugins/streaming/impls/jms/pom.xml

Also fixed versioning on encr command line scripts

[BISERVER-3497] pentaho-support-encyption unit test fixes

---

engine/src/main/java/org/pentaho/di/trans/steps/datagrid/DataGrid.java
engine/src/main/java/org/pentaho/di/trans/steps/datagrid/DataGridMeta.java
engine/src/main/resources/org/pentaho/di/trans/steps/datagrid/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/steps/datagrid/DataGridMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/datagrid/DataGrid_EmptyStringVsNull_Test.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/datagrid/DataGridDialog.java

data grid in order to allow whitespace-only values to be generated.

[PDI-18534] Add the "Null if" option found on text file input steps to

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileCSVImportProgressDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/textfileinput/TextFileCSVImportProgressDialog.java

Removed empty debug System.out.println()
This commit is a cherry-pick from master commit 13e8a4804e

[SP-5616] -Backport of PDI-18757-

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileCSVImportProgressDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/textfileinput/TextFileCSVImportProgressDialog.java

Removed empty debug System.out.println()
This commit is a cherry-pick from master commit 13e8a4804e

[SP-5617] -Backport of PDI-18757-

---

engine/src/main/java/org/pentaho/di/trans/steps/mail/Mail.java
engine/src/test/java/org/pentaho/di/trans/steps/mail/MailTest.java

@pentaho-lmartins @ppatricio @bcostahitachivantara @smmribeiro

[PDI-18225] "Mail" step with "Wildcard field" ignores Regular Expression

---

core/src/main/java/org/pentaho/di/core/database/ConnectionPoolUtil.java
core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/test/java/org/pentaho/di/core/database/ConnectionPoolUtilTest.java

@ssamora 
@ppatricio 
@smmribeiro

[BISERVER-14442] - Database connections using connection pooling will not adhere to changes in the connection details

---

core/src/main/java/org/pentaho/di/core/database/ConnectionPoolUtil.java
core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/test/java/org/pentaho/di/core/database/ConnectionPoolUtilTest.java

Reverts pentaho/pentaho-kettle#7506

Revert "[BISERVER-14442] - Database connections using connection pooling will not adhere to changes in the connection details"

---

ui/src/main/java/org/pentaho/di/ui/core/widget/MultipleSelectionCombo.java
ui/src/main/java/org/pentaho/di/ui/core/widget/SelectionLabel.java

[TAP-1049] adds selection labels to multiselect dropdown

---

engine/src/main/java/org/pentaho/di/trans/steps/mail/Mail.java
engine/src/test/java/org/pentaho/di/trans/steps/mail/MailTest.java

[PDI-18663] Mail step - Is zip filename dynamic option does not work

---

plugins/json/core/pom.xml
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerTest.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzerTest.java

[PDI-18657] Memory leak when customer executes jobs on the server

---

engine/src/main/resources/org/pentaho/di/trans/steps/pentahoreporting/messages/messages_en_US.properties

@ssamora 
@ppatricio 
@smmribeiro

[PDI-18089] - MDI cannot inject Report Definition File to Pentaho Reporting Output

---

core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java

Reverting this commit and handling it differently within big-data-plugin's S3 client code.

[BACKLOG-34406] Revert "[TAP-908] Set the default file system options for S3 to the default S3 VFS."

---

engine/src/main/java/org/pentaho/di/www/StartJobServlet.java
engine/src/main/resources/org/pentaho/di/www/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/www/StartJobServletTest.java

Recreated the PR related with https://github.com/pentaho/pentaho-kettle/pull/7585 due to merging conflicts after the 9.1 code freeze.
@pentaho-lmartins @ppatricio @smmribeiro

[PDI-17007] Issues with Carte Jobs API startJob endpoint in Pentaho REST API

---

core/src/main/java/org/pentaho/di/connections/ConnectionDetails.java
core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
core/src/main/java/org/pentaho/di/connections/vfs/providers/other/OtherConnectionDetails.java
core/src/test/java/org/pentaho/di/connections/ConnectionManagerTest.java
core/src/test/java/org/pentaho/di/connections/common/bucket/TestConnectionDetails.java
core/src/test/java/org/pentaho/di/connections/common/domain/TestConnectionWithDomainDetails.java
plugins/connections/ui/src/test/java/org/pentaho/di/connections/ui/TestConnectionDetails.java
plugins/file-open-save-new/core/src/main/resources-filtered/OSGI-INF/blueprint/blueprint.xml

Reverts pentaho/pentaho-kettle#7659

Revert "[BACKLOG-34496] remove credentials from VFS Connections in embedded m…"

---

core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java
core/src/main/resources/org/pentaho/di/core/xml/messages/messages.properties
core/src/test/java/org/pentaho/di/core/xml/XMLHandlerTest.java

Now, before trying to read the file, the file is checked for existence.
@pentaho-lmartins @ssamora @ppatricio @bcostahitachivantara

[PDI-18885] Performance degradation due to opening of XML files.

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java

@ssamora 
@ppatricio 
@smmribeiro 
I have not attach any unit test, because the fix was inside of anonymous class. 
Besides that this was a typo because on others similar anonymous classes it was passed the correct variable.

[PDI-18876] - Calling API and passing Encrypted passwords fails to Decrypt password resulting in locked accounts

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/job/entries/shell/JobEntryShell.java
engine/src/main/resources/kettle-variables.xml
engine/src/main/resources/org/pentaho/di/job/entries/shell/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/job/entries/shell/JobEntryShellTest.java

Based on https://github.com/pentaho/pentaho-kettle/pull/7603
@ppatricio 
@ssamora

[PDI-18803] - Shell Job entry Argument List too long

---

engine/src/main/java/org/pentaho/di/trans/steps/calculator/Calculator.java
engine/src/test/java/org/pentaho/di/trans/steps/calculator/CalculatorUnitTest.java

@pentaho-lmartins @ppatricio @ssamora @bcostahitachivantara @belxiors

[PDI-18923] Calculator Step: Date A - Date B(hours)

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtilsTest.java

@ssamora 
@ppatricio 
@smmribeiro

[PDI-18868] - The Text File Input step does not handle line breaks correctly

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java

@ssamora 
@smmribeiro 
@belxiors

[SP-5763] - Backport of PDI-18876 - Calling API and passing Encrypted passwords fails to Decrypt password resulting in locked accounts (8.3 Suite)

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java

@ssamora 
@smmribeiro 
@belxiors

[SP-5764] - Backport of PDI-18876 - Calling API and passing Encrypted passwords fails to Decrypt password resulting in locked accounts (9.1 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtilsTest.java

@ssamora 
@smmribeiro 
@belxiors

[SP-5770] - Backport of PDI-18868 - The Text File Input step does not handle line breaks correctly (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtilsTest.java

@ssamora 
@smmribeiro 
@belxiors

[SP-5771] - Backport of PDI-18868 - The Text File Input step does not handle line breaks correctly (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/job/entries/shell/JobEntryShell.java
engine/src/main/resources/kettle-variables.xml
engine/src/main/resources/org/pentaho/di/job/entries/shell/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/job/entries/shell/JobEntryShellTest.java

[SP-5755] - Backport of PDI-18803 - Shell Job entry Argument List too long (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/job/entries/shell/JobEntryShell.java
engine/src/main/resources/kettle-variables.xml
engine/src/main/resources/org/pentaho/di/job/entries/shell/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/job/entries/shell/JobEntryShellTest.java

[SP-5756] - Backport of PDI-18803 - Shell Job entry Argument List to long (9.1 Suite)

---

engine/src/main/java/org/pentaho/di/www/StatusServletUtils.java

[PDI-18856] - PDI Kettle Status Page - Sapphire Theme - Transformation/Job Table Records & References to mantleRuby.css

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
engine/src/main/resources/kettle-variables.xml

[PDI-19020] - White Spaces are ignored in a JSON Input step

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMetaTest.java

[PDI-18935] - Tranformation converting Date to EPOCH giving inconsistent result when executed with or without connecting to repository

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
engine/src/main/resources/kettle-variables.xml

[SP-5822] - Backport of PDI-19020 - White Spaces are ignored in a JSON Input step (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
engine/src/main/resources/kettle-variables.xml

[SP-5821] - Backport of PDI-19020 - White Spaces are ignored in a JSON Input step (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtilsTest.java

[PDI-18918] - [Text file input] - When the enclosure = ) an error is displayed and it is not possible to preview rows

---

engine/src/main/java/org/pentaho/di/trans/steps/delete/DeleteMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/delete/DeleteMetaTest.java

[PDI-18387] - Fields defined in "Key(s) to look up the values" goes missing in the Delete Step

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataMeta.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataMetaTest.java

[PDI-19013] - Get data from XML: "Size field" value not saved when the transformation is saved in repository

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataMeta.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataMetaTest.java

[SP-5853] - Backport of PDI-19013 - Get data from XML: "Size field" value not saved when the transformation is saved in repository (8.3 Suite)

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataMeta.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataMetaTest.java

[SP-5854] - Backport of PDI-19013 - Get data from XML: "Size field" value not saved when the transformation is saved in repository (9.1 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
engine/src/main/java/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepMeta.java

Please, don't forget to squash.
@pentaho-lmartins @ssamora @bcostahitachivantara

[PDI-18294] Limitation with Excel Writer step - appending data to an existing XLSX document does not work when "Stream XLSX data" is enabled.

---

engine/src/main/java/org/pentaho/di/trans/steps/formula/RowForumulaContext.java
engine/src/test/java/org/pentaho/di/trans/steps/formula/RowForumulaContextTest.java

[PDI-18402] - Formula step not considering the metadata of the column when performing the logical operations.

---

core/src/main/java/org/pentaho/di/core/vfs/SftpFileObjectWithWindowsSupport.java
core/src/main/java/org/pentaho/di/core/vfs/SftpFileSystemWindows.java
core/src/main/java/org/pentaho/di/core/vfs/SftpFileSystemWindowsProvider.java
core/src/test/java/org/pentaho/di/core/vfs/SftpFileObjectWithWindowsSupportTest.java

being closed when multiple transformations are starting and stopping on
the same spoon/carte/server instance.

[PDI-18729] Improve synchronization to prevent sftp connections from

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtilsTest.java
ui/src/main/java/org/pentaho/di/ui/trans/step/common/CsvInputAwareStepDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileCSVImportProgressDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileInputDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/textfileinput/TextFileCSVImportProgressDialog.java

[PDI-18962] - Text File Input - Escaped Charaters (\) are not recognized

---

core/src/main/java/org/pentaho/di/core/variables/Variables.java
engine/src/test/java/org/pentaho/di/job/JobMetaTest.java

[PDI-18655] - Variables.initializeVariablesFrom susceptible to NullPointerException

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

[PDI-19049] - v8.3 : Job/Transformation with .KTR/.KJB extension fails to open from Parent Job reference.

---

engine/src/main/java/org/pentaho/di/core/KettleEnvironment.java

[PDI-18929] - Pan - Incomplete log information

---

core/src/main/java/org/pentaho/di/core/database/AzureSqlDataBaseMeta.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/main/resources/kettle-database-types.xml
core/src/test/java/org/pentaho/di/core/database/AzureSqlDataBaseMetaTest.java
dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java
dbdialog/src/main/resources/org/pentaho/ui/database/azuresqldb_native.xul
dbdialog/src/main/resources/org/pentaho/ui/database/databasedialog.properties

Adding Azure Sql Database, SQL data sources types to PDI.
We have not added support for Azure Active Directory - Integrated authentication mode as we have an open issue going on with Microsoft regarding that.

Backlog 34960

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtilsTest.java
ui/src/main/java/org/pentaho/di/ui/trans/step/common/CsvInputAwareStepDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileCSVImportProgressDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileInputDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/textfileinput/TextFileCSVImportProgressDialog.java

[SP-5888] - Backport of PDI-18962 - Text File Input - Escaped Charaters (\) are not recognized (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtilsTest.java
ui/src/main/java/org/pentaho/di/ui/trans/step/common/CsvInputAwareStepDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileCSVImportProgressDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileInputDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/textfileinput/TextFileCSVImportProgressDialog.java

[SP-5889] - Backport of PDI-18962 - Text File Input - Escaped Charaters (\) are not recognized (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/logging/LogChannel.java
core/src/main/java/org/pentaho/di/core/logging/LogChannelInterface.java
core/src/main/java/org/pentaho/di/core/logging/LoggingObjectInterface.java
core/src/main/java/org/pentaho/di/core/logging/LoggingObjectLifecycleInterface.java
core/src/test/java/org/pentaho/di/core/logging/LogChannelTest.java
engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/test/java/org/pentaho/di/job/JobTest.java
engine/src/test/java/org/pentaho/di/trans/TransTest.java

[PDI-13610] - Job "Last Log Date" value not updating

---

engine/src/main/java/org/pentaho/di/trans/steps/http/HTTP.java
engine/src/test/java/org/pentaho/di/trans/steps/http/HTTPTest.java

[PDI-18951] - HTTP Client no longer handles Basic Authentication being passed to other servers

---

plugins/json/assemblies/plugin/pom.xml
plugins/json/core/pom.xml
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInputData.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/reader/CloseableIterator.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/reader/InputsReader.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReaderTest.java
plugins/json/pom.xml

Main improvements:
- avoid cloning unnecessary objects
- guarantee that resources are freed and try to do it as soon as possible
I've also:
- upgraded jayway version (and related dependencies)
- removed avoidable POI dependency
@ssamora @bcostahitachivantara

[PDI-18930] JSON Input Step Performance Degradation and Memory Leak

---

engine/src/main/java/org/pentaho/di/core/KettleEnvironment.java

[SP-5896] - Backport of PDI-18929 - Pan - Incomplete log information (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/core/KettleEnvironment.java

[SP-5897] - Backport of PDI-18929 - Pan - Incomplete log information (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/fileinput/FileInputList.java
core/src/test/java/org/pentaho/di/core/fileinput/FileInputListTest.java

is now encoding them (and wasn't before).

[BACKLOG-35111] Decode file name URI since the commons-vfs file system

---

engine/src/main/java/org/pentaho/di/trans/steps/httppost/HTTPPOST.java

[PDI-18955] - HTTP Post no longer handles Basic Authentication being passed to other servers

---

engine/src/it/java/org/pentaho/di/www/RegisterPackageServletIT.java

[TEST] Test is failing with no indication of what the expected vs actual

---

engine/src/main/java/org/pentaho/di/resource/SimpleResourceNaming.java
engine/src/test/java/org/pentaho/di/resource/SimpleResourceNamingTest.java

@ssamora 
@smmribeiro 
@moraesvc

[PDI-17515] - Duplicate parameter 'DATA_PATH_1' detected error is thrown when we Schedule the job which has sub jobs and transformation.

---

assemblies/client/pom.xml
assemblies/client/src/assembly/assembly.xml
assemblies/lib/pom.xml
pom.xml
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/job/JobGraph.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java

@pminutillo @rmansoor 
@gkuntsevich

[PDI-18866] Mac OS X Unable to start pdi by spoon.sh

---

assemblies/client/pom.xml
assemblies/client/src/assembly/assembly.xml
assemblies/lib/pom.xml
pom.xml
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/job/JobGraph.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java

Reverts pentaho/pentaho-kettle#7930

Revert "[PDI-18866] Mac OS X Unable to start pdi by spoon.sh"

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/ResultFile.java
core/src/main/java/org/pentaho/di/core/fileinput/FileInputList.java
core/src/test/java/org/pentaho/di/core/fileinput/FileInputListTest.java
engine/src/main/java/org/pentaho/di/trans/steps/excelinput/ExcelInput.java
engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputStep.java
engine/src/main/java/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java
engine/src/main/java/org/pentaho/di/trans/steps/getsubfolders/GetSubFolders.java
engine/src/main/java/org/pentaho/di/trans/steps/ldifinput/LDIFInput.java
engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInput.java
engine/src/main/java/org/pentaho/di/trans/steps/propertyinput/PropertyInput.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/src/main/java/org/pentaho/di/trans/steps/xbaseinput/XBaseInput.java

Create a parameter to allow them to be encoded if desired.

[BACKLOG-35111] Fix additional places where URIs are now being encoded.

---

assemblies/client/pom.xml
assemblies/client/src/assembly/assembly.xml
assemblies/lib/pom.xml
pom.xml
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/job/JobGraph.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java

Reverts pentaho/pentaho-kettle#7939
@rmansoor @pminutillo

Revert "Revert "[PDI-18866] Mac OS X Unable to start pdi by spoon.sh""

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/jxl/XLSWorkbook.java

[PDI-18941] VFS path causes file locking issue

---

engine/src/main/java/org/pentaho/di/trans/steps/http/HTTP.java
engine/src/test/java/org/pentaho/di/trans/steps/http/HTTPTest.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5924] - Backport of PDI-18951 - HTTP Client no longer handles Basic Authentication being passed to other servers (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/http/HTTP.java
engine/src/test/java/org/pentaho/di/trans/steps/http/HTTPTest.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5925] - Backport of PDI-18951 - HTTP Client no longer handles Basic Authentication being passed to other servers (9.1 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/httppost/HTTPPOST.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5926] - Backport of PDI-18955 - HTTP Post no longer handles Basic Authentication being passed to other servers (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/httppost/HTTPPOST.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5927] - Backport of PDI-18955 - HTTP Post no longer handles Basic Authentication being passed to other servers (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5930] - Backport of PDI-19049 - v8.3 : Job/Transformation with .KTR/.KJB extension fails to open from Parent Job reference. (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5931] - Backport of PDI-19049 - v8.3 : Job/Transformation with .KTR/.KJB extension fails to open from Parent Job reference. (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/logging/LogChannel.java
core/src/main/java/org/pentaho/di/core/logging/LogChannelInterface.java
core/src/main/java/org/pentaho/di/core/logging/LoggingObjectInterface.java
core/src/main/java/org/pentaho/di/core/logging/LoggingObjectLifecycleInterface.java
core/src/test/java/org/pentaho/di/core/logging/LogChannelTest.java
engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/test/java/org/pentaho/di/job/JobTest.java
engine/src/test/java/org/pentaho/di/trans/TransTest.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5915] - Backport of PDI-13610 - Job "Last Log Date" value not updating (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/logging/LogChannel.java
core/src/main/java/org/pentaho/di/core/logging/LogChannelInterface.java
core/src/main/java/org/pentaho/di/core/logging/LoggingObjectInterface.java
core/src/main/java/org/pentaho/di/core/logging/LoggingObjectLifecycleInterface.java
core/src/test/java/org/pentaho/di/core/logging/LogChannelTest.java
engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/test/java/org/pentaho/di/job/JobTest.java
engine/src/test/java/org/pentaho/di/trans/TransTest.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5914] - Backport of PDI-13610 - Job "Last Log Date" value not updating (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/jxl/XLSWorkbook.java

[SP-5939] - Backport of PDI-18941 - VFS path causes file locking issue (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/jxl/XLSWorkbook.java

[SP-5940] - Backport of PDI-18941 - VFS path causes file locking issue (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/util/HttpClientManager.java
engine/src/main/java/org/pentaho/di/core/HTTPProtocol.java

@ssamora 
@smmribeiro 
@moraesvc

[PDI-19177] - Web Service Lookup fails in 9.1 with Connection pool shut down error

---

plugins/file-stream/pom.xml
plugins/streaming/impls/mqtt/pom.xml
pom.xml

DO NOT MERGE!  Will be merged by automation after validation

[DEVO-851] set repo from nexus to artifactory

---

engine/src/main/resources/org/pentaho/di/trans/steps/tableinput/messages/messages_en_US.properties

@ssamora 
@smmribeiro 
@moraesvc

[PDI-19181] - Line numbers and finished reading query statement not displayed with Table Input Step

---

assemblies/lib/pom.xml

order to avoid pulling in Java 11 artifacts.

[CLEANUP] Need to specify the versions of some eclipse dependencies in

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Reverts pentaho/pentaho-kettle#8008

Revert "[PDI-19138] JSON input: Step does not return record when trying to re…"

---

engine/src/main/java/org/pentaho/di/job/entries/http/JobEntryHTTP.java
engine/src/test/java/org/pentaho/di/job/entries/http/JobEntryHTTP_PDI_19104_Test.java

@ssamora 
@smmribeiro 
@moraesvc

[PDI-19104] - Getting "Illegal character in opaque part at index" error when using the "file:\" protocol in the HTTP Job Entry.

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileOutputMeta.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/JsonOutput.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/JsonOutputMeta.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsonoutput/JsonOutputMetaTest.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsonoutput/JsonOutputTest.java

@ssamora 
@smmribeiro 
@moraesvc

[PDI-19064] - The Append Option in JSON Output will create new files when the number of rows exceed the number of blocs

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/TransDelegate.java

information in the repository.

[PDI-19211] Implement code to save and restore transformation dependency

---

core/src/main/java/org/pentaho/di/core/util/HttpClientManager.java
engine/src/main/java/org/pentaho/di/core/HTTPProtocol.java

@ssamora 
@smmribeiro 
@moraesvc

[SP-5987] - Backport of PDI-19177 - Web Service Lookup fails in 9.1 with Connection pool shut down error (9.2 Suite)

---

engine/src/main/resources/org/pentaho/di/trans/steps/tableinput/messages/messages_en_US.properties

@ssamora 
@smmribeiro 
@moraesvc

[SP-6002] - Backport of PDI-19181 - Line numbers and finished reading query statement not displayed with Table Input Step (8.3 Suite)

---

engine/src/main/resources/org/pentaho/di/trans/steps/tableinput/messages/messages_en_US.properties

@ssamora 
@smmribeiro 
@moraesvc

[SP-6003] - Backport of PDI-19181 - Line numbers and finished reading query statement not displayed with Table Input Step (9.2 Suite)

---

engine/src/main/java/org/pentaho/di/www/AddTransServlet.java
engine/src/test/java/org/pentaho/di/www/AddTransServletTest.java

@bcostahitachivantara @smmribeiro @moraesvc

[PDI-16980] Issues with Carte Transformations API addTrans endpoint in Pentaho REST API

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/TransDelegate.java

information in the repository.

[SP-6010] Implement code to save and restore transformation dependency

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/TransDelegate.java

information in the repository.

[SP-6009] Implement code to save and restore transformation dependency

---

engine/pom.xml
engine/src/main/java/org/pentaho/di/trans/steps/excelinput/poi/PoiCell.java
engine/src/main/java/org/pentaho/di/trans/steps/excelinput/poi/PoiWorkbook.java
engine/src/main/java/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
engine/src/main/java/org/pentaho/di/www/GetJobImageServlet.java
engine/src/main/java/org/pentaho/di/www/GetJobStatusServlet.java
engine/src/main/java/org/pentaho/di/www/JobMap.java
engine/src/main/java/org/pentaho/di/www/exception/DuplicateKeyException.java
engine/src/test/java/org/pentaho/di/www/GetJobStatusServletTest.java
plugins/xml/pom.xml

Cherry pick of:
- [pentaho-kettle#7817](https://github.com/pentaho/pentaho-kettle/pull/7817)
Note that '\plugins\json\core\pom.xml' was not backported as a subsequent backported development removed the affected entries
- [pentaho-kettle#7846](https://github.com/pentaho/pentaho-kettle/pull/7846)
@ssamora @bcostahitachivantara @moraesvc

[SP-5994] Backport of PPP-4590 - XML External Entity (XXE) vulnerability when reading XLSX files (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/step/BaseStep.java

@ssamora 
@smmribeiro 
@moraesvc

[PDI-19105] - Cartesian Join Results In: org.pentaho.di.core.BlockingBatchingRowSet cannot be cast to org.pentaho.di.core.BlockingRowSet

---

core/pom.xml
core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/osgi/api/NamedClusterOsgi.java
core/src/main/java/org/pentaho/di/core/osgi/api/NamedClusterSiteFile.java
core/src/main/java/org/pentaho/di/core/osgi/impl/NamedClusterSiteFileImpl.java

[CUST-253] - Requesting CUST for BAD-1920

---

assemblies/lib/pom.xml

[PDI-18966] Text File output does not write to named staging area with latest snowflake jdbc 3.12.x driver

---

plugins/elasticsearch-bulk-insert/core/src/main/java/org/pentaho/di/trans/steps/elasticsearchbulk/ElasticSearchBulkMeta.java

Deprecating Elastic search bulk insert inside CE

PDI-18618 | Elastic Search Bulk Insert step Support for ElasticSearch 7.x

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/json/core/src/main/resources/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties

@ssamora 
@smmribeiro 
@moraesvc

[PDI-19214] - JSON Input: "Is hidden filed" under Additional output field tab is not working as expected

---

core/src/main/java/org/pentaho/di/core/database/DatabaseInterface.java
core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMeta.java
core/src/test/java/org/pentaho/di/core/database/DatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMetaTest.java

[SP-6069] - Backport of PDI-18959 - Snowflake bulk loader step does not resolve variables in database connection before test (9.2 Suite)

---

core/src/main/java/org/pentaho/di/core/logging/LoggingBuffer.java

[SP-6071] - Backport of PDI-19367 - Fix for LoggingBuffer incorrectly returning log messages on empty lists. (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/logging/log4j/KettleLogChannelAppender.java
core/src/main/java/org/pentaho/di/core/logging/log4j/Log4jFileAppender.java
core/src/main/java/org/pentaho/di/core/logging/log4j/Log4jKettleLayout.java
core/src/main/java/org/pentaho/di/core/logging/log4j/Log4jLayout.java

[BISERVER-14773] Final sqoop changes; logging from sqoop job now being

---

pom.xml

@smmribeiro 
@andreramos89 
@renato-s

[BACKLOG-35399] - Update projects to include locale properties for integration test execution

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java

@smmribeiro 
@andreramos89 
@renato-s

[PDI-19378] - Pentaho 9.2 has much higher Voluntary Context Switches causing reduced performance

---

assemblies/core/static/src/main/resources/classes/log4j2.xml
assemblies/core/static/src/main/resources/system/osgi/log4j2.xml
assemblies/static/src/main/resources/classes/log4j2.xml
assemblies/static/src/main/resources/system/osgi/log4j2.xml
plugins/pur/core/src/test/resources/log4j2.xml

[BISERVER-14794] Upgrade log4j2

---

assemblies/core/static/src/main/resources/classes/log4j2.xml
assemblies/core/static/src/main/resources/system/osgi/log4j2.xml
assemblies/static/src/main/resources/classes/log4j2.xml
assemblies/static/src/main/resources/system/osgi/log4j2.xml
plugins/pur/core/src/test/resources/log4j2.xml

[SP-6107] [BISERVER-14794] Upgrade log4j2

---

assemblies/core/static/src/main/resources/classes/log4j2.xml
assemblies/core/static/src/main/resources/system/osgi/log4j2.xml
assemblies/static/src/main/resources/classes/log4j2.xml
assemblies/static/src/main/resources/system/osgi/log4j2.xml
plugins/pur/core/src/test/resources/log4j2.xml

[SP-6106] [BISERVER-14794] Upgrade log4j2

---

assemblies/lib/pom.xml

webservices-rt-2.3.1.jar to ensure consistent behavior.

[BACKLOG-35537] Remove jar file with duplicate jars found in

---

plugins/streaming/impls/mqtt/pom.xml
pom.xml

[BACKLOG-35509] Use settings in parent pom file to set project compiler

---

plugins/engine-configuration/assemblies/feature/src/main/feature/feature.xml
plugins/engine-configuration/impl/pom.xml
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/pentaho/scheduler/SchedulerRequest.java
plugins/engine-configuration/pom.xml

[BACKLOG-30667] - CSRF- /api/scheduler changes

[BACKLOG-30667] CSRF- /api/scheduler changes

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java

variable to resolve thread concurrency issues when running mulitple
streaming consumer batch threads.

[BACKLOG-35669] Add synchronization around the metaWithFieldOptions

---

assemblies/core/lib/pom.xml

This commit is a cherry-pick from master 5a01357

[BACKLOG-35774] Add missing depdenencies for karaf.

---

core/src/main/java/org/pentaho/di/core/logging/LoggingRegistry.java

[BISERVER-14832] Memory leak by executing data transformation

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

@smmribeiro 
@andreramos89 
@renato-s

[PDI-19445] - Json Parser syntax not working

---

core/src/main/java/org/pentaho/di/core/Condition.java
core/src/test/java/org/pentaho/di/core/ConditionTest.java

@smmribeiro 
@andreramos89 
@renato-s

[PDI-19396] - Error in Null Handling: Filter Rows, Anything using di.core.Condition

---

engine/pom.xml
ui/pom.xml

Hard-coding the Pentaho build to be used as base

[CUST-263] Changes in Pom Versions

---

core/src/main/java/org/pentaho/di/core/database/DataSourceProviderInterface.java
core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/test/java/org/pentaho/di/core/database/DatabaseTest.java

DB connections when the connection is defined using variables.

[PDI-18826] Pentaho platform needs to be able to provide pooled

---

engine/src/main/java/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
engine/src/test/java/org/pentaho/di/job/entries/zipfile/JobEntryZipFileMoveFilesTest.java

…ctory is specified in Source directory/file and Include sub-folders is Y

PDI-19480 : Zip file step- Subdirectories are not moved when a direct..

---

engine/src/test/java/org/pentaho/di/base/AbstractMetaTest.java

[TEST] Add a timeout to the thread safety test to keep any deadlocks

---

ui/pom.xml
ui/src/main/java/org/pentaho/di/ui/core/dialog/ThinDialog.java

Please, see main PR: https://github.com/pentaho/pentaho-platform/pull/5076.

[BACKLOG-35624] Changing call to j_spring_security_check to be CSRF safe

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/json/core/src/main/resources/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties

@smmribeiro 
@andreramos89 
@renato-s

[SP-6096] - Backport of PDI-19214 - JSON Input: "Is hidden filed" under Additional output field tab is not working as expected (8.3 Suite)

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/json/core/src/main/resources/org/pentaho/di/trans/steps/jsoninput/messages/messages_en_US.properties

@smmribeiro
@andreramos89
@renato-s

[SP-6097] - Backport of PDI-19214 - JSON Input: "Is hidden filed" under Additional output field tab is not working as expected (9.2 Suite)

---

core/src/main/java/org/pentaho/di/core/Condition.java
core/src/test/java/org/pentaho/di/core/ConditionTest.java

@smmribeiro 
@andreramos89 
@renato-s

[SP-6122] - Backport of PDI-19396 - Error in Null Handling: Filter Rows, Anything using di.core.Condition (9.2 Suite)

---

engine/src/main/java/org/pentaho/di/www/ExecuteTransServlet.java

[SP-6090] Backport of PDI-19320 - XML output with servlet with carte sh (9.2 Suite)

---

engine/src/main/java/org/pentaho/di/www/ExecuteTransServlet.java

[SP-6090] Backport of PDI-19320 - XML output with servlet with carte.sh (9.2 Suite)

---

engine/pom.xml
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
plugins/pur/core/src/main/java/com/pentaho/di/purge/PurgeUtilityHTMLLayout.java
plugins/pur/core/src/main/java/com/pentaho/di/purge/PurgeUtilityLog.java
plugins/pur/core/src/main/java/com/pentaho/di/purge/PurgeUtilityLogger.java
plugins/pur/core/src/main/java/com/pentaho/di/purge/PurgeUtilityTextLayout.java
plugins/pur/core/src/test/java/com/pentaho/di/purge/PurgeUtilityLoggerTest.java

[SP-6106] - Correct unit test failures related to log4j changes.

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java

[SP-6128] Backport of PDI-19423 - Calculator step: The result of SQRT(A*A+B*B) is incorrect (9.3 Suite)

---

core/src/main/java/org/pentaho/di/core/service/PluginServiceLoader.java
core/src/main/java/org/pentaho/di/core/service/ProviderServicePriority.java
core/src/main/java/org/pentaho/di/core/service/ServiceProviderInterface.java
plugins/connections/ui/pom.xml
plugins/connections/ui/src/main/java/org/pentaho/di/connections/ui/endpoints/ConnectionEndpoints.java
plugins/connections/ui/src/main/java/org/pentaho/di/connections/ui/lifecycle/ConnectionLifecycleListener.java
plugins/connections/ui/src/main/java/org/pentaho/di/connections/ui/tree/ConnectionFolderProvider.java
plugins/connections/ui/src/main/resources-filtered/OSGI-INF/blueprint/beans.xml
plugins/connections/ui/src/test/java/org/pentaho/di/connections/ui/ConnectionEndpointsTest.java
plugins/repository-locator/impl/platform/src/main/java/org/pentaho/kettle/repository/locator/impl/platform/PentahoSessionHolderRepositoryProvider.java
plugins/repository-locator/impl/spoon/src/main/java/org/pentaho/kettle/repository/locator/impl/spoon/SpoonRepositoryProvider.java

[BACKLOG-35889] VFS connection system needs to point to new metastore

---

engine/src/main/resources/org/pentaho/di/trans/step/messages/messages_en_US.properties
plugins/infobright-bulk-loader/impl/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_en_US.properties

[BACKLOG-36059] - Moved the property to related plugin

[BACKLOG-36059] - Moved the property to related plugin

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/logging/Slf4jLoggingEventListener.java
engine/src/main/resources/kettle-variables.xml

PDI-19559 - [Cloned frm TAP-5817] Log line "Start of run." missing from Pdi-job logs

Pdi 19559 job logs missed bug

---

plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/JmsProducerTest.java

[PDI-19549] JMS Producer NullPointerException when no input records (adding unit test)

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index.html

[SP-6173] Backport of PDI-19520 - PDI Welcome screen has wrong links (9.3 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

@smmribeiro 
@andreramos89 
@renato-s

[SP-6167] - Backport of PDI-19445 - Json Parser syntax not working (9.3 Suite)

---

core/src/main/java/org/pentaho/di/core/Condition.java
core/src/test/java/org/pentaho/di/core/ConditionTest.java

@smmribeiro 
@andreramos89 
@renato-s

[SP-6126] - Backport of PDI-19396 - Error in Null Handling: Filter Rows, Anything using di.core.Condition (9.3 Suite)

---

plugins/infobright-bulk-loader/impl/src/main/java/org/pentaho/di/trans/steps/infobrightoutput/InfobrightLoaderMeta.java
plugins/infobright-bulk-loader/ui/src/main/java/org/pentaho/di/ui/trans/infobrightoutput/InfobrightLoaderDialog.java

[BACKLOG-36080] - Changed URL for infobright

[BACKLOG-36080] - Changed URL for infobright

---

plugins/excel/impl/pom.xml
plugins/excel/impl/src/main/java/org/pentaho/di/lifecycle/KettleExcelPluginLifecycleListener.java
plugins/excel/impl/src/main/java/org/pentaho/di/trans/steps/excelinput/ExcelInputExternalResourceConsumer.java
plugins/excel/impl/src/main/java/org/pentaho/di/trans/steps/excelinput/ExcelInputStepAnalyzer.java
plugins/excel/impl/src/main/java/org/pentaho/di/trans/steps/exceloutput/ExcelOutputExternalResourceConsumer.java
plugins/excel/impl/src/main/java/org/pentaho/di/trans/steps/exceloutput/ExcelOutputStepAnalyzer.java
plugins/excel/impl/src/test/java/org/pentaho/di/trans/steps/ClonableStepAnalyzerTest.java
plugins/excel/impl/src/test/java/org/pentaho/di/trans/steps/MetaverseTestUtils.java
plugins/excel/impl/src/test/java/org/pentaho/di/trans/steps/excelinput/ExcelInputStepAnalyzerTest.java
plugins/excel/impl/src/test/java/org/pentaho/di/trans/steps/exceloutput/ExcelOutputStepAnalyzerTest.java

[BACKLOG-36072] - moving excel related metaverse files to kettle

[BACKLOG-36072] - moving excel related metaverse files to kettle

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducer.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/JmsProducerTest.java

[SP-6188] Backport of PDI-19549 - JMS Producer NullPointerException when no input records (8.3 Suite)

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducer.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/JmsProducerTest.java

[SP-6189] Backport of PDI-19549 - JMS Producer NullPointerException when no input records (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFiles.java

[PDI-19562] 'Delete Files' step does not delete files from Windows mapped drive

---

core/pom.xml
core/src/main/java/org/pentaho/di/core/Const.java
engine/pom.xml
engine/src/main/java/org/pentaho/di/base/MetaFileLoaderImpl.java
engine/src/test/java/org/pentaho/di/base/MetaFileLoaderImplTest.java

@andreramos89 
@renato-s 
@rmansoor

[CUST-266] - Requesting CUST for PDI-19578 on 9.3

---

engine/src/main/java/org/pentaho/di/www/StatusServletUtils.java

[BISERVER-14843] Error in pentaho.log when accessing kettle status page after starting Pentaho 9.x as a Windows Service

---

core/pom.xml
plugins/json/core/pom.xml
plugins/meta-inject/pom.xml

This commit is a cherry-pick of 48fee7e1eed2cd36b975548d86891269681010d0

[SP-6179] [PPP-4654] Get commons-io version from parent pom

---

assemblies/lib/pom.xml

[BACKLOG-35831] pom cleanup; moved a dependency but not its version

---

engine/src/main/java/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFiles.java

Backport of PDI-19562 - 'Delete Files' step does not delete files from Windows mapped drive (9.3 Suite)

---

plugins/meta-inject/impl/pom.xml
plugins/meta-inject/ui/pom.xml
plugins/meta-inject/ui/src/main/java/org/pentaho/di/ui/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java
plugins/meta-inject/ui/src/main/java/org/pentaho/di/ui/trans/steps/metainject/lifecycle/KettleMetaInjectPluginLifecycleListener.java

Reverts pentaho/pentaho-kettle#8494

Revert "[BACKLOG-36233] Moved the metaverse analyzer and lifecycle listener"

---

plugins/avro-format/core/src/test/java/org/pentaho/di/trans/steps/avro/input/AvroInputMetaTest.java

Reverts pentaho/pentaho-kettle#8493

Revert "[TEST] - Commenting out a test that is causing random failures"

---

plugins/pur/repository-proxy/pom.xml
plugins/pur/repository-proxy/src/main/java/org/pentaho/di/repository/pur/provider/RepositoryProvider.java
plugins/pur/repository-proxy/src/main/resources/OSGI-INF/blueprint/blueprint.xml

[BACKLOG-36213] Update repository locator interface package and

---

engine/src/main/java/org/pentaho/di/core/logging/BaseLogTable.java
engine/src/main/java/org/pentaho/di/core/logging/JobLogTable.java
engine/src/main/java/org/pentaho/di/core/logging/TransLogTable.java
engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/test/java/org/pentaho/di/core/logging/BaseLogTableTest.java

[PDI-19357] - Incomplete logging in kettle/status page when database logging for a job/transformation is enabled.

---

assemblies/client/pom.xml

Reverts pentaho/pentaho-kettle#8538

Revert "[CLEANUP] temporarily removing samples from assemblies"

---

engine/src/main/java/org/pentaho/di/base/MetaFileLoaderImpl.java

[PDI-19570] - 9.3: Job Entry with path variable (${Internal.Entry.Currenty.Directory}) cannot be resolved.

---

plugins/excel/ui/src/main/java/org/pentaho/di/ui/trans/exceloutput/ExcelOutputDialog.java

[BACKLOG-36303] - fixed the image issue

[BACKLOG-36303] - fixed the image issue

---

core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java

inconsistencies. Also handle the case in KettleVFS when opening a transformation for the first time and the variablespace is null.

[BACKLOG-36356] Consolidate logic for setting dialog state and clean up

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java

the list of files (e.g. when accessing slow cloud services).

[BACKLOG-36366] Show a busy icon when the file dialog is busy loading

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/transexecutor/TransExecutorDialog.java

Updated to the new file dialog from the old dialog in transformation executor step

[BACKLOG-36369] Updated to the new file dialog in transformation executor step

---

engine/pom.xml

[CUST-267] Requesting CUST for PDI-19570 on 9.3 - update versions

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/main/resources/org/pentaho/di/plugins/fileopensave/dialog/messages/messages_en_US.properties

Reverts pentaho/pentaho-kettle#8605

Revert "[PDI-18668] Added filter argument to provider call"

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index_no_osgi.html
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties
ui/src/main/resources/ui/laf.properties

[BACKLOG-36432] - Changes related to marketplace

[BACKLOG-36432] - Changes related to marketplace

---

core/src/main/java/org/pentaho/di/core/util/StringEvaluationResult.java
core/src/main/java/org/pentaho/di/core/util/StringEvaluator.java
core/src/test/java/org/pentaho/di/core/util/StringEvaluatorTest.java
ui/src/test/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileInputTextCSVImportProgressDialogTest.java
ui/src/test/java/org/pentaho/di/ui/trans/steps/textfileinput/TextFileInputCSVImportProgressDialogTest.java

Reverts pentaho/pentaho-kettle#8618

Revert "[PDI-19619] Fix numeric mask and type generation on "Get Fields" logi…"

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/RenameDialog.java
plugins/file-open-save-new/core/src/main/resources/org/pentaho/di/plugins/fileopensave/dialog/messages/messages_en_US.properties

[BACKLOG-36426] - PDI File open dialog, right click menu on File/Folder pane misses Rename Option

[BACKLOG-36426] - PDI File open dialog, right click menu on File/Folder pane misses Rename Option

---

plugins/file-open-save-new/api/src/main/java/org/pentaho/di/plugins/fileopensave/api/providers/BaseFileProvider.java
plugins/file-open-save-new/api/src/main/java/org/pentaho/di/plugins/fileopensave/api/providers/FileProvider.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/controllers/FileController.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/local/LocalFileProvider.java

[BACKLOG-36323] - changes for searching inside sub folders

[BACKLOG-36323] - changes for searching inside sub folders

---

plugins/repositories/core/src/main/java/org/pentaho/di/ui/repo/dialog/RepositoryManagerDialog.java
plugins/repositories/core/src/main/java/org/pentaho/di/ui/repo/menu/RepositoryConnectMenu.java
plugins/repositories/core/src/main/resources/org/pentaho/di/ui/repo/dialog/messages/messages_en_US.properties

[BACKLOG-36433] - Don't show authentication dialogue for File repository connect in PDI

[BACKLOG-36433] - Don't show authentication dialogue for Filerepository connect in PDI

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

Also set user to user home when saving content when not connected to repository and last opened file was from repository

[BACKLOG-36475] - Adjust overwrite check when saving to repository.

---

plugins/repositories/core/src/main/java/org/pentaho/di/ui/repo/dialog/RepositoryManagerDialog.java

[BACKLOG-36433] - Fix Nullpointer when connecting to File repository

[BACKLOG-36433] - Fix Nullpointer when connecting to File repository

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/controllers/FileController.java

[BACKLOG-36514] File type filter not being applied to files read from

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

dialog when saving a file to the repository; was defaulting to All files (*)

[BACKLOG-36544] Need to specify the correct filter type for the file

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index.html
assemblies/static/src/main/resources-filtered/docs/English/welcome/index_no_osgi.html

[BACKLOG-36505] - changes to welcome page content

[BACKLOG-36505] - changes to welcome page content

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index.html
assemblies/static/src/main/resources-filtered/docs/English/welcome/index_no_osgi.html

Backlog 36505 changes to welcome page

[Backlog 36505] - changes to welcome page

---

engine/src/main/java/org/pentaho/di/core/logging/BaseLogTable.java
engine/src/main/java/org/pentaho/di/core/logging/JobLogTable.java
engine/src/main/java/org/pentaho/di/core/logging/TransLogTable.java
engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java
engine/src/test/java/org/pentaho/di/core/logging/BaseLogTableTest.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java

Original PRs:
- https://github.com/pentaho/pentaho-kettle/pull/8481
- https://github.com/pentaho/pentaho-kettle/pull/8563
@andreramos89 
@smmribeiro

[SP-6200] - Backport of PDI-19357 - Incomplete logging in kettle/status page when database logging for a job/transformation is enabled. (9.3 Suite)

---

plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSum.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumTest.java

[PDI-19627] - Add a checksum：When "Compatibility Mode" is checked and "Type" set to SHA-256, transformation errors out.

---

plugins/core/ui/src/main/resources/org/pentaho/di/ui/trans/steps/changefileencoding/messages/messages_en_US.properties

[SP-6210] - Backport of PDI-19621 - Error in change file encoding transformation step (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java

[SP-6207] - Backport of PDI-18989 - PGBulkLoader not closing connection at end of transformation (9.3 Suite)

---

core/src/main/java/org/pentaho/di/core/database/MySQLDatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/NeoviewDatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/TeradataDatabaseMeta.java
core/src/test/java/org/pentaho/di/core/database/InfiniDbDatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/MySQLDatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/NeoviewDatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/TeradataDatabaseMetaTest.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/tableoutput/TableOutputDialog.java

[SP-6206] - Backport of PDI-14921 - Help links of database connections drill to Page Not Found web pages (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/www/GetJobStatusServlet.java
engine/src/main/java/org/pentaho/di/www/GetStatusServlet.java
engine/src/main/java/org/pentaho/di/www/GetTransStatusServlet.java
engine/src/main/java/org/pentaho/di/www/StatusServletUtils.java

[BISERVER-14843] - Error in pentaho.log when accessing kettle status page after starting Pentaho 9.x as a Windows Service

---

engine/src/test/java/org/pentaho/di/www/RegisterPackageServletTest.java

[TEST] Fix unit test

---

engine/src/main/java/org/pentaho/di/job/entries/ping/JobEntryPing.java
engine/src/main/resources/org/pentaho/di/job/entries/ping/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/job/entries/ping/JobEntryPingTest.java
ui/src/main/java/org/pentaho/di/ui/job/entries/ping/JobEntryPingDialog.java

Added changes requested by @NJtwentyone for Timeout(ms) and made similar changes for JobEntryPing#getNbrPackets()

[PDI-19287]- Added Validation checks for "Timeout(ms)"

---

plugins/pur/core/src/it/resources/repository-test-override.spring.xml
plugins/pur/core/src/it/resources/repository.spring.xml

@smmribeiro 
@andreramos89 
@renato-s

[PPP-4758] - Vulnerable Component: Spring Security - CVE-2022-22978

---

engine/src/main/java/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFiles.java

[PDI-19623]-Added additional if condition to check access

[PDI-19623]-Added additional if condition to check access

---

engine/pom.xml
plugins/pur/core/pom.xml

[PPP-4660] - Use of Vulnerable Component: Components/jackson-databind:2.9.10.2

---

engine/pom.xml

[PPP-4815] - Vulnerable Component: Ini4j 0.5.1

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

[PDI-19629] - Added condition for Numeric DataType

[PDI-19629] - Added condition for Numeric DataType

---

core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/main/java/org/pentaho/di/trans/step/BaseDatabaseStep.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java

@andreramos89 
@smmribeiro 
Fix issues when Kettle is executing Transformations without a repository connection

[PDI-19604] - Connection related issues when Connection Pooling is enabled in transformations.

---

plugins/pur/core/src/it/resources/repository-test-override.spring.xml
plugins/pur/core/src/it/resources/repository.spring.xml

[SP-6265] - Backport of PPP-4758 - Vulnerable Component: Spring Security - CVE-2022-22978 (9.4 Suite)

---

plugins/pur/core/src/it/resources/repository-test-override.spring.xml
plugins/pur/core/src/it/resources/repository.spring.xml

@smmribeiro
@andreramos89
@renato-s

[PPP-4827] - Vulnerable Component: Spring Security - CVE-2022-31692

---

engine/pom.xml

[SP-6282] - Backport of PPP-4815 - Vulnerable Component: Ini4j 0.5.1 (9.3 Suite)

---

engine/pom.xml
integration/pom.xml

[PPP-4783] Vulnerable Component: nekohtml

---

engine/pom.xml
plugins/pur/core/pom.xml

[PPP-4610] - Use of Vulnerable Component: Components/snakeyaml:1.25

---

engine/src/main/java/org/pentaho/di/trans/steps/tableoutput/TableOutputMeta.java
engine/src/main/resources/org/pentaho/di/trans/steps/tableoutput/messages/messages_en_US.properties
plugins/meta-inject/impl/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMigration.java
plugins/meta-inject/impl/src/test/java/org/pentaho/di/trans/steps/metainject/MetaInjectMigrationTest.java

@smmribeiro 
@andreramos89 
@renato-s

[PDI-19713] - Metadata Injection Step issue - Step missing mappings

---

engine/pom.xml

@andreramos89 
@smmribeiro 
Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/8769

[SP-6283] - Backport of PPP-4815 - Vulnerable Component: Ini4j 0.5.1 (9.4 Suite)

---

engine/pom.xml
plugins/rss/impl/src/main/java/org/pentaho/di/trans/steps/rssoutput/RssOutput.java
plugins/rss/impl/src/main/java/org/pentaho/di/trans/steps/rssoutput/RssOutputData.java
plugins/salesforce/core/src/test/java/org/pentaho/di/trans/steps/salesforceinput/SalesforceInputTest.java

[PPP-4828] - Component Rome is outdated

---

engine/pom.xml
plugins/pur/core/pom.xml

[SP-6306] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.4 Suite)

---

engine/pom.xml
plugins/pur/core/pom.xml

[SP-6305] - Backport of PPP-4610 - Use of Vulnerable Component: Components/snakeyaml:1.25 (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFiles.java
engine/src/main/resources/org/pentaho/di/job/entries/deletefiles/messages/messages_en_US.properties

This PR fixes below issue.
If files exist, the delete is performed. But if files do not exist, then execution fails.

[PDI-19754] - Job entry "Delete files" fails if the files that needs to be deleted do not exist

---

engine/src/main/java/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFiles.java

Reverts pentaho/pentaho-kettle#8825

Revert "[SP-6275]-Backport of PDI-19623 - PDI "Delete files" Step - An error …"

---

core/src/main/java/org/pentaho/di/connections/vfs/VFSConnectionProvider.java

(Without calling back to ConnectionManager)

[BACKLOG-37508] new API for direct fs access

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml

[PPP-4802] -  Vulnerable Component: hsqldb

---

plugins/core/impl/pom.xml

This commit is a cherry-pick from master 2a57233

[BACKLOG-37531] Exclude BC dependencies from plugin lib folder. (#8878)

---

engine/src/main/java/org/pentaho/di/core/util/ConnectionUtil.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/service/ProviderServiceService.java

metastore locator in ConnectionUtil
- Removed the setting of localMetastore as supplier in ProviderServiceService

[BACKLOG-37379] Replaced the reference to local metastore with the

---

engine/src/main/java/org/pentaho/di/trans/steps/tableoutput/TableOutputMeta.java
engine/src/main/resources/org/pentaho/di/trans/steps/tableoutput/messages/messages_en_US.properties
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMigration.java
plugins/meta-inject/src/test/java/org/pentaho/di/trans/steps/metainject/MetaInjectMigrationTest.java

Reverts pentaho/pentaho-kettle#8873

Revert "[SP-6314] Backport of PDI-19713 - Metadata Injection Step issue- Step…"

---

engine/pom.xml

@renato-s @bcostahitachivantara @smmribeiro

[PPP-4828] - Component Rome is outdated - missing dependencies for Rome

---

core/src/main/java/org/pentaho/di/metastore/MetaStoreConst.java
core/src/main/java/org/pentaho/di/metastore/SuppliedMetaStore.java
engine/src/main/java/org/pentaho/di/www/SlaveServerConfig.java

and a couple other build fixes for other repos.

[BACKLOG-37509] add an accessor for the current metastore

---

plugins/repositories/core/src/main/javascript/app/app.animation.js
plugins/repositories/core/src/main/javascript/app/components/database/details/details.css
plugins/repositories/core/src/main/javascript/app/components/file/details/details.css
plugins/repositories/core/src/main/javascript/app/components/manager/manager.css
plugins/repositories/core/src/main/javascript/app/components/pentaho/details/details.css

@smmribeiro 
@andreramos89 
@renato-s

[SP-6351] - Backport of PDI-19626 - The Repository Manager in Spoon will not display all fields/buttons with certain resolution settings (9.3 Suite)

---

core/src/main/java/org/pentaho/di/connections/vfs/providers/other/OtherConnectionDetailsProvider.java
plugins/gpload/core/pom.xml

This reverts commit b918d3d06d5afab62feb1ad4a9d287cd5c639181.

Revert "[PDI-18433] Fix api changes from VFS upgrade"

---

assemblies/plugins/pom.xml

[BACKLOG-37696] Added the dependency for packaging the rest-plugin under

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

[PDI-18487] - Amount of POST calls from PDI client connected to Repository

---

plugins/rest/core/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java
plugins/rest/core/src/main/java/org/pentaho/di/ui/trans/steps/rest/RestDialog.java

called from Rest EE plugin to add new ui element
[PDI-14825] Made the CTabFolder protected
Made some more UI controls protected so it can be used in EE plugin
- Added new method for adding SSL keystore file/password
[PDI-14825] Change to be protected method: getSslContextWithTrustStoreFile()
Remove static modifier from method getSslContextWithTrustStoreFile()
[PDI-14825] Updated the name of the ui method that adds the sslkeystore group
[pdi-14825] Added method that can be overridden in EE plugin for handling the saving of data in ktr
Checkstyle issue fixes
Rename override method name to be shorter
[PDI-14825]: https://hv-eng.atlassian.net/browse/PDI-14825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PDI-14825]: …

[PDI-14825] Adding the accessor method to get CTabFolder so it can be

---

assemblies/lib/pom.xml
core/src/main/java/org/pentaho/di/connections/vfs/providers/other/OtherConnectionDetailsProvider.java
plugins/avro-format/core/src/main/java/org/pentaho/di/trans/steps/avro/input/BaseFormatInputField.java
plugins/avro-format/core/src/main/resources/org/pentaho/di/trans/steps/avro/input/messages/messages_en_US.properties
plugins/avro-format/core/src/test/java/org/pentaho/di/trans/steps/avro/input/AvroInputMetaInjectionTest.java
plugins/gpload/core/pom.xml

Co-authored-by: Tim Kafalas tkafalas <tkafalas@hitachivantara.com>

[PDI-18433] Upgrade commons-vfs2 to 2.9.0 (#8951)

---

plugins/avro-format/core/src/main/java/org/pentaho/di/trans/steps/avro/metadiscovery/AvroMetadataDiscovery.java
plugins/avro-format/core/src/main/java/org/pentaho/di/trans/steps/avro/metadiscovery/AvroMetadataDiscoveryData.java
plugins/avro-format/core/src/main/java/org/pentaho/di/trans/steps/avro/metadiscovery/AvroMetadataDiscoveryDialog.java
plugins/avro-format/core/src/main/java/org/pentaho/di/trans/steps/avro/metadiscovery/AvroMetadataDiscoveryMeta.java
plugins/avro-format/core/src/main/resources/AvroMetadataDiscovery.svg
plugins/avro-format/core/src/main/resources/org/pentaho/di/trans/steps/avro/metadiscovery/messages/messages_en_US.properties
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dragdrop/ElementDndProcessor.java

…owser Drag and Drop functions.

[BACKLOG-38183] Make Avro metadata discovery step compilable (#8959)

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java
engine/src/test/java/org/pentaho/di/trans/steps/rest/RestTest.java

cherry-pick from:
- https://github.com/pentaho/pentaho-kettle/commit/97cb9d91ded97ba2f0c125edd9d218b9893c0461
- https://github.com/pentaho/pentaho-kettle/commit/8180c1aff4fdf0dea1014284752b22e33f180e56

[SP-6360] Backport of PDI-19777 - REST client step TrustStore validation no longer working (9.5 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java
engine/src/test/java/org/pentaho/di/trans/steps/rest/RestTest.java

cherry-pick from:
- https://github.com/pentaho/pentaho-kettle/commit/97cb9d91ded97ba2f0c125edd9d218b9893c0461
- https://github.com/pentaho/pentaho-kettle/commit/8180c1aff4fdf0dea1014284752b22e33f180e56

[SP-6359] Backport of PDI-19777- REST client step TrustStore validation no longer working (9.3 Suite)

---

engine/pom.xml

[SP-6371] - Backport of PPP-4828 - Component Rome is outdated (9.5 Suite)

---

engine/src/test/java/org/pentaho/di/job/entries/http/JobEntryHTTPTest.java
engine/src/test/java/org/pentaho/di/trans/TransTest.java

@tkafalas. 
Please validate this changes to fix errors on unit tests due to VFS upgrade.

[PDI-18433] - Job Steps: Copy Files and Hadoop Copy Files error out during attempt to un-compress tar.gz file

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java
engine/src/test/java/org/pentaho/di/trans/steps/rest/RestTest.java

Reverts pentaho/pentaho-kettle#8969

Revert "[SP-6359] Backport of PDI-19777- REST client step TrustStore validation no longer working (9.3 Suite)"

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java
engine/src/test/java/org/pentaho/di/trans/steps/rest/RestTest.java

Reverts pentaho/pentaho-kettle#8970

Revert "[SP-6360] Backport of PDI-19777 - REST client step TrustStore validation no longer working (9.5 Suite)"

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/8947

[SP-6390] - Backport of PDI-19887 - Excessive Requests from Spoon to the Pentaho Server when loading DataSources and Databases Connections (9.5 Suite)

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/8947

[SP-6385] - Backport of PDI-19887 - Excessive Requests from Spoon to the Pentaho Server when loading DataSources and Databases Connections (9.3 Suite)

---

plugins/pur/core/src/main/java/com/pentaho/repository/importexport/PdiContentProvider.java

[BACKLOG-38073] Provide variable values and defaults, provide default

---

plugins/pur/core/src/main/java/com/pentaho/repository/importexport/PdiContentProvider.java

populated and shown on the PUC scheduler UI.

[BACKLOG-38641] Ensure the Internal*FileName.Name variables get

---

engine/src/main/java/org/pentaho/di/core/plugins/StepPluginType.java
engine/src/main/resources/org/pentaho/di/trans/step/messages/messages_en_US.properties

Cherry pick of https://github.com/pentaho/pentaho-kettle/pull/8905

[BACKLOG-38850] : Ordering of Hierarchical Category

---

plugins/get-fields/core/src/test/java/org/pentaho/getfields/types/json/JsonSamplerTest.java

Make the same changes that were previously done for master (9.5, at that time) and 9.4/9.4.0.1
(based on commit 680e182bf2d4f5931f0f4b86afc2abea56087903)

[TEST] Ignoring unit tests as UI elements make these unit test unreliable.

---

plugins/ftp-delete/impl/src/main/java/org/pentaho/di/job/entries/ftpdelete/JobEntryFTPDelete.java

[PDI-19752] FTP Delete: the files are not deleted if it contains Japanese as a wildcard or full filename

---

core/src/main/java/org/pentaho/di/core/logging/LoggingBuffer.java
engine/src/main/java/org/pentaho/di/www/GetJobStatusServlet.java
engine/src/main/java/org/pentaho/di/www/GetStatusServlet.java
engine/src/test/java/org/pentaho/di/www/GetJobStatusServletTest.java
ui/src/main/java/org/pentaho/di/ui/spoon/SpoonSlave.java

Original PRs:
- https://github.com/pentaho/pentaho-kettle/pull/9012
- https://github.com/pentaho/pentaho-kettle/pull/9041

[SP-6423] - Backport of PDI-19901 - Carte Jobs API jobStatus endpoint is not honoring parameter "from" (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/JobMeta.java

[PDI-19937]-Database Password Field shows password in plain text when searching job's metadata
[PDI-19937]: https://hv-eng.atlassian.net/browse/PDI-19937?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-19937]-Database Password Field shows password in plain text when searching job's metadata

---

core/pom.xml

[PPP-4747] Vulnerable Component: batik-1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4747] Vulnerable Component: batik-1.19

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
core/src/main/java/org/pentaho/di/core/database/SQLiteDatabaseMeta.java
core/src/test/java/org/pentaho/di/core/database/SQLiteDatabaseMetaTest.java

[PPP-4905]- Vulnerable Component: SQLite
[PPP-4905]: https://hv-eng.atlassian.net/browse/PPP-4905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4905]- Vulnerable Component: SQLite

---

plugins/json/pom.xml

[PPP-4955]-vulnerable component :JSON-Smart
[PPP-4955]: https://hv-eng.atlassian.net/browse/PPP-4955?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4955]-vulnerable component :JSON-Smart

---

assemblies/lib/pom.xml
core/pom.xml
pom.xml

Reverts pentaho/pentaho-kettle#9050

Revert "[PDI-19906] - Google BigQuery Simba driver version 1.3.3.1004 in Pentaho"

---

core/src/main/java/org/pentaho/di/core/database/GoogleBigQueryDatabaseMeta.java

[PPP-4782] -Vulnerable Component:Jackson Libraries
[PPP-4782]: https://hv-eng.atlassian.net/browse/PPP-4782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4782] -Vulnerable Component:Jackson Libraries

---

core/pom.xml

[PPP-4747] -Vulnerable Component :batik:1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4747] -Vulnerable Component :batik:1.19

---

core/pom.xml

[PPP-4747]-Vulnerable Component :batik:1.19
[PPP-4747]: https://hv-eng.atlassian.net/browse/PPP-4747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4747]-Vulnerable Component :batik:1.19

---

assemblies/samples/src/main/resources/transformations/General - Annotated SOAP web service call (celsius to fahrenheit) - dialog.ktr

Removed the ktr under data-integration/samples/transformations - 'General - Annotated SOAP Web Service call - dialog.ktr' and added the new ktr under same folder with name - 'General - Annotated SOAP web service call (celsius to fahrenheit) - dialog.ktr' with valid public url which converts temperature from Celsius to Fahrenheit.

[PDI-19826] Changed the Annotated SOAP Web Service sample ktr to a valid public soap url

---

engine/pom.xml
engine/src/main/java/org/pentaho/di/www/cache/CarteStatusCache.java

Reverts pentaho/pentaho-kettle#9122

Revert "[PPP-4826] Upgrade Vulnerable Hibernate to 5.4.24"

---

engine/src/main/java/org/pentaho/di/job/entries/delay/JobEntryDelay.java

Beside changes to fix this issue, I have also changed some variable names to match with camelCase Java Standard.

[PDI-19107] - Wait for: The Wait for job entry step allow string values.

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
ui/src/main/java/org/pentaho/di/ui/core/PropsUI.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

Includes fix for [PDI-19981](https://hv-eng.atlassian.net/browse/PDI-19981)
[PDI-19981]: https://hv-eng.atlassian.net/browse/PDI-19981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-19944] - After restarting Spoon, the 'Open File' Dialog defaults to user home in Spoon v9.4 ('Recents' in Spoon 9.5)

---

core/src/main/java/org/pentaho/di/connections/ConnectionDetails.java
core/src/main/java/org/pentaho/di/connections/vfs/provider/ConnectionFileSystem.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/VFSFileProvider.java

Please review 
@pentaho/hoth 
To be merged with 
https://github.com/pentaho/pdi-plugins-ee/pull/977
https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/87

[BACKLOG-39194] - Fix saving files in LocalVFS root and removing dummy root

---

plugins/put-a-file-with-ftp/impl/pom.xml
plugins/put-a-file-with-ftp/impl/src/main/java/org/pentaho/di/job/entries/ftpput/JobEntryFTPPUT.java
plugins/put-a-file-with-ftp/impl/src/main/resources/org/pentaho/di/job/entries/ftpput/messages/messages_en_US.properties
plugins/put-a-file-with-ftp/impl/src/test/java/org/pentaho/di/job/entries/ftpput/JobEntryFTPPUTTest.java

reverting this commit as it is causing issue related to ftp put as it couldnot recognize path related to vfs

[Revert]"[PDI-19926] Put a file with FTP: An error doesn't occur when we change the local directory permissions."

---

engine/src/main/java/org/pentaho/di/trans/SingleThreadedTransExecutor.java
engine/src/main/java/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
engine/src/main/java/org/pentaho/di/trans/steps/singlethreader/SingleThreader.java

Original PRs:
- https://github.com/pentaho/pentaho-kettle/pull/9104/
- https://github.com/pentaho/pentaho-kettle/pull/9115/

[SP-6464] - Backport of PDI-19805 - The Single Threader step will not process rows correctly for certain steps (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/delay/JobEntryDelay.java

Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/9134/

[SP-6471] - Backport of PDI-19107 - Wait for: The Wait for job entry step allow string values. (9.3 Suite)

---

plugins/rest/core/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java

httpMethod name from values defined in system properties before using it

[BACKLOG-39672] [PDI-20025] Updated the code to resolve the

---

engine/src/main/java/org/pentaho/di/job/entries/movefiles/JobEntryMoveFiles.java

Cases found in further testing.

[PDI-19836] Handle file cases and missing destination cases

---

core/src/main/java/org/pentaho/di/connections/utils/ConnectionDetailsUtils.java

Issue: https://hv-eng.atlassian.net/browse/BACKLOG-39667
/cc @pentaho/hoth

[BACKLOG-39667] Fixed failing to clone connection details with blank name

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/test/java/org/pentaho/di/ui/spoon/SpoonTest.java

[PDI-19981] - While Connected to Repository Spoon 9.5 does not remember last folder used, always defaults 'Recent' folder when using Open or Save As

---

plugins/excel/core/src/main/java/org/pentaho/di/trans/steps/exceloutput/ExcelOutputDialog.java
plugins/excel/core/src/main/java/org/pentaho/di/trans/steps/exceloutput/ExcelOutputMeta.java
plugins/excel/core/src/main/resources/org/pentaho/di/trans/steps/exceloutput/messages/messages_en_US.properties

in draft pending opening of master for 10.2 commits

[BACKLOG-39185] Deprecate Microsoft Excel output

---

plugins/connections/pom.xml
plugins/repositories/core/pom.xml

chore: update requirejs artifact used in build [BACKLOG-39952]

---

core/src/main/java/org/pentaho/di/core/logging/LoggingObject.java

Backport of https://github.com/pentaho/pentaho-kettle/pull/9198

[PDI-20038] - Pentaho 9.3.0.6 - Getting java.lang.OutOfMemoryError: Java heap space when running PDI Jobs

---

core/src/main/java/org/pentaho/di/core/logging/LoggingObject.java
core/src/test/java/org/pentaho/di/core/logging/LoggingRegistryTest.java

Fixed LoggingObject initialization.
Added new test cases

[PDI-20056] - Implementaion of PDI-20038 in 10.1 reintroduces bug described in PDI-19712

---

core/src/main/java/org/pentaho/di/core/row/ValueMetaInterface.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaInternetAddress.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaInternetAddressTest.java

[PDI-17350] Row denormaliser : Specifying Internet Address as the data type causes an error.

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java

httpMethod name from values defined in system properties before using it

[SP-6497] [BACKLOG-39672] [PDI-20025] Updated the code to resolve the

---

plugins/connections/ui/pom.xml
plugins/connections/ui/src/main/java/org/pentaho/di/connections/ui/tree/ConnectionFolderProvider.java
plugins/connections/ui/src/test/java/org/pentaho/di/connections/ui/tree/ConnectionFolderProviderTest.java

[BACKLOG-40064] - VFS Connections -  Non-admin users would only see the connections list when on the Open/Save dialogs

---

assemblies/plugins/pom.xml

[CLEANUP] Rest plugin not to be released separately; version should

---

assemblies/static/src/main/resources-filtered/purge-utility.bat
assemblies/static/src/main/resources-filtered/purge-utility.sh

[PDI-19780]- purge-utility is giving an error "Unable to find plugin with ID kettle"
[PDI-19780]: https://hv-eng.atlassian.net/browse/PDI-19780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-19780]- purge-utility is giving an error "Unable to find plugin with ID kettle"

---

assemblies/static/src/main/resources-filtered/Spoon.bat
assemblies/static/src/main/resources-filtered/spoon.sh

[BACKLOG-40283] Cleanup and simplify scripts; don't need to check for

---

.gitignore
core/src/main/java/org/pentaho/di/core/variables/Variables.java

See analysis https://hv-eng.atlassian.net/wiki/spaces/ENG/pages/31096799399/Design+for+variables+and+projects

[BACKLOG-39844] - Have initialize not wipe earlier additions

---

core/src/test/java/org/pentaho/di/core/variables/VariablesTest.java

These fail on 10.1.0.0, and pass against master.

[BACKLOG-39844] - Unit tests for new Variables behavior

---

core/src/main/java/org/pentaho/di/core/extension/KettleExtensionPoint.java
engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/job/JobMeta.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java

and JobMeta to call the new extension points.

[BACKLOG-40123] Adding two new extension points and updating TransMeta

---

engine/src/main/java/org/pentaho/di/www/GetDatabaseDetailsServlet.java
engine/src/main/java/org/pentaho/di/www/GetRegisteredStepsServlet.java

Removed the constructors which are not required anymore

[BACKLOG-39854] Handling Carte Server startup issue due to Default Constructors

---

assemblies/static/src/main/resources-filtered/purge-utility.bat
assemblies/static/src/main/resources-filtered/purge-utility.sh

[SP-6510]-Backport of PDI-19780 - purge-utility is giving an error Unable to find plugin with ID 'kettle'" (10.1 Suite)
[SP-6510]: https://hv-eng.atlassian.net/browse/SP-6510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6510]-Backport of PDI-19780 - purge-utility is giving an error Unable to find plugin with ID 'kettle'" (10.1 Suite)

---

assemblies/static/src/main/resources-filtered/purge-utility.bat
assemblies/static/src/main/resources-filtered/purge-utility.sh

[SP-6511]-Backport of PDI-19780 - purge-utility is giving an error Unable to find plugin with ID 'kettle'" (9.3 Suite)
[SP-6511]: https://hv-eng.atlassian.net/browse/SP-6511?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6511]-Backport of PDI-19780 - purge-utility is giving an error Unable to find plugin with ID 'kettle'" (9.3 Suite)

---

assemblies/samples/src/main/resources/transformations/General - Annotated SOAP web service call (celsius to fahrenheit) - dialog.ktr

For Jira - https://hv-eng.atlassian.net/browse/SP-6505 , Backported the changes of ticket (https://hv-eng.atlassian.net/browse/PDI-19826) to 9.3

[SP-6511] - Added a new SOAP web service call in sample transformations of PDI.

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/controllers/FileController.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/controllers/FileControllerTest.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/providers/TestFileProvider.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/providers/model/TestFile.java
ui/src/main/java/org/pentaho/di/ui/core/FileDialogOperation.java

Listeners for file loading
Custom images
Custom condition for opening a file
Option to show only folders

[BACKLOG-40008] File open dialog customization options

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/kettle-variables.xml

Original PRs:
- https://github.com/pentaho/pentaho-kettle/pull/9196
- https://github.com/pentaho/pentaho-kettle/pull/9246
@smmribeiro
@renato-s

[SP-6519] - Backport of PDI-20033 - Sub-job is not executed when “Execute every input row” is checked. (10.1 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/kettle-variables.xml

Original PRs:
- https://github.com/pentaho/pentaho-kettle/pull/9196
- https://github.com/pentaho/pentaho-kettle/pull/9246 
@smmribeiro 
@renato-s

[SP-6518] - Backport of PDI-20033 - Sub-job is not executed when “Execute every input row” is checked. (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java

@smmribeiro 
@renato-s 
Fixing wrongful behavior found during testing

[PDI-20033] - Sub-job is not executed when “Execute every input row” is checked

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java

@smmribeiro 
@renato-s 
fixing issue found in tests

[PDI-20033] - Sub-job is not executed when “Execute every input row” is checked - fixing issue in tests

---

engine/src/main/java/org/pentaho/di/job/entries/deletefile/JobEntryDeleteFile.java

[PDI-17834]-Delete File Step in Job shows incorrect execution logs  the logging.
[PDI-17834]: https://hv-eng.atlassian.net/browse/PDI-17834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-17834]-Delete File Step in Job shows incorrect execution logs  the logging.

---

core/pom.xml
core/src/main/java/org/pentaho/di/core/Const.java
engine/pom.xml
engine/src/main/java/org/pentaho/di/trans/TransMeta.java

[CUST-279] - Requesting CUST for PDI-20078 on top of 9.3.0.7

---

core/src/main/java/org/pentaho/di/connections/vfs/VFSConnectionDetails.java

The supporting variables related to root path is now added to VFSConnectionDetails class.

[BACKLOG-39677] Added root path supporting variables in VFSConnectionDetails class.

---

core/pom.xml
core/src/main/java/org/pentaho/di/connections/utils/EncryptUtils.java
core/src/main/java/org/pentaho/di/connections/vfs/BaseVFSConnectionDetails.java
core/src/main/java/org/pentaho/di/connections/vfs/VFSConnectionDetails.java
core/src/main/java/org/pentaho/di/connections/vfs/providers/other/OtherConnectionDetails.java
core/src/test/java/org/pentaho/di/connections/ConnectionManagerTest.java
core/src/test/java/org/pentaho/di/connections/common/bucket/TestConnectionDetails.java
core/src/test/java/org/pentaho/di/connections/common/domain/TestConnectionWithDomainDetails.java
plugins/connections/ui/src/test/java/org/pentaho/di/connections/ui/TestConnectionDetails.java

Part of PR group
https://github.com/pentaho/pdi-plugins-ee/pull/1050
https://github.com/pentaho/big-data-plugin/pull/2523
https://github.com/pentaho/metastore/pull/89

[BACKLOG-40063] - VFS Connection Manager : Allow permission to be applied on the VFS connections created from PUC

---

plugins/streaming/impls/mqtt/pom.xml
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilderTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSourceTest.java

[BACKLOG-40472] Fixes to get the build working, mockito dependency

---

core/src/main/java/org/pentaho/di/core/vfs/IKettleVFS.java
core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/main/java/org/pentaho/di/core/vfs/KettleVFSImpl.java

Restores backwards compatibility for KettleVFS

[BACKLOG-40099] - remove new Exception from method signature

---

assemblies/static/src/main/resources-filtered/docs/English/welcome/index.html
assemblies/static/src/main/resources-filtered/docs/English/welcome/index_no_osgi.html

Original PRs:
1. ~~[pentaho-kettle#9245](https://github.com/pentaho/pentaho-kettle/pull/9245)~~
2. [pentaho-kettle#9264](https://github.com/pentaho/pentaho-kettle/pull/9264)
@ddiroma

[SP-6527] Backport of PDI-20071 - Broken Welcome page help link in 10.1 PDI Client (10.1 Suite)

---

core/src/main/java/org/pentaho/di/connections/utils/EncryptUtils.java
core/src/test/java/org/pentaho/di/connections/common/bucket/TestConnectionDetailsChild.java
core/src/test/java/org/pentaho/di/connections/utils/EncryptUtilsTest.java

Addresses review comments of https://github.com/pentaho/pentaho-kettle/pull/9283

[BACKLOG-40063] - Address review comments

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java

Fixing case found in Backport 
@smmribeiro 
@renato-s

[BACKLOG-40617] - Automated test failing with index java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 5

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

[PDI-20085] - KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL produces opposite display for NULLS

---

core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
core/src/main/java/org/pentaho/di/connections/utils/VFSConnectionTestOptions.java
core/src/main/java/org/pentaho/di/connections/vfs/BaseVFSConnectionDetails.java
core/src/main/java/org/pentaho/di/connections/vfs/BaseVFSConnectionProvider.java
core/src/main/java/org/pentaho/di/connections/vfs/VFSConnectionDetails.java
core/src/main/java/org/pentaho/di/connections/vfs/VFSConnectionProvider.java
core/src/test/java/org/pentaho/di/connections/ConnectionManagerTest.java
core/src/test/java/org/pentaho/di/connections/vfs/provider/BaseVFSConnectionProviderTest.java

This PR has to be merged along with the PR - https://github.com/pentaho/pentaho-scheduler-plugin-ee/pull/223

[BACKLOG-39677] Added root path code changes for VFS connection.

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java

Encoding password for logins with special characters

[BISERVER-14644] - Users with password having certain special characters, or strings of characters, are not allowed to login to PUC

---

engine/src/main/java/org/pentaho/di/repository/RepositoryOperation.java
engine/src/main/java/org/pentaho/di/repository/RepositorySecurityProvider.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/AbsSecurityProvider.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/AbsSecurityProviderTest.java

@pentaho/millenniumfalcon please review.

fix: scheduler option in menu bar checks permissions [BACKLOG-40763]

---

plugins/core/impl/pom.xml
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/abort/AbortTest.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/blockingstep/BlockingStep_PDI_11344_Test.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/clonerow/CloneRowTest.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/combinationlookup/CombinationLookupTest.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/concatfields/ConcatFieldsMetaTest.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/concatfields/ConcatFieldsTest.java
plugins/mail/impl/pom.xml
plugins/mail/impl/src/test/java/org/pentaho/di/trans/steps/mail/MailTest.java
plugins/meta-inject/impl/pom.xml
plugins/meta-inject/impl/src/test/java/org/pentaho/di/repository/RepositoryImporterTest.java
plugins/meta-inject/impl/src/test/java/org/pentaho/di/trans/TransMetaTest.java
plugins/meta-inject/impl/src/test/java/org/pentaho/di/trans/steps/metainject/MetaInjectMetaTest.java
plugins/meta-inject/impl/src/test/java/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java
plugins/repositories/core/pom.xml
plugins/repositories/core/src/test/java/org/pentaho/di/ui/repo/controller/RepositoryConnectControllerTest.java
plugins/repositories/core/src/test/java/org/pentaho/di/ui/repo/timeout/RepositoryServiceSessionTimeoutHandlerTest.java
plugins/repositories/core/src/test/java/org/pentaho/di/ui/repo/timeout/RepositorySessionTimeoutHandlerTest.java
plugins/repositories/core/src/test/java/org/pentaho/di/ui/repo/timeout/SessionTimeoutHandlerTest.java

[BACKLOG-40472] JDK17 and mockito test fixes for mail, repositories,

---

engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/trans/Trans.java

[PDI-19540] - Error Socket Writer init and sockets communication

---

plugins/pur/core/pom.xml
plugins/pur/core/src/it/java/org/pentaho/di/repository/pur/PurRepositoryIT.java
plugins/pur/core/src/it/java/org/pentaho/di/repository/pur/PurRepository_GetObjectInformation_IT.java
plugins/pur/core/src/test/java/com/pentaho/di/purge/RepositoryCleanupUtilTest.java
plugins/pur/core/src/test/java/com/pentaho/di/purge/UnifiedRepositoryPurgeServiceTest.java
plugins/pur/core/src/test/java/com/pentaho/di/revision/RevisionResourceTest.java
plugins/pur/core/src/test/java/com/pentaho/repository/importexport/PDIImportUtilTest.java
plugins/pur/core/src/test/java/com/pentaho/repository/importexport/StreamToJobNodeConverterTest.java
plugins/pur/core/src/test/java/com/pentaho/repository/importexport/StreamToNodeConvertersPrivateDatabasesTest.java
plugins/pur/core/src/test/java/com/pentaho/repository/importexport/StreamToTransNodeConverterTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/ActiveCacheTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/AttributesMapUtilTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/JobDelegateTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositoryConnectorTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositoryMetaTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositorySecurityManagerTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositoryStressTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositoryTestBase.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_Test.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/UserRoleDelegateTest.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/utils/RepositoryFactoryTest.java
plugins/pur/core/src/test/java/org/pentaho/di/ui/repository/EESpoonPluginTest.java
plugins/pur/core/src/test/java/org/pentaho/di/ui/repository/pur/repositoryexplorer/controller/TrashBrowseControllerTest.java
plugins/pur/core/src/test/java/org/pentaho/di/ui/repository/pur/repositoryexplorer/model/UIEEJobTest.java
plugins/pur/core/src/test/java/org/pentaho/di/ui/repository/pur/repositoryexplorer/model/UIEERepositoryDirectoryTest.java
plugins/pur/core/src/test/java/org/pentaho/di/ui/repository/pur/repositoryexplorer/model/UIEETransformationTest.java
plugins/pur/repository-proxy/src/test/java/org/pentaho/di/repository/pur/provider/PluginRepositoryProviderTest.java
plugins/pur/repository-proxy/src/test/java/org/pentaho/di/repository/pur/provider/PurRepositoryProxyTest.java

Reverts pentaho/pentaho-kettle#9367
Reverting. Local building fails.

Revert "[BACKLOG-40842] JDK17 Unit test fixes for Pur Repository"

---

plugins/pur/core/pom.xml
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_Test.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/utils/RepositoryFactoryTest.java

~Opening this to see if wingman comes back green, don't merge yet please~
Doesn't actually address the issue with these tests, but it should get them passing

[TEST] reuseForks=false for PUR, small test fixes

---

core/src/main/java/org/pentaho/di/core/logging/LoggingRegistry.java
core/src/test/java/org/pentaho/di/core/logging/LoggingRegistryTest.java
engine/src/main/java/org/pentaho/di/core/KettleEnvironment.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/www/CarteSingleton.java

Original PRs:
- [pentaho-kettle#9357](https://github.com/pentaho/pentaho-kettle/pull/9357)
- [pentaho-kettle#9404](https://github.com/pentaho/pentaho-kettle/pull/9404)
- [pentaho-kettle#9406](https://github.com/pentaho/pentaho-kettle/pull/9406)
Note: for PDI-20109 the implementation had to be adapted to the 9.3 code base.
@pentaho/tatooine_dev  @rmansoor

[SP-6550] Backport of PDI-20109, PDI-20119 and PDI-20120

---

core/src/main/java/org/pentaho/di/core/logging/LoggingRegistry.java
core/src/test/java/org/pentaho/di/core/logging/LoggingRegistryTest.java
engine/src/main/java/org/pentaho/di/core/KettleEnvironment.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/www/CarteSingleton.java

Original PRs:
- [pentaho-kettle#9357](https://github.com/pentaho/pentaho-kettle/pull/9357)
- [pentaho-kettle#9404](https://github.com/pentaho/pentaho-kettle/pull/9404)
- [pentaho-kettle#9406](https://github.com/pentaho/pentaho-kettle/pull/9406)
@pentaho/tatooine_dev  @rmansoor

[SP-6551] Backport of PDI-20109, PDI-20119 and PDI-20120

---

engine/src/main/java/org/pentaho/di/job/JobMeta.java

Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/9063
@pentaho/tatooine

[SP-6552] Backport of PDI-19937 - Database Password Field shows password in plain text when searching job's metadata (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/base/MetaFileLoaderImpl.java

[PDI-20124] Ensure we do not write to the cache if the user has disabled

---

assemblies/client/pom.xml
engine/pom.xml
plugins/excel/core/pom.xml
plugins/excel/core/src/main/java/org/pentaho/di/trans/steps/excelinput/poi/PoiCell.java
plugins/excel/core/src/main/java/org/pentaho/di/trans/steps/excelinput/poi/PoiWorkbook.java
plugins/excel/core/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java
plugins/excel/core/src/test/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheetTest.java
plugins/pentaho-reporting/assemblies/plugin/pom.xml
plugins/pom.xml
plugins/xml/pom.xml

[PRD-6159] - upgrading the apache poi libraries

---

plugins/file-open-save-new/api/src/main/java/org/pentaho/di/plugins/fileopensave/api/providers/Entity.java
plugins/file-open-save-new/api/src/main/java/org/pentaho/di/plugins/fileopensave/api/providers/Tree.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/model/VFSFile.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/model/VFSTree.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/providers/vfs/model/VFSFileTest.java

Jira bug - https://hv-eng.atlassian.net/browse/BACKLOG-41229.
Attachment containing changes after code fix :

[BACKLOG-41229] - Decode PVFS File Paths: PDI - Browse - Select a file from VFS

---

plugins/connections/pom.xml

[PPP-4760]-Vulnerable Component: Apache CXF 3.3.1
[PPP-4760]: https://hv-eng.atlassian.net/browse/PPP-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4760]-Vulnerable Component: Apache CXF 3.3.1

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

Can't assume LOCAL and REPOSITORY are the only options

[PDI-20094] - fix VFS recent file for file-open-save

---

plugins/streaming/impls/jms/pom.xml
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/context/WebsphereMQProvider.java

with Java17 compatibility issues.

[BACKLOG-41224] Updated the IBM MQ libraries to version 9.4.0.0 to deal

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonTabsDelegate.java

- Allow plugins to add web functions with names
- add a function to check whether another function is defined

[BACKLOG-40339] - more plugin web functions

---

assemblies/client/pom.xml
assemblies/core/client/pom.xml
assemblies/core/static/src/main/resources-filtered/Spoon.bat
assemblies/static/src/main/resources-filtered/Spoon.bat

[PDI-20157] - Spoon is distributed with Java 8 swt library included

---

plugins/connections/pom.xml

Revert - [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1
[PPP-4760]: https://hv-eng.atlassian.net/browse/PPP-4760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert - [PPP-4760]-Vulnerable Component: Apache CXF 3.3.1

---

engine/src/main/java/org/pentaho/di/trans/TransPreviewFactory.java
engine/src/main/java/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java
engine/src/main/java/org/pentaho/di/trans/steps/getfilenames/GetFileNamesMeta.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/getfilenames/GetFileNamesDialog.java

[BACKLOG-41094] Updated GetFileNames to support reading from global and

---

engine/src/main/java/org/pentaho/di/trans/Trans.java

[BACKLOG-38964] - added overloaded method for prepare execute for webttle
[BACKLOG-38964]: https://hv-eng.atlassian.net/browse/BACKLOG-38964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-38964] - added overloaded method for prepare execute for webttle

---

engine/pom.xml

connection pool for hibernate, and tomcat handles that.

[PPP-4391] Remove c3p0 dependency; was never really used except as a

---

plugins/avro-format/core/pom.xml
plugins/avro-format/core/src/main/java/org/pentaho/di/trans/steps/avro/input/AvroNestedReader.java
plugins/avro-format/core/src/test/java/org/pentaho/di/trans/steps/avro/input/PentahoAvroReadWriteTest.java

This reverts commit 5b00eec0574b63c143c0b82eac79a1320459a659.

Revert "[PPP-5046] - Added changes for Vulnerable Component: Avro"

---

core/src/main/java/org/pentaho/di/core/extension/KettleExtensionPoint.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

[BACKLOG-41827] Added a new extension point that is called when a new

---

engine/src/main/java/org/pentaho/di/trans/steps/tableinput/TableInputMeta.java
engine/src/main/java/org/pentaho/di/www/StatusServletUtils.java

[BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code
[BACKLOG-36134]: https://hv-eng.atlassian.net/browse/BACKLOG-36134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code

---

ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java

@pentaho/tatooine_dev  please review

[PDI-20154] Spoon crashes with NullPointerException, when connected with poweruser role

---

engine/src/main/java/org/pentaho/di/trans/steps/tableinput/TableInputMeta.java
engine/src/main/java/org/pentaho/di/www/StatusServletUtils.java

[BACKLOG-36134]-Consolidate Redundant Secure XML Parsing code
[BACKLOG-36134]: https://hv-eng.atlassian.net/browse/BACKLOG-36134?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

  BACKLOG-36134-Consolidate Redundant Secure XML Parsing code

---

plugins/connections/pom.xml
plugins/repositories/pom.xml

chore: centralize dojo.version [PPP-4824]

---

ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java

[PDI-20154] Add failsafe also for edit and dupe

---

core/src/main/java/org/pentaho/di/core/Const.java
ui/src/main/java/org/pentaho/di/ui/trans/dialog/TransExecutionConfigurationDialog.java

[BISERVER-15051] hide internal variable when hide internal varibles set to Y

---

plugins/connections/pom.xml
plugins/repositories/pom.xml

Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/9567
Depends on:
- https://github.com/pentaho/maven-parent-poms/pull/611

[SP-6590] Backport of PPP-4824 - Vulnerable Component: dojo 1.9.3 (10.2 Suite)

---

ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java

original PRs: https://github.com/pentaho/pentaho-kettle/pull/9569
https://github.com/pentaho/pentaho-kettle/pull/9582

[SP-6591] - Backport of PDI-20154 - Spoon crashes with NullPointerException, when connected with poweruser role (9.3 Suite)

---

plugins/avro-format/core/pom.xml
plugins/avro-format/core/src/main/java/org/pentaho/di/trans/steps/avro/input/AvroNestedReader.java
plugins/avro-format/core/src/test/java/org/pentaho/di/trans/steps/avro/input/PentahoAvroReadWriteTest.java

This is a copy of the previous PR (https://github.com/pentaho/pentaho-kettle/pull/9597) which was inadvertently closed.

[SP-6599]- Backport of Vulnerable Avro component changes.

---

ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java

original PRs: https://github.com/pentaho/pentaho-kettle/pull/9569
https://github.com/pentaho/pentaho-kettle/pull/9582

[SP-6592] -Backport of PDI-20154 - Spoon crashes with NullPointerException, when connected with poweruser role (10.2 Suite)

---

engine/src/main/java/org/pentaho/di/job/JobExecutionConfiguration.java
engine/src/main/java/org/pentaho/di/kitchen/KitchenCommandExecutor.java

* update kitchen to initialize variables from the bowl
* update JobExecutionConfiguration to use getUsedVariables helper method

[BACKLOG-41510] project variable fixes for jobs:

---

core/src/main/java/org/pentaho/di/core/Const.java
plugins/pur/core/src/main/java/com/pentaho/repository/importexport/PdiContentProvider.java

[BISERVER-15051] removing internal variable when hide internal varibles set to Y

---

plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/providers/model/TestRepositoryDirectory.java

Not that it is very problematic, but it looks nicer following Sonar recommendations.
@eddie-martinez @ddiroma

[CLEANUP] Fix Sonar issue on unit test

---

pom.xml

Covers these PRs
- https://github.com/pentaho/pentaho-kettle/pull/9547
- https://github.com/pentaho/pentaho-kettle/pull/9584
- https://github.com/pentaho/pentaho-kettle/pull/9586
One of these was an intermediate(ish) change that was mostly undone by later ones

[SP-6606] Backport Jetty upgrades

---

core/src/main/java/org/pentaho/di/core/database/Database.java

[PDI-20208]-Database Explorer showing all tables on MySQL Server when using MySQL 8 JDBC Driver
[PDI-20208]: https://hv-eng.atlassian.net/browse/PDI-20208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-20208]-Database Explorer showing all tables on MySQL Server when using MySQL 8 JDBC Driver

---

plugins/pur/core/src/main/java/com/pentaho/repository/importexport/PdiContentProvider.java

Reverts pentaho/pentaho-kettle#9653

Revert "[BISERVER-15051] hide internal variables PUC side"

---

core/src/main/java/org/pentaho/di/core/database/Database.java

[Revert] "[PDI-20208]-Database Explorer showing all tables on MySQL Server when using MySQL 8 JDBC Driver"
[PDI-20208]: https://hv-eng.atlassian.net/browse/PDI-20208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[Revert] "[PDI-20208]-Database Explorer showing all tables on MySQL Server when using MySQL 8 JDBC Driver"

---

plugins/pur/core/src/main/java/com/pentaho/repository/importexport/PdiContentProvider.java

Reverts pentaho/pentaho-kettle#9657

Revert "Revert "[BISERVER-15051] hide internal variables PUC side""

---

plugins/pur/core/src/main/java/com/pentaho/repository/importexport/StreamToJobNodeConverter.java
plugins/pur/core/src/main/java/com/pentaho/repository/importexport/StreamToTransNodeConverter.java

[BISERVER-13909] - Uploaded PDI Job/Transformation has file size of 0 on the Properties screen

---

engine/src/main/java/org/pentaho/di/trans/TransMeta.java

- Fixed to ensure the getAll() is not called in loop

[BACKLOG- 42745] Fix: select partition on step only includes Local

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/kettle-variables.xml

[PDI-20195] - inconsistent variable names recently created

---

assemblies/lib/pom.xml
plugins/pur/core/src/main/java/com/pentaho/di/services/PentahoDiPlugin.java
plugins/pur/core/src/main/java/com/pentaho/repository/importexport/PdiContentProvider.java
plugins/repositories/core/pom.xml

[BACKLOG-42810]-Upgrading jackson.jaxrs to jackson.jakarta.rs to support Jakarta functionality as part of tomcat upgradation.
[BACKLOG-42810]: https://hv-eng.atlassian.net/browse/BACKLOG-42810?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-42810]-Upgrading jackson.jaxrs to jackson.jakarta.rs to support Jakarta functionality as part of tomcat upgradation.

---

engine/src/main/java/org/pentaho/di/trans/steps/httppost/HTTPPOST.java

[PDI-20135] - Http Post step does not process configured file paths correctly

---

assemblies/lib/pom.xml

[BACKLOG-42946] - Migrate Jetty from 11 to 12
[BACKLOG-42946]: https://hv-eng.atlassian.net/browse/BACKLOG-42946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-42946] - Migrate Jetty from 11 to 12

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

[PDI-20262] - Uploaded PDI Job/Transformation in PDI and save in Repository has file size of 0 on the Properties screen

---

engine/pom.xml
engine/src/main/java/org/pentaho/di/www/WebServer.java

[BACKLOG-42980]-Fixing Jetty upgrade bugs in pentaho-kettle
[BACKLOG-42980]: https://hv-eng.atlassian.net/browse/BACKLOG-42980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-42980]-Fixing Jetty upgrade bugs in pentaho-kettle

---

engine/pom.xml

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3
[BACKLOG-41596]: https://hv-eng.atlassian.net/browse/BACKLOG-41596?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41596]-Upgrading EhCache 2 to JCache and EhCache 3

---

engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/repository/Repository.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java
plugins/pur/repository-proxy/src/main/java/org/pentaho/di/repository/pur/provider/PurRepositoryProxy.java
ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ClustersController.java
ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsController.java
ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/PartitionsController.java
ui/src/main/java/org/pentaho/di/ui/repository/repositoryexplorer/controllers/SlavesController.java
ui/src/main/java/org/pentaho/di/ui/spoon/SharedObjectSyncUtil.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonClustersDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonPartitionsDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonSharedObjectDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonSlaveDelegate.java

No longer needed/used now that we've switched to Bowls.

[BACKLOG-42827] - remove dead code

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/job/entries/shell/JobEntryShell.java
engine/src/main/resources/kettle-variables.xml

[BISERVER-15147] - Shell Job entry step invoking Perl Script fails

---

core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java
plugins/pur/core/src/main/java/com/pentaho/repository/importexport/StreamToJobNodeConverter.java
plugins/pur/core/src/main/java/com/pentaho/repository/importexport/StreamToTransNodeConverter.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

This PR addresses PDI-20190
@pentaho/tatooine_dev please review

fix: Issues with encoding when reading files with charset different from UTF-8

---

engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInput.java
engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputData.java
engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputField.java
engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputTest.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/loadfileinput/LoadFileInputDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/propertyinput/PropertyInputDialog.java

[PDI-20301] "UnsupportedEncodingException" exception occurred while using Load file content in memory 

---

plugins/put-a-file-with-ftp/impl/src/main/java/org/pentaho/di/job/entries/ftpput/JobEntryFTPPUT.java
plugins/put-a-file-with-ftp/impl/src/main/resources/org/pentaho/di/job/entries/ftpput/messages/messages_en_US.properties

chore: change log level and message

---

engine/src/main/java/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java

[BACKLOG-43059]-Update DatabaseLookup.java

---

engine/pom.xml
plugins/rest/core/pom.xml

[BACKLOG-43209]-OSGi Assembly Issues
[BACKLOG-43209]: https://hv-eng.atlassian.net/browse/BACKLOG-43209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43209]-OSGi Assembly Issues

---

engine/src/main/java/org/pentaho/di/trans/steps/delete/Delete.java
engine/src/main/resources/org/pentaho/di/trans/steps/delete/messages/messages_en_US.properties

Transformation step : Delete backend for webttle

[Backlog 43336] : Transformation step : Delete backend for webttle

---

engine/src/main/java/org/pentaho/di/trans/steps/systemdata/SystemData.java

[BACKLOG-43393] - SystemInfo related changes
[BACKLOG-43393]: https://hv-eng.atlassian.net/browse/BACKLOG-43393?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43393] - SystemInfo related changes

---

engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInput.java
engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputData.java
engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputField.java
engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInputTest.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/loadfileinput/LoadFileInputDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/propertyinput/PropertyInputDialog.java

* [PDI-20301] "UnsupportedEncodingException" exception occurred while using Load file content in memory
* [PDI-20301] Minor corrections and Sonar suggestions
* chore: minor corrections and Sonar suggestions
[PDI-20301]: https://hv-eng.atlassian.net/browse/PDI-20301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PDI-20301]: https://hv-eng.atlassian.net/browse/PDI-20301?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6791] - Backport of PDI-20301 - "UnsupportedEncodingException" exception occurred while using Load file content in memory (10.2 Suite)

---

plugins/connections/pom.xml
plugins/repositories/core/pom.xml
plugins/repositories/pom.xml

chore: vulnerable component requirejs [PPP-5516]

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryExporter.java

Made the change to copy the config objects before
exporting the repository for both transformation and job

[BaCKLOG-43472] Get Spoon: Repository -> Export Repository working with Global/Local

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/tree/TreePopupMenuProvider.java
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties

[BACKLOG-43421] Fixed the right click menu items names for the config

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/JsonOutput.java

[BACKLOG-42864] JSON Output for Webttle

---

core/src/main/java/org/pentaho/di/core/util/Utils.java
engine/src/main/java/org/pentaho/di/trans/step/BaseStep.java
engine/src/main/java/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java
engine/src/main/java/org/pentaho/di/trans/steps/delete/Delete.java
engine/src/main/java/org/pentaho/di/trans/steps/formula/Formula.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
plugins/excel/core/src/main/java/org/pentaho/di/trans/steps/excelinput/ExcelInput.java
plugins/excel/core/src/main/java/org/pentaho/di/trans/steps/excelinput/ExcelInputDialog.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/json/JsonSampler.java

- Excel Input
- JSON Input
- Formula
- Delete
- DBLookup

[BACKLOG-43661] Sonar fixes for steps

---

plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/addsequence/AddSequenceTest.java

[BACKLOG-43558] - Writing test cases for Add Sequence

[BACKLOG-43558] - Writing test cases for Add Sequence

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/tree/TreeManager.java
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties

and update wording on tooltip for view tab search

[BACKLOG-43448] - refresh view tree so filter works

---

engine/src/main/java/org/pentaho/di/trans/steps/systemdata/SystemData.java
engine/src/test/java/org/pentaho/di/trans/steps/systemdata/SystemDataTest.java

[BACKLOG-43558] - Writing test cases for SystemData Sequence

[BACKLOG-43558] - Writing test cases for SystemData Sequence

---

engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

[BACKLOG-43558] - Writing test cases for TextFileInput

[BACKLOG-43558] - Writing test cases for TextFileInput

---

engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

[BACKLOG-43558] - Writing test cases for TextFileInput increasing line coverage

[BACKLOG-43558] - Writing test cases for TextFileInput increasing line coverage

---

assemblies/lib/pom.xml
engine/pom.xml

[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version
[BACKLOG-43757]: https://hv-eng.atlassian.net/browse/BACKLOG-43757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43757]-Upgrading Tomcat and its Related Software's to latest version

---

plugins/email-messages/impl/pom.xml
plugins/mail-job/impl/pom.xml
plugins/mail/impl/pom.xml
plugins/pur/core/src/main/resources/org/pentaho/di/repository/pur/UnifiedRepositoryInvocationHandlerTest.java

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation
[BACKLOG-43098]: https://hv-eng.atlassian.net/browse/BACKLOG-43098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation

---

engine/src/main/java/org/pentaho/di/job/JobMeta.java
engine/src/main/java/org/pentaho/di/kitchen/KitchenCommandExecutor.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java

- safeguard reading Props in JobMeta and TransMeta in case its not initialized
- initialize Props for the kitchen export case

[BACKLOG-42840] - correct props usage for kitchen

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/tree/extension/UIExtension.java
ui/src/main/java/org/pentaho/di/ui/spoon/tree/extension/UIExtensionManager.java

Changes include
- Added a interface that plugins can implement that will add the UI element

[BACKLOG-43439] Added a way for Plugins to add UI elements to Spoon

---

plugins/aggregate-rows/core/pom.xml
plugins/json/core/pom.xml
plugins/pentaho-googledrive-vfs/assemblies/plugin/pom.xml

[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures
[BACKLOG-43874]: https://hv-eng.atlassian.net/browse/BACKLOG-43874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43874]-Fix JDK21 test pipeline(test1) build failures

---

core/src/main/resources/kettle-database-types.xml

Tag Deprecated DB Types in PDI UI

[BACKLOG-43842] Tag Deprecated DB Types in PDI UI

---

plugins/excel/core/src/it/java/org/pentaho/di/trans/steps/excelinput/StaxWorkBookIT.java
plugins/mail-validator/impl/pom.xml
plugins/pentaho-reporting/impl/pom.xml
plugins/pentaho-reporting/impl/src/it/java/org/pentaho/di/trans/steps/pentahoreporting/PDI7502IT.java
plugins/pentaho-reporting/impl/src/it/java/org/pentaho/di/trans/steps/pentahoreporting/PentahoReportingOutputIT.java
plugins/pentaho-reporting/impl/src/it/resources/org/pentaho/di/trans/steps/pentahoreporting/pdi-13434.ktr
plugins/rest/core/pom.xml
plugins/rest/core/src/it/java/org/pentaho/di/trans/steps/rest/RestInputIT.java

[BACKLOG-43728] Fix Integration Test

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/controllers/FileControllerTest.java
ui/src/main/java/org/pentaho/di/ui/core/FileDialogOperation.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

In both left tree and right pane

[BACKLOG-40174] - support custom icons in F-O-S dialogs

---

core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/shared/SharedObjects.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java

originally prompted by sonarqube, these changes break compatibility with other components that we don't want to update, and could break compatibility with third party code.

[BACKLOG-43715] - restore some API changes for backwards compatibility

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/util/StringEvaluatorTest.java
engine/src/main/resources/kettle-variables.xml

fix: throw out of range exception when converting String to Integer [PDI-20377]

---

engine/src/it/java/org/pentaho/di/www/CarteIT.java
plugins/rest/core/pom.xml
plugins/rest/core/src/it/java/org/pentaho/di/trans/steps/rest/RestIT.java
plugins/rest/core/src/it/java/org/pentaho/di/trans/steps/rest/RestInputIT.java

[BACKLOG-44349]-Fixing IT Classes in pentaho-kettle
[BACKLOG-44349]: https://hv-eng.atlassian.net/browse/BACKLOG-44349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-44349]-Fixing IT Classes in pentaho-kettle

---

engine/src/test/java/org/pentaho/di/www/RegisterJobServletTest.java
plugins/repo-vfs/repo-vfs-core/pom.xml
plugins/repo-vfs/repo-vfs-core/src/main/java/org/pentaho/di/repovfs/repo/BasicAuthentication.java
plugins/repo-vfs/repo-vfs-core/src/main/java/org/pentaho/di/repovfs/repo/RepositoryClient.java
plugins/repo-vfs/repo-vfs-core/src/test/java/com/pentaho/di/repovfs/RepositoryClientUploadDeleteTest.java
plugins/repo-vfs/repo-vfs-spoon/pom.xml

[BACKLOG-44499]-Upgrading repo-vfs plugin to support jersey
[BACKLOG-44499]: https://hv-eng.atlassian.net/browse/BACKLOG-44499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-44499]-Upgrading repo-vfs plugin to support jersey

---

engine/src/test/java/org/pentaho/di/shared/SharedObjectUtilTest.java
plugins/pentaho-reporting/impl/src/main/java/org/pentaho/di/trans/steps/pentahoreporting/ReportExportTask.java

- SharedObjectUtilTest depends on KettleEnvironment
- ReportExportTask was missing an assignment

[BACKLOG-41444] - fix build and test issues

---

plugins/core/impl/pom.xml
plugins/excel/core/pom.xml

[PDI_20406]-There are too many transitive dependencies in the excel and core plugins which causes errors

[PDI_20406]-There are too many transitive dependencies in the excel and core plugins which causes errors

---

assemblies/core/static/src/main/resources-filtered/Spoon.bat
assemblies/core/static/src/main/resources-filtered/spoon.sh
assemblies/static/src/main/resources-filtered/Spoon.bat
assemblies/static/src/main/resources-filtered/spoon.sh

Reference PR: https://github.com/pentaho/pentaho-kettle/pull/10049

[SP-6874] Backport of PPP-5643 - Vulnerable Component: protobuf (deep scan) - Hadoop (10.2 Suite)

---

core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
plugins/connections/ui/src/main/java/org/pentaho/di/vfs/connections/ui/dialog/ConnectionDialog.java
plugins/repo-vfs/repo-vfs-spoon/src/main/java/org/pentaho/di/repovfs/plugin/vfs/RepoVfsPdiProvider.java

types when creating a new vfs connection in ConnectionDilaog

[BACKLOG-44582] Filter out the "PentahoRepository" from the Connection

---

ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonClustersDelegate.java
ui/src/main/resources/org/pentaho/di/ui/spoon/messages/messages_en_US.properties

[BACKLOG-44755] Added confirmation dialog before deleting cluster

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/main/java/org/pentaho/di/core/util/Utils.java
engine/src/main/java/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java
engine/src/main/java/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/databaselookup/DefaultCache.java
engine/src/main/java/org/pentaho/di/trans/steps/dummytrans/DummyTrans.java
engine/src/test/java/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java
engine/src/test/java/org/pentaho/di/trans/steps/databaselookup/PDI5436Test.java
engine/src/test/java/org/pentaho/di/trans/steps/mock/StepMockHelper.java

feat[PDI-20372]: optimize DatabaseLookup cache creation

---

engine/src/main/java/org/pentaho/di/base/AbstractBaseCommandExecutor.java
engine/src/main/java/org/pentaho/di/base/IParams.java
engine/src/main/java/org/pentaho/di/base/Params.java
engine/src/main/java/org/pentaho/di/kitchen/Kitchen.java
engine/src/main/java/org/pentaho/di/kitchen/KitchenCommandExecutor.java
engine/src/main/java/org/pentaho/di/pan/CommandLineOptionProvider.java
engine/src/main/java/org/pentaho/di/pan/Pan.java
engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java
engine/src/main/java/org/pentaho/di/repository/RepositoryBowl.java
plugins/repo-vfs/repo-vfs-spoon/src/main/java/org/pentaho/di/repovfs/plugin/spoon/RepoVfsSpoonLifecycleListener.java
plugins/repo-vfs/repo-vfs-spoon/src/main/java/org/pentaho/di/repovfs/plugin/vfs/RepoVfsPdiProvider.java

This reverts commit 478d45e1fe2596505add6df7bb039ab41b91f287.

Revert "[BACKLOG-44137] Update Pan/Kitchen to support execution of"

---

engine/pom.xml
engine/src/main/java/org/pentaho/di/trans/steps/propertyinput/PropertyInput.java
engine/src/main/java/org/pentaho/di/trans/steps/propertyinput/PropertyInputData.java
engine/src/main/java/org/pentaho/di/trans/steps/propertyinput/PropertyInputField.java
engine/src/main/java/org/pentaho/di/trans/steps/propertyinput/PropertyInputMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/propertyinput/PropertyInputMetaTest.java
pom.xml
ui/pom.xml
ui/src/main/java/org/pentaho/di/ui/trans/steps/propertyinput/PropertyInputDialog.java

feat[PPP-5739]: replace ini4j with commons-configuration2

---

engine/pom.xml
plugins/monet-db-bulk-loader/impl/pom.xml
plugins/xml/core/pom.xml
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmljoin/XmlJoinOmitNullValuesTest.java
plugins/xml/pom.xml
pom.xml

chore[PPP-5719]: upgrade Saxon dependency

---

plugins/ftp-delete/impl/src/main/java/org/pentaho/di/job/entries/ftpdelete/JobEntryFTPDelete.java
plugins/ftp-delete/ui/src/main/java/org/pentaho/di/ui/job/entries/ftpdelete/JobEntryFTPDeleteDialog.java

fix[PDI-20484]: change timeout type from int to String in FTPDelete Step

---

plugins/ftp-delete/impl/src/main/java/org/pentaho/di/job/entries/ftpdelete/JobEntryFTPDelete.java

fix[PDI-20484]: initialize timeout to "0" in FTPDelete Step

---

plugins/get-file-with-ftp/impl/src/main/java/org/pentaho/di/job/entries/ftp/JobEntryFTP.java
plugins/get-file-with-ftp/ui/src/main/java/org/pentaho/di/ui/job/entries/ftp/JobEntryFTPDialog.java

fix[PDI-20495]: change timeout type from int to String in JobEntryFTP

---

engine/src/main/java/org/pentaho/di/base/MetaFileLoaderImpl.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java

- pass along repository when creating TransMeta
- store bowl in TransMeta when we get one during construction
- handle getSteps() returning null during setBowl during early construction

[BACKLOG-41965] - let sub-trans inherit the project

---

plugins/repo-vfs/repo-vfs-spoon/src/main/java/org/pentaho/di/repovfs/plugin/server/RepositoryTypeGuesser.java

[BACKLOG-46381] - update RepositoryTypeGuesser for carte

---

plugins/pur/core/src/main/java/com/pentaho/repository/importexport/PDIImportUtil.java
plugins/xml/core/src/main/java/org/pentaho/di/job/entries/xsdvalidator/JobEntryXSDValidator.java
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmljoin/XMLJoin.java
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xsdvalidator/XsdValidator.java

fix[PPP-5982]: add proper initialization to XML parser

---

engine/src/it/java/org/pentaho/di/kitchen/KitchenIT.java
engine/src/it/java/org/pentaho/di/pan/PanIT.java

[BACKLOG-46527]-Remove securitymanager from IT classes
[BACKLOG-46527]: https://hv-eng.atlassian.net/browse/BACKLOG-46527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-46527]-Remove securitymanager from IT classes
