pentaho/pentaho-kettle

engine/src/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderMeta.java

Replace Drools' StringUtils with PDI Const.isEmpty()
Related: #877 (Drools Cleanup in Text File Output)
See Also: #272 and http://jira.pentaho.com/browse/PDI-10657

[CLEANUP] Remove import of Drools StringUtils from OraBulkLoader

---

core/src/org/pentaho/di/core/util/EnvUtil.java
core/src/org/pentaho/di/i18n/PackageMessages.java
engine/src/kettle-servlets.xml
engine/src/org/pentaho/di/cluster/SlaveServer.java
engine/src/org/pentaho/di/www/BodyHttpServlet.java
engine/src/org/pentaho/di/www/Carte.java
engine/src/org/pentaho/di/www/CarteServlet.java
engine/src/org/pentaho/di/www/GetPropertiesServlet.java
engine/src/org/pentaho/di/www/messages/messages_en_US.properties
ui/src/org/pentaho/di/ui/core/dialog/KettlePropertiesFileDialog.java

What was done:
1) added new servlet, that shows running server kettle.properties
2) added 2 configuration parameters telling slave which master to use for
obtaining properties on startup
3) added changes to startup logic, based on configuration

BACKLOG-1621 Send kettle.properties across Carte cluster

---

core/src/org/pentaho/di/core/database/Database.java

Some drivers' PreparedStatement objects do not return metadata via getMetaData(). In our fallback code, we eventually try executing the query, then getting the metadata. If it is still not available via PreparedStatement.getMetaData(), since we have the ResultSet we should again fall back to ResultSet.getMetaData().

[PDI-12870]: Fixed issue with null metadata from PreparedStatement

---

core/src/kettle-database-types.xml

add Redshift to kettle-database-types.xml
@mbatchelor @lucboudreau this fixes failing projects that use metadata(like PIR)

[PMD-994] - Add Redshift dialect to Pentaho Metadata

---

core/src/org/pentaho/di/core/row/RowMeta.java
core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java
core/test-src/org/pentaho/di/core/row/RowMetaTest.java

When searching for value index, verify name is correct before returning.
Add/remove cached value metas while searching and modifying instead of complete reindex
http://jira.pentaho.com/browse/BACKLOG-1938
@mattyb149

[BACKLOG-1938]Lazy ValueMeta name caching

---

core/src/org/pentaho/di/core/database/SqlScriptParser.java
core/test-src/org/pentaho/di/core/database/SqlScriptParserTest.java

What was done:
1) added unit test
2) changed comments parsing logic -- added support for /*+  construction

PDI-13054 - Execute SQL Script ignores Oracle hint

---

assembly/package-res/spoon.sh

@rmansoor, could you review, please
here is some improvements for https://github.com/pentaho/pentaho-kettle/pull/1023
Now absolute path to file is used. Thus STARTUP variable doesn't depend on current directory.

[PDI-13365] - Spoon.sh: unable to run Spoon outside the spoon home dir (remastered)

---

engine/src/org/pentaho/di/trans/steps/datagrid/DataGridMeta.java
engine/src/org/pentaho/di/trans/steps/formula/Formula.java

Also related to the reproduction transformation in the Jira case, a fix for the Formula step was provided to cast null formula results to the correct data type

[PDI-13420]: Fixed bug in DataGrid to allow creation of NULL values

---

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
engine/src/org/pentaho/di/trans/steps/excelwriter/messages/messages_en_US.properties

There is a fix that consists of avoiding using CellUtil.setCellStyleProperty() method on POI because of known issue:
https://bz.apache.org/bugzilla/show_bug.cgi?id=56548.

[BACKLOG-2253]: ExcelWriter: cell background goes completely black when editing a cell that has been formatted

---

engine/src/org/pentaho/di/job/entries/job/JobEntryJob.java

@mattyb149 review it please.
This is suggested instead of https://github.com/pentaho/pentaho-kettle/pull/889
The behavior implemented is like in JobEntryTrans when execute transformation on the local machine:
if subjob result contains rows, they are used as the JobEntryJob result rows
if subjob result contains no rows, JobEntryJob result rows stay unchanged

[PDI-13315] [v2] Subjobs called from jobs are duplicating result rows

---

engine/src/org/pentaho/di/core/compress/gzip/GZIPCompressionOutputStream.java
engine/test-src/org/pentaho/di/core/compress/gzip/GZIPCompressionOutputStreamTest.java

Corrected GZip Output Stream handler to properly close the stream, instead of only flushing pending writes.

[PDI-13325] Close GZip Files in Text File Output

---

core/src/org/pentaho/di/core/row/RowMeta.java
core/src/org/pentaho/di/core/row/RowMetaInterface.java
core/test-src/org/pentaho/di/core/row/RowMetaTest.java
engine/src/org/pentaho/di/trans/steps/mergejoin/MergeJoinMeta.java
engine/test-src/org/pentaho/di/trans/steps/mergejoin/MergeJoinMetaTest.java

I deprecated one API method in RowMetaInterface and added a new one (delegating the old to the new), but since this is for 6.0 I figured it was ok.
This change allows the origin step for fields to be retained even if in info streams, and if they are renamed then the origin step is set as the one that is passed in. For this Jira case, I only updated Merge Join. In the future we can change other steps (Join Rows, e.g.) to use the new API method and pass its own name in as the origin.
@mattcasters @hudak @rfellows Do you mind reviewing this? Thanks!
P.S. Sorry about the inline Checkstyle changes, I have a habit of typing quickly then hitting the AutoFormat key combo to get it pretty...

[PDI-13539]: Fixed the setting of origin step in Merge Join

---

engine/src/org/pentaho/di/trans/steps/reservoirsampling/ReservoirSampling.java
engine/src/org/pentaho/di/trans/steps/reservoirsampling/ReservoirSamplingMeta.java
engine/test-src/org/pentaho/di/trans/steps/reservoirsampling/ReservoirSamplingMetaTest.java

Fix an issue where the step attributes were not being read back out of a repository, falling back to the default values

[PDI-13554] Reservoir Sampling Save to Repository

---

engine/src/org/pentaho/di/core/KettleEnvironment.java
engine/src/org/pentaho/di/core/lifecycle/KettleLifecycleSupport.java
engine/src/org/pentaho/di/core/lifecycle/LifecycleSupport.java
engine/test-src/org/pentaho/di/core/lifecycle/KettleLifecycleSupportTest.java

Environment init fails when KettleLifecycleListeners are registered while environment init is in progress

[TEST]Handle concurrent registration of lifecycle listeners

---

engine/src/org/pentaho/di/job/entries/ftpsget/FTPSConnection.java
engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java
ui/src/org/pentaho/di/ui/job/entries/ftpdelete/JobEntryFTPDeleteDialog.java
ui/src/org/pentaho/di/ui/job/entries/ftpput/JobEntryFTPPUTDialog.java
ui/src/org/pentaho/di/ui/job/entries/ftpsget/JobEntryFTPSGetDialog.java
ui/src/org/pentaho/di/ui/job/entries/ftpsput/JobEntryFTPSPUTDialog.java
ui/src/org/pentaho/di/ui/job/entries/sftp/JobEntrySFTPDialog.java
ui/src/org/pentaho/di/ui/job/entries/sftpput/JobEntrySFTPPUTDialog.java

In several FTP, SFTP, and FTPS job entries, when clicking the Test Connection button, the job entry does not retest the connection after the first test is completed.
This fixes false-positive connections resulting from the test.

[PDI-11388] - FTPx settings not retested in Dialog

---

core/src/org/pentaho/di/core/database/SqlScriptParser.java
core/test-src/org/pentaho/di/core/database/SqlScriptParserTest.java

Correctly passes through hard-coded quotes that appear within a string, instead of blindly switching back to SQL mode.

[PDI-13654] SQLScriptParser Hardcoded Quotes

---

engine/src/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoader.java
engine/src/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoaderMeta.java
engine/src/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDbVersion.java
engine/src/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDbVersionException.java
engine/src/org/pentaho/di/trans/steps/monetdbbulkloader/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDbVersionTest.java

The problem was:
Starting from Jan 2014-SP2 bugfix release we should not use double write of empty line (see the sample http://dev.monetdb.org/hg/MonetDB/file/tip/java/example/SQLcopyinto.java).
At the same time for "old" versions of MonetDB (before Jan 2014-SP2) we are still need to do this one otherwise the error appears.
The fix consists of:
1)Getting current MonetDB version (via JDBC property) during execution the step
2)Defining if the current version is before boundary Jan 2014-SP2 version or not (so-called compatibility with old version db mode).
3)Addition condition for such case during writing buffer.
Also there are several unit tests.

[PDI-12278]: MonetDB Bulk Loader error with MonetDB Jan 2014-SP2 bugfix  release

---

engine/src/org/pentaho/di/job/entries/ftpput/JobEntryFTPPUT.java
engine/src/org/pentaho/di/job/entries/ftpsput/JobEntryFTPSPUT.java
engine/test-src/org/pentaho/di/job/entries/ftpput/JobEntryFTPPUTLoadSaveTest.java
engine/test-src/org/pentaho/di/job/entries/ftpsput/JobEntryFTPSPUTLoadSaveTest.java

The serverPort variable has been stored as a String since 4.0, when the job was first introduced.  Stripped the offending code as serverport was never stored as an Integer.

[PDI-13658] FTPS Put Step with Variable Port Number

---

engine/src/org/pentaho/di/job/entries/mssqlbulkload/JobEntryMssqlBulkLoad.java

Change logging-level of message from "Detailed" to "Error" when the bulk loader doesn't find the destination table.

[PDI-13605] Use Error log for missing table

---

build.xml
engine/src/org/pentaho/di/job/entries/sftp/JobEntrySFTP.java
engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java
ivy.xml
test/org/pentaho/di/job/entries/sftp/JobEntrySFTPTest.java
test/org/pentaho/di/job/entries/sftp/SFTPClientTest.java
test/org/pentaho/di/job/entries/sftp/SftpServer.java

Use KettleVFS for the target file in SFTP Get job entry, so that target files that use variables in the path are parsed correctly

[PDI-12593] SFTP Target Directory with Variables

---

ui/src/org/pentaho/di/ui/core/database/dialog/tags/ExtTextbox.java

Fixes the display of the ExtTextbox class, used for the Amazon EMR and Amazon Hive job entries.
Requires pentaho/pentaho-commons-xul#77

[PDI-13770] Password Field Consistency

---

ui/src/org/pentaho/di/ui/core/widget/TableView.java

I wasn't able to figure out how to prevent call of FocusListener when items disposed, so  I just add isDisposed() check.  
@mdamour1976  please review.

[BACKLOG-3294] - Setting parameters in transformation (connected to DI Server) through exception

---

core/src/org/pentaho/di/core/database/Database.java
core/src/org/pentaho/di/core/database/map/DatabaseConnectionMap.java
core/test-src/org/pentaho/di/core/database/DatabaseConnectingTest.java

- make connections' map a CHM instance
- eagerly initialize singleton
- improve concurrency correctness by marking counters with 'volatile'
- add an integration test

[PDI-12717] - Race condition in database connection creation

---

core/src/org/pentaho/di/core/database/Database.java

PDI-13789 - Intermittent ConcurrentModificationException in Database.getValueFromSQLType - Fix ConcurrentModificationException by moving valueMetaPluginClasses initialization to static initializer per suggestion in previous [PR comment] (https://github.com/pentaho/pentaho-kettle/pull/1274#issuecomment-110572241). Tested locally and on server with test cases attached to PDI-13789.
Related to PDI-12194. I have not addressed registeredDrivers initialization mentioned in PDI-12194. This is currently protected by a synchronized block. Possible improvement is to use concurrentHashMap for registeredDrivers?

  PDI-13789 - Intermittent ConcurrentModificationException in Database.getValueFromSQLType

---

engine/src/org/pentaho/di/trans/steps/multimerge/MultiMergeJoin.java
ui/src/org/pentaho/di/ui/trans/steps/multimerge/MultiMergeJoinDialog.java

Error occurred because different parts of the dialog had a different idea of what the input steps were (previous steps according to transformation vs infosteps as per step meta configuration). This fix takes both into account so that any newly linked input steps can be configured, and any saved configuration does not get lost when the incoming hop is disabled.
To make this work the step's rowprocessor needed to be modified as well and this now takes all input steps into account that are also present as info stream. This allows a disabled incoming hop to be ignored during row processing (as it should).

PDI-11215: Cannot Edit Multiway Merge Join After Deleting an Input Hop.

---

core/src/org/pentaho/di/core/util/StringEvaluator.java
test/org/pentaho/di/core/util/StringEvaluatorTest.java

Set up actual length=maxLength for ValueMetaInterface.TYPE_INTEGER of StringEvaluationResult instead of default hardcoded length=15.

[BISERVER-12153]: DSW defaults for zero length for numeric fields in CSV datasource

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInputData.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java

[SP-1934] - Text File Input - 1 extra line read when using wrapped lines and 1 header line
- force reading from input when breaks' buffer is empty
- add a test for scenario of wrapped input with no headers
picked from https://github.com/pentaho/pentaho-kettle/pull/1362/
@mattyb149 @brosander @rmansoor please merge

[SP-1934] - Text File Input - 1 extra line read when using wrapped lines

---

assembly/ivy.xml
engine/ivy.xml

We need to bring in servlet-api 3 for karaf 3.0.3.

[BACKLOG-3855] - Using servlet-api 3.0.1 for karaf upgrade

---

engine/src/org/pentaho/di/core/lifecycle/KettleLifecycleSupport.java

The cause is in using Guava API available since v. 14.0
In case of PMR the Guava v.11 comes from Hadoop classpath.
This version of the library does not have the methods called.
The fix is to remove the causing Guava calls and replace them by
more verbose but universaly working code

[PDI-14037] - PMR jobs fails with NoSuchMethodException

---

test/org/pentaho/di/cluster/CarteLauncherTest.java

This is not elegant, but hanging test is not OK either. This approach doesn't lurk the problem (the test fails), but lets the other tests to be executed, so we can see who is failing and who is passing

[TEST] - abort the test after 10 minutes

---

core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

- enable a test case
- appy formatting
- small refactoring to improve readability
@mattyb149, @brosander, I noticed, ```test4ArgCtor()``` is not invoked during ```test``` phase (http://ci.pentaho.com/view/Data%20Integration/job/kettle-code-coverage/619/testReport/org.pentaho.di.core.row.value/ValueMetaBaseTest/). I've enabled it within this PR and made other non-significant changes. Review it please.

[TEST] - ValueMetaBaseTest changes

---

ui/src/org/pentaho/di/ui/job/dialog/JobDialog.java
ui/src/org/pentaho/di/ui/job/entries/job/JobEntryJobDialog.java
ui/src/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialog.java
ui/src/org/pentaho/di/ui/repository/RepositoryDirectoryUI.java
ui/src/org/pentaho/di/ui/repository/dialog/SelectDirectoryDialog.java
ui/src/org/pentaho/di/ui/trans/dialog/TransDialog.java
ui/src/org/pentaho/di/ui/trans/steps/jobexecutor/JobExecutorDialog.java
ui/src/org/pentaho/di/ui/trans/steps/mapping/MappingDialog.java
ui/src/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java
ui/src/org/pentaho/di/ui/trans/steps/simplemapping/SimpleMappingDialog.java
ui/src/org/pentaho/di/ui/trans/steps/singlethreader/SingleThreaderDialog.java
ui/src/org/pentaho/di/ui/trans/steps/transexecutor/TransExecutorDialog.java

- Add a list of restricted directories to the SelectDirectoryDialog dialog (Disable Ok button if the selection is in the restricted paths list)
- Move the code in TransDialog and JobDialog that sets up the SelectDirectoryDialog into RepositoryDirectoryUI so it can be setup consistently
- Restrict selection of the root when creating the SelectDirectoryDialog so people cant save their transformation or job there.
- Instead of defaulting the repository to a new directory (which points to the root), use the user home directory
- Use current repository directory as default when creating a new Transformation with the mapping step
- Use current repository directory as default when creating a new Transformation with the etl metadata injection step
- Use current repository directory as default …

PDI-13867: Able to save job/transformation in the root folder

---

engine/ivy.xml
engine/src/org/pentaho/di/base/AbstractMeta.java
engine/src/org/pentaho/di/core/attributes/metastore/AttributesInterfaceEntry.java
engine/src/org/pentaho/di/core/attributes/metastore/EmbeddedMetaStore.java
engine/src/org/pentaho/di/core/attributes/metastore/JsonElement.java
engine/src/org/pentaho/di/core/attributes/metastore/JsonElementType.java
engine/test-src/org/pentaho/di/core/attributes/metastore/EmbeddedMetaStoreTest.java

Embeddable metastore for use within TransMeta/JobMeta
Metastore elements and types are stored as entries in the attributes map. Elements and types are serialized as JSON when created or updated.
The following structures are added to the attributes map:
* `METASTORE.<namespace>`:
* `<type id>` : `<type as json>`
* `{'_': 'Embedded MetaStore Elements': 'namespace': '<namespace>': 'type':'<type id>'}`
* `<element id>` : `<element as json>`

[BACKLOG-3857]Embedded MetaStore impl

---

plugins/googleanalytics/src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialog.java

@mattyb149 please review. Previous version of GA api returned list of entries and column info needed to be fetched from it. New API returns null in case of no rows matched however column headers info is available.
See https://developers.google.com/gdata/javadoc/com/google/gdata/data/BaseFeed.html#getEntries()
https://developers.google.com/resources/api-libraries/documentation/analytics/v3/java/latest/com/google/api/services/analytics/model/GaData.html

[BACKLOG-4257] [Google Analytics Step] NPE - Clicking Get Fields button

---

core/src/org/pentaho/di/core/extension/ExtensionPointHandler.java
core/src/org/pentaho/di/core/extension/ExtensionPointMap.java
core/test-src/org/pentaho/di/core/extension/ExtensionPointIntegrationTest.java
core/test-src/org/pentaho/di/core/extension/ExtensionPointMapTest.java

Extension points of the same type are overriding each other, allowing only one of each type.
Instead save each extension point to a table by type and id
This allows overwriting old extension points with updated version of the same id and multiple callbacks
@mattyb149 @rmansoor

[PDI-13210]Allow multiple call backs per extension point

---

core/src/org/pentaho/di/core/extension/ExtensionPointMap.java
core/test-src/org/pentaho/di/core/extension/ExtensionPointMapTest.java

Use instance caching suppliers in ExtensionPointMap instaed of instances.
Some extension points rely on a Spoon environment and instances were failing in headless enironments.
This change creates a lazy loader for each callback, and the plugin class is instantiated only on first call.
@mattyb149 @rmansoor

[PDI-13210]Lazy loading extension point interfaces

---

engine/src/org/pentaho/di/job/entries/shell/JobEntryShell.java
engine/test-src/org/pentaho/di/job/entries/shell/JobEntryShellTest.java

@mattcasters, @brosander, @mattyb149, here is backport of https://github.com/pentaho/pentaho-kettle/pull/1485. Thanks

Backport of PDI-12176 - "Execute a shell script" job fails with "No such file or directory" (when developed on Windows, executed on Linux) (5.4 Suite)

---

core/src/org/pentaho/di/core/database/Database.java
core/test-src/org/pentaho/di/core/database/DatabaseConnectingTest.java

- fix the problem by moving fields' initialisation inside critical section
@mattyb149, @brosander, have you noticed ```DatabaseConnectingTest``` fails from time to time? I found out the reason and this fix is aimed to resolve it. Review it please.

[BACKLOG-4238] - Incorrect synchronization in Database class

---

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GoogleAnalyticsApiFacade.java

@mattyb149 please review. 
Fix is to detect case when path passed is absolute URI (it is in case of using variables like internal.transformtaion.filename.directory) and call corresponding File constructor, the one with String argument cannot handle absolute URIs.
No test since class affected by the change has only static method and constructor, creating test will involve refactoring it to be testable.

[BACKLOG-4250] [Google Analytics Step] The field Key File doesn't support the variable ${Internal.Transformation.Filename.Directory}

---

engine/src/org/pentaho/di/www/GetStatusServlet.java
engine/test-src/org/pentaho/di/www/GetStatusServletTest.java
engine/test-src/org/pentaho/di/www/ServletTestUtils.java

Japanese strings in DI server:
http://localhost:9080/pentaho-di/kettle/status
are garbled.
normal strings:
garbled strings:

fixed Japanese garbled page

---

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GoogleAnalyticsApiFacade.java

@mattyb149 Tested following cases:
- path with variable on win and mac
- absolute path on win and mac
- drive different from the one where PDI located
According to documentation getName().getPath() returns path starting with /, replaced with getURL().

[BACKLOG-4543] [Google Analytics Step] The field Key File doesn't work with windows path

---

engine/src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariables.java
engine/test-src/org/pentaho/di/job/entries/setvariables/ASCIIText.properties
engine/test-src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java
engine/test-src/org/pentaho/di/job/entries/setvariables/UTF8Text.properties

In Setvariables JobEntry,
I want to write a property file with Japanese strings, not in native2ascii-encoded strings.
With multi-byte character languages such as Japanese, Korean and Chinese,
it's too much trouble with native2ascii encoded strings.
Both UTF8 strings and native2ascii-encoded strings are accepted.

Reading properties file without native2ascii in SetVariables JobEntry

---

engine/src/org/pentaho/di/trans/steps/mail/Mail.java

If a "Comment" field was not specified and files were to be attached, an erroneous error message would be presented saying that content files could not be found when in fact it is the "Comment" field that was not specified.

Fixed invalid error message for Mail step

---

engine/src/org/pentaho/di/trans/TransMeta.java
engine/test-src/org/pentaho/di/trans/TransMetaTest.java

provider name when the output step name is changed
What was done:
1) During the fix of initial issue the tests using TransMeta.addOrReplace
failed. SO added a unit tetst demonstrating this and created the fix for
the issue.

BACKLOG-2941 -- Shared Dimension step should automatically update data

---

engine/src/org/pentaho/di/job/entries/shell/JobEntryShell.java

Update the step to use the Java temp directory when the script is embedded in the step.  The working directory is set elsewhere in ProcessBuilder.

[PDI-9585] JobEntryShell Write Script to Temp Dir

---

core/src/org/pentaho/di/core/database/Database.java
core/src/org/pentaho/di/core/database/ExtendedDSProviderInterface.java
core/src/org/pentaho/di/core/database/util/DatabaseUtil.java
core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java

- introduce a new interface for distinguishing the source where to look for data sources; the interface is 5.4-only, make it deprecated
- leave the rest of Database.normalConnect()
- add tests
@mattyb149, @brosander, @mattcasters, @deinspanjer, @pentaho-nbaker, @rmansoor, review it please.
**Note! This is not a direct backport of https://github.com/pentaho/pentaho-kettle/pull/1655 !**
/cc @pamval

[SP-1979] - Backport of PDI-13961 - Spoon firstly tries to conect via JNDI although connection type is JDBC (5.4 Suite)

---

assembly/package-res/spoon.sh

I've adapted the changes made in the pull request #1396 to the current master to fix the issue http://jira.pentaho.com/browse/PDI-13952

[PDI-13952] Return the correct exit code in spoon.sh

---

ui/src/org/pentaho/di/ui/trans/steps/loadfileinput/LoadFileInputDialog.java

When saving the Step Settings in the UI, do not save information about the listed files if "Filename in field" is set.

[PDI-12969] - Remove File List when File in Field

---

engine/src/org/pentaho/di/job/entries/getpop/JobEntryGetPOP.java

Replaced "throw exception" with logDebug, as it is informational, and not an issue that a directory already exists.

[PDI-14089] Fix logDebug error when directory exists

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/JobDelegate.java

This is the other half.. previously we had just transformations working right.

[BACKLOG-5063] Missing plugins trigger an error when opening transformation/job that were saved on DI repository

---

engine/src/org/pentaho/di/base/AbstractMeta.java
engine/test-src/org/pentaho/di/job/JobMetaTest.java
engine/test-src/org/pentaho/di/trans/TransMetaTest.java

Replaced AbstractMeta inheritance of ChangeFlag with delegation to prevent circular override.

[BACKLOG-3431]Fire content listeners on set/clear

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java

- set parsing value to null to prevent the regression from PDI-11194
- add test
As far as I know, the code freeze was not announced so far, hence I suppose it make sense to include this fix into 6.0 to remove the regression from the brand new release.

[PDI-14172] - Text file input Repeat doesn't work

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java
ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTabsDelegate.java

It was assumed the Welcome tab was the only SpoonBrowser. The closing of other
SpoonBrowser tab caused the closing of Welcome tab, and probably the deficient
disposal of the intended tab.
@graimundo

[MARKET-314] Allow close and disposal of SpoonBrowser tabs other than the Welcome tab

---

engine/src/org/pentaho/di/trans/step/BaseStep.java

Issue with 'Error Handling settings' when the value of 'min nr of rows to read before doing % evaluation' is greater than 100

[PDI-10210] - min nr of rows before % evaluation issue

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java

On Windows, browser tabs are instances of `org.eclipse.swt.ole.win32.OleClientSite`
that manages embedded ActiveX controls.
When disposed (at least in SWT 4.3.2) `OnInPlaceDeactivate` is called and if the
tab has focus forces its move to the next focusable control (the next open tab).
Great when closing a tab!
Unfortunately when quiting the app it seems it can end up on an already disposed tab,
throwing a NullPointerException.
Moving in advance the focus to other non-embedded control prevents it.
@graimundo

[MARKET-315] Prevent NPE when quitting with open SpoonBrowser tabs on Windows

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java

adding a null check, discovered as part of the backup/restore work relating to the metastore

[BACKLOG-4449] -Implement the MetaStore portion of the Import process

---

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinput/SalesforceConnection.java
plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceupsert/SalesforceUpsertDialog.java

What was done:
1)It's moved to org.pentaho.di.trans.steps.salesforceinput.SalesforceConnection
2)The fields with type="id" should not be excluded - we need mapped this fied when Upset Comparison Field=Id.
3)Deleted the code that belongs to PDI-11864. It should be in the separate PR.

PDI-11863: As a Salesforce ETL Developer Make Upsert Mapping exclude non-updatable fields

---

engine/src/org/pentaho/di/trans/steps/samplerows/SampleRows.java

Sample Rows was hanging up the row set buffers by refusing to read in more rows once it completes.
@mattyb149
/cc @bkemper-pentaho  @dkincade

[BACKLOG-5133]Continue to read rows after sampling is done

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTest.java

- do not create new revision when simply moving files
- add test cases
(cherry picked from commit 448b01d)
@mbatchelor, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1779 for 6.0

[BACKLOG-5173] - it is impossible to transfer KTR & JOB to another folder.

---

core/src/org/pentaho/di/core/KettleClientEnvironment.java
core/src/org/pentaho/di/core/logging/LoggingPlugin.java
core/src/org/pentaho/di/core/logging/LoggingPluginType.java
plugins/kettle5-log4j-plugin/ivy.xml
plugins/kettle5-log4j-plugin/res/log4j.xml
plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/CentralLogStore.java
plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/log4j/Log4jLogging.java

@mdamour1976 please have a look
I added log4j into plugin. This way we will avoid 2 issues: 
1. issues with version changes for other components of kettle.
2. easy way to prevent sharing log4j (its class instances and configuration)  with karaf which also uses log4j
There is no deduplication of kettle5-log4j-plugin-{version}.jar. As I mentioned on our today meeting kettle5-log4j-plugin used in big-data-plugin (big-data-plugin uses some class form it). Thus for deduplication we have to find a reason why we have such strange use case and move this class to kettle or big-data-plugin. 
From my perspective it is better to do this operation after code freeze.

[PDI-13206] - The Kettle5-log4j plugin doesn't work because init never gets called on the plugin

---

engine/src/org/pentaho/di/repository/filerep/KettleFileRepository.java

@dkincade 
BACKLOG-5231 - Importing repository to File System repos saved Transformation doesn't open
http://jira.pentaho.com/browse/BACKLOG-5231
Master Commit:
https://github.com/pentaho/pentaho-kettle/pull/1785
DevCI:
http://devci.pentaho.com/job/6.0-snapshot/job/pdi-engine-core/147/

[BACKLOG-5231] Fix for transformation not opening in file system repo

---

core/src/org/pentaho/di/core/jdbc/ThinDriver.java

@dkincade 
master: https://github.com/pentaho/pentaho-kettle/pull/1810
CI: http://devci.pentaho.com/job/6.0-snapshot/job/pdi-engine-core/157/

[BACKLOG-5343]Log deprecation warning when using old ThinDriver

---

engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
engine/test-src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMetaTest.java

Only clear the input row meta if asking about a non-"main" output step.
Also added unit tests

[PDI-14440] Fixed TransExecutor step to declare main output fields

---

plugins/googleanalytics/test-src/org/pentaho/di/trans/steps/googleanalytics/GoogleAnalyticsApiFacadeTest.java

- handle different exceptions thrown on different OSes
@mattyb149, @brosander, merge it please - this is the fix to repair the test broken by https://github.com/pentaho/pentaho-kettle/pull/1837.
I investigated why it happened. Surprisingly, VFS behaves differently on Windows and on Linux, that is why I got no errors when was doing the changes. I checked the test on Ubuntu and could manage to reproduce the problem.

[TEST] - Fix GoogleAnalyticsApiFacadeTest

---

engine/src/org/pentaho/di/repository/RepositoryCommonValidations.java
engine/src/org/pentaho/di/repository/RepositorySecurityUserValidator.java
engine/src/org/pentaho/di/repository/kdr/KettleDatabaseRepositorySecurityProvider.java
engine/src/org/pentaho/di/repository/kdr/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/repository/RepositoryCommonValidationsTest.java
engine/test-src/org/pentaho/di/repository/kdr/KettleDatabaseRepositorySecurityProviderTest.java
plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositorySecurityManager.java
plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/UserRoleDelegate.java
plugins/pdi-pur-plugin/src/org/pentaho/di/ui/repository/pur/services/RepositorySecurityRoleValidator.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositorySecurityManagerTest.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/UserRoleDelegateTest.java

@mattyb149, @brosander, this is my third attempt to publish the changes.
This PR has nothing related to UI changes. It prohibits creating users (for DB and EE) and roles (EE) if:
1. Name is empty
2. Name already exists
As a separate test case it is checked, that ```user``` and ```User``` are handled as different.
/cc @bkemper-pentaho

[PDI-12814] - Need to prohibit empty names when adding new users or roles

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_Revisions_IT.java

- improve PurRepository
- remove code duplication in ```saveTrans0()``` and ```saveJob0()```
- add java docs for ```saveKettleEntity()```
- fix checkstyle violations
- re-organize tests
- delete revision-related tests from ```PurRepositoryIT```
- introduce ```PurRepository_Revisions_I```T and implement revision-related test cases there
@mattyb149, @brosander, review it please. The problem described in the ticket has been already fixed. This PR eliminates code duplication and brushes up tests

[PDI-14343] - Timestamp for jobs in DI repository continuously displays the same value for different versions

---

plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTestBase.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_IT.java

I continue splitting ```PurRepositoryIT``` moving groups of linked tests to separate classes.
The fist commit fixes a lurk flaw -- it properly shutdowns ```PentahoSystem```. Without it, each next attempt to initialise the system causes an thrown exception. It is not reproduced in tests executions, because Ant task forks JVM ```perTest```. However, it fails when I run all tests within IDE as it executes them within one virtual machine.

[TEST] - Continue splitting PurRepositoryTest

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java

- set parsing value to null to prevent the regression from PDI-11194
- add test
(cherry picked from commit 9e3e72d)
@mattyb149, @brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1731

[SP-2060] - Backport of PDI-14172 - Text file input Repeat don't work (5.4 Suite)

---

build.xml

@lgrill-pentaho @brosander Mind taking a look? This won't impact CI as it calls the continuous-sonar target. Instead for manual builds it replaces Cobertura with Jacoco (by switching to the standard "build" target in subfloor).

[BUILD] Change module/plugin build targets to use Jacoco

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_IT.java

- clear "createdDate" on renaming to force the repository to inject current time
- update tests to check this condition

[PDI-14375] - Incorrect time displayed in Version History after some operations with transformation/jobs in the DI repository

---

core/test-src/org/pentaho/di/core/parameters/DuplicateParamExceptionTest.java
core/test-src/org/pentaho/di/core/parameters/NamedParamsExceptionTest.java
core/test-src/org/pentaho/di/core/parameters/UnknownParamExceptionTest.java

These tests fail on Windows because of different line separators

[TEST] - Repair tests for Windows

---

core/src/org/pentaho/di/core/database/DatabaseMeta.java
core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java
engine/src/org/pentaho/di/repository/filerep/KettleFileRepository.java
engine/src/org/pentaho/di/repository/kdr/KettleDatabaseRepository.java
engine/test-src/org/pentaho/di/repository/filerep/KettleFileRepositoryTestBase.java
engine/test-src/org/pentaho/di/repository/filerep/KettleFileRepository_DatabaseNames_Test.java
engine/test-src/org/pentaho/di/repository/kdr/KettleDatabaseRepository_DatabaseNames_Test.java
engine/test-src/org/pentaho/di/repository/kdr/KettleDatabaseRepository_GetObjectInformation_Test.java
ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsController.java
ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsControllerTest.java

- prohibit creating connections with similar names different only in case by handling getDatabaseID() method properly
- keep backward-compatibility by letting existing connections to be proceeded (exact match is done firstly)
- add tests for all affected classes
(backported from commits 3003bde1e3ade56b3f64f49266449f2866b97c04 and 99722de042c165b80b755796175526ee89ab9b0a)

[SP-2081] - Backport of PDI-13353 - When having duplicate DB Connection names (difference in capitals) PDI defaults to the first (5.4 Suite)

---

ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsController.java
ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsControllerTest.java

- handle NULL returned from the dialog
- trim connection's names
- add tests

[PDI-13353] - When having duplicate DB Connection names (difference in capitals) PDI defaults to the first

---

ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsController.java
ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsControllerTest.java

- handle NULL returned from the dialog
- trim connection's names
- add tests
(cherry picked from commit bba8ff7)
@mattyb149, @brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1907

[SP-2208] - Backport of PDI-13353 - When having duplicate DB Connection names (difference in capitals) PDI defaults to the first (6.0 Suite)

---

core/src/org/pentaho/di/core/Const.java
core/src/org/pentaho/di/core/util/EnvUtil.java
core/test-src/org/pentaho/di/core/util/EnvUtilTest.java
engine/src/kettle-variables.xml
engine/test-src/org/pentaho/di/core/util/KettleVariablesListTest.java

@mattcasters, @brosander, @mattyb149 take a look, please.
What was done: 
1) USER_DIR_IS_ROOT is set to false by default. 
2) Is added corresponding flag to pentaho-variables.xml in order to user has possibility to change USER_DIR_IS_ROOT apache.vfs property
JUnit tests are also provided.

[PDI-14522] - When sftp server has default user folder, absolute urls don't work

---

engine/src/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
engine/src/org/pentaho/di/workarounds/BufferedOutputStreamWithCloseDetection.java

- backport 1a548fc and 9c833cf
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1888

[SP-2220] - Backport of PDI-13413 - Zip file job entry: org.apache.commons.vfs.FileSystemException: File closed. (Java 8) (6.0 Suite)

---

core/src/org/pentaho/di/core/Const.java
core/src/org/pentaho/di/core/util/EnvUtil.java
core/test-src/org/pentaho/di/core/util/EnvUtilTest.java
engine/src/kettle-variables.xml
engine/test-src/org/pentaho/di/core/util/KettleVariablesListTest.java

@mattcasters, @brosander, @mattyb149 here is backport of https://github.com/pentaho/pentaho-kettle/pull/1905 to 6.0, thanks.

SP-2185 - Backport of BACKLOG-5088 - When sftp server has default user folder, absolute urls don't work (6.0 Suite)

---

engine/src/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java

Set font formatting with each new file

[PDI-13487] Excel Output field formats are ignored when "Split Every ... Rows" is used

---

ui/src/org/pentaho/di/ui/trans/steps/insertupdate/InsertUpdateDialog.java

Solution
1. Copied the update status of targets to a hashmap (Target as Key,
update status as value) from the wReturn during the existing map
generation
2. At the time of populate the wReturn, get the update status from the
hash map for the target and set the same.
3. If the Target is new and there is no update status, make “Y” as
default.
Why not Copy from Meta/Input?
- If the user change the update status by keying/mouse selection, the
change is not updated to input until the “OK” event, so the wReturn
always has the latest value.

PDI-14364 In spoon, the Insert/update step’s “Edit mapping” leaves Update Y/N selection in Update/Insert Table empty.

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInputMeta.java
engine/src/org/pentaho/di/trans/steps/textfileinput/messages/messages_en_US.properties
ui/src/org/pentaho/di/ui/trans/steps/textfileinput/TextFileInputDialog.java
ui/test-src/org/pentaho/di/ui/trans/steps/textfileinput/TextFileInputDialogTest.java

Implements a Minimal width button on the Fields tab of Text file input. This improvement is meant to save the user time from setting each fields Trim type to "both" when attempting to eliminate padded data.
JIRA Issue: http://jira.pentaho.com/browse/PDI-14253

[PDI-14253] Text file input: adding 'Minimal width' button to Fields tab

---

engine/src/org/pentaho/di/trans/step/BaseStepMeta.java
engine/test-src/org/pentaho/di/trans/step/BaseStepMetaCloningTest.java

- set ioMeta = null for clones to prevent sharing its instance among all clones
- add a test
(cherry picked from commit 9dae9ae)
@brosander, @hudak, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1873

[SP-2248] - Backport of PDI-14419 - Table Input Step - Insert data from step - writes to other table input steps (6.0 Suite)

---

engine/src/org/pentaho/di/trans/step/BaseStepMeta.java
engine/test-src/org/pentaho/di/trans/step/BaseStepMetaCloningTest.java

- set ioMeta = null for clones to prevent sharing its instance among all clones
- add a test
(cherry picked from commit 9dae9ae)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1873

[SP-2249] - Backport of PDI-14419 - Table Input Step - Insert data from step - writes to other table input steps (5.4 Suite)

---

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinsert/SalesforceInsert.java
plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceupdate/SalesforceUpdate.java
plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsert.java
plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceutils/SalesforceUtils.java
plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceutils/messages/messages_en_US.properties
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinsert/SalesforceInsertTest.java
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceupdate/SalesforceUpdateTest.java
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsertTest.java
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceutils/SalesforceUtilsTest.java

The problem was:
when isUseExtId=Y for the field, we add incorrect field name in FieldsToNull.
What was done:
1)Added utility method to get valid names for null fields candidates.
2)Added calls this method in the steps: SalesforceUpsert, SalesforceInput, SalesforceUpdate.
3)Added a couple of unit tests.

[PDI-13271]: External Ids are not handled properly when incoming key is null

---

assembly/ivy.xml

Rename pdi-dataservice-client-plugin-assembly to pdi-dataservice-client-plugin-bundle

[BACKLOG-5020] The dataservice client zip should be easily retrievable from the dataservice edit dialog

---

ui/src/org/pentaho/di/ui/trans/dialog/TransDialog.java

- showing metricsLogTable option instead of channelLogTable value when showMetricsLogTableOptions method is called.
@brosander, @mattcasters review it please

[PDI-13240]  Setting for 'Log record timeout' field under Logging - Metrics cannot be saved

---

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

- manually check if input sample is equal to "nullif" value
- add a test and refactor TextFileInputTest a bit
@deinspanjer, do you mind reviewing it? That is the case we were discussing a month ago.
@brosander, you are also welcomed, but please look at the ticket's last comment (http://jira.pentaho.com/browse/PDI-14358) before

[PDI-14358] - Text File Input Interpreting missing values as empty strings instead of null

---

engine/src/org/pentaho/di/repository/RepositoryExporter.java
engine/src/org/pentaho/di/repository/RepositoryImporter.java
engine/src/org/pentaho/di/repository/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/repository/RepositoryImporterTest.java

@mdamour1976 please review.
p.s.: it is a "cheap & dirty" solution. if it is too dirty - let me know i'll present the other one - we can add a new interface which specifies method to recalculate path for current location. Then this interface should be added to all steps/job entries which need path correction on import/export.

[PDI-14015] - Repository import does not populate the transformation reference correctly on the Metadata Injection step

---

engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java
engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java

@mdamour1976  please review.
It would be better to refactor the mapping algorithm for metadata to fix the issue (actually the bug located in code that sets values into "injectable" steps - however we can add workarownd with some if() {} constructions ), but we already have a brand new MDI mechanism. So it seems unreasonable to spend time on code that will be deprecated .

[PDI-12667] - Metadata Injection Step not accepting more than one input step

---

ui/src/org/pentaho/di/ui/core/PropsUI.java

This message is now showing up in the logs since the KettleXmlPluginLifecycleListener exists without implementing GUIOption (nor do we want it to).

[BACKLOG-6041] Reducing log message from basic to debug

---

engine/src/org/pentaho/di/imp/Import.java

@brosander @e-cuellar @rmansoor 
Please review.
"comment" is not is not a Yes/No flag.
Also i have sent an email to Wes Brown:
Hello Wes,
Could you please find someone to amend this documentation ?
http://infocenter.pentaho.com/help/index.jsp?topic=%2Fpdi_admin_guide%2Freference_import_options.html
http://wiki.pentaho.com/display/EAI/Import+User+Documentation
Because right now only one parameter (“-norules”) is documented(at wiki page) as Yes/No flag, what I see from the source code(https://github.com/pentaho/pentaho-kettle/blob/master/engine/src/org/pentaho/di/imp/Import.java#L183-L184) these parameters were designed to be used in such manner too:
“-replace”, “-coe”
So, for the wiki page this example:
```sh import.sh -rep=PRODUCTION -user=joe -pass=password -dir=/import …
```

PDI-14178 - Command-line Import Incorrectly Reports Exceptions

---

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java

- manually check if input sample is equal to "nullif" value
- add a test and refactor TextFileInputTest a bit
(cherry picked from commit 84cd194)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1997

[SP-2346] - Backport of PDI-14358 - Text File Input Interpreting missing values as empty strings instead of null (6.0 Suite)

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java

- manually check if input sample is equal to "nullif" value
- add a test and refactor TextFileInputTest a bit
- fix Checkstyle violations
(adopted from commit 84cd194c725e9f7d43a9635817b08451980f230e)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1997

[SP-2347] - Backport of PDI-14358 - Text File Input Interpreting missing values as empty strings instead of null (5.4 Suite)

---

engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java
engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java

@mdamour1976 please review.
The fix only copies parameters from parent transformation to child transformation (this decision was done by Bill F - it was marked in comments).

[PDI-7224] - ETL Metadata Injection step: need an option to Set Parameters

---

engine/src/org/pentaho/di/job/entries/dostounix/JobEntryDosToUnix.java
engine/test-src/org/pentaho/di/job/entries/dostounix/JobEntryDosToUnix_ConversionIdempotency_Test.java

- In JobEntryDosToUnix:
- replace unsafe data reading with try-with-resource block
- introduce state machine to properly convert data streams
  - fix Checkstyle violations
- add tests for:
- single separator
- separator with other characters
- huge input (exceeding reading buffer's capacity)

[PDI-14161] - Unix to Dos Conversion is not idempotent

---

engine/src/org/pentaho/di/trans/steps/datagrid/DataGrid.java
engine/src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitter.java
engine/test-src/org/pentaho/di/trans/TransTestingUtil.java
engine/test-src/org/pentaho/di/trans/steps/datagrid/DataGrid_EmptyStringVsNull_Test.java
engine/test-src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitter_EmptyStringVsNull_Test.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
engine/test-src/org/pentaho/di/trans/steps/regexeval/RegexEval_EmptyStringVsNull_Test.java
engine/test-src/org/pentaho/di/trans/steps/script/ScriptTest.java
engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesModTest.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java
engine/test-src/org/pentaho/test/util/FieldAccessor.java
test/org/pentaho/di/trans/steps/datagrid/DataGridTest.java
ui/src/org/pentaho/di/ui/core/dialog/EditRowsDialog.java
ui/test-src/org/pentaho/di/ui/core/dialog/EditRowsDialog_EmptyStringVsNull_Test.java

@brosander, review it please.
I'll give you a context of the case. With PDI-11194, conversion rules were changed, and this caused regressions. Actually, the fix was correct, and it is legacy code, which does not handle all cases properly. Namely, it is not calling `isNull()` to get whether or not the given value is undefined; meanwhile it is possible to force Kettle not to distinguish empty strings and nulls, that's why we get troubles.
There was a discussion (see it on http://jira.pentaho.com/browse/PDI-14358), and the final resolution was: "we need to somehow improve conversion (see http://jira.pentaho.com/browse/PDI-14693), but for now the changes must be as local as possible -- not to cause any other differences in behaviour".
The list of affected classes is given on …

[PDI-13684] - Change in null behavior in 5.x version

---

core/src/org/pentaho/di/core/logging/LoggingRegistry.java
core/test-src/org/pentaho/di/core/logging/LoggingRegistryTest.java

- If loggingSource duplicate found, check that original and found sources have the same parent and return logChanelId of the found source.
@pamval, @brosander, review it please, This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1996

[SP-2388] Backport of PDI-14448 - Kitchen logging changes for Local and DI server execution (6.0 Suite)

---

core/src/org/pentaho/di/core/logging/LoggingRegistry.java
core/test-src/org/pentaho/di/core/logging/LoggingRegistryTest.java

- If loggingSource duplicate found, check that original and found sources have the same parent and return logChanelId of the found source.
@pamval, @brosander, review it please, This is a backport of #1996

[SP-2389] Backport of PDI-14448 - Kitchen logging changes for Local and DI server execution (5.4 Suite)

---

engine/src/org/pentaho/di/job/entries/dostounix/JobEntryDosToUnix.java
engine/test-src/org/pentaho/di/job/entries/dostounix/JobEntryDosToUnix_ConversionIdempotency_Test.java

- In JobEntryDosToUnix:
- replace unsafe data reading with try-with-resource block
- introduce state machine to properly convert data streams
  - fix Checkstyle violations
- add tests for:
- single separator
- separator with other characters
- huge input (exceeding reading buffer's capacity)
(cherry picked from commit 6384e6a)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2038

[SP-2409] - Backport of PDI-14161 - Unix to Dos Conversion is not idempotent (6.0 Suite)

---

core/src/org/pentaho/di/core/util/EnvUtil.java
core/test-src/org/pentaho/di/core/util/EnvUtilTest.java
engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValues_LocaleHandling_Test.java

- do not create locale instances for empty strings
(cherry picked from commit 6a7e129)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2063

[SP-2404] - Backport of PDI-14823 - Using week in year date format with "Select values" step (6.0 Suite)

---

core/src/org/pentaho/di/core/util/EnvUtil.java
core/test-src/org/pentaho/di/core/util/EnvUtilTest.java
engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValues_LocaleHandling_Test.java

- do not create locale instances for empty strings
(adopted from commit 6a7e129)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2063

[SP-2405] - Backport of PDI-14823 - Using week in year date format with "Select values" step (5.4 Suite)

---

plugins/kettle-gpload-plugin/ivy.xml
plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/GPLoad.java
plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/GPLoadMeta.java
plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/messages/messages_en_US.properties
plugins/kettle-gpload-plugin/src/org/pentaho/di/ui/trans/steps/gpload/GPLoadDialog.java
plugins/kettle-gpload-plugin/test-src/org/pentaho/di/trans/steps/gpload/GPLoadMetaTest.java

This allows a known value in an import file to be treated as NULL when data is
imported - this has some bearing on http://jira.pentaho.com/browse/PDI-8457 although that may need more work for a full resolution - this PR just adds support for the NULL_AS option, not the ESCAPE option

[PDI-14861] Add NULL_AS support to kettle-gpload-plugin

---

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java

- in TextFileInput, set input string to null instead of setting result to null
- add test case
- fix Checkstyle violations
(cherry picked from commit 61a5ad9)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2076

[SP-2439] - Backport of PDI-14832 - Default values not working in TextFileInput (6.0 Suite)

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java

- in TextFileInput, set input string to null instead of setting result to null
- add a test case
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2076

[SP-2440] - Backport of PDI-14832 - Default values not working in TextFileInput (5.4 Suite)

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java

Fixed: run dialog was opening with F9 even if checkbox was not checked for "always show dialog"
@mdamour1976

[BACKLOG--5675] Add the Ability to remember run options

---

ui/src/org/pentaho/di/ui/trans/steps/analyticquery/AnalyticQueryDialog.java

Remove the variable icon from the dialog, as the step does not support variable replacement for this field

[PDI-12074] Analytic Query Variable Icon

---

engine/src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoader.java
engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java

- Reset default conversion mask for Number type and make it to be calculated according to field length and precision.
- Unit test.

[PDI-11421] - Moving MySQL data via Bulk Loader with DECIMAL Data Type from one MySQL Table to another has precision errors

---

engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java
test/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByIntTest.java

Avoid throwing an error when no input rows are available

[PDI-12501] MemoryGroupBy with no input rows

---

engine/src/org/pentaho/di/trans/steps/databaselookup/readallcache/ReadAllCache.java
engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/ReadAllCacheTest.java

- check if lookup value really exists
- add a test
@brosander, review it please. This PR fixes another problem in the step.

[BACKLOG-6496] - Database lookup step with "IS NOT NULL" comparator fails on 6.1

---

core/src/org/pentaho/di/core/jdbc/ThinUtil.java
core/test-src/org/pentaho/di/core/jdbc/ThinUtilTest.java
core/test-src/org/pentaho/di/core/sql/SQLFieldsUnitTest.java

and is referenced with tablename
Modified to avoid stripping quotes when whitespace is present.

[BACKLOG-6598]  Data Service SQL fails if field contains a space

---

engine/src/kettle-variables.xml
plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java

org.pentaho.di.repository.Repository.LAZY_REPOSITORY to
KETTLE_LAZY_REPOSITORY in order to be consistent with the remaining
kettle variables names

[BACKLOG-6565] Renamed kettle-variable from

---

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
test/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepIntTest.java

Generate an empty RowMeta, as some settings require an empty file be created before finishing.

[PDI-14854] Excel Writer NPE when no rows

---

core/src/org/pentaho/di/core/jdbc/ThinUtil.java
core/src/org/pentaho/di/core/sql/SQLCondition.java
core/src/org/pentaho/di/core/sql/SQLField.java
core/test-src/org/pentaho/di/core/sql/SQLConditionTest.java
core/test-src/org/pentaho/di/core/sql/SQLFieldTest.java
core/test-src/org/pentaho/di/core/sql/SQLFieldsUnitTest.java
core/test-src/org/pentaho/di/core/sql/SQLTest.java

is referenced with tablename
The former commit for this issue did not address fields inside of
aggregate functions or conditional expressions.

[BACKLOG-6598]  Data Service SQL fails if field contains a space and

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputRowNumberTest.java

- set meta data columns on last, incomplete CSV row
- add a test
(adopted from commits 6e436e0, 268c314)
@brosander, @hudak, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2185

[SP-2495] - Backport of PDI-4837 - CSV File Input - fails to populate rownum, filenameField, input row count (6.0 Suite)

---

core/src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta.java
core/test-src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta_FieldDefinitionTest.java

- In case of non zero precision and zero length choosing float as a type for a column.
- Tests wirtten.
- Checkstyle applied.
@brosander, could you please review it?

[BISERVER-12601] MS SQL repository: csv data source can't be created if any of column has non zero precision

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputRowNumberTest.java

- set meta data columns on last, incomplete CSV row
- add a test
(adopted from commits 6e436e0, 268c314)
@brosander, @hudak, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2185

[SP-2496] - Backport of PDI-4837 - CSV File Input - fails to populate rownum, filenameField, input row count (5.4 Suite)

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/LazyUnifiedRepositoryDirectory.java
ui/src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIRepositoryDirectory.java

UIRepositoryDirectory to first try to delete the directory from the
system and then from UI. Minor fix to LazyUnifiedRepositoryDirectory to
prevent IndexOutOfBoundsException on getSubdirectory( int i ) calls.

[BACKLOG-6700] Changed order of directory removal at

---

core/src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta.java
core/test-src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta_FieldDefinitionTest.java

- In case of non zero precision and zero length choosing float as a type for a column.
- Tests wirtten.
- Checkstyle applied.
@akhayrutdinov, review it please. It is a backport of #2207
@tgf, @pamval, could you please start WM?

[SP-2517] Backport of BISERVER-12601 - MS SQL repository: csv data source can't be created if any of column has non zero precision (5.4 Suite)

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/LazyUnifiedRepositoryDirectory.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java

LazyUnifiedRepositoryDirectory when creating a new
LazyUnifiedRepositoryDirectory, now it will have the right parent
directory as argument

[BACKLOG-6777] Fixed getDirectory( String path ) method of

---

core/src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta.java
core/test-src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta_FieldDefinitionTest.java

- In case of non zero precision and zero length choosing float as a type for a column.
- Tests wirtten.
- Checkstyle applied.
@akhayrutdinov, review it please. It is a backport of https://github.com/pentaho/pentaho-kettle/pull/2207

[SP-2516] Backport of BISERVER-12601 - MS SQL repository: csv data source can't be created if any of column has non zero precision (6.0 Suite)

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java

on renameRepositoryDirectory method so the KettleException message can
be properly written.

[BACKLOG-6777] Minor fix that sets the home folder verification to later

---

core/src/org/pentaho/di/core/jdbc/ThinUtil.java
core/test-src/org/pentaho/di/core/jdbc/ThinUtilTest.java

The OTHER type is mapped to TYPE_NONE and treated effectively as an
unknown type.
This has a corresponding change in the data service client to handle
setObject with a null value (in which case type is unknown).  Using
sql type OTHER in such cases for consistency with several other db
drivers (mysql, oracle, postgres, etc.)
http://jira.pentaho.com/browse/PRD-5662
@hudak

[PRD-5662]  Adding support for java.sql.Types.OTHER to ThinUtil

---

plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java

SimpleDateFormat class did't support ISO-8601 fully in java-6, but in java 7 new date-patterns were added, and ISO-8601 support became possible.
The purpouse of [this PR](https://github.com/pentaho/pentaho-kettle/commit/0125c88f7f614073986ea8076740117a80cef3ce#diff-21e5912b7c8385e7a9d0f2adef44829eR697) was to provide the ISO-8601 support, and the code for helping SimpleDateFormat (in java 6) to provide ISO-8601 support was to removed.
Since it is removed, we need to change the pattern to java-7 style.
[Here is the test ](https://github.com/pentaho/pentaho-kettle/blob/master/core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java#L497) for parsing this date pattern with SimpleDateFormat.
@akhayrutdinov, @brosander, review it please.

[PDI-14606] Salesforce Input default field format (yyyy-MM-dd'T'HH:mm:ss'.000'Z) fails for Date/Time fields

---

engine/src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRows.java
engine/test-src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRowsTest.java

- manually handle `null` value of `delimiter` property
@pamval, @pedrofvteixeira, start WM for this PR please

[PDI-14999] - ‘Split Field to Rows’ step fails with NullPointerException after import into repository

---

engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInputMetaCloningTest.java

- in clone(), fix the mistake of assigning original values to themselves instead of setting cloned values
- add a test
(cherry picked from commit 0cbb1c6)
@pamval, @pedrofvteixeira, please start WM for this PR

[SP-2532] - Backport of PDI-14972 - Input Mapping Specification step not saving length and precision on export to xml (6.1 Suite)

---

engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java
engine/test-src/org/pentaho/di/job/entries/sftp/SFTPClientTest.java

- reordered default preferred authentications list
The whole fix is reordering of preferred authentications list on the client.
Default order is: `gssapi-with-mic,publickey,keyboard-interactive,password`
Moving GSSAPI to the end: `publickey,keyboard-interactive,password,gssapi-with-mic`
This will make the JSch trying GSSAPI authentication only if other previous have failed.
To reproduce the issue and test the fix a Kerberos authentication server was set up. 
The issue is reproduced when 2 conditions are met:
- GSSAPI Authentication is enabled on the SSH server we want to connect to in SFTP Put step
- Client doesn't have TGT Ticket for that SSH server.
Command line is asking for password and waiting without timeout, no matter how authentication is configured in job entry. …

[PDI-14988] - Add option to disable interactive GSSAPI authentication

---

engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInputMetaCloningTest.java

- in clone(), fix the mistake of assigning original values to themselves instead of setting cloned values
- add a test
(cherry picked from commit 0cbb1c6)
@pamval, @pedrofvteixeira, start WM for this PR please

[SP-2533] - Backport of PDI-14972 - Input Mapping Specification step not saving length and precision on export to xml (5.4 Suite)

---

engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValues.java
engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java

Revert recent public API changes caused metaverse build failures. In case the change was intended use http://wiki.pentaho.com/display/PEOpen/Deprecation+Guidelines guide for public api deprecation.
Please run wingman for this.
@bmorrise @AndreyBurikhin

[PDI-15032] Revert public api change

---

core/src/org/pentaho/di/core/database/DatabaseMeta.java
core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java

The reason why this bug occures is [this line] (https://github.com/pentaho/pentaho-kettle/blob/master/core/src/org/pentaho/di/core/database/DatabaseMeta.java#L2717).
We set extra option, specifying MSSQL (that is a hardcoded string) as databaseTypeCode in all cases, though it can be of type MSSQLNATIVE also. 
My first approach was to treat this plugins as seperate databaseTypeCode, but it's not such an easy task as it seemed to be. In short: I could not do it, because when edditing/creating a database we can't pull an up-to-date databasePluginId *before* clicking on "OK" button. I can provide a more detailed description for the problems of this approach, if necessary.
My second approach is described bellow in a short form and more explisit in java docs.
When generating connection URL, …

[PDI-14950] Spoon does not pass instanceName parameter to MSSQL Server JDBC connection string

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaStringTest.java

- due to `JLS 17.5.3` (http://docs.oracle.com/javase/specs/jls/se8/html/jls-17.html#jls-17.5.3) JVM does not expect final fields to be changed; looks like Java 8 applies some optimisations that utilise that assumption
- change `ValueMetaBase` to be able to get `empty vs null` parameter dynamically and re-implement `ValueMetaStringTest` so, that it becomes stable
@brosander, @deinspanjer, review it please.
While dealing with https://github.com/pentaho/pentaho-kettle/pull/2342, I noticed two failed tests. However, I could manage to reproduce those fails only with Java 8 and that was not stable (~ 1 time from 5 executions). I have only one explanation -- the test is incorrect, because it changes `static final` field with reflection. JVM is allowed to cache `final` values if it needs it for …

[TEST] - Repair incorrect test

---

plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java

- Changing date time format to java 7 style (it would be parsed with SimpleDateFormat class, that supports ISO - 8601 from java 7)
@akhayrutdinov , could you please review it? It's a backport of  https://github.com/pentaho/pentaho-kettle/pull/2272
@pamval , @pedrofvteixeira , could you please run WM?

[SP-2592] Backport of PDI-14606 - Salesforce Input default field format (yyyy-MM-dd'T'HH:mm:ss'.000'Z) fails for Date/Time fields (6.1 Suite)

---

engine/src/org/pentaho/di/repository/RepositoryOperation.java
plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/AbsSecurityProvider.java
plugins/pdi-pur-plugin/src/org/pentaho/di/ui/repository/pur/services/IAbsSecurityProvider.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/AbsSecurityProviderTest.java

- Since we have a separate "Schedule content" permission in permission list, we separately check permissions for this operation.
- Test written
More details:
**AbsSecurityProvider**
- Added check for scheduling action
- Refactored code a little
**IAbsSecurityProvider**
- Added constant for scheduling action
- Removed unnecessary public static final on fields, as this is done by default since this are variables of an interface.
**RepositoryOperation**
- Added enums for job and trans scheduling
@akhayrutdinov, review it please, it is a backport of https://github.com/pentaho/pentaho-kettle/pull/2326
@pamval, @pedrofvteixeira , run WM for this PR please

[SP-2593] Backport of PDI-15018 - DI Server security not behaving properly. (6.1 Suite)

---

engine/src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRows.java
engine/test-src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRowsTest.java

- manually handle `null` value of `delimiter` property
(cherry-picked from 47560270a85b39b4767f4db9d19998c182063e6b)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2282

[SP-2588] - Backport of PDI-14999 - 'Split Field to Rows' step fails with NullPointerException after import into repository (6.1 Suite)

---

engine/src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRows.java
engine/test-src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRowsTest.java

- manually handle `null` value of `delimiter` property
(cherry-picked from 47560270a85b39b4767f4db9d19998c182063e6b)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2282

[SP-2589] - Backport of PDI-14999 - 'Split Field to Rows' step fails with NullPointerException after import into repository (5.4 Suite)

---

engine/src/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
engine/test-src/org/pentaho/di/job/entries/zipfile/JobEntryZipFileTest.java

- fail on non-existing path
- in JobEntryZipFile, remove useless assignments (highlighted by Intelij) and useless stream closing
- add tests
(adopted from ef893f58535aa489e7c959f1c23ec06ae7f3c811)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2338

[SP-2597] - Backport of PDI-15013 - Create zip files runs successfully with wrong Source path (5.4 Suite)

---

engine/src/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java
engine/test-src/org/pentaho/di/job/entries/zipfile/JobEntryZipFileIT.java

- fail on non-existing path
- in JobEntryZipFile, remove useless assignments (highlighted by Intelij)
- add tests
(cherry-picked from ef893f58535aa489e7c959f1c23ec06ae7f3c811)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2338

[SP-2596] - Backport of PDI-15013 - Create zip files runs successfully with wrong Source path (6.1 Suite)

---

engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java
engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaTest.java

@mkambol please review.
I decided to stay with -2 "magic number" and just added constant for it. Of course I could replace int[] with array of objects (integers), but I think it better to stay it "as is". It worked this way before my changes, so it would work the same after them.
(I executed tests for pdi-dataservice-server-plugin and all tests from SqlTransGeneratorTest passed successfully. Let me know if other tests were broken and i didn't fix it them)

 [PDI-15032] - Metadata Injection on all tabs of select values step is causing error - fix getters

---

engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java

@pamval please find someone to merge this PR as it fixes compilation error.
@lgrill-pentaho

[BACKLOG-7186] - Metadata Injection for Metadata Injection step - rename method to prevent error: 'reference to call ambiguous'

---

plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/addxml/AddXMLMetaInjectionTest.java

@pamval, @bmorrise  please review. I removed getTypeCodes method from AddXMLMetaInjectionTest so now it uses the same method from BaseMetadataInjectionTest class.

[BACKLOG-7186] - Metadata Injection for Metadata Injection step - fix test

---

core/src/org/pentaho/di/core/database/DatabaseMeta.java
core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java
core/test-src/org/pentaho/di/core/database/DatabaseMeta_AppendExtraParamsTest.java

-  Validating extra parameter value before appending it's key to url.
- Checking whether the underlying database for two DatabaseInterface's is the same depending on the class hierarchy (if check by pluginId fails).
@brosander , could you review it please?
It is a **backport** for this PR's: https://github.com/pentaho/pentaho-kettle/pull/2311, https://github.com/pentaho/pentaho-kettle/pull/2342,  https://github.com/pentaho/pentaho-kettle/pull/2355

[SP-2639] Backport of PDI-14950 - Spoon does not pass instanceName parameter to MSSQL Server JDBC connection string (6.1 Suite)

---

dbdialog/src/org/pentaho/ui/database/databasedialog.properties
dbdialog/src/org/pentaho/ui/database/event/DataHandler.java
dbdialog/src/org/pentaho/ui/database/kettlethin_native.xul
dbdialog/test-src/org/pentaho/ui/database/event/DataHandlerTest.java

- Add field for webappName
- Store webappName as a separate parameter
- Provide default value for webappName
Data services part is in https://github.com/pentaho/pdi-dataservice-plugin/pull/65
@hudak

[BACKLOG-5453] Add the field "webapp name" for Pentaho Data Service database type (SWT Dialog)

---

core/src/org/pentaho/di/core/database/DatabaseMeta.java
core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java
core/test-src/org/pentaho/di/core/database/DatabaseMeta_AppendExtraParamsTest.java

-  Validating extra parameter value before appending it's key to url.
- Checking whether the underlying database for two DatabaseInterface's is the same depending on the class hierarchy (if check by pluginId fails).
@brosander , could you review it please?
It is a **backport** for this PR's: https://github.com/pentaho/pentaho-kettle/pull/2311, https://github.com/pentaho/pentaho-kettle/pull/2342,  https://github.com/pentaho/pentaho-kettle/pull/2355

[SP-2638] Backport of PDI-14950 - Spoon does not pass instanceName parameter to MSSQL Server JDBC connection string (5.4 Suite)	

---

engine/test-src/org/pentaho/di/core/logging/MetricsPainterTest.java

@brosander, here is reworked test. The reason of failing was not here https://github.com/pentaho/pentaho-kettle/pull/2416. It's environment specific I guess. Thanks

[TEST] - reworked MetricsPainterTest .testDrawTimeScaleLineInfinityLoop

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java

- Making a decision whether not to skip a line after checking whether we are actually starting with a new line, that wasn't read by the previous step (see javadocs or description bellow for more details)
- Tests for parallel work of CSVInputStep written.
More detailed:
We need to skip row only if a line, that we are currently on is read by the previous step partly.
In other words, we DON'T skip a line if we are just beginning to read it from the first symbol.
We have to do some work for this: read last byte from the previous step and make sure that it is a new line byte.
But it's not enough. There could be a situation, where new line is indicated by '\r\n' construction. And if we are
between this construction, we want to skip last '\n', and don't want to include it in …

[PDI-15162] "Running in parallel", CSV input step misses some records.

---

engine/src/org/pentaho/di/cluster/SlaveServer.java
engine/src/org/pentaho/di/www/GetPropertiesServlet.java
engine/test-src/org/pentaho/di/cluster/SlaveServerTest.java
engine/test-src/org/pentaho/di/www/GetPropertiesServletTest.java

PDI Carte API allows reading the Kettle.properties entrie
http://jira.pentaho.com/browse/PDI-14973
Added encrypting for sending  properties Kettle.properties via GetPropertiesServlet.
@brosander @mchen-len-son Could you please review?

PDI Carte API allows reading the Kettle.properties entries

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java

- Making a decision whether not to skip a line after checking whether we are actually starting with a new line, that wasn't read by the previous step (see javadocs or description bellow for more details)
- Tests for parallel work of CSVInputStep written.
More detailed:
We need to skip row only if a line, that we are currently on is read by the previous step partly.
In other words, we DON'T skip a line if we are just beginning to read it from the first symbol.
We have to do some work for this: read last byte from the previous step and make sure that it is a new line byte. But it's not enough. There could be a situation, where new line is indicated by '\r\n' construction. And if we arebetween this construction, we want to skip last '\n', and don't want to include it in …

[SP-2654] Backport of PDI-15162 - "Running in parallel", CSV input step misses some records. (5.4 Suite)

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java

- Making a decision whether not to skip a line after checking whether we are actually starting with a new line, that wasn't read by the previous step (see javadocs or description bellow for more details)
- Tests for parallel work of CSVInputStep written.
More detailed:
We need to skip row only if a line, that we are currently on is read by the previous step partly.
In other words, we DON'T skip a line if we are just beginning to read it from the first symbol.
We have to do some work for this: read last byte from the previous step and make sure that it is a new line byte. But it's not enough. There could be a situation, where new line is indicated by '\r\n' construction. And if we arebetween this construction, we want to skip last '\n', and don't want to include it in …

[SP-2655] Backport of PDI-15162 - "Running in parallel", CSV input step misses some records. (6.1 Suite)

---

plugins/pdi-pur-plugin/ivy.xml

IT tests are broken because of: https://github.com/pentaho/pentaho-platform/commit/006922cd99b7d78602eeac48234df0662b243539#diff-1104b650dc14a9bec1183f54df14745aR39
PUR-plugin uses MagicAceDefinition class (that uses classes from newly added *org.yaml* package) somewhere between creating jcrSessionFactory bean, and as there is no depencency for *org.yaml* for pur, and as a dependeny to pentaho-repository is not transitive we get NoClassDefFoundError.
Thats the cause off falling IT tests.

[TEST] Fixing IT tests

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositoryConnector.java
ui/src/org/pentaho/di/ui/spoon/SpoonPerspectiveManager.java
ui/test-src/org/pentaho/di/ui/spoon/SpoonPerspectiveManagerTest.java

- When logging to repository check whether user is allowed to schedule content and remove "Schedule perspective" it he has no permissions for this.
- provided an ability to manipulate perspective's UI list from SpoonPerspectiveManager.
If I understand the idea of PerspectiveInitializer class, it's goal was to make lazy initialization for all perspectived, except the first one, that would be inited immediately. Other perspectives would be initialized when needed and removed from initializerMap.
So, PerspectiveInitializer encapsulates the list of perspectives, and is the only place where perspective list can be accessible and changed.
I added few more methods there: for adding and removing perspective names (unfortunately there is no oppotunity to 'hide' …

[PDI-15118] User with no schedule permissions has access to schedule perspective

---

core/src/org/pentaho/di/core/Condition.java
core/test-src/org/pentaho/di/core/ConditionTest.java

Added an additional processing to the unknown of expression, which сondition is always FALSE

[BACKLOG-7168] - Data Services fails if SQL contains "=NULL"

---

engine/src/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFiles.java
engine/src/org/pentaho/di/job/entries/deletefiles/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/job/entries/deletefiles/JobEntryDeleteFilesTest.java
ui/src/org/pentaho/di/ui/job/entries/deletefiles/JobEntryDeleteFilesDialog.java

**General description**
- Populate data before processing files.
- Checking whether the file path is blank before processing the file. Relative paths are permitted, and providing an empty path means deleting all files inside a root pdi-folder.
It is much more likely to be a mistake than a desirable action, so we don't delete anything. We also don't consider this to be an error (see Jens comment about it, and just log about it if log is detailed).
- Adding some new messages.
- Refactoring (encapsulating  JobEntryDeleteFiles data,  editing some field names, simplifying some checks)
**More details about implementation**
For job execution path to files and file masks should be provided.  These values can be obtained in two ways:
1. As an argument of a …

[PDI-15181] Delete Files job entry will delete all files under the install directory when file location parameter is blank

---

core/src/org/pentaho/di/core/xml/XMLHandler.java

Moved note about replacing ESAPI to a TODO, instead of marking the method signature as deprecated.
Original commit: 837c7cde60505ff0dda0e9e2d8675763d5763153

[CLEANUP] Remove Deprecation Tag

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositoryConnector.java
ui/src/org/pentaho/di/ui/spoon/SpoonPerspectiveManager.java
ui/test-src/org/pentaho/di/ui/spoon/SpoonPerspectiveManagerTest.java

- When logging to repository check whether user is allowed to schedule content and remove "Schedule perspective" it he has no permissions for this.
- provided an ability to manipulate perspective's UI list from SpoonPerspectiveManager.
If I understand the idea of PerspectiveInitializer class, it's goal was to make lazy initialization for all perspectived, except the first one, that would be inited immediately. Other perspectives would be initialized when needed and removed from initializerMap.
So, PerspectiveInitializer encapsulates the list of perspectives, and is the only place where perspective list can be accessible and changed.
I added few more methods there: for adding and removing perspective names (unfortunately there is no oppotunity to 'hide' …

[SP-2676] Backport of PDI-15118 - User with no schedule permissions has access to schedule perspective (6.1 Suite)

---

engine/src/org/pentaho/di/cluster/SlaveServer.java
engine/src/org/pentaho/di/www/GetPropertiesServlet.java
engine/test-src/org/pentaho/di/cluster/SlaveServerTest.java
engine/test-src/org/pentaho/di/www/GetPropertiesServletTest.java

[SP-2665][PDI-14973] PDI Carte API allows reading the Kettle.properties entries
http://jira.pentaho.com/browse/PDI-14973
Added encrypting for sending  properties Kettle.properties via GetPropertiesServlet.
@brosander Could you please merge it?

[SP-2665][PDI-14973] PDI Carte API allows reading the Kettle.properties entries

---

engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java
engine/src/org/pentaho/di/trans/steps/groupby/GroupByData.java
engine/src/org/pentaho/di/trans/steps/groupby/GroupByMeta.java
engine/src/org/pentaho/di/trans/steps/groupby/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByTest.java

- Closing streams before deleting file
- Refactoring
More details:
**GroupBy**
- Closing streams before deleting files.
- Logging an error if stream can't be closed
- Logging detailed message if temp file wasn't deleted. I've chosen this log level because in most cases temp file wouldn't be deleted because streams to this file are not closed (and we do log about close-stream error)
- Refactoring
**GroupByData**
- Changed name of streams, pointing that they are related to temp file only.
**GroupByMeta**
- Refactoring some field names
**GroupByTest**
- Updating to JUnit 4.0
- Added positive test for temp file deletion
- No negative test added, as in this case it would be equivalent to testing logger.
**messages**
- Added message, notifying that temp file wasn't deleting
- …

[PDI-15246] Group By with include all rows option does not clean up temp files

---

engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java
engine/src/org/pentaho/di/trans/steps/groupby/GroupByData.java
engine/src/org/pentaho/di/trans/steps/groupby/GroupByMeta.java
engine/src/org/pentaho/di/trans/steps/groupby/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByTest.java

- Closing streams before deleting file
- Refactoring
More details:
**GroupBy**
- Closing streams before deleting files.
- Logging an error if stream can't be closed
- Logging detailed message if temp file wasn't deleted. I've chosen this log level because in most cases temp file wouldn't be deleted because streams to this file are not closed (and we do log about close-stream error)
- Refactoring
**GroupByData**
- Changed name of streams, pointing that they are related to temp file only.
**GroupByMeta**
- Refactoring some field names
**GroupByTest**
- Updating to JUnit 4.0
- Added positive test for temp file deletion
- No negative test added, as in this case it would be equivalent to testing logger.
**messages**
- Added message, notifying that temp file wasn't deleting
- …

[SP-2678] Backport of PDI-15246 - Group By with include all rows option does not clean up temp files (5.4 Suite)

---

engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java
engine/src/org/pentaho/di/trans/steps/groupby/GroupByData.java
engine/src/org/pentaho/di/trans/steps/groupby/GroupByMeta.java
engine/src/org/pentaho/di/trans/steps/groupby/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByTest.java

- Closing streams before deleting file
- Refactoring
More details:
**GroupBy**
- Closing streams before deleting files.
- Logging an error if stream can't be closed
- Logging detailed message if temp file wasn't deleted. I've chosen this log level because in most cases temp file wouldn't be deleted because streams to this file are not closed (and we do log about close-stream error)
- Refactoring
**GroupByData**
- Changed name of streams, pointing that they are related to temp file only.
**GroupByMeta**
- Refactoring some field names
**GroupByTest**
- Updating to JUnit 4.0
- Added positive test for temp file deletion
- No negative test added, as in this case it would be equivalent to testing logger.
**messages**
- Added message, notifying that temp file wasn't deleting
- …

[SP-2677] Backport of PDI-15246 - Group By with include all rows option does not clean up temp files (6.1 Suite)

---

engine/test-src/org/pentaho/di/job/entry/loadSave/JobEntryLoadSaveTestSupport.java
engine/test-src/org/pentaho/di/job/entry/loadSave/LoadSaveBase.java
engine/test-src/org/pentaho/di/job/entry/loadSave/LoadSaveTester.java
engine/test-src/org/pentaho/di/trans/steps/loadsave/LoadSaveTester.java
engine/test-src/org/pentaho/di/trans/steps/loadsave/initializer/InitializerInterface.java
engine/test-src/org/pentaho/di/trans/steps/loadsave/initializer/JobEntryInitializer.java
engine/test-src/org/pentaho/di/trans/steps/loadsave/initializer/StepMetaInitializer.java
engine/test-src/org/pentaho/di/trans/steps/rest/RestIT.java
engine/test-src/org/pentaho/di/trans/steps/rest/RestMetaTest.java

Some steps require calling allocate() before calling some setter methods.
Pass the object back to a user-defined Initializer class, in order for the allocate() or other methods to be called as needed.

[TEST] Allow meta changes during LoadSaveTester

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/org/pentaho/di/core/row/value/ValueMetaInternetAddress.java
core/src/org/pentaho/di/core/row/value/ValueMetaTimestamp.java
core/test-src/org/pentaho/di/compatibility/ValueTest.java

Confirm that Value.Value_Type_X constants are the same as ValueMetaInterface.TYPE_X constants.
Update ValueMetaBase and related classes to use the correct constants

[CLEANUP] Cleanup Value references

---

engine/src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesAddedFunctions.java
engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValueAddFunctions_GetVariableScopeTest.java
engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValueAddFunctions_SetVariableScopeTest.java

- Refactoring (changing variable names, representing variable scopes as enums, separating logic of setting variable on different scope-levels in different methods)
- Starting to climb variable-space hierarchy from the step's transformation (not from the step itself, as the first call to step's parent will lead to the transformation itself, which is not the expected behavior)
It's a backport of https://github.com/pentaho/pentaho-kettle/pull/2524

[SP-2694] Backport of PDI-14852 - setVariable in Javascript Step with scope of parent job does not work (6.1 Suite)

---

engine/src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesAddedFunctions.java
engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValueAddFunctions_GetVariableScopeTest.java
engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValueAddFunctions_SetVariableScopeTest.java

- Refactoring (changing variable names, representing variable scopes as enums, separating logic of setting variable on different scope-levels in different methods)
- Starting to climb variable-space hierarchy from the step's transformation (not from the step itself, as the first call to step's parent will lead to the transformation itself, which is not the expected behavior)
@mchen-len-son, @pamval  could you please take a look at this PR? It's a backport of https://github.com/pentaho/pentaho-kettle/pull/2524

[SP-2695] Backport of PDI-14852 - setVariable in Javascript Step with scope of parent job does not work (5.4 Suite)

---

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java

Check if the variable-substituted filter is not empty before trying to set a filter

[PDI-15152] GA Filter allows empty variable values

---

engine/src/org/pentaho/di/www/GetJobStatusServlet.java
engine/src/org/pentaho/di/www/GetStatusServlet.java
engine/src/org/pentaho/di/www/GetTransStatusServlet.java
engine/src/org/pentaho/di/www/SlaveServerJobStatus.java
engine/src/org/pentaho/di/www/SlaveServerTransStatus.java
engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/DateLoadSaveValidator.java
engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/DefaultFieldLoadSaveValidatorFactory.java
engine/test-src/org/pentaho/di/www/SlaveServerJobStatusLoadSaveTester.java
engine/test-src/org/pentaho/di/www/SlaveServerJobStatusTest.java
engine/test-src/org/pentaho/di/www/SlaveServerTransStatusLoadSaveTester.java
engine/test-src/org/pentaho/di/www/SlaveServerTransStatusTest.java
ui/src/org/pentaho/di/ui/spoon/SpoonSlave.java
ui/src/org/pentaho/di/ui/spoon/messages/messages_en_US.properties

PDI-6202 adds the log date to XML responses of the Carte API, to match existing data available via HTML
PDI-9262 takes the functionality added in the PDI-6202 commit, and allows the log date to be displayed as part of Spoon's Slave Server Monitor UI.

[PDI-6202] and [PDI-9262] - Get Job/Trans Log Dates via Status Messages

---

engine/src/org/pentaho/di/trans/steps/joinrows/JoinRows.java
engine/test-src/org/pentaho/di/trans/steps/joinrows/JoinRowsTest.java

This resulted in an NPE during the dispose, leaving
files open and the step still running.
Indexing of temp files with this step begins with 1,
index 0 is used for RowMeta not stored to file.
(see .getRowData)

[BACKLOG-8520]  File index was off by one in prev commit.

---

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java

Check if the variable-substituted filter is not empty before trying to set a filter.
Backport of https://github.com/pentaho/pentaho-kettle/pull/2390

[SP-2721] Backport of PDI-15152 - Google Analytics Input Step does not accept empty filter as a variable (6.1 Suite)

---

core/src/org/pentaho/di/core/Const.java
engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java
engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMeta.java
engine/src/org/pentaho/di/trans/steps/memgroupby/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByAggregationTest.java
engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMetaTest.java

- SUM and Average should return the same type as they are aggregating, instead of always Numeric (w/ decimal) values.
It's a backport of https://github.com/pentaho/pentaho-kettle/pull/2248

[SP-2716] Backport of PDI-5537 - "Memory Group By" changes data types of the summation fields (6.1 Suite)

---

engine/src/org/pentaho/di/trans/Trans.java
engine/test-src/org/pentaho/di/trans/TransTest.java

- When starting threads, check if transformation has any step to run, and finish it, if it has no steps.
- Test written

[PDI-14948] Transformation with Metadata Injection runs endlessly if no input is received by Injection Step

---

core/src/org/pentaho/di/core/Const.java
engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java
engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMeta.java
engine/src/org/pentaho/di/trans/steps/memgroupby/messages/messages_en_US.properties
engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByAggregationTest.java
engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMetaTest.java

SUM and Average should return the same type as they are aggregating, instead of always Numeric (w/ decimal) values.

[SP-2717] Backport of PDI-5537 - "Memory Group By" changes data types  of the summation fields (5.4 Suite)

---

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMetaTest.java

- Adding null-checks before obtaining File Object from filename, that can be null.
**Summary**
After this fix behavior is the following:
- When exporting trans with empty filenames, they are kept empty and not converted to related path
**More details**
Situation is the following here:
In transformation's xml fileNames with empty strings are stored as <fileName/> and extracted as nulls when transformation is loaded.
First I wanted to store and load them as empty strings. But it was a bad idea - it leads us to some problems that are hard to overcome with such storing. Here the pitfall of this approach: when exporting trans with empty (non-null) strings in file name - they are converted into related path (root of kettle in this case). And in 99 % cases it's not what user expects.
So what we …

[PDI-15120] Export Linked Resources to XML fails if Text File Input contains empty row

---

engine/src/org/pentaho/di/trans/Trans.java
engine/test-src/org/pentaho/di/trans/TransTest.java

- When starting threads, check if transformation has any step to run, and finish it, if it has no steps.
- Test written
Backport of https://github.com/pentaho/pentaho-kettle/pull/2660

[SP-2754] Backport of PDI-14948 - Transformation with Metadata Injection runs endlessly if no input is received by Injection Step (6.1 Suite)

---

engine/test-src/org/pentaho/di/concurrency/JobTrackerConcurrencyTest.java
engine/test-src/org/pentaho/di/concurrency/PluginRegistryConcurrencyTest.java

Ignoring some old concurrent tests as they are running with different results on different JDK build versions.
Before doing this made sure that test itself is correct and it is an issue with JDK (not in test).
Test:
- runs fine on OpenJDK
- runs fine but very long on Oracle JDK 8 92 build
- runs with OutOfMemoryError on Oracle JDK 8 77 build
@mchen-len-son , could you please review this PR?

[TEST] Ignoring some old concurrent tests as they are running with different results on different JDK build versions.

---

engine/ivy.xml

Replace antrl-3.4-complete with antlr-complete-3.5.2.
To build pentaho-kettle  it previously needs to build:
- pentaho-reporting (pentaho-reporting-engine-classic-core) as it was changed to use antlr-complete-3.5.2 (pentaho/pentaho-reporting#792);

[BACKLOG-8389] - Upgrade antlr to version 3.5.2 across Pentaho product suite - changes for Kettle Engine repository

---

build.properties

Newer version ignores static imports of `org.junit.Assert.*`

[CLEANUP] Update Checkstyle Version

---

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMetaTest.java

- Adding null-checks before obtaining File Object from filename, that can be null.
**Summary**
After this fix behavior is the following:
- When exporting trans with empty filenames, they are kept empty and not converted to related path
**More details**
Situation is the following here:
In transformation's xml fileNames with empty strings are stored as <fileName/> and extracted as nulls when transformation is loaded.
First I wanted to store and load them as empty strings. But it was a bad idea - it leads us to some problems that are hard to overcome with such storing. Here the pitfall of this approach: when exporting trans with empty (non-null) strings in file name - they are converted into related path (root of kettle in this case). And in 99 % cases it's not what user expects.
So what we …

[SP-2786] Backport of PDI-15120 - Export Linked Resources to XML fails if Text File Input contains empty row (6.1 Suite)

---

engine/src/org/pentaho/di/trans/Trans.java
engine/src/org/pentaho/di/trans/steps/mapping/Mapping.java
engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java
engine/src/org/pentaho/di/trans/steps/simplemapping/SimpleMapping.java
engine/src/org/pentaho/di/trans/steps/singlethreader/SingleThreader.java
engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java
engine/test-src/org/pentaho/di/concurrency/ActiveSubTransformationsConcurrencyTest.java
engine/test-src/org/pentaho/di/concurrency/ConcurrencyTestRunner.java
engine/test-src/org/pentaho/di/concurrency/ExecutionResult.java
engine/test-src/org/pentaho/di/concurrency/JobMapConcurrencyTest.java
engine/test-src/org/pentaho/di/concurrency/JobTrackerConcurrencyTest.java
engine/test-src/org/pentaho/di/concurrency/PluginRegistryConcurrencyTest.java
engine/test-src/org/pentaho/di/concurrency/RowMetaConcurrencyTest.java
engine/test-src/org/pentaho/di/concurrency/StopOnErrorCallable.java
engine/test-src/org/pentaho/di/trans/steps/simplemapping/SimpleMappingTest.java
ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java

- Changing HM to CHM for synchronization
- Separating add/remove/get methods, encapsulating map-implementation
- Test written
- Concurrent tests from kettle's core project are moved to engine, as they are not running on CI

[SP-2795] Backport of PDI-8927 - Trans.activeSubtransformations not threadsafe (5.4 Suite)

---

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
engine/test-src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep_StyleFormatTest.java

- clone existing cell style when applying data format
- created a unit test for applying Format and Style from cell (from a template) when writing fields in Excel Writer step
Backport of https://github.com/pentaho/pentaho-kettle/pull/2680

[SP-2784] Backport of PDI-15386 - PDI 5.4/6.1.0 - Excel Writer step does not retain the cell style when data format is also applied (6.1 Suite)

---

engine/src/org/pentaho/di/trans/Trans.java
engine/test-src/org/pentaho/di/trans/TransTest.java

- When starting threads, check if transformation has any step to run, and finish it, if it has no steps.
- Test written
Backport of https://github.com/pentaho/pentaho-kettle/pull/2660
@mchen-len-son , could you please review this PR?

[SP-2755] Backport of PDI-14948 - Transformation with Metadata Injection runs endlessly if no input is received by Injection Step (5.4 Suite)

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInputMeta.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputMetaTest.java

- Adding null-checks before obtaining File Object from filename, that can be null.
**Summary**
After this fix behavior is the following:
- When exporting trans with empty filenames, they are kept empty and not converted to related path
**More details**
Situation is the following here:
In transformation's xml fileNames with empty strings are stored as <fileName/> and extracted as nulls when transformation is loaded.
First I wanted to store and load them as empty strings. But it was a bad idea - it leads us to some problems that are hard to overcome with such storing. Here the pitfall of this approach: when exporting trans with empty (non-null) strings in file name - they are converted into related path (root of kettle in this case). And in 99 % cases it's not what user expects.
So what we …

[SP-2787]  Backport of PDI-15120 - Export Linked Resources to XML fails if Text File Input contains empty row (5.4 Suite)

---

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java
engine/test-src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep_StyleFormatTest.java

- clone existing cell style when applying data format
- created a unit test for applying Format and Style from cell (from a template) when writing fields in Excel Writer step
Backport of https://github.com/pentaho/pentaho-kettle/pull/2680.
@pamval , @mchen-len-son , could you please review this PR?

[SP-2785] Backport of PDI-15386 - PDI 5.4/6.1.0 - Excel Writer step does not retain the cell style when data format is also applied (5.4 Suite)

---

core/src/org/pentaho/di/core/RowMetaAndData.java

From my investigation RowMetaAndData class is not used in concurrent environment, so synchronization is redundant here.
@mchen-len-son , @mbatchelor, could you please review this PR?

[PDI-8942] RowMetaAndData - inconsistent synchronization

---

assembly/ivy.xml
engine/ivy.xml
plugins/pdi-pur-plugin/ivy.xml

The fix is needed due to using java 1.8, and incompatibility of asm old version (is used by jersey) reading new java 1.8 features 
The following scope of repositories is upgraded(except webdetails): The list is sorted in the order of build team runs
https://github.com/pentaho/pentaho-reporting
https://github.com/pentaho/mondrian
https://github.com/pentaho/pentaho-kettle
https://github.com/pentaho/pentaho-mondrianschemaworkbench-plugins
https://github.com/pentaho/pentaho-platform
https://github.com/webdetails/cpf
https://github.com/pentaho/pentaho-metaverse
https://github.com/pentaho/pdi-platform-utils-plugin
https://github.com/pentaho/pentaho-data-profiling
https://github.com/pentaho/data-access
https://github.com/pentaho/big-data-plugin
https://github.com/pentaho/pentaho-data-refinery …

[BACKLOG-8388] - Upgrade Jersey to 1.19.1 across the suite for Java 8 compatibility

---

core/src/org/pentaho/di/core/plugins/PluginFolder.java
core/test-src/org/pentaho/di/core/plugins/PluginFolderTest.java

There are fix and unit tests to cover it and around it.

[BAD-537]: Misleading error messages in Pentaho MapReduce mapper logs

---

core/src/org/pentaho/di/core/row/RowMeta.java
core/test-src/org/pentaho/di/core/row/RowMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterTest.java

[PDI-15523] - Select Values Step Throws Errors when multiple fields with same field name occur
Earlier it used to work since RowMeta clone was implemented as sequential addValueMeta calls.
After reworking the RowMeta implementation this logic was eliminated, what is right:
cloning should replicate the state as is (w/o) taking care of fixing incosistencies.
Real inconsistancy (duplicated fields' names) were caused by the fact that setValueMeta method
did not process the case when duplicated field's name is introduced.
The fix is to incorporate deduplication to the setValueMeta() call logic.
license header

[SP-2819] - Backport of PDI-15523 - Select Values Step Throws Errors when multiple fields with same field name occur (6.1 Suite)

---

engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeMeta.java
engine/test-src/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeMetaInjectionTest.java

[BACKLOG-9667] - ETL Metadata Injection step fails when we check the option 'Don't execute resulting transformation' for Synchronize after merge step

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

@CodeOnCoffee, @pamval could you please take a look?
Current behavior is following: if KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=Y then null is retrieved as empty string like it was in old product versions ( 4.4.0 ).
when KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL=N we have null as returned value.

[PDI-11194] - Formula now treating empty strings as null

---

core/src/org/pentaho/di/core/row/ValueDataUtil.java
core/test-src/org/pentaho/di/core/row/ValueDateUtilTest.java

values
- DateWorkingDiff calculation now considers last day of month
- added unit test (divided tests into separate ones by months since in case of errors some months are failing some not)

[PDI-15344] Date A - Date B (working days) Calculation returns incorrect

---

core/src/org/pentaho/di/core/RowMetaAndData.java

From my investigation RowMetaAndData class is not used in concurrent environment, so synchronization is redundant here.
@mchen-len-son , @mbatchelor, could you please review and merge this PR?

[SP-2823][PDI-8942] RowMetaAndData - inconsistent synchronization

---

core/src/org/pentaho/di/core/RowMetaAndData.java

From my investigation RowMetaAndData class is not used in concurrent environment, so synchronization is redundant here.
@mchen-len-son , @mbatchelor, could you please review and merge this PR?

[SP-2824][PDI-8942] RowMetaAndData - inconsistent synchronization

---

core/ivy.xml
plugins/pdi-pur-plugin/ivy.xml

- Changed the kettle-core and pdi-pur-plugin to use the newer version of
javassist

[BACKLOG-10323] Standardizing on javassist version 3.20.0-GA

---

assembly/package-res/Kitchen.bat
assembly/package-res/Pan.bat
assembly/package-res/kitchen.sh
assembly/package-res/pan.sh
engine/src/org/pentaho/di/kitchen/Kitchen.java
engine/src/org/pentaho/di/pan/Pan.java

[PDI-15255] kitchen.sh/pan.sh cannot use relative paths to jobs/transformations stored on the filesystem
-calculate current (run) directory in scripts,
-sent current directory to kitchen and pan,
-calculate absolute path to file if used relative.

[PDI-15255] kitchen.sh/pan.sh cannot use relative paths to jobs/transformations stored on the filesystem

---

engine/src/org/pentaho/di/job/entries/columnsexist/messages/messages_en_US.properties

[BACKLOG-11303] - Missing word in the error message of the job entry "Columns exist in a table"

---

engine/src/org/pentaho/di/job/JobExecutionConfiguration.java
engine/test-src/org/pentaho/di/job/JobExecutionConfigurationTest.java
ui/src/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java

[PDI-15296] Arguments (legacy) do not work in Spoon 6.1
-getting argument job as argument all transformation fo jobs
-test
Using new method org.pentaho.di.job.JobExecutionConfiguration#getUsedArguments (which is not a getter at all) in analogy with 
org.pentaho.di.trans.TransExecutionConfiguration#getUsedArguments
My changes improved unit test coverage in my changes files.

[PDI-15296] Arguments (legacy) do not work in Spoon 6.1

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

[PDI-15070] Get rows from result" step does not pass rows when a transformation is executed on a remote carte server
-fix using encode XML tags for "binary-string" node
I saw that the same issue is available for STORAGE_TYPE_INDEXED (tag "index-value") but I codln't find using this storage type (except junit tests).

[PDI-15070] Get rows from result" step does not pass rows when a transformation is executed on a remote carte server

---

core/src/org/pentaho/di/core/database/ConnectionPoolUtil.java
core/test-src/org/pentaho/di/core/database/ConnectionPoolUtilTest.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

When configuring the DataSource, the call to setDriverClassname
would fail if the driver is not in the current thread's classpath.
Addressed by explicitly setting the BasicDataSource driver cp.
http://jira.pentaho.com/browse/BACKLOG-11444

[BACKLOG-11444]  Pooled big-data connections fail in Spoon

---

assembly/package-res/spoon.sh

* To be able to return to folder which contains spaces in name

[BACKLOG-11582]-Escaping variable to correctly work with spaces

---

core/src/org/pentaho/di/core/row/value/ValueMetaInternetAddress.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaInternetAddressTest.java

Removed override for binary string converter.
`InetAddress.getByAddress` expects a byte array representing the IP Address value, not an encoded String.
@matthewtckr -- this override was added with https://github.com/pentaho/pentaho-kettle/pull/2766/commits/162d73be33164980f9a3dcc5d8b7239d902f6d1d
I added more unit testing and checked the related cases for regression, everything seems to be okay. Is there anything else that should be tested?

[BACKLOG-11693]Use default binary string conversion for Internet Address

---

ui/package-res/ui/images/kettle_logo_small.svg

[CHERRY-PICK] https://github.com/pentaho/pentaho-kettle/pull/3068/commits/7aa391755e44a27b13d0ae4e5627badda6cb2782
- fixed kettle_logo_small.svg icon

[BACKLOG-11620] Update product App icons and splash screens

---

engine/src/org/pentaho/di/job/JobExecutionConfiguration.java
engine/test-src/org/pentaho/di/job/JobExecutionConfigurationTest.java
ui/src/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java

[SP-2959][PDI-15296] Arguments (legacy) do not work in Spoon 6.1
-getting argument job as argument all transformation fo jobs
-test
@brosander @mchen-len-son Could you please reviewand merge?

[SP-2959][PDI-15296] Arguments (legacy) do not work in Spoon 6.1

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

[SP-2964][PDI-15070] Get rows from result" step does not pass rows when a transformation is executed on a remote carte server
-fix using encoding XML tags for "binary-string" node

[SP-2964][PDI-15070] Get rows from result" step does not pass rows when a transformation is executed on a remote carte server

---

assembly/ivy.xml

@CodeOnCoffee @rmansoor @mbatchelor @pentaho/rogueone Please review
Related PRs:
https://github.com/pentaho/pentaho-platform/pull/3207
https://github.com/pentaho/pentaho-reporting/pull/869
https://github.com/pentaho/pentaho-reportdesigner-ee/pull/53
https://github.com/pentaho/pentaho-kettle/pull/3087

[BACKLOG-11621] Removes JTDS driver dependency

---

plugins/kettle-drools5-plugin/ivy.xml

@mbatchelor, @pamval, #3088 to 7.0.0.0. Thanks.

[BACKLOG-11939] - Drools upgrade bringing in vulnerable xstream jar

---

core/src/org/pentaho/di/core/database/DatabaseMeta.java
core/src/org/pentaho/di/core/database/messages/messages_en_US.properties

[SP-2950] Backport of BISERVER-12713 - L10N - Error messages are not translated to different languages (6.1 Suite)

---

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Fixed removing row when parsing a null field using JSON Input step. Now if the json field is null and the row has another input fields then Json Input step wont skip the row and will set the missed value to null

PDI-15681- Fixed removing row when parsing a null field

---

engine/src/org/pentaho/di/trans/steps/filterrows/FilterRowsMeta.java
engine/test-src/org/pentaho/di/trans/steps/filterrows/FilterRowsMetaTest.java

Reverts previous fixes that caused this regression
2fa882af41b0baaee72d4cc0faa7fa44921326aa
3c46aa03c8f54ecb00995aa01388c5cd61b15222
@dkincade @kcruzada 
Backport of #3112

[BACKLOG-12003]Persist Filter step output when target is renamed

---

engine/src/org/pentaho/di/trans/step/BaseStepMeta.java
engine/src/org/pentaho/di/trans/step/StepMetaInterface.java
engine/src/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
engine/test-src/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMetaTest.java
ui/src/org/pentaho/di/ui/spoon/Spoon.java
ui/test-src/org/pentaho/di/ui/spoon/SpoonTest.java

[SP-2993][PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step
-add method in StepMetaInterface for clean after removing hop
-add default implementation for BaseStep
-add implementation for Job and Transformation Executor
-add tests

[SP-2993][PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step

---

engine/src/org/pentaho/di/trans/step/BaseStepMeta.java
engine/src/org/pentaho/di/trans/step/StepMetaInterface.java
engine/src/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
engine/test-src/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMetaTest.java
ui/src/org/pentaho/di/ui/spoon/Spoon.java
ui/test-src/org/pentaho/di/ui/spoon/SpoonTest.java

[SP-2994][PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step
-add method in StepMetaInterface for clean after removing hop
-add default implementation for BaseStep
-add implementation for Job and Transformation Executor
-add tests

[SP-2994][PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step

---

ui/src/org/pentaho/di/ui/core/dialog/ThinDialog.java

[BACKLOG-10381] Thin Repository dialog opens always to the left

---

ui/src/org/pentaho/di/ui/job/entries/job/JobEntryJobDialog.java
ui/test-src/org/pentaho/di/ui/job/entries/job/JobEntryJobDialogTest.java

@bmorrise , @wseyler , @e-cuellar , @mbatchelor please review.
PDI-15690 (http://jira.pentaho.com/browse/PDI-15690)
The idea of this fix is to replace the deprecated variable by actual variable in the JobEntryJobDialog class and to make the use of constant for file name testable.

[PDI-15690] Deprecated variable replaced by actual

---

ui/src/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialog.java
ui/test-src/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialogTest.java

@bmorrise , @wseyler , @e-cuellar , @mbatchelor please review.
PDI-15690 (http://jira.pentaho.com/browse/PDI-15691)
The idea of this fix is to replace the deprecated variable by actual variable in the JobEntryTransDialog class and to make the use of constant for file name testable.

[PDI-15691] Deprecated variable replaced by actual

---

core/src/org/pentaho/di/core/database/DatabaseMeta.java
core/src/org/pentaho/di/core/database/messages/messages_en_US.properties

Reverts pentaho/pentaho-kettle#3103

Revert "[SP-2950] Backport of BISERVER-12713 - L10N - Error messages are not translated to different languages (6.1 Suite)"

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java
ui/src/org/pentaho/di/ui/util/EngineMetaUtils.java
ui/test-src/org/pentaho/di/ui/util/EngineMetaUtilsTest.java

The idea of this fix is to detect that activeMeta instance is Job/Transformation meta, so we should process it the same way as we do with MainPrespective.
The best option for this issue - to extract open (close) operation from the perspectives' code, but is a much bigger change (and right now I do not have a clear view how to refactor this code)..
Let me know if you have ideas how to make the fix less "hacky".
https://github.com/pentaho/pdi-scheduler-plugin/pull/44

[BACKLOG-11530] - Cannot disconnect from the repository when in Schedule perspective and ask to close all files

---

engine/src/org/pentaho/di/trans/step/BaseStepMeta.java
engine/src/org/pentaho/di/trans/step/StepMetaInterface.java
engine/src/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
engine/test-src/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMetaTest.java
ui/src/org/pentaho/di/ui/spoon/Spoon.java
ui/test-src/org/pentaho/di/ui/spoon/SpoonTest.java

Revert "[SP-2994][PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step"
This reverts commit f3f7ab00200c04138c454cf9ee7bec82c553dd74.

Revert "[SP-2994][PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step"

---

core/src/org/pentaho/di/core/logging/LoggingObject.java
core/test-src/org/pentaho/di/core/logging/LoggingObjectTest.java

[PDI-15628] Results from jobs run in parallel should not be mixed in log files
-added checking object name in LoggingObject equals()

[PDI-15628] Results from jobs run in parallel should not be mixed in log files

---

core/src/org/pentaho/di/core/logging/LoggingObject.java
core/test-src/org/pentaho/di/core/logging/LoggingObjectTest.java

[SP-3048][PDI-15628] Results from jobs run in parallel should not be mixed in log files
-added checking object name in LoggingObject equals()

[SP-3048][PDI-15628] Results from jobs run in parallel should not be mixed in log files

---

engine/src/org/pentaho/di/trans/step/BaseStepMeta.java
engine/src/org/pentaho/di/trans/step/StepMetaInterface.java

[PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step"
-added default implementation in interface

[PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step"

---

engine/src/org/pentaho/di/trans/step/BaseStepMeta.java
engine/src/org/pentaho/di/trans/step/StepMetaInterface.java

[SP-2993][PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step"
-added default implementation in interface

[SP-2993][PDI-14937] executors_output_step not cleared when a hop is deleted from the transformation executor step"

---

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java
plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputMetaTest.java

Backport of PDI-15707 - JSON Input is not processing HDFS files that come from a Field when connected to repository

SP-3019 - Backport of PDI-15707 - JSON Input is not processing HDFS files that come from a Field when connected to repository (7.0 Suite)

---

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java
plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/exception/JsonInputException.java
plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java
plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java

Fixed skipping rows if json field is null, empty or if there are no matches with json fields and at the same time there are no additional not null row fields. Corrected filtering out rows

SP-3069 - Backport of PDI-15196 - JSON Input Step does not ignore missing paths

---

engine/src/org/pentaho/di/www/GetStatusServlet.java

I added comparators for jobs and transformations in carte status lists so that jobs and transformations will be order this way:
1. firstly by last log date (desc)
2. if last log date is null in one of transformations/jobs or last log dates are equal, compare by name, then by guid

[PDI-14058] Kettle Status page should show the history of jobs in a logical sequence

---

plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmljoin/XMLJoin.java
plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmljoin/XMLJoinMeta.java
plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/xmljoin/XmlJoinMetaGetFieldsTest.java

The problem was that previewing data called getFields method and got the wrong result -> which was which contained source step fields and target step's ones + result xml field. But XMLJoin step produces only  one row which will be produced containing the fields of the target step plus the result field of the join, 
therefore there was a field mismatch in preview data

PDI-15577 - XML Join saves output in random input fields

---

core/ivy.xml
core/src/org/pentaho/di/core/row/ValueMetaAndData.java
core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/row/ValueMetaAndDataTest.java
ui/src/org/pentaho/di/ui/core/dialog/EnterValueDialog.java

[PDI-14449] Filter Rows step and Kettle date variables,
[PDI-14417] Filter rows step behaviour with inputting dates - problem with EnterValueDialog,
[PDI-14418] Filter Rows step is not displaying date values after closing then re-opening a transformation
-added reading date in compatible format (how it was saved)
-replaced modify listener on focus lost listener
-added test
-added power mock dependency

[PDI-14449]  [PDI-14417] [PDI-14418] 

---

ui/src/org/pentaho/di/ui/core/widget/TableView.java

…n is selected  it created a non-sized array(length == 0) for the options and trying to display it in a table in "logging" tab in "executions resuts" caused  java.lang.ArrayIndexOutOfBoundsException as it tried to get the first element from the array. And also fixed unexpected additional row appending when you click on checkbox "Include?" in Transformation properties in "Logging" tab

SP 3120 - Backport of PDI-15661 - Spoon Crashes when Logging is Removed (java.lang.ArrayIndexOutOfBoundsException) 

---

ui/src/org/pentaho/di/ui/core/widget/TableView.java

…n is selected  it created a non-sized array(length == 0) for the options and trying to display it in a table in "logging" tab in "executions resuts" caused  java.lang.ArrayIndexOutOfBoundsException as it tried to get the first element from the array. And also fixed unexpected additional row appending when you click on checkbox "Include?" in Transformation properties in "Logging" tab

SP 3121 - Backport of PDI-15661 - Spoon Crashes when Logging is Removed (java.lang.ArrayIndexOutOfBoundsException) 

---

engine/src/org/pentaho/di/trans/steps/ldapinput/LdapSslProtocol.java
test/org/pentaho/di/trans/steps/ldapinput/LdapSslProtocolTest.java

[PDI-13754] LDAP Input Step - Using variable for "Trust store path"
-added resolving variable for trust store path
-added resolving and decoding variable for Trust store password

[PDI-13754] LDAP Input Step - Using variable for "Trust store path"

---

engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java
engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByAggregationNullsTest.java

In case "minNullIsValued" is false, firstly, we need to set the first non-null value for further comparing

PDI-15648 - Group by step - Minimum aggregation doesn't work when null value in first row

---

pdi-execution-engine/impl/model/src/main/java/org/pentaho/di/engine/model/Transformation.java

Small fix: An operation created from a parent transformation should be added immediately
@CodeOnCoffee @mkambol

[BACKLOG-12856]Fix Creating Operations

---

engine/src/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java
engine/test-src/org/pentaho/di/trans/steps/exceloutput/ExcelOutputTemplateTest.java
engine/test-src/org/pentaho/di/trans/steps/exceloutput/ExcelOutputTest.java

[PDI-13487]Excel Output field formats are ignored when "Split Every Rows" is used….. Rows" is used
-added clearing formats in closing file, so for next file format will be reinitialize and write in next file
-added test

[PDI-13487]Excel Output field formats are ignored when "Split Every Rows" is used

---

engine/src/org/pentaho/di/trans/steps/ldapinput/LdapSslProtocol.java
test/org/pentaho/di/trans/steps/ldapinput/LdapSslProtocolTest.java

[SP-3198][PDI-13754] LDAP Input Step - Using variable for "Trust store path"
-added resolving variable for trust store path
-added resolving and decoding variable for Trust store password
-added tests

[SP-3198][PDI-13754] LDAP Input Step - Using variable for "Trust store path"

---

engine/src/org/pentaho/di/trans/steps/ldapinput/LdapSslProtocol.java
test/org/pentaho/di/trans/steps/ldapinput/LdapSslProtocolTest.java

[SP-3197][PDI-13754] LDAP Input Step - Using variable for "Trust store path"
-added resolving variable for trust store path
-added resolving and decoding variable for Trust store password
-added tests

[SP-3197][PDI-13754] LDAP Input Step - Using variable for "Trust store path"

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java

https://github.com/pentaho/pentaho-kettle/blob/master/engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java#L536 Here the facts that enclosure character(s) may be represented not only as 1 byte and that enclosure can consist of more than one character weren't taken into account

PDI-15877 - Enclosure character is not removed from output stream

---

engine/src/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java
engine/test-src/org/pentaho/di/trans/steps/exceloutput/ExcelOutputTemplateTest.java
engine/test-src/org/pentaho/di/trans/steps/exceloutput/ExcelOutputTest.java

[SP-3247][PDI-13487]Excel Output field formats are ignored when "Split Every ... Rows" is used
-added clearing formats in closing file, so for next file format will be reinitialize and write in next file
-added test

[SP-3247][PDI-13487]Excel Output field formats are ignored when "Split Every ... Rows" is used

---

engine/src/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java
engine/test-src/org/pentaho/di/trans/steps/exceloutput/ExcelOutputTemplateTest.java
engine/test-src/org/pentaho/di/trans/steps/exceloutput/ExcelOutputTest.java

[SP-3244][PDI-13487]Excel Output field formats are ignored when "Split Every ... Rows" is used
-added clearing formats in closing file, so for next file format will be reinitialize and write in next file
-added test

[SP-3244][PDI-13487]Excel Output field formats are ignored when "Split Every ... Rows" is used

---

pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/converter/RowConversionManager.java
pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/events/BaseEvent.java
pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/events/DataEvent.java
pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/events/MetricsEvent.java
pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/events/StatusEvent.java
pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/model/Row.java
pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/model/Rows.java
pdi-engine-api/api/src/main/java/org/pentaho/di/engine/api/model/Transformation.java

Common base class for events.
Updated DataEvent to use Rows class as its data to
simplify subscription to events, and include TYPE and STATE
@hudak @CodeOnCoffee @ccaspanello

[BACKLOG-14309]  AEL API simplification.

---

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java

The problem was : getLastRowNum() returns row number of the last row in sheat beginning from 0, so the first row( header ) has 0 number. And then https://github.com/pentaho/pentaho-kettle/blob/master/engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java#L827-L829  we dont increment the index to the next row.

PDI-12261 - Microsoft Excel Writer - Appending lines to existing sheet

---

engine/ivy.xml
engine/src/org/pentaho/di/trans/steps/syslog/SyslogMessage.java
engine/test-src/org/pentaho/di/trans/steps/syslog/SyslogMessageConcurrentTest.java

"running forever" was caused by an npe exception in dispose method in finally block which prevented transformation from proper finishing. Shutdown method in 0.9.34 in syslog api isnt thread safe and is not intended to be used multiple times . the method in 0.9.46 is also non fully thread safe. https://github.com/pentaho/pentaho-kettle/blob/master/engine/src/org/pentaho/di/trans/steps/syslog/SyslogMessage.java#L187

PDI-14840 - Having two syslog steps in transformation makes it running forever

---

engine/src/org/pentaho/di/trans/ael/adapters/TransMetaConverter.java
engine/test-src/org/pentaho/di/trans/ael/adapters/TransMetaConverterTest.java
pdi-engine-api/src/main/java/org/pentaho/di/engine/api/HasConfig.java
pdi-engine-api/src/main/java/org/pentaho/di/engine/model/Configurable.java

Related: updated TransMetaConverter to pass the transmeta xml in config,
instead of TransMeta.
@hudak

[BACKLOG-14636] Enforcing serializable config items in ael HasConfig

---

engine/src/org/pentaho/di/trans/ael/adapters/StepInterfaceEngineAdapter.java
engine/src/org/pentaho/di/trans/ael/adapters/TransEngineAdapter.java
engine/src/org/pentaho/di/trans/step/StepMeta.java

- config stored with Operations now has the string xml from the stepmeta,
TransEngineAdapter was still expecting the StepMeta object.
- short circuit .putRow in the adapter when no conversionManager is
available.

[BACKLOG-14636]  Updates to support engine adapters

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java

- fix for regression BACKLOG-14781
- fixed unittest

[PDI-15922]-Missing data when using delimiters like "aa" in the CSV file

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java

- fix for regression BACKLOG-14781
- fixed unittest

[SP-3273][PDI-15922]-Missing data when using delimiters like "aa" in the CSV file

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java

- fix for regression BACKLOG-14781
- fixed unittest

[SP-3274][PDI-15922]-Missing data when using delimiters like "aa" in the CSV file

---

ui/src/org/pentaho/di/ui/spoon/ExpandedContentManager.java
ui/test-src/org/pentaho/di/ui/spoon/ExpandedContentManagerTest.java

This fixes an SWT browser issue on the Mac.  Now when you on the mac when the user goes into DET if there is an existing execution panel open it is hidden so that artifacts from it won't "come through" to the DET screen.  When leaving DET it is set visible again.  The additional code is only active on OS X. @mdamour1976 @bmorrise

[BACKLOG-11126][BACKLOG-11425] - Updated ExpandedContentManger for OSX

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteBigCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteLittleCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiBytePatternMatcher.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputDoubleLineEndTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java

This reverts commit 173c7306b6d1ae3f93929695b721abe355d1327c.
This reverts commit 42ac888b31e1b3593c37a33da5c6fa339ff0fb2f.

Revert "[SP-3273][PDI-15922]-Missing data when using delimiters like "aa" in the CSV file"

---

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputData.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteBigCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiByteLittleCrLfMatcher.java
engine/src/org/pentaho/di/trans/steps/csvinput/MultiBytePatternMatcher.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputDoubleLineEndTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java
engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvProcessRowInParallelTest.java

This reverts commit 8abc001c2429d655e9c6d0d52393513dfe0a2345.
This reverts commit 2edc55734fd0b080ebddcf488cda2ee3bc3dbdfe.

Revert "[SP-3274][PDI-15922]-Missing data when using delimiters like "aa" in the CSV file"

---

core/src/org/pentaho/di/core/vfs/KettleVFS.java
core/test-src/org/pentaho/di/core/vfs/KettleVFSTest.java
engine/src/org/pentaho/di/pan/Pan.java

"File>Export>Linked Resources to XML" returns [error: can't open file]
Currently the code uses the regular expression to identify if there is
"zip" in the name. Now we check to see if the fileName starts with
protocol like "Zip". If is does not, checks to see if the path is relative
-Added a utility method in KettleVFS
-Added test case for new method in KettleVFS

[BACKLOG-11769] PDI - Pan is unable to run a zip File exported as

---

engine/src/org/pentaho/di/trans/steps/denormaliser/Denormaliser.java
engine/test-src/org/pentaho/di/trans/steps/denormaliser/DenormaliserAggregationsTest.java

[PDI-16017] Denormaliser step: Minimum Aggregation with multiple columns carries data across columns
- reworked fix PDI-9662. Method newGroup should not initialize result by default for MIN
[PDI-16015] Denormaliser step: KettleValueException on Minimum Aggregation only
- initialization code didn't have converting data
I retested PDI-9662

[PDI-16017] Denormaliser step: Minimum Aggregation with multiple columns carries data across columns

---

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java

[PDI-14390] Text file input throws NPE if skipping error rows and passing through incoming fieds
- fixed NPE
- added test

[PDI-14390] Text file input throws NPE if skipping error rows and passing through incoming fieds

---

assembly/ivy.xml

Hadoop Job Executor job entry uses org.pentaho.di.core.logging.LogWriter. This is located in kettle5-log4j-plugin-xxx.jar.
This jar was pulled into <PENTAHO>\data-integration\lib transitively from pentaho-reporting-engine-classic-extensions-kettle project.
After GAV changes for reporting projects (https://github.com/pentaho/pentaho-kettle/commit/8136fd585deb77007d06a89a0df369cae83285c1) this jar stopped to be pulling out transitively and disappeared from <PENTAHO>\data-integration\lib.
But we need to have it for big-data-project.
So the fix is to receive this dependency directly.

[BACKLOG-15186]: PMR and Hadoop Job Executor job entries fail because of they can not find "LogWriter" class (NoClassDefFoundError)

---

engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java

So content conversion logic can be accessible within AEL functions.

[BACKLOG-14876] Making TextFileOutput.writeRowToFile public

---

engine/src/org/pentaho/di/repository/kdr/KettleDatabaseRepository.java
engine/src/org/pentaho/di/repository/kdr/messages/messages_en_US.properties

[BACKLOG-15034] - When creating a Database Repository, an 'Invalid user credentials' error is thrown to the logs - change log message

---

engine/src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesAddedFunctions.java
engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesModTest.java

Update the step's variable space as well when calling the setVariable
function.

[SP-3367] - Backport of PDI-16049 - getVariable does not return variable set by setVariable in same Javascript step

---

assembly/ivy.xml

Version 4.2.0 was being resolved tinybundles->bndlib->org.osgi.core.

[BACKLOG-15330] Explicit exclude for org.osgi.core

---

engine/src/org/pentaho/di/trans/steps/webservices/wsdl/Wsdl.java

The error occurred inside WSDLReader#readWSDL(String wsdlURI) method call and we can not change the way how WSDLReader reads WSDL document from the defined URI. We also can not improve/remove its error message as logging part also happens inside readWSDL call. However in WebService we have a fallback for WSDL retriving: readWsdl method, that uses HTTPProtocol utility to load  WSDL content. This utility works well while getting WDSL from the same server. So I decided to remove WSDLReader#readWSDL and use the fallback as only approach for getting WSDL.

[BACKLOG-15514] - [Web Service Lookup] Improve the Fatal Error message that is thrown to the logs

---

engine/src/org/pentaho/di/trans/ael/adapters/StepInterfaceEngineAdapter.java

Addressing NPEs that occur when status is updated
due to rowsets not being present in the StepAdapter.

[BACKLOG-15550]  Stream status

---

engine/src/org/pentaho/di/trans/step/BaseStep.java
engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

- update output Row and input Row meta for 2 and more sources
- fixed writing encode for "fast data dump" off

[PDI-13987] “Text file output” step writes field to the file with different encoding (binary data with different encoding, lazy conversion)

---

plugins/meta-inject-plugin/src/main/java/org/pentaho/di/trans/steps/metainject/OpenMappingExtension.java
plugins/meta-inject-plugin/src/test/java/org/pentaho/di/trans/steps/metainject/OpenMappingExtensionTest.java

pmr job log full of exceptions when some common step classes contains import to swt libraries 
localized needed for OpenMappingExtension is from spoon package, 
so to fix that situation and have correct localized message PKG is now SpoonLifecycleListener which doesn't have import for swt

[BAD-587] - PMR Mapper log is full of errors related to org.eclipse.jface.window.ApplicationWindow

---

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/UserRoleDelegate.java
plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/UserRoleDelegateTest.java

- fixed role creation - now users cannot create roles with the same name but with different case.

[PDI-14598] When creating roles with the existing names but with lowercase letters the roles are added but they cannot be removed

---

plugins/pdi-engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/spark/SparkRunConfigurationExecutor.java
plugins/pdi-engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/spark/SparkRunConfigurationExecutorTest.java

ael-security marker feature is installed.

[BACKLOG-15748] Adding pentaho-kerberos-jaas capability only if

---

engine/src/org/pentaho/di/trans/steps/denormaliser/Denormaliser.java
engine/test-src/org/pentaho/di/trans/steps/denormaliser/DenormaliserAggregationsTest.java

[PDI-16017] Denormaliser step: Minimum Aggregation with multiple columns carries data across columns
- reworked fix PDI-9662. Method newGroup should not initialize result by default for MIN
[PDI-16015] Denormaliser step: KettleValueException on Minimum Aggregation only
- initialization code didn't have converting data

[SP-3376][PDI-16017] Denormaliser step: Minimum Aggregation with multiple columns carries data across columns

---

engine/src/org/pentaho/di/trans/step/BaseStep.java
engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

- update output Row and input Row meta for 2 and more sources
- fixed writing encode for "fast data dump" off

[SP-3431][PDI-13987] “Text file output” step writes field to the file with different encoding (binary data with different encoding, lazy conversion)

---

plugins/gp-bulk-loader/gp-bulk-loader-core/pom.xml
plugins/gp-bulk-loader/gp-bulk-loader-core/src/main/resources/version.properties

@pminutillo Now the version.properties content is produced like this:
#GP Bulk Loader Plugin build information
version=8.0-SNAPSHOT
builddate=2017/05/01 07\:21

[BACKLOG-13069] Fixes to the version.properties in gp-bulkloader-plugin

---

engine/src/org/pentaho/di/trans/steps/rest/Rest.java

- fix for case when parameters are defined in the "Matrix Parameters" tab

[PDI-16045]-Rest Client step does not encode parameter list properly

---

engine/src/org/pentaho/di/trans/steps/rest/Rest.java

- fix for case when parameters are defined in the "Matrix Parameters" tab

[SP-3448][PDI-16045]-Rest Client step does not encode parameter list properly

---

plugins/pdi-pur-plugin/ivy.xml

[PPP-3742]-Use of vulnerable component gwt-servlet-2.0.3.jar CVE-2012-4563

---

engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java
engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByAggregationNullsTest.java

[PDI-16150] Pivot Table - Binary Type with another field - java.langRuntimeException: java.util.concurrent.ExecutionException
-fixed processing (ClassCastException) in kettle and in mondrian for binary data
mondrian: https://github.com/pentaho/mondrian/pull/887

[PDI-16150] Pivot Table - Binary Type with another field - java.langRuntimeException: java.util.concurrent.ExecutionException

---

plugins/kettle-drools5-plugin/kettle-drools5-core/pom.xml

Exclude drools-reteoo. This is a legacy engine which is not used by default. There is no need for us to include it.

[COMP-5831] Exclude drools-reteoo

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

When using MySQL as repository database every SELECT statement has to be followed by a COMMIT to avoid locking issues in parallel sessions. For this reason the current code contains the method closeReadTransaction() which also needs to be called after SELECTs in getNextTableID(), getIDs() and getStrings().
The patch fixes the issue described in  [[PDI-7090]](http://jira.pentaho.com/browse/PDI-7090).

[PDI-7090] Only one user can make changes in a repository at any time. (Database Repository is locked)

---

ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java
ui/src/org/pentaho/xul/swt/tab/TabSet.java
ui/test-src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegateTest.java
ui/test-src/org/pentaho/xul/swt/tab/TabSetTest.java

- Fix inconsistencies when closing tabs with the same name
- Improve cobertura tests coverage

[SP-3559][PDI-16196]-Saving a transformation with a duplicate name makes PDI work inconsistently

---

ui/src/org/pentaho/di/ui/core/dialog/PreviewRowsDialog.java
ui/test-src/org/pentaho/di/ui/core/dialog/PreviewRowsDialogTest.java

In rare cases in rare environments sometimes buffer can contain additional null row value.
It was not possible reproduce it in debugging with breakpoints on modification points of buffer.
Fix NPE. See additional PDI-16198.

[PDI-16198] Multiple Preview dialogs when previewing a step using "Number of Copies" > 1

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

Commit open transactions after select statement to avoid locking of parallel sessions when using MySQL as repository database.

[SP-3565]Commit open transactions

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

[SP-3564][PDI-7090] - Only one user can make changes in a repository at any time. (Database Repository is locked)
Fixed an additional problem. When user editing or create slave server via toolbar it locks database.
This commit uses approach from base commit https://github.com/pentaho/pentaho-kettle/pull/3857/commits/befadee3293dd4f8f3c5999dd1e345f56b4cdabd

[SP-3564][PDI-7090] - Only one user can make changes in a repository at any time. (Database Repository is locked)

---

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java

Fixed an additional problem in 6.1. When user editing or create carte server it locks database (see steps in comments [SP-3565]).
This commit uses approach from base commit https://github.com/pentaho/pentaho-kettle/pull/3857/commits/befadee3293dd4f8f3c5999dd1e345f56b4cdabd

[SP-3565] Backport of PDI-7090 - Only one user can make changes in a repository at any time. (Database Repository is locked) (6.1 Suite).

---

engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java

- the newline is now updates in the file format setter
- the "injection" annotation was moved on the setter in order to implement the above thing in metadata injection

[PDI-16275] Output File incorrect after meta-injection due to derived value not being updated

---

core/src/org/pentaho/di/core/database/OracleDatabaseMeta.java
core/test-src/org/pentaho/di/core/database/OracleDatabaseMetaTest.java

- now avaliable uncheck "Supports the timestamp data type"
- updated unit test

[PDI-16236]-Cannot uncheck database identifier "Timestamp" (Oracle database only)

---

engine/src/kettle-variables.xml

New property to hide knox gateway.

[BACKLOG-17138] Add KETTLE_HADOOP_CLUSTER_GATEWAY_CONNECTION variable.

---

core/src/org/pentaho/di/core/vfs/KettleVFS.java

Proposed change for [PDI-16378](http://jira.pentaho.com/browse/PDI-16378)

[PDI-16378] Add cause to exception thrown in KettleVFS#getFileObject

---

engine/src/org/pentaho/di/trans/ael/adapters/TransMetaConverter.java
engine/test-src/org/pentaho/di/trans/ael/adapters/TransMetaConverterTest.java

Use TransMeta.realClone(false) in order to avoid resetting unnecessary fields.
@mkambol @hudak

[BACKLOG-17072] AEL - spoon can't run a second transformation after the first completes

---

plugins/file-open-save/core/src/main/javascript/app/components/breadcrumb/breadcrumb.css

Fix for #69 from https://docs.google.com/spreadsheets/d/17QboBxK0V064iFzd3GXdpYGZ5I2bg-yWP5OOCYyC9u0/edit#gid=1166424294
69: The breadcrumb truncated menu text color should be #333333
@bmorrise

[BACKLOG-15721] Fix for truncated breadcrumb extra item color per UX

---

plugins/file-open-save/core/src/main/javascript/app/components/files/files.css

Fix for #61 from https://docs.google.com/spreadsheets/d/17QboBxK0V064iFzd3GXdpYGZ5I2bg-yWP5OOCYyC9u0/edit#gid=1166424294
61: In the list view, sort icon looks incorrect in all operating systems. The icon doesn't look like what was provided by ux.Image is 7px x 11px *(see ux mockups)*
@bmorrise

[BACKLOG-15721] fix sorting icon per UX

---

plugins/file-open-save/core/src/main/javascript/app/app.css
plugins/file-open-save/core/src/main/javascript/app/app.html
plugins/file-open-save/core/src/main/javascript/app/components/card/card.css
plugins/file-open-save/core/src/main/javascript/app/components/card/card.html
plugins/file-open-save/core/src/main/resources/i18n/file-open-save/messages_en.properties

Fixes for #'s 6, 7, 8, 10, 11, 12, and 13 for https://docs.google.com/spreadsheets/d/17QboBxK0V064iFzd3GXdpYGZ5I2bg-yWP5OOCYyC9u0/edit#gid=1166424294
6: Normal card background color should be #FDFDFD. (this was my bad - PJ)
7: Right now the text in the cards (name and date info) are not vertically aligned. Adding a line height of 14 pix to the Card title should fix this.
8: When there are no recent files the message "You haven't opened anything recently." is missing a period.
10: Before the user selects a recent file, the open button should be disabled.
11: Before vertical scrollbar appears, maintain 20px gutter to right, currently looks bigger than 20px.
12: When vertical scrollbar appears, maintain 20px gutter to right of card between card edge and scrollbar (dev to see if thats …

[BACKLOG-15718] Fixes for the following:

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java

- if the entity is an empty string, the DefaultApacheHttpMethodExecutor will not set headers due to the null com.sun.jersey.client.property.chunkedEncodingSize property.

[PDI-16318] REST Client Step: Http Method DELETE results in 401 where GET, PUT succeed. Postman works fine with OK/200

---

plugins/repositories/core/src/main/resources-filtered/web/index.html

When Security_HKLM_only registry key set to DWORD 0x01, it forces the browser into IE7 compatibility mode. This change forces IE into IE11 mode which is what we need to work.

[PDI-15858] - Fix for blank repository dialog in Windows

---

plugins/pur/core/pom.xml

Upgrading jackrabbit version to 2.14.2
Refer to BACKLOG-17562 and PPP-3714 for details. 
Related PRs being opened to upgrade other projects that depend on jackrabbit.
pentaho-platform : https://github.com/pentaho/pentaho-platform/pull/3708
pdi-ee-plugin: pentaho/pdi-ee-plugin#340
data-access: pentaho/data-access#917
@pentaho/rogueone @pentaho/rebelalliance

BACKLOG-17562: Upgrade jackrabbit library to 2.14.2

---

core/src/org/pentaho/di/core/database/OracleDatabaseMeta.java
core/test-src/org/pentaho/di/core/database/OracleDatabaseMetaTest.java

- now avaliable uncheck "Supports the timestamp data type"
- updated unit test

[SP-3662][PDI-16236]-Cannot uncheck database identifier "Timestamp" (Oracle database only)

---

core/src/main/java/org/pentaho/di/core/database/OracleDatabaseMeta.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java
dbdialog/src/main/resources/org/pentaho/ui/database/databasedialog.properties
dbdialog/src/main/resources/org/pentaho/ui/database/databasedialog.xul

Added new advanced database connection option "Strict number(38) interpretation (Oracle specific) ".
If true Oracle NUMBER with 38 precision is interpreted as BigDecimal

[PDI-16337] - Error reading from Oracle Number(38) column

---

engine/src/main/java/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClassMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClassMetaTest.java

added running compilation customer's class in separate thread for avoid crash the application in case of an unchecked compilation error

[PDI-13416] Adding a duplicate method in UDJC causes exception and crashes Spoon

---

ui/src/main/java/org/pentaho/di/ui/core/database/dialog/XulDatabaseDialog.java

-  replaced the variable-aware fields with normal fields and removed the
variable indicators next to the fields

[PMD-679]-Variable symbols displaying in the database dialog; PME does not support variables

---

engine/src/org/pentaho/di/core/util/FileUtil.java
engine/src/org/pentaho/di/kitchen/Kitchen.java
engine/src/org/pentaho/di/pan/Pan.java
engine/test-src/org/pentaho/di/utils/FileUtilsTest.java

- fixed definition of the absolute path

[SP-3694] Backport of PDI-16221 - "file" option of Kitchen and Pan do not work in the file system (7.1 Suite)

---

dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java
dbdialog/src/test/java/org/pentaho/ui/database/event/DataHandlerTest.java

Now after selecting and changing database type, db cache will hold and update the correct value of database interface

[PDI-16337]-Spoon db dialog cache doesn't update value of database interface after changing db type

---

engine/src/main/java/org/pentaho/di/trans/steps/csvinput/NamedFieldsMapping.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/NamedFieldsMappingTest.java

I modified mapping mechanism, so now it is possible to map indexes to non unique column names, thus it fixes the bug with getting data from columns that share the same name.
@pamval , @bmorrise  please review.

[BACKLOG-18271] - CSV File Input: Columns with the same name in the csv are not read properly

---

plugins/file-open-save/assemblies/feature/src/main/feature/feature.xml
plugins/file-open-save/pom.xml

Reverts pentaho/pentaho-kettle#4281
common-ui builds after pdi-core-plugins ... this change will need significant build orchestration changes before it can be cleared

Revert "[BACKLOG-18159] Enable new file open/save for CE"

---

engine/src/main/java/org/pentaho/di/trans/steps/csvinput/CsvInput.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileinput/EncodingType.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputUnicodeTest.java

@bmorrise , @pamval please review.
This PR excludes BOM from head strings. It also excludes BOM from field names that might exist in .ktr files (BOM comes to field names during "Get fields" operation and it would be better to keep this behaviour - as these "BOM'ed" fields could be copied to other steps).

[BACKLOG-18274] - CSV Files with BOM are not being correctly read by CSV File Input Step

---

engine/src/main/java/org/pentaho/di/core/injection/AfterInjection.java
engine/src/main/java/org/pentaho/di/core/injection/bean/BeanInjector.java
engine/src/main/java/org/pentaho/di/trans/steps/insertupdate/InsertUpdate.java
engine/src/main/java/org/pentaho/di/trans/steps/insertupdate/InsertUpdateMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/streamlookup/StreamLookupMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/insertupdate/InsertUpdateMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java
engine/src/test/java/org/pentaho/di/trans/steps/streamlookup/StreamLookupMetaTest.java
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInject.java

[PDI-16472] Oracle bulk loader is not working with metadata injection (ArrayIndexOutOfBoundsException)
[PDI-16349] Metadata Injection for Insert/Update step get IndexOutOfBoundsException error
[PDI-16110] java.lang.ArrayIndexOutOfBoundsException exception with Metadata Injection step and Streamlookup step
[PDI-16423] Metadata Injection for String Replace step get IndexOutOfBoundsException error when not all the fields in the injection step are populated.
added AfterInjection annotation and implementation synchronization arrays lengths for consistency behavior with UI

[PDI-16472] [PDI-16349] [PDI-16110] [PDI-16423]

---

ui/src/org/pentaho/di/ui/core/database/dialog/XulDatabaseDialog.java

-  replaced the variable-aware fields with normal fields and removed the
variable indicators next to the fields

[SP-3705][PMD-679]-Variable symbols displaying in the database dialog; PME does not support variables

---

engine/src/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClassMeta.java
engine/test-src/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClassMetaTest.java

[SP-3707][PDI-13416] Adding a duplicate method in UDJC causes exception and crashes Spoon
added catching unchecked compilation error

[SP-3707][PDI-13416] Adding a duplicate method in UDJC causes exception and crashes Spoon

---

engine/src/org/pentaho/di/core/injection/AfterInjection.java
engine/src/org/pentaho/di/core/injection/bean/BeanInjector.java
engine/src/org/pentaho/di/trans/steps/insertupdate/InsertUpdate.java
engine/src/org/pentaho/di/trans/steps/insertupdate/InsertUpdateMeta.java
engine/src/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderMeta.java
engine/src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMeta.java
engine/src/org/pentaho/di/trans/steps/streamlookup/StreamLookupMeta.java
engine/test-src/org/pentaho/di/trans/steps/insertupdate/InsertUpdateMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderMetaTest.java
engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java
engine/test-src/org/pentaho/di/trans/steps/streamlookup/StreamLookupMetaTest.java
plugins/meta-inject-plugin/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInject.java

[SP3754][PDI-16472] Oracle bulk loader is not working with metadata injection (ArrayIndexOutOfBoundsException)
[PDI-16349] Metadata Injection for Insert/Update step get IndexOutOfBoundsException error
[PDI-16110] java.lang.ArrayIndexOutOfBoundsException exception with Metadata Injection step and Streamlookup step
[PDI-16423] Metadata Injection for String Replace step get IndexOutOfBoundsException error when not all the fields in the injection step are populated.
added AfterInjection annotation and implementation synchronization arrays lengths for consistency behavior with UI

[SP3754][PDI-16472] Oracle bulk loader is not working with metadata injection (ArrayIndexOutOfBoundsException)

---

engine-ext/api/src/main/java/org/pentaho/di/engine/api/events/SubTransCreationEvent.java
engine-ext/api/src/main/java/org/pentaho/di/engine/api/reporting/SubTransCreation.java
engine/src/main/java/org/pentaho/di/trans/ael/websocket/MessageEventService.java
engine/src/test/java/org/pentaho/di/trans/ael/websocket/MessageEventServiceTest.java

This will allow the subtrans running within AEL/Spark to bubble up to
logging to the Client just like it does in the kettle classic engine.

[BACKLOG-18612] Add functionality for subtrans logging within AEL/Spark

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/src/main/resources/kettle-variables.xml

Released resources to free up memory for the case when OOME occurs.
Introduced a new kettle property to allow user the choose old way vs new way (memory based vs file system based) during writing file to Amazon S3.

[PDI-13628]: "Read end dead" error when writing large file to Amazon S3 (OOME)

---

plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforceinsert/SalesforceInsert.java
plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsert.java
plugins/salesforce/core/src/test/java/org/pentaho/di/trans/steps/salesforceinsert/SalesforceInsertTest.java
plugins/salesforce/core/src/test/java/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsertTest.java

[PDI-16434]Salesforce Upsert (and possibly insert) fails when upserting an integer into account object
-fixing sending Pentaho Integer value to Salesforce (SalesforceInsert and SalesforceUpsert steps)

[PDI-16434]Salesforce Upsert (and possibly insert) fails when upserting an integer into account object

---

plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationImportExtensionPoint.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationImportExtensionPointTest.java

Changed to create run configuration with remote server info for cases when Run configuration does not exist for Transformation job entry but slave_server_name is specified.

[BACKLOG-18969] Transformations no longer run on carte after 7.1 upgrade

---

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java
core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

-fixed comparing binary values. Fix is based on PR https://github.com/pentaho/pentaho-kettle/pull/4026 by GavinHacker

[SP-3784][PDI-16455] Problem when comparing binary values

---

ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java

[BACKLOG-19122] Data Grid "java.lang.IllegalArgumentException: Index out of bounds" inserting several meta fields
was added calling cellFocusLost when it was focus was lost via keyboard

[BACKLOG-19122] Data Grid "java.lang.IllegalArgumentException: Index out of bounds" inserting several meta fields

---

ui/src/org/pentaho/di/ui/core/widget/TableView.java

[SP-3807][BACKLOG-19122] Data Grid "java.lang.IllegalArgumentException: Index out of bounds" inserting several meta fields
was added calling cellFocusLost when focus was lost via keyboard

[SP-3807][BACKLOG-19122] Data Grid "java.lang.IllegalArgumentException: Index out of bounds" inserting several meta fields

---

core/src/test/java/org/pentaho/di/core/encryption/KettleTwoWayPasswordEncoderTest.java

@pentaho/2-1b @smaring 
The removed code put stuff in `/tmp/vfs_cache` and didn't affect the tests at all.

[BACKLOG-17898] Stop unit test from touching the file system

---

ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

This fixes the issue: [PDI-14492] Copy Table Wizard_UI Issue.
The `page.createControl( shell )` will be called in `Wizard.createPageControls(Composite)`, so should not be called in `Spoon.copyTableWizard()`.

[PDI-14492] Copy Table Wizard_UI Issue

---

plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforce/SalesforceConnection.java
plugins/salesforce/core/src/test/java/org/pentaho/di/trans/steps/salesforce/SalesforceConnectionTest.java

PDI-16459 Salesforce Insert - sObject type 'string' is not supported
removed wrong using RelationshipName instead of Name
There are no one reasons for using RelationshipName:
1. Salesforce web service expects a value for name but not for RelationshipName. PDI-16459 will not work without parameter ParentId.
2. SalesforceInputDialog (input fields from Salesforce) don't use RelationshipName.  
It was fixed for SalesforceUpdate step and SalesforceInsert step.
After fixing.
It is necessary configure a correct mapping.
1. Edit "Salesforce Insert".
2. Press "Edit mapping".
3. After fix instead of "Parent" you will see correct name of the field "ParentId".
4. Run the transformation successfully.
Affected areas:
the same behavior for a step "Salesforce Update"
@bmorrise Could you please review and …

PDI-16459 Salesforce Insert - sObject type 'string' is not supported

---

ui/src/main/java/org/pentaho/di/ui/core/widget/TableView.java

[PDI-15268] PDI locks up when changing Job - Properties - Parameters.
added calculation wrong focus event (a workaround for SWT bug)

[PDI-15268] PDI locks up when changing Job - Properties - Parameters.

---

engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java

In PR https://github.com/pentaho/pentaho-kettle/pull/4292, the problem was basically fixed, except for a small place. 
Truncate statement shouldn't be returned as part of the copyCmd.

[PDI-16430] Delete truncate statement from getCopyCommand() function

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/mapping/MappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/simplemapping/SimpleMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/singlethreader/SingleThreaderMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
engine/src/main/resources/org/pentaho/di/trans/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/StepWithMappingMetaTest.java
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java

The issue concerns following steps: Mapping, SimpleMapping, JobExecutor,SingleThreader, TransExecutor, MetaInjectMeta. The problem was that we didn't set the specification method to "filename" when exporting using 'Linked resources to XML'.

[PDI-15891]-Problem running a zipped file with Pan.bat

---

plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforce/SalesforceStep.java
plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforceinsert/SalesforceInsert.java
plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforceupdate/SalesforceUpdate.java
plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsert.java
plugins/salesforce/core/src/test/java/org/pentaho/di/trans/steps/salesforce/SalesforceStepTest.java
plugins/salesforce/core/src/test/java/org/pentaho/di/trans/steps/salesforceinsert/PDI_10836_Test.java

[PDI-16480] Salesforce: Datetime fields are not being set with Pentaho 7.1 version
-added saving hh:mm:ss for saving datetime in Salesforce
-created one method with one rules for normalizing data for all Salesforce modify steps

[PDI-16480] Salesforce: Datetime fields are not being set with Pentaho 7.1 version

---

assemblies/pdi-ce/src/main/resources/spoon.command

- added license to the command file

[PSW-229] Script files don't have an header with Copyright data

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepositoryConnector.java

- fixed. Now user searching in the list of users

[PDI-16535]-Errors creating transformations and jobs when the user connects to Pentaho Repository using a different case of the user name created

---

ui/src/org/pentaho/di/ui/core/widget/TableView.java

[SP-3824][PDI-15268] PDI locks up when changing Job - Properties - Parameters.
added calculation wrong focus event (a workaround for SWT bug)

[SP-3824][PDI-15268] PDI locks up when changing Job - Properties - Parameters.

---

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforce/SalesforceConnection.java
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforce/SalesforceConnectionTest.java

[SP-3818][PDI-16459] Salesforce Insert - sObject type 'string' is not supported
removed wrong using RelationshipName instead of Name

[SP-3818][PDI-16459] Salesforce Insert - sObject type 'string' is not supported

---

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceinsert/SalesforceInsert.java
plugins/salesforce/src/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsert.java
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceinsert/SalesforceInsertTest.java
plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsertTest.java

[SP-3806][PDI-16434]Salesforce Upsert (and possibly insert) fails when upserting an integer into account object
-fixing sending Pentaho Integer value to Salesforce (SalesforceInsert and SalesforceUpsert steps)

[SP-3806][PDI-16434]Salesforce Upsert (and possibly insert) fails when upserting an integer into account object

---

ui/src/org/pentaho/di/ui/spoon/Spoon.java

- The page.createControl( shell ) will be called in Wizard.createPageControls(Composite), so should not be called in Spoon.copyTableWizard()

[SP-3812] Backport of PDI-14492 - Copy Table Wizard_UI Issue

---

engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/core/EngineMetaInterface.java
engine/src/test/java/org/pentaho/di/base/AbstractMetaTest.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/SpoonSlave.java
ui/src/test/java/org/pentaho/di/ui/spoon/SpoonTest.java

[PDI-16684] Every click on the PDI UI sending a request to the Pentaho Server
cache was added for versioningConfiguration property
It is not necessary to check VersioningEnabled on the server every time.
The property versioningConfiguration depends on files
server/pentaho-server/pentaho-solutions/system/ImportHandlerMimeTypeDefinitions.xml
server/pentaho-server/pentaho-solutions/system/repository.spring.properties
Live changes in these files are not supported. If we make changes in these files it doesn't change behavior without pentaho-server restart. So we don't need rechecked this property in server every time. It is enough to check it one time.
@bmorrise Could you please review and merge it?

[PDI-16684] Every click on the PDI UI sending a request to the Pentaho Server

---

core/src/main/java/org/pentaho/di/cluster/HttpUtil.java
core/src/main/java/org/pentaho/di/core/logging/KettleLogStore.java
core/src/main/java/org/pentaho/di/core/logging/LoggingBuffer.java
core/src/main/java/org/pentaho/di/core/xml/XMLHandlerCache.java
core/src/test/java/org/pentaho/di/cluster/HttpUtilTest.java
core/src/test/java/org/pentaho/di/core/logging/LoggingBufferTest.java
engine/src/main/java/org/pentaho/di/www/GetJobStatusServlet.java
engine/src/main/java/org/pentaho/di/www/GetTransStatusServlet.java
engine/src/main/java/org/pentaho/di/www/PrepareExecutionTransServlet.java
engine/src/main/java/org/pentaho/di/www/RemoveJobServlet.java
engine/src/main/java/org/pentaho/di/www/RemoveTransServlet.java
engine/src/main/java/org/pentaho/di/www/StartJobServlet.java
engine/src/main/java/org/pentaho/di/www/StartTransServlet.java
engine/src/main/java/org/pentaho/di/www/cache/CachedItem.java
engine/src/main/java/org/pentaho/di/www/cache/CarteStatusCache.java
engine/src/test/java/org/pentaho/di/www/GetJobStatusServletTest.java
engine/src/test/java/org/pentaho/di/www/GetTransStatusServletTest.java
engine/src/test/java/org/pentaho/di/www/cache/CarteStatusCacheTest.java
ui/src/main/java/org/pentaho/di/ui/spoon/SpoonSlave.java

-Optimized LoggingBuffer( by using concurrent collections and streams)
-Implemented local-temp-file cache for keeping statuses of stopped or finished transformations or jobs which significantly decreases carte response time and cpu usage ( especially for medium and large logs)
-The saved log content will be alive during specified by user properties in kettle.properties ( By default 1 day)
-The changes remove restrictions to saving limited number of logs ( It was 5000 lines by default before ) since statuses are saved as temp files, not in memory
-Optimized SpoonSlave:
-Disabled excess events( which requested ktr/kjb status many times at one moment )
-Fixed memory leak. SpoonSlave saved all the carte ktr/kjbs logs in map (id,log) and never cleared it( even if it was removed ) . In case of …

[PDI-2301]-Slave server monitor refresh freezes Spoon

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/loadfileinput/LoadFileInputDialog.java

- wrong logic was fixed
- the issue with the absence of the prompt for save for all checkboxes on the content tab was also fixed

[PDI-16074] "Load file content in memory" step does not output additional filename field

---

engine/src/main/java/org/pentaho/di/trans/steps/loadfileinput/LoadFileInput.java

- Array Out Of Bounds Exception was fixed
- error message was translated into English

[PDI-13264] load file content in memory step errors when filename is defined in field

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/mapping/Mapping.java
engine/src/main/java/org/pentaho/di/trans/steps/simplemapping/SimpleMapping.java
engine/src/main/java/org/pentaho/di/trans/steps/simplemapping/SimpleMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/singlethreader/SingleThreader.java
engine/src/main/java/org/pentaho/di/trans/steps/singlethreader/SingleThreaderMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java
engine/src/test/java/org/pentaho/di/trans/StepWithMappingMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/mapping/MappingParametersTest.java
engine/src/test/java/org/pentaho/di/trans/steps/transexecutor/TransExecutorUnitTest.java

-fixed a broken option "Inherit all variables from the transformation"
-extracted a common behavior for activation params in one methods for children of StepWithMappingMeta
-overwriting parameters and the next logic
When the child parameter does not exist in the parent parameters, keep it.
When the child parameter does exist in the parent parameters, overwrite the child parameter by the parent parameter.
All other parent parameters need to get copied into the child parameters  (when the 'Inherit all variables from the transformation?' option is checked)
@bmorrise Could you please review and merge it?

[PDI-16066] Transformation Executor Step does not Inherit Parameters

---

engine/src/main/java/org/pentaho/di/trans/steps/sftpput/SFTPPut.java

- SFTPPut step was modified in order to work with input stream as with binary array

[PDI-14250] SFTP Put step corrupts file data when "Input is a stream" option is used

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/repository/HasRepositoryDirectories.java
engine/src/main/java/org/pentaho/di/repository/RepositoryImporter.java
engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/test/java/org/pentaho/di/repository/RepositoryImporterTest.java
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java

Issues with several steps during exporting - importing in an EE repository : directories are not updated properly. 
-Removed hardcoded step name checks (like stepMeta.isMapping() or stepMeta.isTransformation() ) which identify whether we should update step inner directories or not 
-Added interface which means that a step has directory(ies) to another transformations(jobs)
Affected by the issue steps : JobEntryJob, JobEntryTrans, Mapping, SimpleMapping, SingleThreader, TransExecutor, JobExecutor, Metainject, Pentaho MapReduce

[PDI-16436]- Issues with 3 steps when exporting - importing in an EE repository

---

engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/test/java/org/pentaho/di/trans/TransMetaTest.java

- added a getCacheVersion method to the TransMeta class responsible for calculating the cache version considering only the relevant transformation properties

[BACKLOG-20407] - Replace cache version creation

---

engine/pom.xml
engine/src/main/java/org/pentaho/di/trans/streaming/api/StreamSource.java
engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStep.java
engine/src/main/java/org/pentaho/di/trans/streaming/common/BlockingQueueStreamSource.java
engine/src/test/java/org/pentaho/di/trans/streaming/common/BlockingQueueStreamSourceTest.java
plugins/file-stream/src/main/java/org/pentaho/di/trans/step/filestream/FileStream.java
plugins/file-stream/src/main/java/org/pentaho/di/trans/step/filestream/TailFileStreamSource.java
plugins/file-stream/src/test/java/org/pentaho/di/trans/step/filestream/FileStreamTest.java

Groundwork.  Created a BlockingQueueStreamSource base
implementation to handle pause/resume and creation of
a blocking iterable.
Also moved some more common logic up to BaseStreamStep.
Remaining to do-  moving logger messages into a resource.
That will come in a follow up commit.

[BACKLOG-20210] MQTT- create PDI Consumer Step

---

engine/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSum.java
engine/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSumMeta.java
engine/src/main/resources/org/pentaho/di/trans/steps/checksum/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumTest.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/checksum/CheckSumDialog.java

- added new logic for the binary data checksum generation
- added new compatibility flag "Old Checksum Behaviour Mode"
- added new checkbox on the "Add Checksum" step UI
- regression with the wrong field checksum calculation was fixed
- new tests were created

[PDI-16809|PDI-16812|PDI-16824] Add a checksum - generates wrong checksum

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/test/java/org/pentaho/di/job/entries/job/JobEntryJobTest.java
engine/src/test/java/org/pentaho/di/job/entries/trans/JobEntryTransTest.java
engine/src/test/java/org/pentaho/di/trans/StepWithMappingMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMetaTest.java
plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/autodoc/AutoDocMeta.java
plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java
plugins/meta-inject/src/test/java/org/pentaho/di/trans/steps/metainject/MetaInjectMetaTest.java

- deprecated variables have been changed to ${Internal.Entry.Current.Directory}
- unit-tests for exportResources have been added

[PDI-16786] Export linked resources uses deprecated variables

---

plugins/salesforce/core/src/main/java/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsert.java
plugins/salesforce/core/src/test/java/org/pentaho/di/trans/steps/salesforceupsert/SalesforceUpsertTest.java

[PDI-16857] External Id doesn't work in the step Salesforce upsert.
- fixed sending Foreign key for Salesforce upsert step

[PDI-16857] External Id doesn't work in the step Salesforce upsert.

---

engine/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSum.java
engine/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSumMeta.java
engine/src/main/resources/org/pentaho/di/trans/steps/checksum/messages/messages_en_US.properties
engine/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumTest.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/checksum/CheckSumDialog.java

[SP-4022] Backport of PDI-16824 - The sample "Add a checksum - basic CRC32" does not work in 8.0 if you delete a field (8.0 Suite)

---

plugins/salesforce/core/src/main/java/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java

[SP-4066][PDI-16805] Salesforce Input doesn't get the transformation status 'changed'
- added status 'changed' when button 'Get fields' is pressed
- added status 'changed' for checkboxes of tab Content if they are changed

[SP-4066][PDI-16805] Salesforce Input doesn't get the transformation status 'changed'

---

ui/src/main/java/org/pentaho/di/ui/trans/dialog/TransLoadProgressDialog.java

[PDI-16833] Invalid thread access error when opening a transformation, containing steps of missing plugins, from a repository
-fixed SWTException: Invalid thread access

[PDI-16833] Invalid thread access error when opening a transformation, containing steps of missing plugins, from a repository

---

engine/src/main/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariables.java
engine/src/test/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java

[PDI-16387] Running a Job for Every Input Row, sub job does not reset variables or parameters with every execution
added recovering changed values of variables if we use VARIABLE_TYPE_CURRENT_JOB

[PDI-16387] Running a Job for Every Input Row, sub job does not reset variables or parameters with every execution

---

engine/src/main/resources/org/pentaho/di/trans/steps/replacestring/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/trans/steps/replacestring/ReplaceStringDialog.java

Additionally, localized the "Is Unicode" column name within the "Replace in string" step
@pentaho/r2d2

[BACKLOG-20681] The 'ETL Meta Injection' step is missing a 'Target description' for the 'Replace in string' IS_UNICODE field

---

engine/src/main/java/org/pentaho/di/core/logging/BaseLogTable.java

To assure that "lost values values" aren't assign to variables connectionName, schemaName and tableName even if the connectionNameFromRepository, schemaNameFromRepository and tableNameFromRepository return null values.
This "lost values values" might happen in between saving a job/transformation to repository, closing and open it again.
The "lost value values" are default parameters that might come from server side settings in between saving and open the job/transformation (if the connectionName, schemaName and tableName variables haven't been assign previously).
@duarteteixeira @pamval

[PDI-16858] - Log connection is set to "live_logging_info" on Transformation and Job logging

---

core/src/main/java/org/pentaho/di/core/logging/Slf4jLoggingEventListener.java
core/src/test/java/org/pentaho/di/core/logging/Slf4jLoggingEventListenerTest.java

...while logging is in-flight.
When viewing a referenced subtrans object, if you close the tab
it causes the object to be deregistered, which was formerly causing
an NPE in Slf4LoggingEventListener when a log event is received
for the no-longer registered object.

[BACKLOG-21239] Adding support for case where log object deregistered

---

core/pom.xml
core/src/main/java/org/pentaho/di/core/logging/KettleLogStore.java
core/src/main/java/org/pentaho/di/core/logging/LoggingBuffer.java
core/src/test/java/org/pentaho/di/concurrency/ConcurrencyTestRunner.java
core/src/test/java/org/pentaho/di/concurrency/ExecutionResult.java
core/src/test/java/org/pentaho/di/concurrency/LoggingBufferConcurrencyTest.java
core/src/test/java/org/pentaho/di/concurrency/StopOnErrorCallable.java
core/src/test/java/org/pentaho/di/core/logging/LoggingBufferTest.java
engine/pom.xml

configuration Clusterd & never ends
- replaced LinkedBlockingDeque with a plain ArrayList defended by
ReadWriteLock, as LBD is not fully thread-safe due to bug in JDK.
Also, LBD does not seem to be the right collection for LoggingBuffer
(for exmaple, even though it is backed by linked list, iterator.remove
runs in a linear time).
- added concurrent test for logging buffer
- moved ConcurrentTestRunner utility to the core module
- added test jar to core module to be used by engine module, since it still needs
ConcurrentTestRunner

[BACKLOG-21008] Yarn job hangs in Transformation step set with run

---

engine/src/main/java/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaInjectionTest.java

[PDI-16932] Specifying the Select Fieldname in the Metadata Injectionstep does not give correct results.
added default value for default values for length and precision

[PDI-16932] Specifying the Select Fieldname in the Metadata Injectionstep does not give correct results.

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/test/java/org/pentaho/di/job/entries/trans/JobEntryTransTest.java
engine/src/test/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorTest.java

[PDI-16844] The step Job Executor should overwrite the child parameter by the parent parameter.
Overwriting parameters and the next logic:
1. When the child parameter does not exist in the parent parameters, keep it.
2. When the child parameter does exist in the parent parameters, overwrite the child parameter by the parent parameter.
3. All other parent parameters need to get copied into the child parameters (when the 'Inherit all variables from the transformation?' option is checked)

[PDI-16844] The step Job Executor should overwrite the child parameter by the parent parameter.

---

engine/src/main/java/org/pentaho/di/core/util/SerializationHelper.java
engine/src/main/java/org/pentaho/di/core/util/serialization/BaseSerializingMeta.java
engine/src/main/java/org/pentaho/di/core/util/serialization/MetaXmlSerializer.java
engine/src/main/java/org/pentaho/di/core/util/serialization/README.md
engine/src/main/java/org/pentaho/di/core/util/serialization/RepoSerializer.java
engine/src/main/java/org/pentaho/di/core/util/serialization/Sensitive.java
engine/src/main/java/org/pentaho/di/core/util/serialization/StepMetaProps.java
engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMeta.java
engine/src/test/java/org/pentaho/di/core/util/serialization/MetaXmlSerializerTest.java
engine/src/test/java/org/pentaho/di/core/util/serialization/RepoSerializerTest.java
engine/src/test/java/org/pentaho/di/core/util/serialization/StepMetaPropsTest.java
engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepMetaTest.java

**StepMetaProps** - a slim "holder" for stepmeta properties
**JAXBMetaSerializer** - reads and writes StepMetaProps as XML using JAXB
**RepoSerializer** - reads and writes StepMetaProps to a repository.
To serialize XML within a StepMetaInterface implementation, the call
is:
` JAXBMetaSerializer.serialize( StepMetaProps.from( myMeta ) )`
For deserialization:
` JAXBMetaSerializer.deserialize( xml ).to( myMeta )`
Repo writes/reads use
```
RepoSerializer
.builder()
.repo( repo )
.stepMeta( stepMeta )
.stepId( stepId )
.transId( transId )
.serialize()   /  .deserialize()
```

[BACKLOG-21249] Classes for generically handling stepmeta serialization

---

engine/src/main/java/org/pentaho/di/core/util/serialization/RepoSerializer.java

They can be null during repo save operations.

[BACKLOG-21866] Removing nonNull requirement for trans and step objid

---

plugins/xml-input-stream/pom.xml
plugins/xml/pom.xml

The property exists but it's not used in this or any child project.
Related PRs:
https://github.com/pentaho/pentaho-det-ee/pull/530
https://github.com/pentaho/pentaho-det/pull/1142
https://github.com/pentaho/pentaho-ee/pull/1066

[BACKLOG-19695][CLEANUP] Remove unused property for commons-vfs2 version

---

engine/src/main/java/org/pentaho/di/core/injection/bean/BeanInjector.java
engine/src/main/java/org/pentaho/di/core/util/serialization/README.md
engine/src/main/java/org/pentaho/di/core/util/serialization/StepMetaProps.java
engine/src/test/java/org/pentaho/di/core/util/serialization/StepMetaPropsTest.java

serialization.
This will allow embedding objects in JmsConsumer meta objects for
better reuse.

[BACKLOG-21800] Adding support for @InjectionDeep to StepMetaProps

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/context/WrappedWebsphereMQProvider.java
plugins/streaming/impls/jms/src/main/resources/OSGI-INF/blueprint/blueprint.xml
plugins/streaming/impls/jms/src/main/resources/org/pentaho/di/trans/step/jms/messages/messages_en_US.properties

WrappedWebpshereMQProvider is used to prevent blueprint
from failing with ClassNotFound when loading the
WebsphereMQProvider, since that class directly references
IBMMQ classes which may not be available.
Also makes it possible to give a message for users to
check whether they've installed the IBMMQ jars, comparable
to the older version of the jms plugin.

[BACKLOG-21800] JMS Consumer - Changes for blueprint load

---

core/pom.xml
plugins/google-analytics/core/pom.xml
plugins/gpload/pom.xml
plugins/json/core/pom.xml
plugins/openerp/pom.xml
plugins/pentaho-googledrive-vfs/core/pom.xml
plugins/repositories/core/pom.xml

**Warning:** To be merged together with all other projects that need this change, **please do not merge** until then 
**This PR relates to:**
https://github.com/pentaho/pentaho-commons-database/pull/152
https://github.com/pentaho/apache-vfs-browser/pull/42
https://github.com/pentaho/data-access/pull/992
https://github.com/pentaho/mondrian/pull/1033
https://github.com/pentaho/pdi-jms-plugin/pull/53
https://github.com/pentaho/pdi-platform-utils-plugin/pull/92
https://github.com/pentaho/pdi-sap-hana-bulk-loader-plugin/pull/76
https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/39
https://github.com/pentaho/big-data-plugin/pull/1340
https://github.com/pentaho/pentaho-cassandra-plugin/pull/106
https://github.com/pentaho/pentaho-data-mining/pull/15 …

[BACKLOG-19695] Update commons-vfs2 artifact version from 2.1 to 2.2

---

engine/src/main/java/org/pentaho/di/core/changed/ChangedFlag.java

There is no point to have the synchronized on deleteObserver and hasChanged, it isn't doing nothing. The list and the boolean are already thread safe.
@mbatchelor

[PDI-8933] - ChangedFlag - race/deadlock condition possible

---

engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java

This is the cherry-pick of the fix for [PDI-16927]: PostgreSQL Bulk Loader : "DB Name Override" option is not working as expected.

[SP-4180]: Backport of PDI-16927 - PostgreSQL Bulk Loader : "DB Name Override" option is not working as expected (8.0 Suite).

---

ui/src/main/java/org/pentaho/di/ui/trans/dialog/TransLoadProgressDialog.java

[SP-4159][PDI-16833] Invalid thread access error when opening a transformation, containing steps of missing plugins, from a repository
-fixed SWTException: Invalid thread access

[SP-4159][PDI-16833] Invalid thread access error when opening a transformation, containing steps of missing plugins, from a repository

---

engine/src/main/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariables.java
engine/src/test/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java

[SP-4165][PDI-16387] Running a Job for Every Input Row, sub job does not reset variables or parameters with every execution
added recovering changed values of variables if we use VARIABLE_TYPE_CURRENT_JOB

[SP-4165][PDI-16387] Running a Job for Every Input Row, sub job does not reset variables or parameters with every execution

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java
engine/src/test/java/org/pentaho/di/job/entries/trans/JobEntryTransTest.java
engine/src/test/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutorTest.java

[SP-4220][PDI-16844] The step Job Executor should overwrite the child parameter by the parent parameter.
Overwriting parameters and the next logic:
1. When the child parameter does not exist in the parent parameters, keep it.
2. When the child parameter does exist in the parent parameters, overwrite the child parameter by the parent parameter.
3. All other parent parameters need to get copied into the child parameters (when the 'Inherit all variables from the transformation?' option is checked)

[SP-4220][PDI-16844] The step Job Executor should overwrite the child parameter by the parent parameter.

---

engine/src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariables.java
engine/test-src/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java

[SP-4164][PDI-16387] Running a Job for Every Input Row, sub job does not reset variables or parameters with every execution
added recovering changed values of variables if we use VARIABLE_TYPE_CURRENT_JOB

[SP-4164][PDI-16387] Running a Job for Every Input Row, sub job does not reset variables or parameters with every execution

---

engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java
engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaInjectionTest.java

[SP-4209][PDI-16932] Specifying the Select Fieldname in the Metadata Injection step does not give correct results.
added default value for default values for length and precision

[SP-4209][PDI-16932] Specifying the Select Fieldname in the Metadata Injection step does not give correct results.

---

engine/src/main/java/org/pentaho/di/cluster/SlaveServer.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/java/org/pentaho/di/www/GetTransStatusServlet.java
engine/src/main/java/org/pentaho/di/www/SlaveServerTransStatus.java
engine/src/test/java/org/pentaho/di/www/SlaveServerTransStatusTest.java

[PDI-17061] "Get rows from result" step does not pass rows when a transformation is executed on a remote carte server
added possibility to add result to XML when it needs

[PDI-17061] "Get rows from result" step does not pass rows when a transformation is executed on a remote carte server

---

engine/src/org/pentaho/di/trans/StepWithMappingMeta.java

[SP-4219][PDI-16844] Steps Job Executor and Transformation should overwrite the child parameter by the parent parameter.
- correction for case when mapping Variables is null. JobEntryTrans has parameters == null, when it was created not from UI.

[SP-4219][PDI-16844] Steps Job Executor and Transformation should overwrite the child parameter by the parent parameter.

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java

[SP-4220][PDI-16844] Steps Job Executor and Transformation should overwrite the child parameter by the parent parameter.
- correction for case when mapping Variables is null. JobEntryTrans has parameters == null, when it was created not from UI.

[SP-4220][PDI-16844] Steps Job Executor and Transformation should overwrite the child parameter by the parent parameter.

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java

[PDI-16844] Steps Job Executor and Transformation should overwrite the child parameter by the parent parameter.
- correction for case when mapping Variables is null. JobEntryTrans has parameters == null, when it was created not from UI.

[PDI-16844] Steps Job Executor and Transformation should overwrite the child parameter by the parent parameter.

---

integration/pom.xml
plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputExternalResourceConsumer.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerTest.java

Additionally, fixing failing integration tests.
Related pentaho-metaverse PR: https://github.com/pentaho/pentaho-metaverse/pull/455
@pentaho/r2d2

[BACKLOG-21736] Adding input files for the case when JSON Input step file name is expressed in a field

---

core/src/main/java/org/pentaho/di/core/logging/LoggingRegistry.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/main/java/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClass.java
engine/src/main/java/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClassDef.java
engine/src/main/java/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClassMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/userdefinedjavaclass/UserDefinedJavaClassMetaTest.java

On PDI-16658, I advocate for actual re-writes of the code creating the issues in this case. The code is really broken. That said, these fixes are tactical and alleviate the massive performance slow-down, so they're valuable until such time as a sprint team can take up the task of re-implementation of the logging registry using a proper LRU cache and the observer (or possibly the visitor) pattern to make this area of PDI sane.

[PDI-16658] - Fixes for the effects of PDI-16658.

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java

[BACKLOG-22633] Set all step rows without errors backgrounds to white so that fixed step errors don't stay red on the step metrics table.

[BACKLOG-22633] Set all step rows without errors backgrounds to white so that fixed step errors don't stay red on the step metrics table.

---

engine/src/main/java/org/pentaho/di/base/AbstractBaseCommandExecutor.java
engine/src/main/java/org/pentaho/di/kitchen/KitchenCommandExecutor.java
engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java
engine/src/test/java/org/pentaho/di/kitchen/KitchenTest.java
engine/src/test/java/org/pentaho/di/pan/PanTest.java

@pentaho/rogueone please review
Under pentaho-kettle/engine:
- to trigger the execution of Kitchen-specific UTs and ITs and no others:
- `mvn clean verify -Dtest=KitchenTest -DrunITs -Dit.test=KitchenIT`
- to do the above and allow for source code attachment on executing test cases ( port 5005 ):
- `mvn clean verify -Dtest=KitchenTest -DrunITs -Dit.test=KitchenIT -Dmaven.failsafe.debug`
- to trigger the execution of Pan-specific UTs and ITs and no others:
- `mvn clean verify -Dtest=PanTest -DrunITs -Dit.test=PanIT`
- to do the above and allow for source code attachment on executing test cases ( port 5005 ):
- `mvn clean verify -Dtest=PanTest -DrunITs -Dit.test=PanIT -Dmaven.failsafe.debug`

[BACKLOG-22541] have params accept 'true' as well as the default 'yes'

---

engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/test/java/org/pentaho/di/trans/TransMetaTest.java

Caused by a change to TransMeta.getStepFields() (adc9506bd)
That change switched from checking the number of prev steps via
findNrPrevSteps() to doing a count on the results of
findPreviousSteps().  The new logic, however, also includes the “info”
steps, changing behavior and resulting in extra columns in output
for some types of steps.
To address, switched to the overload of findPreviousSteps which
excludes info steps.
https://jira.pentaho.com/browse/BACKLOG-20815

[BACKLOG-20815] Extra columns included in append data step.

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsProducer.java
plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/ui/JmsProducerDialog.java

[BACKLOG-22165] Set the jms property name column to use variables, and get the environment substitute for the property variables

[BACKLOG-22165] Set the jms property name column to use variables, and get the environment substitute for the property variables

---

plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilder.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducer.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilderTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSourceTest.java

When a bad username/password was used the error message wasn't being
caught correctly and displayed. Samething was happening for QOS. This
fix unifies the behavior between MQTT Producer and Consumer when an
error message occurs and disconnects the from the client as needed.

[BACKLOG-22805] Displaying MQTT Error messages appropriately

---

engine/src/main/java/org/pentaho/di/core/util/serialization/BaseSerializingMeta.java
engine/src/main/java/org/pentaho/di/core/util/serialization/StepMetaProps.java
engine/src/test/java/org/pentaho/di/core/util/serialization/StepMetaPropsTest.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilder.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducer.java
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSource.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTClientBuilderTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMetaTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTStreamSourceTest.java

2 commits.  First commit adds a method to BaseSerializingMeta that supports swapping environment variables in all strings within a meta.  This can be used as an all purpose way of setting env variables without needing to remember to handle them individually.  Second commit updates MQTT consumer / producer to use this new method.

[BACKLOG-22806] Variable substitution doesn't work with MQTT SSL params

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/ExcelInput.java

@pentaho/millenniumfalcon, @denisprotopopov and @mbatchelor please review.
Fixes regression introduced by PDI-16942 (https://github.com/pentaho/pentaho-kettle/pull/5014).
`fpis` **can** be null if `data.workbook` **is not null** when `getRowFromWorkbooks()` is called.
Note that PDI-16942 was backported to 8.0 (https://github.com/pentaho/pentaho-kettle/pull/5102) and 7.1 (https://github.com/pentaho/pentaho-kettle/pull/5115), so the regression probably is also present there.

[BACKLOG-22822] Fix NPE when disposing ExcelInput step

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

* Allow the conversion of a date-time object with nanosecond precision.

[PDI-11089] - Cannot sort preview data (NullPointerException )

---

plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MqttDialogSecurityLayout.java

[BACKLOG-21845] Grey out top left cell in disabled mqtt consumer/producer table by not selecting the cell after clearing the table.  TableView.clearAll() edits the top left cell in the table, so we do not call that method.

[BACKLOG-21845] Grey out top left cell in disabled mqtt consumer/producer table by not selecting the cell after clearing the table

---

engine/src/main/java/org/pentaho/di/job/entries/talendjobexec/JobEntryTalendJobExec.java
engine/src/test/java/org/pentaho/di/job/entries/talendjobexec/JobEntryTalendJobExecTest.java

[PDI-8929] JobEntryTalendJobExec has static hashmap classLoaderCache that is mutated without protection
- changed HashMap to ConcurrentHashMap

[PDI-8929] JobEntryTalendJobExec has static hashmap classLoaderCache that is mutated without protection

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java

[BACKLOG-22898] Change step metrics step number column meta to string to prevent sub step numbers from being cut off.

[BACKLOG-22898] Change step metrics step number column meta to string to prevent sub step numbers from being cut off

---

core/src/main/java/org/pentaho/di/i18n/GlobalMessageUtil.java
core/src/test/java/org/pentaho/di/i18n/GlobalMessageUtilTest.java

**Stats prior to this fix:**
`GlobalMessageUtil.getBundle() ....................... 473,847 ms`
`GlobalMessageUtil.calculateString() ................... 6,243 ms`
`GlobalMessageUtil.getActiveLocales() .................. 6,165 ms`
`GlobalMessageUtil.getLocaleString() ..................... 573 ms`
`GlobalMessageUtil.buildHashKey() ........................ 480 ms`
`GlobalMessageUtil.<clinit> .............................. 203 ms`
_Total build time: 10:38 min_
**Stats after the fix:**
`GlobalMessageUtil$GlobalMessageControl.newBundle() ...... 235 ms`
`GlobalMessageUtil.calculateString() ..................... 200 ms`
`GlobalMessageUtil.getActiveLocales() .................... 192 ms`
`GlobalMessageUtil.getBundle() ............................ 99 ms `
`GlobalMessageUtil.isMissingKey() …

[BACKLOG-22705][CLEANUP] GlobalMessageUtil optimizations and performance improvements

---

engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/test/java/org/pentaho/di/trans/TransMetaTest.java

- StreamLookupMeta should clone value metas before changing
Having introduced the caching of rowMetas, we observe that StreamLookupMeta fails to find a field it needs when a cache hit occurs. Because previously it already found and changed that field in rowMeta (due to its configuration). 
Before introducing step field cache, rowMeta was instantiated every time it was needed, and it was fine to change the field.
Now StreamLookupMeta should clone valueMetas before changing, as not to break cached objects.

[BACKLOG-23112] DET: many errors running test case "with SDR"

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java

[BACKLOG-24014] adding guards against null and incorrect data from the step metrics table

[BACKLOG-24014] adding guards against null and incorrect data from the step metrics table

---

engine/src/main/java/org/pentaho/di/job/entry/validator/JobEntryValidatorUtils.java
engine/src/main/java/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java
engine/src/main/java/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryTransDelegate.java
engine/src/main/java/org/pentaho/di/trans/steps/dimensionlookup/DimensionLookup.java
engine/src/main/java/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java
engine/src/main/java/org/pentaho/di/trans/steps/execprocess/ExecProcess.java
engine/src/main/java/org/pentaho/di/trans/steps/file/BaseFileInputMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/formula/Formula.java
engine/src/main/java/org/pentaho/di/trans/steps/ldapinput/LDAPConnection.java
engine/src/main/java/org/pentaho/di/trans/steps/mergerows/MergeRows.java
engine/src/main/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkDataOutput.java
engine/src/main/java/org/pentaho/di/trans/steps/reservoirsampling/ReservoirSampling.java
engine/src/main/java/org/pentaho/di/trans/steps/script/ScriptAddedFunctions.java
engine/src/main/java/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesAddedFunctions.java
engine/src/main/java/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java
engine/src/main/java/org/pentaho/di/trans/steps/tableinput/TableInputMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/terafast/TeraFast.java
engine/src/main/java/org/pentaho/di/trans/steps/univariatestats/UnivariateStats.java
engine/src/test/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheetTest.java
engine/src/test/java/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseTest.java
engine/src/test/java/org/pentaho/di/www/GetJobStatusServletTest.java
engine/src/test/java/org/pentaho/di/www/GetTransStatusServletTest.java

https://github.com/google/error-prone
Specifically, these 5 categories of errors:
[NullTernary] This conditional expression may evaluate to null, which will result in an NPE when the result is unboxed.
(see http://errorprone.info/bugpattern/NullTernary)
[ArrayToString] Calling toString on an array does not provide useful information
(see http://errorprone.info/bugpattern/ArrayToString)
[SizeGreaterThanOrEqualsZero] Comparison of a size >= 0 is always true, did you intend to check for non-emptiness?
(see http://errorprone.info/bugpattern/SizeGreaterThanOrEqualsZero)
[InfiniteRecursion] This method always recurses, and will cause a StackOverflowError
(see http://errorprone.info/bugpattern/InfiniteRecursion)
[DeadException] Exception created but not thrown
(see …

[CLEANUP] Fixing errors preventing ErrorProne compilation, + checkestyle

---

engine/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java

Contributed by the field SE organisation of Pentaho in EMEA.
Fixes problem where REST Client only uses one of the Application drop down content options, and always ignores Content-Type header. This fixes that. Tested against 8.0.0.0-R with Allegrograph SPARQL and N-Quad REST calls.
Without this fix you will only ever be able to send one of: text/plain, application/xml, applicatoin/json, octet stream, xhtml, form urlencoded, atom xml, svg xml, text xml.

[PDI-17215] Pentaho se rest content type fix

---

engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java

Fixing a regression introduced in PDI-16844. Including again the lost logic for fieldname parameters in JobExecutor: https://github.com/ppatricio/pentaho-kettle/blame/5682a8b08389bff683703af22f6af21f5cb41ded/engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java
@pentaho-lmartins @pamval @bmorrise @mbatchelor

[PDI-17303] Job Executor does not read parameter values from fields

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/uniquerows/UniqueRowsDialog.java

Fixed https://jira.pentaho.com/browse/BACKLOG-23973 for both Kettle and AEL by removing the error hops when the "Reject Duplicate Rows" is unselected.

[BACKLOG-23973] AEL - Inside Unique Row step,Ktr hangs if the Redirect duplicate row is unchecked but there is error handling step

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java
engine/src/test/java/org/pentaho/di/trans/StepWithMappingMetaTest.java

Fix to ensure the main rules validated by Jens:
-	In case of same parameters in parent, step and child, the value of step parameter prevails.
-	In case of same parameters in parent and child only, the value of parent parameter prevails.
Some code were removed since that logic is already granted at StepWithMappingMeta.java - loadMappingMeta (https://github.com/ppatricio/pentaho-kettle/blob/eb0e00c59188b0e4e6d62388f040e75a92532b70/engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java#L209)

[PDI-17362] Not possible pass a fixed value to a sub transformation

---

core/src/main/java/org/pentaho/di/core/ObjectLocationSpecificationMethod.java
core/src/main/java/org/pentaho/di/core/util/StringUtil.java
core/src/test/java/org/pentaho/di/core/util/StringUtilTest.java
engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/test/java/org/pentaho/di/job/entries/job/JobEntryJobTest.java
ui/src/main/java/org/pentaho/di/ui/job/entries/job/JobEntryJobDialog.java
ui/src/test/java/org/pentaho/di/ui/job/entries/job/JobEntryJobDialogTest.java

Maybe I went too far with the code changes, but there was some logic to handle use cases we should not be supporting. The new code makes much more sense to me while still running all possible configurations of `JobEntryJob` created prior to 7.0, namely, when it was possible to specify a child job by repository name, repository object id and file system filename.
Please review and let me know if you think we should be supporting any other use cases.
See use cases in the comment blocks [here](https://github.com/pentaho-lmartins/pentaho-kettle/blob/d24e413b66c7dab188d83ee8aab054ad6ac6949c/engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java#L369-L377) and [here](https://github.com/pentaho-lmartins/pentaho-kettle/blob/d24e413b66c7dab188d83ee8aab054ad6ac6949c/engine/src/main/jav …

[PDI-17278] Repository Job Fails Using Variable to Run Local Job

---

assemblies/core/client/pom.xml
assemblies/core/client/src/assembly/assembly.xml

- Adding "classic" PDI plugins ( via mounted-volumes ) is causing errors when being registered in pdi-core with
> ERROR (version 9.0.0.0-102, build 9.0.0.0-102 from 2018-07-04 10.16.57 by buildguy) : java.lang.ClassNotFoundException: org.pentaho.di.ui.
(...)
This is due to the fact that PDI plugins are ( sadly ) still tightly coupled to kettle-ui classes, which in turn are coupled to `swt` libs. 
So `data-integration/libswt` ( ~ 10 MB ) must continue on being bundled as part of pdi-core.
Also: removed unused / unneeded content from pdi-core's assembly process, namely
- `data-integration/Data Service JDBC Driver` ( ~ 13 MB )
- `data-integration/adaptive-execution` ( ~ 20 MB ) 
Should be merged alongside pdi-core-ee's assembly changes: https://github.com/pentaho/pentaho-ee/pull/1346 …

[BACKLOG-24046] Implement streamlined volume directory structure

---

ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGridDelegate.java

[BACKLOG-24014] Amqp Consumer bug fix for step metrics table, fill table even when contains empty row.

[BACKLOG-24014] Amqp Consumer bug fix for step metrics table, fill table even when contains empty row.

---

engine/src/main/java/org/pentaho/di/trans/steps/pentahoreporting/PentahoReportingOutput.java

* Backport of PDI-17293 - Pentaho Reporting Output: Paged HTML option throws error when selected as output processor (8.1 Suite)
(cherry picked from commit 86decbdd986e25245145cd48e60e7cbf14c23642)
@pentaho-lmartins , @ricardosilva88

[SP-4456] - Backport of PDI-17293 - Pentaho Reporting Output: Paged HTML option throws error when selected as output processor (8.1 Suite)

---

engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/core/EngineMetaInterface.java
engine/src/main/java/org/pentaho/di/core/injection/bean/BeanInjector.java
engine/src/main/java/org/pentaho/di/core/util/serialization/StepMetaProps.java
engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/trans/TransAdapter.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/main/java/org/pentaho/di/trans/step/BaseStep.java
engine/src/main/java/org/pentaho/di/trans/step/BaseStepData.java
engine/src/main/java/org/pentaho/di/trans/step/StepInterface.java
engine/src/main/java/org/pentaho/di/trans/steps/cubeinput/CubeInput.java
engine/src/main/java/org/pentaho/di/trans/steps/cubeinput/CubeInputMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/script/ScriptDummy.java
engine/src/main/java/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesModDummy.java
engine/src/main/java/org/pentaho/di/www/AddTransServlet.java
engine/src/main/java/org/pentaho/di/www/BaseJobServlet.java
engine/src/main/java/org/pentaho/di/www/ExecuteTransServlet.java
engine/src/main/java/org/pentaho/di/www/jaxrs/TransformationResource.java
engine/src/test/java/org/pentaho/di/core/util/serialization/MetaXmlSerializerTest.java
engine/src/test/java/org/pentaho/di/core/util/serialization/StepMetaPropsTest.java

and arrays.
This involves a change to BeanInjector.getPropVal, which now walks
down the full list of BeanLevelInfos, specially handling LIST and
ARRAY.
Also fixes a handful of compiler warnings, mostly involving missing
@override.
Files changed for injectiondeep support are just these 3:
BeanInjector
MetaXmlSerializerTest
StepMetaPropsTest
https://jira.pentaho.com/browse/BACKLOG-24617

[BACKLOG-24617] Adding support for serialization of InjectionDeep lists

---

engine/src/main/java/org/pentaho/di/trans/steps/http/HTTP.java
engine/src/test/java/org/pentaho/di/trans/steps/http/HTTPTest.java

HTTP Client step would not handle the content encoding if not specified in the response entity.
The value specified in the step dialog was never used in the code path.
@pamval @cravobranco @bmorrise @mbatchelor

[PDI-17336] HTTP Client step doesn't respect the encoding

---

assemblies/plugins/pom.xml

The metadata-injection de-OSGification process, while working fine on Spoon, is *not* working on AEL
In light of that - and given that there is no clear strategy yet on how non-OSGi kettle plugins ( that live outside kettle-engine ) can work on AEL - it’s safer to revert the changes done, and keep metadata-injection OSGified for the time being.
@pentaho/rogueone @kurtwalker @mdamour1976 @tmcsantos @hbfernandes 
To be merged alongside
- https://github.com/pentaho/pentaho-ee/pull/1457
- https://github.com/pentaho/pentaho-kettle/pull/5712
- https://github.com/pentaho/pentaho-karaf-assembly/pull/475
**Please hold off merging until there's a say so by @mdamour1976 or @kurtwalker**

Revert [BACKLOG-25015] Meta-inject - Move step to Kettle plugin system

---

core/src/main/java/org/pentaho/di/core/row/ValueDataUtil.java
engine/src/test/java/org/pentaho/di/core/row/ValueDataUtilTest.java

@bmorrise 
@mbatchelor 
https://docs.oracle.com/javase/8/docs/api/java/math/BigDecimal.html#divide-java.math.BigDecimal
https://docs.oracle.com/javase/8/docs/api/java/math/RoundingMode.html
https://docs.oracle.com/javase/8/docs/api/java/math/MathContext.html
Previously, MathContext was DECIMAL64 - "A MathContext object with a precision setting matching the IEEE 754R Decimal64 format, 16 digits, and a rounding mode of HALF_EVEN, the IEEE 754R default." which was causing problems with BigDecimals > 16 digits.

[PDI-17534] - Multiplying BigNumbers in calculator loses precision

---

engine/src/main/java/org/pentaho/di/trans/SlaveStepCopyPartitionDistribution.java
engine/src/test/java/org/pentaho/di/trans/SlaveStepCopyPartitionDistributionTest.java

The problem is that the DataService cache increases exponentially and the number of instances of RowMetaAndData in memory also increase with every change done. This was confirmed using Java VisualVM looking at the memory spent and heapdump. It was seen this exponential increase of RowMetaAndData.
The problem resides with the fact that the stored key in the cache relies on getCacheVersion() of TransMeta.java
The getCacheVersion() then relies on the hashCode each TransMeta member. The problem is that one of its members SlaveStepCopyPartitionDistribution did not have hashCode() implemented.
This caused that each run of the transformation would store everytime new RowMetaAndData even if no change was done in the Transformation.
implementing the missing hashCode in …

[PDI-17353] OutOfMemory exception while play with DET for Geo viz

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java

@pentaho-lmartins @mbatchelor @bmorrise @lucboudreau 
This issue was introduced in PDI-13987, which caused the inputRowMeta to be cloned for each row processed. It was then changed again to check for the outputfields lenght in BACKLOG-16118, which continues to clone the rowMeta for each row. This fix makes the code similar what it was in 6.1 before PDI-13987. 
The removal of the outputfields length check has no effect in the correction done in BACKLOG-16118 (meaning, the expected result still occurs).

[PDI-17577] Text File Output Step 2-5 Times Slower in V8.1 than V6.1

---

engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java

On the OS which has default character set other than UTF8, PGBulkloader may throw error of encoding issue.
In this patch, I fix above issue by encoding data string using PostgreSQL client encoding instead of OS default.

[PDI-17623] PGBulkLoader match client encoding automatically

---

engine/src/main/java/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java

Empty Cell creates an additional Object with null in the cells field.
Problem Scenario:
Consider an Excel (xlsx with POI Streaming) file with 5 columns.
Header1,Header2,Header3,Header4,Header5
Data11,Data12,Data13,Data14,Data15                      => cells arraylist holds 5 objects [Data11,Data12,Data13,Data14,Data15] =>Correct
Data21,Data22,,Data24,Data25                                 => cells arraylist holds 6 objects [Data21,Data22,null,null,Data24,Data25] =>Wrong
Solution:
undefinedColIndex must be incremented always.

[PDI-17644] - StaxPoiSheet.java creates additional object with null

---

engine/src/main/java/org/pentaho/di/trans/streaming/common/BaseStreamStep.java
engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepTest.java

Determination of the Current.Directory needs to account for resources
being exported for use on  a slave server.  Formerly we were
setting the variables for the meta before the correct Current directory
could be determined.
https://jira.pentaho.com/browse/BACKLOG-26249

[BACKLOG-26249] Kafka Consumer fails to load with "Send resources"

---

engine/src/main/java/org/pentaho/di/trans/streaming/common/BlockingQueueStreamSource.java
engine/src/test/java/org/pentaho/di/trans/streaming/common/BlockingQueueStreamSourceTest.java

We poll kafka records 1000 at a time, so this should leave enough buffer in case we've read rows from kafka before the rxjava window has been constructed

[BACKLOG-26378] - limiting streaming ReplayProcessor buffer size to 1000

---

core/src/main/java/org/pentaho/di/core/row/RowMeta.java
core/src/test/java/org/pentaho/di/core/row/RowMetaTest.java
engine/src/main/java/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/selectvalues/SelectValuesTest.java

repeated field names could arise after inserting or deleting value metas
select values not checking for conflicts when renaming

[BACKLOG-26374] steps creating field name conflicts

---

plugins/meta-inject/src/main/java/org/pentaho/di/ui/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java

Integration test related to this functionality is located within the pentaho-metaverse project. These tests are currently disabled due to an unfavorable dependency chain, but can be enabled and run locally.
Related PR: https://github.com/pentaho/pentaho-metaverse/pull/533

[BACKLOG-26444] Additional data lineage support for ETL Metadata Injection step

---

ui/src/main/java/org/pentaho/di/ui/trans/steps/synchronizeaftermerge/SynchronizeAfterMergeDialog.java

Important note - Variable substitution is already being done by the class. This just fixes up the UI: https://github.com/pentaho/pentaho-kettle/blob/master/engine/src/main/java/org/pentaho/di/trans/steps/synchronizeaftermerge/SynchronizeAfterMerge.java#L870

[PDI-15138] - Synchronize UI for commit size

---

core/src/main/java/org/pentaho/di/core/Const.java
plugins/s3csvinput/core/src/main/java/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputDialog.java
plugins/s3csvinput/core/src/main/java/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta.java
plugins/s3csvinput/core/src/test/java/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMetaNewInjectionTest.java
plugins/s3csvinput/core/src/test/java/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMetaTest.java

Partial revert of 5bc0e4b85473fa7f5fe8c7f595ee7fda60ec5d41 to bring back lost functionality, i.e. ability to specify AWS credentials within the step as requested in JIRA case.
By default, if you don't specify AWS credentials, Spoon will get credentials from the Amazon Default Credentials Provider Chain. If credentials are specified in the step, Spoon will use those (legacy behavior).
For legacy transformations with embedded credentials you now have the option to override those credentials and use the provider chain by setting the Kettle property `KETTLE_USE_AWS_DEFAULT_CREDENTIALS` to `Y`.
@rmansoor @mbatchelor @pentaho/tatooine

[PDI-17449] S3 CSV Input does not work after upgrade from 7.1 to 8.1

---

assemblies/core/static/src/main/resources/spoon.sh
assemblies/static/src/main/resources/spoon.sh

This affects Debian-based systems like Ubuntu 16.04 LTS

Fixed missing ldconfig error when running as unprivileged user PDI-17771

---

engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/job/JobMeta.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/test/java/org/pentaho/di/job/JobMetaTest.java
engine/src/test/java/org/pentaho/di/job/JobTest.java
engine/src/test/java/org/pentaho/di/trans/TransMetaTest.java
engine/src/test/java/org/pentaho/di/trans/TransTest.java

When we execute on a Carte Server, there´s no filename, since we load data from a block of xml and not from a file. Even more if we are not in a repository context, we also don't have the repository directory info. So the job was not running remotely because the internal variable directory logic didn't take this case in consideration. This logic was added.
@mbatchelor @lucboudreau

[PDI-17736] Job Runs Locally but not on a Carte server

---

plugins/streaming/impls/jms/src/main/java/org/pentaho/di/trans/step/jms/JmsStreamSource.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/JmsStreamSourceTest.java

need to wait for receive loop to finish before completing publishProcessor
rx Observable created multiple threads so that emitter.onNext was asyncronous before hitting the publisher.  that allowed time for the publisher to close before it got the last message sent.  removed in favor of a single thread for receive loop

j[BACKLOG-26905] - jms consumer might lose messages on safe stopping

---

core/src/main/java/org/pentaho/di/core/plugins/PluginRegistry.java
engine/src/main/java/org/pentaho/di/job/entry/JobEntryCopy.java

This is a race condition issue with 9 fails in 10 in my environment. The JobEntryType (of BuildModel for example) is not registered when we try to run it in Kitchen and the job ends unsuccessfully due to plugin missing. This PR complements that logic, providing a way of giving more time for that plugin registration process, instead of aborting the execution immediately.  A waitLimit flag is provided, preventing looping issues. Should this be a Const? Configured and visible to users?
This is a wait to get fix. Probably a more architectural approach is needed to ensure we have all plugins we need (or know at least they are already installed in Karaf and then wait for them to be active) before start running those objects in kitchen. But at the same time we should keep our code separated from …

[PDI-17622] Build Model step works fine in Spoon but fails from Kitchen

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java

@pentaho/tatooine @pentaho-lmartins 
@lucboudreau 
There was a condition to see if the BigInt is a Long (Type_Integer) or a BigDecimal (Type_BigNumber).
But a SQL BigInt is equivalent to a Java Long, and its max value is 9.223.372.036.854.775.807.

[PDI-17843] Lookup Step Output Metadata not set correctly in 8.2

---

engine/src/main/java/org/pentaho/di/trans/StepWithMappingMeta.java
engine/src/test/java/org/pentaho/di/trans/StepWithMappingMetaTest.java

The internal variables were always being replaced by parent meta. This PR excludes the JOB & TRANS internal variables from being replaced, keeping them correct in their own context.
@mbatchelor 
@mkambol  

[PDI-17652] Internal.Entry.Current.Directory not reporting correctly

---

plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xmloutput/XMLField.java
plugins/xml/core/src/main/java/org/pentaho/di/ui/trans/steps/xmloutput/XMLOutputDialog.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmloutput/XMLOutputTest.java

* [PDI-15575] Added in code to allow for default selection of the ContentType Enum if a user tries to add a ContentType that does not exist (or leaves it empty).
* [PDI-15575] Adding Test code to verify the getIfPresent default value is being set appropriately. Updating copyright years

[PDI-15575] XML Output Step - should allow developers to save and edit when step configuraton is incomplete

---

engine/src/main/java/org/pentaho/di/trans/steps/httppost/HTTPPOST.java
engine/src/main/java/org/pentaho/di/trans/steps/httppost/HTTPPOSTMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/httppost/HTTPPOSTMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/httppost/HTTPPOSTTest.java

An easy fix, inspired by the code already present in the `HTTP Client` step.
@pentaho/tatooine

[PDI-16411] HTTP Post step requires Encoding in PDI 7.1

---

assemblies/lib/pom.xml

Merge after https://github.com/pentaho/maven-parent-poms/pull/105.
@graimundo please review.

[BACKLOG-27567] Remove org.osgi.core version override

---

engine/src/main/java/org/pentaho/di/pan/Pan.java
engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java

Bringing in POC work from @pedrofvteixeira's branch to master.
Verified and tested locally, works as expected. PDI-Service's `/ktr` endpoint now takes two new parameters `resultSetStepName` and `resultSetCopyNumber`
@pentaho/rogueone

[BACKLOG-24264] PDI Service/Job supporting 'result-set' capability

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
core/pom.xml
plugins/engine-configuration/impl/pom.xml
plugins/file-open-save/pom.xml
plugins/get-fields/pom.xml
plugins/repositories/core/pom.xml

@graimundo and @Pancho7 please review.
Note that this targets pentaho:karaf_update, so wingman will not run. Our build pipeline will, when all related PRs are merged.
Needs [pentaho/maven-parent-poms#107](https://github.com/pentaho/maven-parent-poms/pull/107).

[BACKLOG-27577] Centralize karaf dependencies management

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
engine/src/main/java/org/pentaho/di/trans/steps/nullif/NullIfMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/datagrid/DataGrid_EmptyStringVsNull_Test.java
engine/src/test/java/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitter_EmptyStringVsNull_Test.java
engine/src/test/java/org/pentaho/di/trans/steps/ifnull/IfNullTest.java
engine/src/test/java/org/pentaho/di/trans/steps/nullif/NullIfMetaTest.java
engine/src/test/java/org/pentaho/di/trans/steps/regexeval/RegexEval_EmptyStringVsNull_Test.java
ui/src/test/java/org/pentaho/di/ui/core/dialog/EditRowsDialog_EmptyStringVsNull_Test.java

@pentaho-lmartins @pentaho/tatooine 
Two problems in the inconsistency of "Null If" step:
1 - The Kettle property KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL was saved in a static variable, causing that as soon as it was set, no further changes in the property were "seen", unless PDI was restarted.
2 - The value to turn to null in the "Null if" step if it was set to "" (empty string) was always interpreted as null, although the KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL was set to "Y".

[PDI-17588] null if step is not working consistently

---

core/pom.xml
core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/main/resources/org/pentaho/di/core/vfs/providers.xml
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
plugins/google-analytics/core/pom.xml
plugins/gpload/pom.xml
plugins/json/core/pom.xml
plugins/openerp/pom.xml
plugins/pentaho-googledrive-vfs/core/pom.xml
plugins/repositories/core/pom.xml
pom.xml

@pentaho/tatooine @pentaho-lmartins @ssamora @wseyler 
* [PDI-17775] Updated providers to point to new HTTP 4 scheme.
* [PDI-17775] Updated poms to use the new commons-vfs2 and httpclient dependencies.
* [PDI-17775] Updated KettleVFS to force set the VFS Manager, so we use our own instead of the default stored in the commons-vfs2 dependency.
* [PDI-17775] Fixing test issues with upgrade
This is a multi-pull request:
- #6316 
- pentaho/pentaho-osgi-bundles#315

[PDI-17775] Process Files step no longer supports HTTP scheme

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java

The problem was on the calculation of the 'writingToFileForFirstTime' variable: it's value was inverted!
Fixed some tests and, on the ones that had processing, I've unmocked methods to guarantee that the newly fixed code was called.
@ssamora @pentaho-lmartins @pentaho/tatooine

[BACKLOG-28007] "Get files from result" Step Is Not Returning The Files

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

@pentaho/tatooine @pentaho-lmartins 
@mbatchelor @lucboudreau 
Using MySQL, the ResultSet was returning an invalid COLUMN_SIZE ( Pentaho length ) of 22.

[PDI-17935] Dimension lookup / update step - Data type error:

---

engine/src/main/java/org/pentaho/di/trans/steps/infobrightoutput/InfobrightLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoader.java
engine/src/main/java/org/pentaho/di/trans/steps/terafast/TeraFast.java
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_en_US.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_es_AR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_fr_FR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_it_IT.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_ja_JP.properties
engine/src/main/resources/org/pentaho/di/trans/steps/infobrightoutput/messages/messages_ko_KR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_en_US.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_fr_FR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_it_IT.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_ja_JP.properties
engine/src/main/resources/org/pentaho/di/trans/steps/ivwloader/messages/messages_ko_KR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_en_US.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_fr_FR.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_it_IT.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_ja_JP.properties
engine/src/main/resources/org/pentaho/di/trans/steps/terafast/messages/messages_ko_KR.properties
engine/src/test/java/org/pentaho/di/trans/steps/infobrightoutput/InfobrightLoaderTest.java
engine/src/test/java/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseTest.java
engine/src/test/java/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoaderTest.java
engine/src/test/java/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java
engine/src/test/java/org/pentaho/di/trans/steps/pgbulkloader/PGBulkLoaderTest.java
engine/src/test/java/org/pentaho/di/trans/steps/terafast/TeraFastTest.java

@pentaho/tatooine  @ssamora @pentaho-lmartins 
* [PDI-17481] Adding in tests for Infobright, MonetDB, TeraFast plugins. Adding in functions to check for Database Connections and ensuring they're not null, added messages for IngresVectorwise. Added messages from previously written message files (MySQLBulkLoader Messages)
* [PDI-17481] Code adjustments. Refactoring use of verification of data
* [PDI-17481] Updating imports
* [PDI-17481] Making PR Comment adjudication: Updated tests to force failure, import cleanup, fix postgres issue

[PDI-17481] Some steps of Bulk loading return NPE if previous steps have no rows

---

plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSum.java
plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSumData.java
plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/checksum/CheckSumMeta.java
plugins/core/impl/src/main/resources/org/pentaho/di/trans/steps/checksum/messages/messages_en_US.properties
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumMetaInjectionTest.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumMetaTest.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/checksum/CheckSumTest.java
plugins/core/ui/src/main/java/org/pentaho/di/ui/trans/steps/checksum/CheckSumDialog.java
plugins/core/ui/src/main/resources/org/pentaho/di/ui/trans/steps/checksum/messages/messages_en_US.properties

- Cleans up step processRow into single codepath
- Allows nulls to be in fields of New Behavior (does not update the digest)
- Added field separator option to step impl
- Added field separator option to step ui

PDI-17916 - CheckSum step cleanup and field separator

---

engine/src/main/java/org/pentaho/di/base/IParams.java
engine/src/main/java/org/pentaho/di/base/KettleConstants.java
engine/src/main/java/org/pentaho/di/base/Params.java
engine/src/main/java/org/pentaho/di/kitchen/JobParams.java
engine/src/main/java/org/pentaho/di/kitchen/Kitchen.java
engine/src/main/java/org/pentaho/di/kitchen/KitchenCommandExecutor.java
engine/src/main/java/org/pentaho/di/pan/Pan.java
engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java
engine/src/main/java/org/pentaho/di/pan/TransParams.java

`Pan` and `Kitchen` uses `PanCommandExecutor` and `KitchenCommandExecutor` and passes all the parameters it receives as individual `String`.  This PR introduces pojos that represents `JobParams` and `TransParams` and makes changes to `Pan` and `Kitchen` to use pojos instead.
@pentaho/rogueone 
After merging this PR,  https://github.com/pentaho/pentaho-ee/pull/1929 needs to be merged as well ( re-trigger wingman )

[CLEANUP] Use POJO from Pan and Kitchen to call it's corresponding CommandExecutors

---

assemblies/core/lib/pom.xml

[BACKLOG-27577] Add missing karaf main dependency to pdi core assembly

---

core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/main/java/org/pentaho/di/core/database/DatabaseInterface.java
core/src/main/java/org/pentaho/di/core/database/Exasol4DatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMeta.java
core/src/main/resources/kettle-database-types.xml
engine/src/main/java/org/pentaho/di/trans/steps/gettablenames/GetTableNames.java

Naming SNOWFLAKEHV to avoid collision with the Inquidia marketplace
plugin.
This plugin is mostly the same as the inquidia version with minor
corrections to DDL generation.
Also added  a supportsIndexes() method to the interface, with
snowflake and exasol being the only current dbs where this is false.
https://jira.pentaho.com/browse/BACKLOG-28164

[BACKLOG-28164]  New database type for Snowflake

---

core/src/main/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMeta.java

With the snowflake jdbc driver, .getTimestamp throws NPE when a Date
field has a NULL value.
https://jira.pentaho.com/browse/BACKLOG-28164

[BACKLOG-28164]  Addressing issue with NULL date vals using Snowflake

---

engine/src/main/java/org/pentaho/di/trans/steps/pentahoreporting/PentahoReportingOutput.java

New implementation of `ResourceData` and `ResourceLoader` for Apache VFS's `FileObject` would load resource of type `FileObject`
@tmorgner @pentaho/rogueone 
To be merged with https://github.com/pentaho/pentaho-reporting/pull/1248

[PDI-15742] Unable to load a prpt from the repository in the Pentaho Reporting Output step

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml

Removal of the Apache Derby version in favor of retrieving a unified version from the Maven parent POM. At the time of this PR, the latest version of Apache Derby is 10.15.1.3. Other PRs related to this one are listed below:
https://github.com/pentaho/maven-parent-poms/pull/122
https://github.com/pentaho/pentaho-platform/pull/4399
https://github.com/pentaho/pentaho-kettle/pull/6402
https://github.com/pentaho/pentaho-reporting/pull/1256
https://github.com/pentaho/data-access/pull/1053
**NOTE:** Should we also upgrade the derbyclient.version as well?

[BACKLOG-28357] Updates derby version, retrieved from parent POM

---

engine/src/main/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkDataOutput.java
engine/src/main/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkDataOutputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderTest.java

@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-15207] Adding in KettleVFS calls to the control/data file, and logs.  So it can handle the file:/// calls better
* [PDI-15207] Cleaned up method calls for getFileObject
* [PDI-15207] Cleaned up inputName retrieval, verified it can also use the internal variables per the ticket
* [PDI-15207] Added Tests, methods and new file.

[PDI-15207] Oracle Bulk Loader don't parse internal variable

---

core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/main/java/org/pentaho/di/core/database/DatabaseInterface.java
core/src/main/java/org/pentaho/di/core/database/MariaDBDatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/MySQLDatabaseMeta.java
core/src/main/resources/org/pentaho/di/core/database/messages/messages_en_US.properties
core/src/test/java/org/pentaho/di/core/database/MariaDBDatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/MySQLDatabaseMetaTest.java

@pentaho/tatooine @pentaho-lmartins @gryphendowre @wseyler
[PDI-17801] Moving MySQL logic from db class to db dialects
[PDI-17801] Adding unit tests for MariaDB legacy column feature
[PDI-17801] Adding unit tests for MySQL legacy column feature
[PDI-17801] Refactoring MariaDB and MySQL unit tests for legacy column name methods
[PDI-17801] Changing try catch block to match code style
[PDI-17801] Changing try catch code style

[PDI-17801] Different output fields of Table Input for MySQL and MariaDB driver

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/test/java/org/pentaho/di/job/entries/trans/JobEntryTransTest.java

Previously if the result rows were 0, the current result was not updated. In any other case the result was always updated.
This causes the error reported. 
I can't see any reason why not to update the result rows with zero rows if the result is zero.
I've runned all samples in kettle that had jobs and calls to transformations passing results.
Can you please review this? 
@pentaho-lmartins @bmorrise @mbatchelor @mkambol @lucboudreau

[PDI-17926] Copy Rows to Results: Clear Result Rows at initialization

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/JobDelegate.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/JobDelegateTest.java

The redshift bulk load dialog assumes that the parentjobmeta has been
set.  When loaded from the filesystem this was true, but not from
repo.  Issue was the jobentry was being added to its the list
of entries directly in JobDelegate, rather than via the
.addJobEntry() method.
https://jira.pentaho.com/browse/BACKLOG-28866

[BACKLOG-28866] Unable to edit redshift bulk job entry saved in repo

---

core/src/main/java/org/pentaho/di/core/database/RedshiftDatabaseMeta.java

[BACKLOG-28773] Add default timeout of 10 seconds to Redshift DB

---

core/src/main/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMeta.java
dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java

Adding a special case workaround in DataHandler which will
set warehouse as an "extra" option.  This will allow PRDs custom
metadata handling to capture the val.
https://jira.pentaho.com/browse/BACKLOG-29127

BACKLOG-29127  PRD - Snowflake warehouse value does not save when

---

core/src/main/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMeta.java
dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java

Adding a special case workaround in DataHandler which will
set warehouse as an "extra" option.  This will allow PRDs custom
metadata handling to capture the val.
https://jira.pentaho.com/browse/BACKLOG-29127
(cherry picked from commit 730f03973c07436fcb36a566b02300d99566cc96)
@kcruzada - validated on master (9.0-16).

[BACKLOG-29127]  PRD - Snowflake warehouse value does not save

---

core/src/main/java/org/pentaho/di/core/database/SnowflakeHVDatabaseMeta.java
dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java

Adding a special case workaround in DataHandler which will
set warehouse as an "extra" option.  This will allow PRDs custom
metadata handling to capture the val.
https://jira.pentaho.com/browse/BACKLOG-29127
(cherry picked from commit 730f03973c07436fcb36a566b02300d99566cc96)
@kcruzada - validated on master (9.0-16).

BACKLOG-29127  PRD - Snowflake warehouse value does not save

---

core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
ui/src/main/java/org/pentaho/di/ui/spoon/JobFileListener.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/spoon/TransFileListener.java

Master: https://github.com/pentaho/pentaho-kettle/pull/6572
8.3: https://github.com/pentaho/pentaho-kettle/pull/6587
8.3.0.0: https://github.com/pentaho/pentaho-kettle/pull/6586

[BACKLOG-29252] Connection name being passed as null instead of null

---

plugins/meta-inject/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInject.java

Reverts pentaho/pentaho-kettle#6637

[BACKLOG-29190] revert: Use the environment to determine the separator

---

plugins/core/impl/src/main/resources/org/pentaho/di/trans/steps/cubeinput/messages/messages_de_DE.properties
plugins/core/impl/src/main/resources/org/pentaho/di/trans/steps/cubeinput/messages/messages_es_ES.properties
plugins/core/impl/src/main/resources/org/pentaho/di/trans/steps/cubeinput/messages/messages_pt_BR.properties
plugins/core/impl/src/main/resources/org/pentaho/di/trans/steps/cubeinput/messages/messages_pt_PT.properties
plugins/core/ui/src/main/resources/org/pentaho/di/ui/trans/steps/cubeinput/messages/messages_de_DE.properties
plugins/core/ui/src/main/resources/org/pentaho/di/ui/trans/steps/cubeinput/messages/messages_es_ES.properties

Fixed *.properties files that had incorrect byte-encoding.

[BACKLOG-22191] Decouple cubeinput step from Kettle engine

---

engine/src/main/java/org/pentaho/di/trans/steps/mail/Mail.java
engine/src/test/java/org/pentaho/di/trans/steps/mail/MailTest.java

@pentaho/tatooine @pentaho-lmartins @wseyler 
* [PDI-13333] Making sure the mail.mime.charset is being set appropriately when sending emails. This allows special language characters to be preserved so that Email clients can translate them correctly.
* [PDI-13333] Add Test file

[PDI-13333] Send Mail Step does not handle multi-byte characters file attachment.

---

core/src/main/java/org/pentaho/di/core/plugins/BasePluginType.java
core/src/test/java/org/pentaho/di/core/plugins/BasePluginTypeTest.java

@pentaho/tatooine @wseyler @pentaho-lmartins 
* [PDI-17862] Cleaned up try/catch methods. Split it into 2, kept the original stack trace for the FileObject. Added in the try/catch as it's scanning each plugin jar, so that if an error occurs, it'll send a general error to the console and continue (if in debug mode, the full error gets printed)
* [PDI-17862] Added a test to verify that the try/catch allows a graceful log and continues to scan.

[PDI-17862] Spoon - Scan of plugin jars at startup does not handle exceptions gracefully

---

plugins/xml/core/src/main/java/org/pentaho/di/job/entries/xsdvalidator/JobEntryXSDValidator.java
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/xsdvalidator/XsdValidator.java
plugins/xml/core/src/main/resources/org/pentaho/di/job/entries/xsdvalidator/messages/messages_en_US.properties
plugins/xml/core/src/main/resources/org/pentaho/di/trans/steps/xsdvalidator/messages/messages_en_US.properties

Our version of xerces doesn't support JAXP 1.5. Earlier implementations of JAXP do not support ACCESS_EXTERNAL_DTD and ACCESS_EXTERNAL_SCHEMA properties. Thus, to block access to external entities, we need to write our own EntityResolver, by always throwing an IOException.
@pentaho-lmartins @ssamora

[PDI-17759] XSD Validator step and job entry are vulnerable to XXE hacks

---

ui/src/main/java/org/pentaho/di/ui/core/widget/ConditionEditor.java

This patch originally came from @Valeran86 to HiromuHota/pentaho-kettle as HiromuHota/pentaho-kettle#121 but I think it should be merged to the upstream.

[PDI-17656] Use internalization key instead of hardcode

---

engine/src/main/java/org/pentaho/di/trans/step/errorhandling/AbstractFileErrorHandler.java
engine/src/test/java/org/pentaho/di/trans/step/errorhandling/AbstractFileErrorHandlerTest.java

@pentaho/tatooine @pentaho-lmartins @smmribeiro 
* [PDI-18153] Added in further null/empty string check to ensure that null/empty string encoding does not cause an encoding issue.

[PDI-18153] Text File Input step - Error Handling issue. Failure to write to file due to java.io.UnsupportedEncodingException

---

engine/src/main/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoader.java
engine/src/test/java/org/pentaho/di/trans/steps/orabulkloader/OraBulkLoaderTest.java
plugins/gpload/core/src/main/java/org/pentaho/di/trans/steps/gpload/GPLoad.java
plugins/gpload/core/src/test/java/org/pentaho/di/trans/steps/gpload/GPLoadTest.java

@pentaho/tatooine @pentaho-lmartins @wseyler  
* [PDI-18073] Added a database connection null check to verify that if someone fails to put in a database connection, the error log will state that's what is missing.
* [PDI-18073] Added test cases to verify this check.
Part of a set of PRs:
- https://github.com/pentaho/pentaho-kettle/pull/6798
- https://github.com/pentaho/pdi-teradata-tpt-plugin/pull/49

[PDI-18073] Bulk Loading steps returning NPE if previous steps does not have rows

---

core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java
engine/src/main/java/org/pentaho/di/repository/RepositoryExportSaxParser.java
engine/src/test/java/org/pentaho/di/repository/RepositoryExportSaxParserTest.java

RepositoryExportSaxParser did not handle attributes,
and KafkaConsumer sets some meta info in attributes.
This impacted other steps besides Kafka- anything w/ attributes
in the meta.  In other cases I tested the import "succeeded", but
attribute info was missing.
-->  https://jira.pentaho.com/browse/PDI-18254

[PDI-18254]  Exported Kafka Consumer Step cannot be imported

---

core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/test/java/org/pentaho/di/core/vfs/KettleVFSTest.java
engine/src/test/java/org/pentaho/di/job/entries/unzip/JobEntryUnZipTest.java

The PPP-4374 case ( https://github.com/pentaho/pentaho-kettle/pull/6641 ) popped up some invalid getObject calls. For instance, it looks likes kettleAnalyzerUtil.java (pentaho-metaverse) calls KettleVFS and then saves the result as resource even if **it is not a valid file path**, so we should be validating if we really want to request a "getFileObject" from a whole json string as argument, and not just validating if it is empty:
https://github.com/pentaho/pentaho-metaverse/blob/master/api/src/main/java/org/pentaho/metaverse/api/analyzer/kettle/KettleAnalyzerUtil.java#L156
At the same time KettleVFS should also be prepared to deal with this. And we have more cases where this also happen. This PR added a scheme validation (getScheme function) that now throws an exception with invalid paths …

[PDI-18211] JSON Input Step Performance Degradation in 8.3

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/test/java/org/pentaho/di/job/entries/trans/JobEntryTransTest.java

This case is related with a non-existing condition of clearing out previous values from previous executions in case of actual values are empty or null.
That logic was added in this PR.
A new test was added for the actual possible parameter definition combinations on a JobEntryTrans Step
@ssamora

[PDI-18227] Nulls do not initialize variables when passed

---

plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/configuration/impl/spark/SparkTunableProperties.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/spark/SparkTunablePropertiesTest.java

Add support on "Spark Tuning Parameters" for join-specific tuning params (steps MergeRows, MergeJoin and JoinRows)

[BACKLOG-31173] - Spark Tuning - UI JoinTunable Support

---

core/src/main/java/org/pentaho/di/core/logging/Slf4jLoggingEventListener.java
core/src/test/java/org/pentaho/di/core/logging/Slf4jLoggingEventListenerTest.java

@pentaho/tatooine @pentaho-lmartins @rmansoor 
* [PDI-17983] Ensuring that the name of the job/transformation is printed. Either pull from the filename string if it exists, or to pull from the object name and append the appropriate extension to replicate the filename.
* [PDI-17983] Adding test code
* [PDI-17983] Updating license year
Work with: https://github.com/pentaho/pdi-platform-plugin/pull/79

[PDI-17983] pdi.log: Excuting Jobs/Transformation using Slave Server results to Jobs/Transformation name as null along with duplicate entries.

---

engine/src/main/java/org/pentaho/di/base/KettleConstants.java
engine/src/main/java/org/pentaho/di/kitchen/Kitchen.java
engine/src/main/java/org/pentaho/di/kitchen/KitchenCommandExecutor.java
engine/src/main/java/org/pentaho/di/pan/Pan.java
engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java

@pentaho/rogueone 
- Adds a new `uuid` parameter (this is hidden, like the `base64zip` parameter, so it won't need external documentation)
- Adds the UUID from params into the log4j MDC so it can be inserted into log lines

[BACKLOG-31521] Allow UUIDs to be passed from Pan/Kitchen, add them to the log4j MDC on execution

---

plugins/drools/core/pom.xml

This is part of a series of PRs. See https://github.com/pentaho/maven-parent-poms/pull/170 for details.
**Don't merge before the PR above.**
Removing all the dependencies will keep the plugin assembly the same with the exception of the updated `XStream` component.

[PPP-4448] Use of Vulnerable Component - XStream 1.4.10

---

engine/src/main/java/org/pentaho/di/kitchen/KitchenCommandExecutor.java
engine/src/main/java/org/pentaho/di/pan/PanCommandExecutor.java

These calls aren't needed with the new approach.
The `--uuid` option for Pan/Kitchen isn't really either, but it probably will be for future work, and those are very low impact, so we'll leave them in for now.

[BACKLOG-31992] Remove MDC calls

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/test/java/org/pentaho/di/job/entries/trans/JobEntryTransTest.java

Mix of two approaches:
https://github.com/pentaho/pentaho-kettle/pull/6930
https://github.com/pentaho/pentaho-kettle/pull/6998
@smmribeiro

[SP-5248] Backport of PDI-18227 - Nulls do not initialize variables when passed (8.3 Suite)

---

core/src/main/java/org/pentaho/di/connections/ConnectionDetails.java

https://jira.pentaho.com/browse/BACKLOG-30731

[BACKLOG-30731] Adding getProperties method to ConnectionDetails

---

plugins/pur/core/pom.xml

Replaces #6947. We actually depend on `jackrabbit-api` and not `jackrabbit-core`.
**Do not merge before https://github.com/pentaho/maven-parent-poms/pull/178!**
@ssamora @RPAraujo

[PPP-4447] Use of vulnerable component - Tika Core 1.1x

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
core/src/main/java/org/pentaho/di/core/database/SQLiteDatabaseMeta.java
core/src/test/java/org/pentaho/di/core/database/SQLiteDatabaseMetaTest.java

This change is needed for PDI-18453 changes.

[PDI-18456] Update the SQLite JDBC Driver to the latest (3.27.2.1).

---

engine/src/main/java/org/pentaho/di/kitchen/Kitchen.java
engine/src/main/java/org/pentaho/di/pan/Pan.java

The default Locale was not being set when we run transformations with PAN.
That caused differences between spoon and Pan executions, since spoon was initializing it accordingly to the LanguageChoice value.
In this case, the NumberFormat was different due to Locale, causing the described behavior.
Kitchen had also the same problem. It was also fixed in this PR.

[PDI-18228] Pan bad read of Data Grid Step

---

plugins/file-open-save-new/core/pom.xml

AWS libraries use XMLReaderFactory.  xerces parser needed in the event
that XMLReaderFactory was initialized elsewhere, since parser classname
is statically ref'd in the factory.
https://jira.pentaho.com/browse/BACKLOG-32300

[BACKLOG-32300] S3 VFS can fail due to class not found error.

---

engine/src/main/java/org/pentaho/di/repository/Repository.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java
plugins/pur/core/src/test/java/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java

Adding a .getUri() method to the Repository interface to simplify
retrieval of the pur repository endpoint.
https://jira.pentaho.com/browse/BACKLOG-32449

BACKLOG-32449 Hadoop Cluster UX - Update options for Client/Repository

---

assemblies/static/src/main/resources-filtered/set-pentaho-env.bat

The JAVA_HOME environment variable may already contain quotes. If so these, have to be stripped before re-quoting further in the script.

Bugfix - JAVA_HOME etc may already contain quotes

---

ui/src/main/java/org/pentaho/di/ui/core/events/dialog/SelectionAdapterFileDialog.java

Occurred when non fileExceptions threw such as bad hostname from hdfs. This prevented the VFS Browser dialog from appearing.

[BACKLOG-32823] Fix for unhandled exceptions related to VFS browser.

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileLine.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileinput/TextFileInputData.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java
engine/src/test/resources/org/pentaho/di/trans/steps/csvinput/files/enclosures.csv
ui/src/main/java/org/pentaho/di/ui/trans/step/common/CsvInputAwareStepDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileCSVImportProgressDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileInputDialog.java
ui/src/main/java/org/pentaho/di/ui/trans/steps/textfileinput/TextFileCSVImportProgressDialog.java

Merge Masters: @ppatricio and @bcostahitachivantara
Cherry-picks:
* https://github.com/Pentaho/pentaho-kettle/commit/c970269d66109f9f356a144d1a2c239d0d268ece
* https://github.com/Pentaho/pentaho-kettle/commit/d4a3cbb9aea2732d009925ac4742f61a568c88e8

[SP-5344] Backport of PDI-18175 - Hadoop file input step cannot read RFC-4180 CSV files if there are fields containing line breaks (8.3 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/main/java/org/pentaho/di/core/xml/XMLHandler.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest_NullEmpty.java
core/src/test/java/org/pentaho/di/core/xml/XMLHandlerTest.java
engine/src/main/resources/kettle-variables.xml
plugins/xml/core/src/main/java/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataTest.java

This is the proposed fix using three different Kettle properties to override the behavior of `KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL` which is producing different results from previous versions considering version **4.4.2** as the correct behavior.
When `KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL` is set to "Y", three other flags may need to be set to "Y" to accommodate changes in behavior between versions.
- `KETTLE_DO_NOT_NORMALIZE_NULL_STRING_TO_EMPTY` - prevents the **Data grid** step from producing empty values when the "Set empty value" option is not set for a given field
- `KETTLE_XML_EMPTY_TAG_YIELDS_EMPTY_VALUE` - allows the **Filter rows** step to filter rows on an empty values, if not set, the empty value will be converted to a `null` and the comparison between empty and null will …

[PDI-18440][PDI-18442] Fixes issues with null v.s. empty values

---

engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/org/pentaho/di/job/entries/trans/messages/messages_en_US.properties
ui/src/main/java/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialog.java

Provide the capability to suppress result data from a transformation running on a remote slave.  First commit provides this ability via named parameters for back-porting, second commit adds a GUI checkbox.

[PDI-18578]

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaConverter.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaConverterTest.java

integers in nanoseconds; follows implementation in PDI-18369.

[BACKLOG-33339] Update ValueMetaConverter to convert timestamps to

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaConverterTest.java

* [PPP-4496] Upgrading to version 0.10.2.2
* [PPP-4496] Removing version reference, maven-parent-pom will control version info.
* [PPP-4496] Fixing unit test since nano default was set back to milli default in PDI-18369
This is from a series of Pull Requests:
- https://github.com/pentaho/maven-parent-poms/pull/218
- https://github.com/pentaho/big-data-plugin/pull/2032
- https://github.com/pentaho/pdi-plugins-ee/pull/168
- https://github.com/pentaho/pentaho-platform/pull/4649
- https://github.com/pentaho/pentaho-reporting/pull/1327
- https://github.com/pentaho/pentaho-reportdesigner-ee/pull/152
- https://github.com/pentaho/pentaho-metadata-editor/pull/190
- https://github.com/pentaho/pentaho-metadata-editor-ee/pull/85
- https://github.com/pentaho/pentaho-kettle/pull/7309
- …

[PPP-4496] Use of Vulnerable Component: Components/kafka

---

core/src/main/java/org/pentaho/di/core/logging/DefaultLogLevel.java
core/src/main/java/org/pentaho/di/core/logging/LogChannel.java

The global log channels in PDI are initialized on startup with the
default log level of BASIC.
The default log level (loaded from .spoonrc|LogLevel) is read after these
fields are initialized, so those logchannels are not updated.  When the
default log level is changed we should update the global log channels.
https://jira.pentaho.com/browse/PDI-18719

[PDI-18719] Global LogChannels do not pick up DefaultLogLevel changes

---

engine/src/main/java/org/pentaho/di/job/JobMeta.java

Internal.Entry.Current.Directory from Sub Job in Spoon (8.3 Suite)

[SP-5523] Backport of PDI-18621 - Using 'Open Referenced Object' removes

---

engine/src/main/java/org/pentaho/di/job/JobMeta.java

Internal.Entry.Current.Directory from Sub Job in Spoon (9.0 Suite)

[SP-5524] Backport of PDI-18621 - Using 'Open Referenced Object' removes

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaTimestamp.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaTimestampTest.java
engine/src/main/resources/kettle-variables.xml

Original PRs:
- [#7251](https://github.com/pentaho/pentaho-kettle/pull/7251)
- [#7259](https://github.com/pentaho/pentaho-kettle/pull/7259)
- [#7271](https://github.com/pentaho/pentaho-kettle/pull/7271)
- [#7364](https://github.com/pentaho/pentaho-kettle/pull/7364): on this PR there's code that should have been done/merged under [BACKLOG-33399](https://jira.pentaho.com/browse/BACKLOG-33399) but was, for convenience, done here (to know: classes 'ValueMetaConverter' and 'ValueMetaConverterTest') - **This code is not supposed to be backported!**
It may be a good idea **not to squash** the commits for everyone to see these details.
@ppatricio @pentaho/tatooine

[SP-5576] Backport of PDI-18369 - Converting Integer to Timestamp type using Select values step results in incorrect date (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/repository/RepositoryImporter.java

causing erroneous changes to the imported job when the directory to
contain the job did not exist prior to import.

[PDI-18786] CurrentDirectoryChangedListener was firing during import and

---

engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/repository/RepositoryImporter.java

[SP-5613]
CurrentDirectoryChangedListener was firing during import and
causing erroneous changes to the imported job when the directory to
contain the job did not exist prior to import.
This commit is a cherry-pick from master d74dc98ebe.

[PDI-18786]

---

core/pom.xml
core/src/main/resources/kettle-password-encoder-plugins.xml

Fix encryption-support version property to use property used by jenkins
move kettle-password-encoder-plugins.xml out of kettle-core so it will use the on in classes

[BISERVER-3497] Introduce pentaho-support-encyption project

---

core/src/main/java/org/pentaho/di/core/Const.java
core/src/main/java/org/pentaho/di/core/row/value/ValueMetaTimestamp.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaTimestampTest.java
engine/src/main/resources/kettle-variables.xml

Original PRs:
- [#7251](https://github.com/pentaho/pentaho-kettle/pull/7251)
- [#7259](https://github.com/pentaho/pentaho-kettle/pull/7259)
- [#7271](https://github.com/pentaho/pentaho-kettle/pull/7271)
- [#7364](https://github.com/pentaho/pentaho-kettle/pull/7364): on this PR there's code that should have been done/merged under [BACKLOG-33399](https://jira.pentaho.com/browse/BACKLOG-33399) but was, for convenience, done here (to know: classes 'ValueMetaConverter' and 'ValueMetaConverterTest') - **This code is not supposed to be backported!**
It may be a good idea **not to squash** the commits for everyone to see these details.
@ppatricio @pentaho/tatooine

[SP-5575] Backport of PDI-18369 - Converting Integer to Timestamp type using Select values step results in incorrect date (9.0 Suite)

---

ui/src/main/java/org/pentaho/di/ui/core/database/dialog/XulDatabaseDialog.java

* Adding in a null check for other design tools that do not spin up a Spoon instance (metadata-editor in this case). Check prevents non-Spoon related tools from throwing null exceptions and not generating the database connection dialog.

[BACKLOG-33920] Create or Edit a Connection is broken in PME

---

ui/src/main/java/org/pentaho/di/ui/util/EnvironmentUtils.java
ui/src/main/resources/org/pentaho/di/ui/core/default.properties
ui/src/test/java/org/pentaho/di/ui/util/EnvironmentUtilsTest.java

The particular message being show is about the absence of _libwebkitgtk_ in Ubuntu. It does not relate with any version in particular of Ubuntu. 
We were only verifying for the supported versions at the time (14 and 16). As soon as users start to use newer versions the message would not appear (although we would still face the problems of not having _libwebkitgtk_ installed). 
A possible correction could be to update the versions to the current supported ones (which now are 16 and 18) but, 
since the error occurs because of the absence of lib and the message it self only refers to the lib itself, we should not verify the version of the OS and warn the user. 
Also, we always show the error in the log messages regardless of the version (it also, like this correction, only checks if the lib …

[PDI-18096] Missing alert message in Ubuntu 18.04

---

engine/src/main/java/org/pentaho/di/trans/SingleThreadedTransExecutor.java

Added logging to clearly indicate the transformation being executed from the Single Threaded executer.

[PDI-18543] Duplicate logging issues when using Single Threader step.

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java

This test was erroring prior to the change.
```
ERROR] Failures:
[ERROR]   RowKeyTest.testHashCodeCalculationsandEquals:69 expected:<-798137542> but was:<-227281350>
[INFO]
[ERROR] Tests run: 2469, Failures: 1, Errors: 0, Skipped: 6
```

[TAP-1868] Fix an NPE when logging a KettleException.

---

engine/src/main/resources/org/pentaho/di/trans/steps/pentahoreporting/messages/messages_en_US.properties

This is an additional PR due to an incomplete fix already merged ( master ) before 9.1 code freeze.
Could you please review and merge?
@rmansoor 
@pentaho-svigneri

[PDI-18089] - MDI cannot inject Report Definition File to Pentaho Reporting Output

---

ui/src/main/java/org/pentaho/di/ui/core/widget/MultipleSelectionCombo.java

This fixes the issue of when a parameter tag is removed of being placed in the list of tags from the catalog.  This insures the tag list only contains tags from the catalog.

[BACKLOG-34401] Fixed a bug with parameters appearing on the TAG

---

core/src/main/java/org/pentaho/di/connections/vfs/provider/ConnectionFileObject.java
core/src/main/java/org/pentaho/di/core/vfs/AliasedFileObject.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputMeta.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java
engine/src/test/java/org/pentaho/di/trans/ael/adapters/TransMetaConverterTest.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMetaTest.java

[BACKLOG-34530] converts s3 to s3a for AEL pvfs files

[BACKLOG-34530] converts s3 to s3a before sending to AEL

---

core/src/main/java/org/pentaho/di/core/database/ConnectionPoolUtil.java
core/src/main/java/org/pentaho/di/core/database/DataSourceProviderInterface.java
core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/util/DatabaseUtil.java
core/src/test/java/org/pentaho/di/core/database/ConnectionPoolUtilTest.java
core/src/test/java/org/pentaho/di/core/database/DatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/DatabaseTest.java
core/src/test/java/org/pentaho/di/core/database/util/DatabaseUtilTest.java

Cherry-pick of #7535 and #7631 into 9.1 branch.
Merge before https://github.com/pentaho/pentaho-platform/pull/4762 and https://github.com/pentaho/pdi-platform-plugin/pull/84
@ssamora @ppatricio

[SP-5729] Backport of BISERVER-14442 - Database connections using connection pooling will not adhere to changes in the connection details (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/database/ConnectionPoolUtil.java
core/src/main/java/org/pentaho/di/core/database/DataSourceProviderInterface.java
core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
core/src/main/java/org/pentaho/di/core/database/util/DatabaseUtil.java
core/src/test/java/org/pentaho/di/core/database/ConnectionPoolUtilTest.java
core/src/test/java/org/pentaho/di/core/database/DatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/DatabaseTest.java
core/src/test/java/org/pentaho/di/core/database/util/DatabaseUtilTest.java

Cherry-pick of #7535 and #7631 into 8.3 branch.
Merge before https://github.com/pentaho/pentaho-platform/pull/4763 and https://github.com/pentaho/pdi-platform-plugin/pull/85
@ssamora @ppatricio

[SP-5728] Backport of BISERVER-14442 - Database connections using connection pooling will not adhere to changes in the connection details (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/www/StatusServletUtils.java

@ssamora 
@smmribeiro 
I did not add unit test because it is not easy to do and it was clearly a mistake using explicit file separator for windows instead of generic File.separator.
I refactored the code just for simplicity. (Take a look at line 56)

[PDI-18856] - PDI Kettle Status Page - Sapphire Theme - Transformation/Job Table Records & References to mantleRuby.css

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/trans/Trans.java

ArrayBlockingQueue used to signal when steps are finished.  Set new
default high enough to avoid it filling up in the future.

[PDI-18849] Add a kettle property to control the size of the

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/trans/Trans.java

ArrayBlockingQueue used to signal when steps are finished.  Set new
default high enough to avoid it filling up in the future.
This commit is a cherry-pick from master 3b9592ef0d

[SP-5826] Add a kettle property to control the size of the

---

engine/src/main/java/org/pentaho/di/trans/steps/delete/DeleteMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/delete/DeleteMetaTest.java

@ssamora 
@smmribeiro 
It only was backported the changes needed to fix the issue, it was not backported changes related with sonnar.

[SP-5843] - Backport of PDI-18387 - Fields defined in "Key(s) to lookup the values" goes missing in the Delete Step (8.3 Suite)

---

engine/src/main/java/org/pentaho/di/trans/steps/delete/DeleteMeta.java
engine/src/test/java/org/pentaho/di/trans/steps/delete/DeleteMetaTest.java

@ssamora 
@smmribeiro 
It only was backported the changes needed to fix the issue, it was not backported changes related with sonnar.

[SP-5844] - Backport of PDI-18387 - Fields defined in "Key(s) to look up the values" goes missing in the Delete Step (9.1 Suite)

---

core/src/main/java/org/pentaho/di/core/vfs/SftpFileSystemWindows.java

A nullcheck was missing
This fixes PDI-19201:
https://jira.pentaho.com/browse/PDI-19201

PDI-19201: Fix creation of SFTP connections/sessions to an SFTP Windows server

---

assemblies/lib/pom.xml

order to avoid pulling in Java 11 artifacts.
This commit is a cherry-pick from master 98a58a36a7f6

[CLEANUP] Need to specify the versions of some eclipse dependencies in

---

engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java
engine/src/test/java/org/pentaho/di/trans/steps/transexecutor/TransExecutorUnitTest.java

fields in a case-insensitive manner in order to match previous
functionality.

[PDI-19098] Variable name needs to be compared to the incoming row

---

core/src/main/java/org/pentaho/di/core/database/Database.java

[BISERVER-14546] - ProAuditDatabasejob locks MySQL8's pentaho_operations_mart.pro_audit_staging and pro_audit_tracker tables

---

engine/src/test/java/org/pentaho/di/job/entries/http/JobEntryHTTP_PDI_19104_Test.java

@ssamora 
@smmribeiro 
@moraesvc

[PDI-19104] - Getting "Illegal character in opaque part at index" error when using the "file:\" protocol in the HTTP Job Entry.

---

engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java
engine/src/test/java/org/pentaho/di/trans/steps/transexecutor/TransExecutorUnitTest.java

fields in a case-insensitive manner in order to match previous
functionality.
This commit is a cherry-pick from master 2193eef6

[SP-5983] Variable name needs to be compared to the incoming row

---

engine/src/main/java/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java
engine/src/test/java/org/pentaho/di/trans/steps/transexecutor/TransExecutorUnitTest.java

fields in a case-insensitive manner in order to match previous
functionality.
This commit is a cherry-pick from master 2193eef6

[SP-5984] Variable name needs to be compared to the incoming row

---

engine/src/main/java/org/pentaho/di/www/ExecuteTransServlet.java

@bcostahitachivantara @smmribeiro 
keeping the old behavior where in a positive result we do not output any message. (transformation may already have output and we are adding into it probably corrupting any xml output).
This does not invalidate the previous correction since all error paths remain the same and have their error status correctly updated.

[PDI-19320] XML output with servlet with carte.sh

---

assemblies/lib/pom.xml

Upgrading java mongo driver to the latest possible version without many changes in the code.

[PDI-19163] Upgraded mongo java driver version from 3.10.2 to 3.12.10

---

engine/src/main/java/org/pentaho/di/base/MetaFileLoaderImpl.java

[BACKLOG-35689] NPE generated when using the "Get parameters" button on Job/Trans executor Steps

[BACKLOG-35689] NPE generated when using the "Get parameters" button on Job/Trans executor Steps

---

engine/src/main/java/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java

PDI-19457 "PDI - Microsoft Excel Output Step Using Template Errors - Regression": Correct Error message is displayed when different worksheet name is used in Template and output file.
This PR is only to log the right error message and not change functionality. 
The other sub-issues of the ticket have been dealt with by updating the documentation by raising another ticket for the same as mentioned in the comments section of the ticket.
Kindly review the PR.

[PDI-19457] : "PDI - Microsoft Excel Output Step Using Template Errors - Regression"

---

plugins/pom.xml

not highdeps, in order to preserve the original build order.

[BACKLOG-36063] Plugins migrated from kettle engine should be lowdeps,

---

assemblies/lib/pom.xml

dependency on mongo plugin so the jar does not need to be in /lib

[BACKLOG-36073] Cleanup mongo dependencies; metaverse no longer has a

---

assemblies/core/lib/pom.xml
assemblies/lib/pom.xml

no-osgi artifacts because it is a dependency of PentahoSystem/OSGIRuntimeObjectFactory

[BACKLOG-36110] org.osgi.core library still needs to be present in

---

engine/src/test/java/org/pentaho/di/trans/streaming/common/BaseStreamStepTest.java
plugins/meta-inject/src/test/java/org/pentaho/di/trans/steps/metainject/OpenMappingExtensionTest.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/JmsProducerTest.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/context/ActiveMQProviderTest.java
plugins/streaming/impls/mqtt/pom.xml
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTConsumerTest.java
plugins/streaming/impls/mqtt/src/test/java/org/pentaho/di/trans/step/mqtt/MQTTProducerTest.java

KettleLogStore.logChannelInterfaceFactory is a static variable that gets
replaced by a mock in many (but not all) unit tests, which, if not
cleaned up after the test, can lead to problems in other tests running
concurrently or on the same fork.  Additionally, BeanInjectionInfo has a
static variable to hold its LogChannelInterface object, which can cause
problems depending on whether it's initialized by a normal factory or a
mock.

[TEST] Some tests were periodically failing because the

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/base/MetaFileLoaderImpl.java
engine/src/test/java/org/pentaho/di/base/MetaFileLoaderImplTest.java

control whether trans/job/step metas are cached when being loaded
multiple times over the life of a parent trans/job.  Cache is currently
broken; variable space is not updated even if a parent parameter value
has changed, resulting in undesired behavior.

[PDI-19578] Introduce property KETTLE_USE_META_FILE_CACHE (default N) to

---

assemblies/lib/pom.xml
assemblies/plugins/pom.xml

big-data-legacy-core jar required in both builds now.

[BACKLOG-35831] Add assemblies for kafka plugin migration.

---

plugins/meta-inject/impl/pom.xml
plugins/meta-inject/impl/src/main/java/org/pentaho/di/trans/steps/metainject/analyzer/MetaInjectAnalyzer.java
plugins/meta-inject/impl/src/main/java/org/pentaho/di/trans/steps/metainject/lifecycle/KettleMetaInjectPluginLifecycleListener.java
plugins/meta-inject/ui/pom.xml

plugins to the same jar as the step meta class; keeping them separate
was causing classloading issues during metaverse execution.

[BACKLOG-36233] Moved the metaverse analyzer and lifecycle listener

---

assemblies/client/pom.xml
assemblies/core/client/pom.xml
assemblies/core/lib/pom.xml
assemblies/lib/pom.xml

be declared inside profiles; they must be in the main pom file.

[BACKLOG-36213] Pom cleanup; properties for Pentaho dependencies cannot

---

engine/src/main/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariables.java
engine/src/test/java/org/pentaho/di/job/entries/setvariables/JobEntrySetVariablesTest.java

Code is added to respect Variable Substitution flag so that variables declared in the Set Variables step operated as below
Variable will be overridden if the same variable is available in the property file and Variable Substitution flag is true
Variable will not be overridden if the Variable Substitution flag is false
Variable will be added if the variable is not available in the property file and Variable Substitution flag is true/false.

[PDI-19160]-Set variables(job entry): When "Variable substitution" is N, the value of the externally set variable is replaced.

---

plugins/file-open-save-new/api/src/main/java/org/pentaho/di/plugins/fileopensave/api/providers/exception/ProviderServiceInterface.java
plugins/file-open-save-new/core/pom.xml
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/extension/FileOpenSaveExtensionPoint.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/ProviderService.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/service/ProviderServiceService.java

plugin to allow file system providers to register themselves.  Updated
the ProviderServiceService to register itself with the
PluginServiceLoader. ProviderService will only allow one provider with a
given name/type pair to exist, in case a karaf bundle restarts and
re-registers itself.

[BACKLOG-35995] Need to expose the ProviderService outside of this

---

assemblies/plugins/pom.xml
plugins/excel/impl/src/main/java/org/pentaho/di/trans/steps/exceloutput/ExcelOutputMeta.java

[BACKLOG-35812] - Corrected spelling of the plugin Id

[BACKLOG-35812] - Corrected spelling of the plugin Id

---

engine/src/main/java/org/pentaho/di/job/Job.java
engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/trans/Trans.java
engine/src/main/java/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java
ui/src/main/java/org/pentaho/di/ui/spoon/trans/TransGraph.java

Changing the initialization of the new parameter to the beginning of Job/Transformation execution to avoid unit tests issues.
@andreramos89 
@smmribeiro

[BACKLOG-36316] - Test cases failing inside QAT build 238 (after PDI-19357)

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/local/LocalFileProvider.java

It covers below fixes
[BACKLOG-36415](https://jira.pentaho.com/browse/BACKLOG-36415) - Copy and Paste a folder in the Open/Select File or Folder window resulting infinite subfolder with its contents
[BACKLOG-36427](https://jira.pentaho.com/browse/BACKLOG-36427) - PDI File open dialog, right click menu on File/Folder pane misses Cut Option
Disabling right click menu when connected to a repository(Similar to 9.3)
[BACKLOG-36412](https://jira.pentaho.com/browse/BACKLOG-36412) - PDI File open dialog, right click menu on File/Folder pane misses Delete Option

[BACKLOG-36427]- PDI File open dialog, right click menu on File/Folder pane misses Cut Option

---

plugins/file-open-save-new/core/pom.xml
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
ui/src/main/java/org/pentaho/di/ui/core/events/dialog/SelectionAdapterFileDialog.java

given path when using SelectionAdapterFileDialog and ensure that the FileOpenSaveDialog is able to open to the correct directory when they are specified in the FileDialogOperation.  Should work for VFS and cluster connections as well as local files.

[BACKLOG-36524] Determine the connection and file provider from the

---

engine/src/main/java/org/pentaho/di/job/entries/movefiles/JobEntryMoveFiles.java

The empty sub-folders are now being moved.

[PDI-18947] : Move files - Empty sub-directories are not moved with "Move Empty Folders" checked

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/controllers/FileController.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/repository/model/RepositoryFile.java

after saving a file, and the cache had not been updated to reflect the new file.  Cache is now cleared for the parent directory when saving a file so that it shows up later.
Also corrects an issue with filtering repository files when accessing the cache.

[BACKLOG-36549] File cache was being accessed when opening the dialog

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java

replace escape characters using a regexp even when the user had not specified any escape character to use.  Corrected the boolean expression to check for an empty escape char string first.
Need to reconsider the use of Const.replace here in the future; regular expression parsing is expensive when done repeatedly.

[BACKLOG-36581] The convertLineToStrings method was attempting to

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java

characters are used; searching for and replacing the empty string "" within a given string is a waste of resources.

[BACKLOG-36581] Further optimization for the case where no escape

---

engine/src/main/java/org/pentaho/di/base/MetaFileLoaderImpl.java

Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/8534
@andreramos89 
@smmribeiro

[SP-6201] - Backport of PDI-19570 - 9.3: Job Entry with path variable (${Internal.Entry.Currenty.Directory}) cannot be resolved. (9.3 Suite)

---

plugins/avro-format/core/src/test/java/org/pentaho/di/trans/steps/avro/input/AvroInputMetaTest.java

setting type to be invalid type.
test failing in PR:
https://github.com/pentaho/pentaho-kettle/pull/8770#issuecomment-1373853815
When the mock is created #getPentahoType() will return "0" by default, since no mocking instructions were given.
An unrelated test is creating a pluginType that occupies the id of "0". I set the mock type to an unrealistic value.

[CLEANUP] update test to use invalid type to force exception

---

engine/src/test/java/org/pentaho/di/trans/TransTest.java

using vfs filesystem "file" intstead of "ram"
This the test org.pentaho.di.trans.TransTest.testPDI12424ParametersFromMetaAreCopiedToTrans was started failing recently in branch 9.4 and in current master (9.5). The test works in branch 9.3.
Failing test in other pull requests:
https://github.com/pentaho/pentaho-kettle/pull/8759#issuecomment-1361313448
https://github.com/pentaho/pentaho-kettle/pull/8754#issuecomment-1370048608
the main failing of the test was the creation of the temporary file used to test ktr logic. The file location was VFS ram://.
The issue is on the Apache side where AbstractFileSystem#resolve(FileName name, boolean useCache) wasn't able to retrieve the ram:// from the cache. 
The ultimate reason why the caching stop for the ram:// is uknonwn. However, changing to …

[CLEANUP] fix for failing test in TransTest

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/trans/streaming/common/FixedTimeStreamWindow.java

a batch worker; required for kinesis to handle shard lease loss.  Adding a new Kettle parameter to control the number of records returned at a time by the KCL.

[PDI-19737] Provide the ability to filter records before handing them to

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml

[PDI-19723] - Input rows with only <null> Strings are skipped by Python Executor step

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml

@andreramos89 
@smmribeiro 
Original PR: https://github.com/pentaho/pentaho-kettle/pull/8841

[SP-6339] - Backport of PDI-19723 - Input rows with only <null> Strings are skipped by Python Executor step (9.3 Suite)

---

engine/pom.xml
plugins/file-stream/pom.xml
plugins/google-analytics/assemblies/plugin/pom.xml
plugins/json/core/pom.xml
plugins/pentaho-googledrive-vfs/assemblies/plugin/pom.xml
plugins/pentaho-googledrive-vfs/core/pom.xml
plugins/streaming/impls/mqtt/pom.xml
plugins/streaming/impls/mqtt/src/main/java/org/pentaho/di/trans/step/mqtt/MQTTProducerMeta.java
plugins/streaming/pom.xml
pom.xml

in poms. Needed to allow license manager code in EE to use Google dependencies.

[BACKLOG-37825] Update guava to latest version and clean up dependencies

---

assemblies/lib/pom.xml

[BACKLOG-37825] Library needed by google vfs plugin was missing from CE

---

core/src/main/java/org/pentaho/di/connections/vfs/VFSConnectionProvider.java

Prevents KettleVFS from loading other connections, causing infinite recursion.

[BACKLOG-38056] use an empty Variable space

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml

[SP-6367] - Backport of PDI-19723 - Input rows with only <null> Strings are skipped by Python Executor step (9.5 Suite)

---

engine/src/main/java/org/pentaho/di/www/WebServer.java

This changed the basic carte constraint mapping to ANY_AUTH, which allows any authorized user to access any part of Carte (removing the default role and ANY_ROLE combination). Jetty processes ANY_ROLE before ANY_AUTH during init, and ignores ANY_AUTH. Also, had to assign a DefaultIdentityService, because without it, the authenticator of the IdentityService was not initialized and skipped, resulting in 403 forbidden responses whenever JAAS was used.

PDI-19588 - Fix JAAS in Carte

---

assemblies/plugins/pom.xml

[BACKLOG-38435] Code changes for moving Mail Validator from core to plugin
[BACKLOG-38435]: https://hv-eng.atlassian.net/browse/BACKLOG-38435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-38621] Code changes for adding dependency in FTP plugin

---

plugins/google-analytics/core/src/main/java/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMeta.java

Cherry pick of https://github.com/pentaho/pentaho-kettle/pull/9047

[BACKLOG-38431] : Deprecate the CE GA plugin as it no longer supports

---

engine/src/main/java/org/pentaho/di/trans/TransMeta.java

[PDI-19938]-Database Password Field is missing when searching transformation's metadata
[PDI-19938]: https://hv-eng.atlassian.net/browse/PDI-19938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-19938]-Database Password Field is missing when searching transformation's metadata

---

core/src/main/java/org/pentaho/di/core/database/Database.java
engine/src/test/java/org/pentaho/di/core/compress/snappy/SnappyCompressionInputStreamTest.java
engine/src/test/java/org/pentaho/di/core/compress/snappy/SnappyCompressionProviderTest.java

1. Due to thread concurrency issue, Database::getRow is fetching incorrect data. This method is being called by both Table Input step and Database Lookup step.
2. Fixed test cases related to Snappy

[PDI-19750] - Database lookup step fetches incorrect data from the database

---

engine/src/main/java/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java

This issue is happening because metaWithFieldOptions is not refreshed every time changes are made to the step. Removed the null condition check in the beginning of the method, which is stopping the meta data to reload.

[PDI-19869] - TextFileOutput throws transformation runtime error if output field columns are changed

---

assemblies/core/static/src/main/resources-standard/classes/simplelogger.properties
assemblies/static/src/main/resources/classes/simplelogger.properties

Adding simplelogger.properties file as discussed in the issue's comments
@smmribeiro 
@renato-s 

[BAD-1930] - When Cloudera HIVE driver is used, a side effect in the LOGs with error messages start to show

---

core/src/main/java/org/pentaho/di/core/Const.java
plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/concatfields/ConcatFields.java
plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/concatfields/ConcatFieldsData.java
plugins/core/impl/src/test/java/org/pentaho/di/trans/steps/concatfields/ConcatFieldsTest.java

For backward compatibility, new Kettle property is added -  KETTLE_COMPATIBILITY_CONCAT_FIELDS_SPLIT_ROWS_HEADER_OFFSET
By default, value will be KETTLE_COMPATIBILITY_CONCAT_FIELDS_SPLIT_ROWS_HEADER_OFFSET= N indicating existing functionality and KETTLE_COMPATIBILITY_CONCAT_FIELDS_SPLIT_ROWS_HEADER_OFFSET= Y, which will correct the offset and populates the header at right position

[PDI-17309] - "Split every ... rows" option in Concat Field step does not work as expected after enabling the footer

---

plugins/rest/core/pom.xml

[PPP-4870]-Jetty Security Vulnerability -CVE-2022-2048
[PPP-4870]: https://hv-eng.atlassian.net/browse/PPP-4870?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PPP-4870]-Jetty Security Vulnerability -CVE-2022-2048

---

ui/src/main/java/org/pentaho/di/ui/core/PropsUI.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

Also fixes issue introduced with [PDI-19944](https://hv-eng.atlassian.net/browse/PDI-19944), where it was failing to save files (or exiting the Options dialog) if no file had been previously opened.
[PDI-19944]: https://hv-eng.atlassian.net/browse/PDI-19944?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-39430] - PDI - unable to close PDI instance after installation startup

---

core/src/main/java/org/pentaho/di/core/extension/KettleExtensionPoint.java
engine/src/main/java/org/pentaho/di/www/WebServer.java

This extension point allows the embedded Jetty Server for Carte to be further configured beyond the default Handler setup in WebServer.java.

[PDI-20003] Add a new extension point before the Carte webserver is started

---

plugins/core/impl/src/main/java/org/pentaho/di/trans/steps/cubeinput/CubeInput.java

This is a temporary workaround while we figure out what to do with this library. This bug is only present in commons-vfs 2.8.0 (not present in 2.7.0 and fixed in 2.9.0) but:
- we had to move off of 2.7.0 to get around an sftp bug
- we couldn't move up to 2.9.0 because of a bug where file writes were truncated
This issue was the simplest to workaround. We'll address this in a permanent way and revert this in another ticket.

[BACKLOG-39189] Temporary workaround for bug in apache commons-vfs

---

engine/pom.xml

[BACKLOG-39454]-Lots of errors coming up on logs when server 10.1 is configured to use Java 8 [updating jboss-logging jar ]
[BACKLOG-39454]: https://hv-eng.atlassian.net/browse/BACKLOG-39454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-39454]-Lots of errors coming up on logs when server 10.1 is configured to use Java 8 [updating jboss-logging jar ]

---

assemblies/samples/src/main/resources/transformations/General - check Sequence and Abort.ktr

[PDI-19761]-Sample Transformation "General General - check Sequence and Abort" fails due to incorrect column names
[PDI-19761]: https://hv-eng.atlassian.net/browse/PDI-19761?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-19761]-Sample Transformation "General General - check Sequence and Abort" fails due to incorrect column names

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java

Fixing issue already described in PDI-18776, later revised in PDI-19275, and unconsidering 0 rows to process
@smmribeiro 
@renato-s

[PDI-20033] - Sub-job is not executed when “Execute every input row” is checked.

---

core/src/main/java/org/pentaho/di/core/logging/LoggingObject.java

Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/9198

[SP-6496] - Backport of PDI-20038 - Pentaho 9.3.0.6 - Getting java.lang.OutOfMemoryError: Java heap space when running PDI Jobs (9.3 Suite)

---

plugins/ftp-delete/impl/src/main/java/org/pentaho/di/job/entries/ftpdelete/JobEntryFTPDelete.java

[PDI-19386] FTP_Delete step: Not recognizing "Copy previous results to" option when enabled.
[PDI-19386]: https://hv-eng.atlassian.net/browse/PDI-19386?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-19386] FTP_Delete step: Not recognizing "Copy previous results to" option when enabled.

---

engine/src/main/java/org/pentaho/di/job/entries/ftpdelete/JobEntryFTPDelete.java

[SP-6506]-Backport of PDI-19752 - FTP Delete: the files are not deleted if it contains Japanese as a wildcard or full filename (9.3 Suite)
[SP-6506]: https://hv-eng.atlassian.net/browse/SP-6506?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

 [SP-6506]-Backport of PDI-19752 - FTP Delete: the files are not deleted if it contains Japanese as a wildcard or full filename (9.3 Suite)

---

engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java

Original PRs:
https://github.com/pentaho/pentaho-kettle/pull/9196
https://github.com/pentaho/pentaho-kettle/pull/9246
@smmribeiro
@renato-s

[SP-6519] - Backport of PDI-20033 - Sub-job is not executed when “Execute every input row” is checked. (10.1 Suite)

---

core/src/main/java/org/pentaho/di/core/database/RedshiftDatabaseMeta.java
core/src/test/java/org/pentaho/di/core/database/DatabaseMetaTest.java
core/src/test/java/org/pentaho/di/core/database/RedshiftDatabaseMetaTest.java
dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java

[SP-6534]-Backport of PDI-19759 - Authentication methods are showing information on clear text when using Redshift connection type (9.3 Suite)
[SP-6534]: https://hv-eng.atlassian.net/browse/SP-6534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6534]-Backport of PDI-19759 - Authentication methods are showing information on clear text when using Redshift connection type (9.3 Suite)

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java

Validations were inverted.
@smmribeiro 
@renato-s 
@befc

[PDI-20085] - KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL produces opposite display for NULLS - fixing inverted validations

---

core/src/main/java/org/pentaho/di/core/fileinput/FileInputList.java

[PDI-20100] - 'Get subfolder names' step does not work with Windows mapped drive

---

core/src/main/java/org/pentaho/di/connections/utils/ConnectionUriParser.java
core/src/test/java/org/pentaho/di/connections/utils/ConnectionUriParserTest.java
engine/src/main/java/org/pentaho/di/core/LastUsedFile.java
plugins/file-open-save-new/api/src/main/java/org/pentaho/di/plugins/fileopensave/api/providers/BaseFileProvider.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dialog/FileOpenSaveDialog.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dragdrop/Element.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dragdrop/ElementDragListener.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dragdrop/ElementTransfer.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/dragdrop/ElementTreeDropAdapter.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/extension/FileOpenSaveExtensionPoint.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/OverwriteAwareFileSelector.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/VFSFileProvider.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/model/VFSDirectory.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/model/VFSFile.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/service/KettleVFSService.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/util/Util.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/dragdrop/ElementTest.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/dragdrop/ElementTransferTest.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/extension/FileOpenSaveExtensionPointTest.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/providers/vfs/VFSFileProviderTest.java
plugins/file-open-save-new/core/src/test/java/org/pentaho/di/plugins/fileopensave/providers/vfs/model/VFSFileTest.java
ui/src/main/java/org/pentaho/di/ui/core/FileDialogOperation.java
ui/src/main/java/org/pentaho/di/ui/core/events/dialog/SelectionAdapterFileDialog.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/test/java/org/pentaho/di/ui/core/events/dialog/SelectionAdapterFileDialogTest.java

- only use "pvfs://..." URI in VFSFileProvider
- remove or deprecated the use of the variables 'connection' and 'domain'
gains:
1. simplifies code for VFSFileProvider.java by using the abstraction layer of PVFS
2. VFSFileProvider does not have to contain every VFS Providers URl logic for Provider URI <--> PVFS URI
I  removed (ie set null, set "", or eliminated ) or deprecated all the uses of connection and domain variables and code. I was running out of time for to fully remove them. I created https://hv-eng.atlassian.net/browse/BACKLOG-40656 to track this. As the code is harmless.  Currently the sonarqube code smells/bugs are related to me adding @depracted or unreachable code, which is expected.
PR dependencies:
- The new root logic in VFSFileProvider#getRoot depends correct bucket …

[BACKLOG-40476] Change PDI File Browser to use PVFS URI on Backend

---

core/src/main/java/org/pentaho/di/core/fileinput/FileInputList.java

Original PR:
- https://github.com/pentaho/pentaho-kettle/pull/9318/

[SP-6543] - Backport of PDI-20100 - 'Get subfolder names' step does not work with Windows mapped drive (9.3 Suite)

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest_NullEmpty.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaStringTest.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/src/test/java/org/pentaho/di/trans/steps/datagrid/DataGrid_EmptyStringVsNull_Test.java
engine/src/test/java/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterTest.java
engine/src/test/java/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitter_EmptyStringVsNull_Test.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java
ui/src/test/java/org/pentaho/di/ui/core/dialog/EditRowsDialog_EmptyStringVsNull_Test.java

This is a squash and rebase of [pentaho-kettle#9324](https://github.com/pentaho/pentaho-kettle/pull/9324) but with the fix for the "unreachable statement" error (due to a return on line 3605)!

[PDI-20085] - KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL produces opposite display for NULLS - fixing unit tests

---

engine/src/test/java/org/pentaho/di/trans/steps/mock/StepMockHelper.java
plugins/xml/core/pom.xml
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/addxml/AddXMLTest.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataMetaTest.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/getxmldata/GetXMLDataStepAnalyzerTest.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamTest.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmljoin/XmlJoinOmitNullValuesTest.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmloutput/XMLOutputMetaTest.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmloutput/XMLOutputStepAnalyzerTest.java
plugins/xml/core/src/test/java/org/pentaho/di/trans/steps/xmloutput/XMLOutputTest.java
plugins/xml/pom.xml

There was an unused mock error coming from the engine `StepMockHelper` that got used in one test, so I threw a `lenient` in there, only usual thing about this one

[BACKLOG-40843] Unit test fixes for JDK17

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaBaseTest_NullEmpty.java
core/src/test/java/org/pentaho/di/core/row/value/ValueMetaStringTest.java
engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java
engine/src/main/java/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java
engine/src/test/java/org/pentaho/di/trans/steps/datagrid/DataGrid_EmptyStringVsNull_Test.java
engine/src/test/java/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterTest.java
engine/src/test/java/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitter_EmptyStringVsNull_Test.java
engine/src/test/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
engine/src/test/java/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java
ui/src/test/java/org/pentaho/di/ui/core/dialog/EditRowsDialog_EmptyStringVsNull_Test.java

This reverts all development done under PDI-20085 in the last three weeks, namely the following PRs:
1. [pentaho-kettle#9311](https://github.com/pentaho/pentaho-kettle/pull/9311) - merged May 9<sup>th</sup>
2. [pentaho-kettle#9311](https://github.com/pentaho/pentaho-kettle/pull/9317) - merged May 14<sup>th</sup>
3. [pentaho-kettle#9311](https://github.com/pentaho/pentaho-kettle/pull/9321) - merged May 16<sup>th</sup>
4. [pentaho-kettle#9311](https://github.com/pentaho/pentaho-kettle/pull/9347) - merged May 27<sup>th</sup>
For easier review, I made four individual commits (one for each PR) but these can be squashed at the end.

Revert "[PDI-20085] - KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL produces opposite display for NULLS"  

---

core/src/main/java/org/pentaho/di/connections/ConnectionDetails.java
core/src/main/java/org/pentaho/di/connections/vfs/VFSConnectionDetails.java
core/src/main/java/org/pentaho/di/connections/vfs/provider/ConnectionFileObject.java
core/src/main/java/org/pentaho/di/connections/vfs/provider/ConnectionFileSystem.java
core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/main/java/org/pentaho/di/core/vfs/KettleVFSImpl.java

See commit message for details or jira comment - https://hv-eng.atlassian.net/browse/BACKLOG-40513?focusedCommentId=2011165
manually setting ConnectionFileSystem#getUrl to pre SMB
- https://github.com/pentaho/pentaho-kettle/blob/1da3c08f00bb6fac2999d08ed35d6cb04fe87dd8/core/src/main/java/org/pentaho/di/connections/vfs/provider/ConnectionFileSystem.java
manually reverting hard coded SMB into KettleVFS(Impl).java#buildFsOption and ConnectionFileObject.java#getChild
- introduced by https://github.com/pentaho/pentaho-kettle/commit/089b78b720bbee248ffad1d4eb131f128984312c
Move ConnectionDetails.java#hasBuckets to VFSConnectionDetails.java#hasBuckets
**PR depends on:**
1. https://github.com/pentaho/pdi-plugins-ee/pull/1109
Should be merged together, only side effect will be, SMB VFS will break …

[BACKLOG-40513] Integrate SMB VFS as a PVFS "Bucketed" Connection

---

core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
core/src/main/java/org/pentaho/di/core/bowl/BaseBowl.java
core/src/test/java/org/pentaho/di/connections/ConnectionManagerTest.java

This makes the bowl that creates and "owns" a connection manager accessible as a property of the connection manager.

[BACKLOG-40356] Added bowl property to ConnectionManager

---

core/src/main/java/org/pentaho/di/core/database/Database.java
core/src/main/java/org/pentaho/di/core/database/MySQLDatabaseMeta.java
core/src/test/java/org/pentaho/di/core/xml/XMLHandlerUnitTest.java

[BACKLOG-40978] 10.2: Default driver class used is org.gjt.mm.mysql.driver instead of recommended com.mysql.jdbc.Driver
[BACKLOG-40978]: https://hv-eng.atlassian.net/browse/BACKLOG-40978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-40978] 10.2: Default driver class used is org.gjt.mm.mysql.driver instead of recommended com.mysql.jdbc.Driver

---

integration/pom.xml
plugins/elasticsearch-bulk-insert/core/pom.xml
plugins/engine-configuration/impl/pom.xml
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/RunConfigurationManagerTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationImportExtensionPointTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationInjectExtensionPointTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationRunExtensionPointTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/extension/RunConfigurationSaveExtensionPointTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/pentaho/DefaultRunConfigurationExecutorTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/pentaho/DefaultRunConfigurationProviderTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/pentaho/scheduler/JobScheduleParamTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/configuration/impl/pentaho/scheduler/JobScheduleRequestTest.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/ui/RunConfigurationDelegateTest.java
plugins/streaming/impls/jms/pom.xml
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/JmsProducerTest.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/JmsStreamSourceTest.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/context/ActiveMQProviderTest.java
plugins/streaming/impls/jms/src/test/java/org/pentaho/di/trans/step/jms/context/WebsphereMQProviderTest.java
pom.xml

This also removes `mockito-all` from the root pom, leaving it only in the integration tests (which we should probably address in a separate ticket)
We had marked `plugins/file-stream` for update as well, but I wound up skipping that -- this module is not included in the plugins pom, and both the tests and implementation haven't compiled since sometime in 2018 (due to changes in the `StreamSource` class). We should probably remove this instead, but that seemed out of scope for these updates.

[BACKLOG-40921] Update mockito versions in non-failing plugin tests

---

core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
core/src/main/java/org/pentaho/di/connections/ConnectionUpdateSubscriber.java
core/src/main/java/org/pentaho/di/connections/vfs/VFSHelper.java
core/src/main/java/org/pentaho/di/connections/vfs/provider/ConnectionFileSystem.java
core/src/main/java/org/pentaho/di/core/bowl/BaseBowl.java
core/src/main/java/org/pentaho/di/core/bowl/Bowl.java
core/src/main/java/org/pentaho/di/core/bowl/BowlManagerFactoryRegistry.java
core/src/main/java/org/pentaho/di/core/bowl/DefaultBowl.java
core/src/main/java/org/pentaho/di/core/bowl/ManagerFactory.java
core/src/main/java/org/pentaho/di/core/vfs/KettleVFS.java
core/src/main/java/org/pentaho/di/core/vfs/KettleVFSImpl.java
core/src/test/java/org/pentaho/di/connections/ConnectionManagerTest.java
engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
plugins/connections/ui/src/main/java/org/pentaho/di/connections/ui/tree/ConnectionFolderProvider.java
plugins/connections/ui/src/main/java/org/pentaho/di/vfs/connections/ui/dialog/ConnectionDelegate.java
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/ui/RunConfigurationFolderProvider.java
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/ui/RunConfigurationPopupMenuExtension.java
plugins/engine-configuration/impl/src/main/java/org/pentaho/di/engine/ui/RunConfigurationViewTreeExtension.java
plugins/engine-configuration/impl/src/test/java/org/pentaho/di/engine/ui/RunConfigurationDelegateTest.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/vfs/VFSFileProvider.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

- one of each manager per Bowl
- separate bowls for "execution" vs "management" (see also PR for pdi-plugins-ee) Spoon will have "Management" Bowl, each Meta will have "Execution" bowl.
- BowlManagerFactoryRegistry to register new types of managers
- switch ConnectionManager to new APIs

[BACKLOG-40519] - Refactor Bowl, add manager registry

---

assemblies/static/src/main/resources-filtered/purge-utility.bat
assemblies/static/src/main/resources-filtered/purge-utility.sh

Needs more than just `sun.net.www.protocol.jar` because OSGI needs to be able to start up if that's there

[BACKLOG-41085] add-opens for purge-utility on JDK17

---

engine/src/main/java/org/pentaho/di/trans/TransMeta.java

@pentaho/tatooine_dev 
Original PR:
- https://github.com/pentaho/pentaho-kettle/commit/1a0f4dd81fc3dc4192c0078e158825c51c41c820

[SP-6553] - Backport of PDI-19938 - Database Password Field is missing when searching transformation's metadata (9.3 Suite)

---

core/src/main/java/org/pentaho/di/core/Const.java

fail if the required hdfs file system is not present.

[PDI-20140] Add a property to force Hadoop File Input/Output steps to

---

assemblies/static/src/main/resources/ui/menubar.xul
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java
ui/src/main/java/org/pentaho/di/ui/trans/step/BaseStepDialog.java
ui/src/test/java/org/pentaho/di/ui/trans/step/EditConnectionListenerTest.java

- Removed the code in Spoon that is related to share/unshare menu items
- Spoon.saveToFile() and Spoon.saveFile() no longer save the shared objects in shared.xml

[BACKLOG-40795] Removed the share/unshare menu options from the tree.

---

core/src/main/java/org/pentaho/di/core/plugins/PluginFolder.java
ui/src/main/java/org/pentaho/di/ui/spoon/SpoonPluginType.java
ui/src/main/java/org/pentaho/di/ui/spoon/SpoonUiExtenderPluginType.java

This change allows "SpoonPluginType" to be loaded from user specified paths with the **-DKETTLE_PLUGIN_BASE_FOLDERS** option, which also allows this type of plugin to be loaded from ~/.kettle/plugins (user home directory plugins that cross versions).

[PDI-20138] Make SpoonPluginType honor plugins base folder settings

---

core/src/main/java/org/pentaho/di/core/Const.java

[PDI-20086] Add a kettle parameter to control whether we wait for a lock

---

core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/shared/DatabaseConnectionManager.java
engine/src/main/java/org/pentaho/di/shared/DatabaseManagementInterface.java
engine/src/main/java/org/pentaho/di/shared/PassthroughDbConnectionManager.java
engine/src/test/java/org/pentaho/di/shared/DatabaseConnectionManagerTest.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java

- DatabaseConnectionManager makes defensive copies
- added small unit test for this behavior
- changed Comparator in DatabaseMeta to avoid NPEs
- added remove by name method to DatabaseManagementInterface

[BACKLOG-40797] - delete old db on rename

---

plugins/file-open-save-new/core/pom.xml

Jira: https://hv-eng.atlassian.net/browse/PPP-4899
- upgrade eclipse ui workbench version 3.127.0 -> 3.132.0 -- This gets us to commons-io 2.11.0, which is 2.7+, addressing CVE-2021-29425
- libloader case handled in https://github.com/pentaho/pentaho-reporting/pull/1678
```
[INFO] |  +- org.eclipse.platform:org.eclipse.ui.workbench:jar:3.132.0:compile
...
[INFO] |  |  +- org.eclipse.platform:org.eclipse.e4.ui.workbench.swt:jar:0.17.400:compile
...
[INFO] |  |  |  +- org.eclipse.platform:org.eclipse.e4.ui.css.core:jar:0.14.400:compile
[INFO] |  |  |  |  \- org.apache.xmlgraphics:batik-css:jar:1.17:compile
...
[INFO] |  |  |  |     \- org.apache.xmlgraphics:xmlgraphics-commons:jar:2.9:compile
[INFO] |  |  |  |        +- commons-io:commons-io:jar:2.11.0:compile
```
Related PRs: …

[PPP-4899] Vulnerable Component: commons-io

---

core/src/main/java/org/pentaho/di/core/row/value/ValueMetaBase.java

[PDI-17310/PDI-17311] - Currency sign, replaced by currency symbol (¤) specified in Generate Rows/Regex Evaluation step errors out.

---

plugins/rest/core/src/main/java/org/pentaho/di/trans/steps/rest/Rest.java
plugins/rest/core/src/test/java/org/pentaho/di/trans/steps/rest/RestTest.java

The changes to Rest.java are primarily changing UriComponent.Type.QUERY_PARAM to UriComponent.Type.QUERY_PARAM_SPACE_ENCODED so spaces wouldn't be double-encoded, and splitting `callRest()` into several methods so they could be unit tested. 
Github doesn't seem to handle the change well, despite the only changes being indentation for most lines.

[PDI-20159] - prevent double encoding of spaces

---

engine/pom.xml
plugins/excel/core/pom.xml

[SP-6602]-Backport of PPP-4968 - Vulnerable Component: xmlbeans 2.5.0 (10.2 Suite)
[SP-6602]: https://hv-eng.atlassian.net/browse/SP-6602?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6602]-Backport of PPP-4968 - Vulnerable Component: xmlbeans 2.5.0 (10.2 Suite)

---

engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/job/JobMeta.java
engine/src/main/java/org/pentaho/di/job/entry/JobEntryInterface.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java

Fixed clone, which had resulted in the local shared objects being wiped out on both the source and the target
Fixed a call to exportResources that hadn't been updated with a Bowl, resulting in the wrong method being called.

[BACKLOG-42335] - fix calling carte

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/kettle-variables.xml

1. Created the NEW variables names compliant with the standard
2. Added a fallback on the OLD name, and give a ERROR message to the Logs saying that that name is deprecated, and upgrade to the new name

[PDI-20195] - inconsistent variable names recently created

---

assemblies/plugins/pom.xml

Remove pdi-google-analytics-plugin and pentaho-googledrive-vfs-plugin from plugin assemblies

[PPP-4582] Use of Vulnerable Component: Components/oauth_client_library_for_java

---

assemblies/plugins/pom.xml

Remove pdi-google-analytics-plugin and pentaho-googledrive-vfs-plugin from plugin assemblies

[SP-6608] Backport of [PPP-4582] - Use of Vulnerable Component: Components/oauth_client_library_for_java (10.2 Suite)

---

core/src/test/java/org/pentaho/di/core/variables/VariablesTest.java
dbdialog/src/test/java/org/pentaho/ui/database/event/FragmentHandlerTest.java
engine/src/test/java/org/pentaho/di/core/util/AsyncDatabaseActionTest.java
engine/src/test/java/org/pentaho/di/trans/steps/csvinput/CsvInputContentParsingTest.java
engine/src/test/java/org/pentaho/di/www/ExecuteJobServletTest.java
plugins/ivw-bulk-loader/impl/src/test/java/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseTest.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsoninput/analyzer/JsonInputAnalyzerTest.java
plugins/json/core/src/test/java/org/pentaho/di/trans/steps/jsonoutput/analyzer/JsonOutputAnalyzerTest.java
plugins/rest/core/src/test/java/org/pentaho/di/trans/steps/rest/RestTest.java

[BACKLOG-41283]-Upgrading Pentaho kettle from Java EE 9 to Jakarta EE 10
[BACKLOG-41283]: https://hv-eng.atlassian.net/browse/BACKLOG-41283?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-41283]-Upgrading Pentaho kettle from Java EE 9 to Jakarta EE 10

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/java/org/pentaho/di/job/entries/job/JobEntryJob.java
engine/src/main/java/org/pentaho/di/job/entries/trans/JobEntryTrans.java
engine/src/main/resources/kettle-variables.xml

original PRs:
https://github.com/pentaho/pentaho-kettle/pull/9640
https://github.com/pentaho/pentaho-kettle/pull/9714

[SP-6677] - Backport of PDI-20195 - inconsistent variable names recently created (10.2 Suite)

---

ui/src/main/java/org/pentaho/di/ui/i18n/MessagesSourceCrawler.java

[SP-6685]-Backport of PPP-4817 -  Improper Restriction of XML External Entity Reference (10.2 Suite)
[SP-6685]: https://hv-eng.atlassian.net/browse/SP-6685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6685]-Backport of PPP-4817 -  Improper Restriction of XML External Entity Reference (10.2 Suite)

---

plugins/ftps/impl/src/main/resources/org/pentaho/di/job/entries/ftpsput/messages/messages_ja_JP.properties

[SP-6684]-Backport of PDI-20189 - Step (or Job) names are unchanged to Japanese character in PDI. (10.2 Suite)
[SP-6684]: https://hv-eng.atlassian.net/browse/SP-6684?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[SP-6684]-Backport of PDI-20189 - Step (or Job) names are unchanged to Japanese character in PDI. (10.2 Suite)

---

dbdialog/src/main/java/org/pentaho/ui/database/event/DataHandler.java
engine/src/main/java/org/pentaho/di/job/JobMeta.java
engine/src/main/java/org/pentaho/di/job/entries/tableexists/JobEntryTableExists.java
ui/src/main/java/org/pentaho/di/ui/core/database/dialog/DataOverrideHandler.java

Exception was caused by an array with a single null member. Fixed both the code that produced it, and added a safety check in the consumer.

[BACKLOG-42865] - fix db edit, exception

---

engine/src/main/java/org/pentaho/di/job/Job.java

the parent.  This reverts the change made for PDI-20199, which will need to be reconsidered.

[PDI-20282] Ensure job status of parallel sub jobs gets passed back to

---

plugins/email-messages/impl/src/main/java/org/pentaho/di/trans/steps/mailinput/MailInputMeta.java

[PDI-19580]-Enable Use of OAUTH for PDI Mail Steps and Entries that use IMAP/SMTP
[PDI-19580]: https://hv-eng.atlassian.net/browse/PDI-19580?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[PDI-19580]-Enable Use of OAUTH for PDI Mail Steps and Entries that use IMAP/SMTP

---

core/src/main/java/org/pentaho/di/core/bowl/BaseBowl.java
core/src/main/java/org/pentaho/di/core/bowl/DefaultBowl.java
core/src/main/java/org/pentaho/di/core/database/DatabaseMeta.java
core/src/main/java/org/pentaho/di/repository/RepositoryElementInterface.java
core/src/main/java/org/pentaho/di/shared/SharedObjectInterface.java
core/src/main/java/org/pentaho/di/shared/VfsSharedObjectsIO.java
engine/src/main/java/org/pentaho/di/cluster/ClusterSchema.java
engine/src/main/java/org/pentaho/di/cluster/SlaveServer.java
engine/src/main/java/org/pentaho/di/partition/PartitionSchema.java
engine/src/main/java/org/pentaho/di/repository/filerep/KettleFileRepository.java
engine/src/main/java/org/pentaho/di/shared/RepositorySharedObjectsIO.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/test/java/org/pentaho/di/shared/RepositorySharedObjectsIOTest.java
engine/src/test/java/org/pentaho/di/trans/steps/loadsave/MemoryRepository.java
engine/src/test/java/org/pentaho/di/trans/steps/loadsave/MemoryRepositoryExtended.java
plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/repository/model/RepositoryDirectory.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/ISharedObjectsTransformer.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/JobDelegate.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/TransDelegate.java
plugins/repositories/core/src/main/java/org/pentaho/di/ui/repo/controller/RepositoryConnectController.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

- RepositorySharedObjectsIO and test
- fixed file-open-save for repositories (partial backport)
- stopped saving or loading shared objects to the repository as part of
transformations or jobs.
- Still links steps to databases
- Keep ObjectId in various Node-based memory structures, but don't store on
disk in VfsSharedObjectsIO
- Reset DefaultBowl managers on connect/disconnect from Repository

[BACKLOG-42827] - CRUD for Global objects in repository

---

engine/src/main/java/org/pentaho/di/trans/steps/fileinput/text/TextFileInputReader.java

A new `TextFileInputReader` is initialized for each input file of several in a step.
Before the creation of the `linesWritten` variable, we used `step.getLinesWritten()` directly, which prevented the count of lines written from being reset when we move on to a new input file (and therefore a new reader).
The changed was done in this PR: https://github.com/pentaho/pentaho-kettle/pull/9200 (because using `step.getLinesWritten()` directly caused other problems regarding the order in which the lines were processed).
For this reason, the only thing we have to do is initialize the count in the new reader as the ongoing count stored in the step.

[PDI-20292] - The count of records is not accurately determined in the Text file input step when multiple input files are used.

---

core/src/main/java/org/pentaho/di/core/Const.java
engine/src/main/resources/kettle-variables.xml

[PDI-20322] -Disable gather performance metrics when scheduling jobs/ktrs from Spoon's schedule perspective

---

core/src/main/java/org/pentaho/di/shared/MemorySharedObjectsIO.java
core/src/main/java/org/pentaho/di/shared/SharedObjectsIO.java
core/src/main/java/org/pentaho/di/shared/VfsSharedObjectsIO.java
engine/src/main/java/org/pentaho/di/shared/BaseSharedObjectsManager.java
engine/src/main/java/org/pentaho/di/shared/RepositorySharedObjectsIO.java
engine/src/test/java/org/pentaho/di/shared/DatabaseConnectionManagerTest.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/AbstractDelegate.java

- change SharedObjectsIO.findSharedObjectIgnoreCase to take a Set instead of a Map so it can be used in more cases.
- Support case renames in BaseSharedObjectManager
- correct RepositorySharedObjectsIO handling of renames (DON'T delete first)
- make sure import identifies name changes as changes.

[BACKLOG-43080] - support case changes on SO import

---

plugins/file-open-save-new/core/src/main/java/org/pentaho/di/plugins/fileopensave/providers/recents/RecentFileProvider.java

- If the .spoonrc file is referring to repolastdir and reposlastfile that does not exist in repository, the FileOpenSave dialog throws an IllegalAccessError which was not caught. Updated the catch to also  catch IllegalAccessError

[BACKLOG-43259] File Open/Save dialog fails to open

---

engine/src/main/java/org/pentaho/di/trans/step/BaseStep.java

This PR addresses the issue described in PDI-20183, where the `MappingOutput` remote steps configuration, done in `Mapping.processRow()`, was being overridden in `BaseStep.openRemoteOutputStepSocketsOnce()`.
- **Issue**: The configuration for `MappingOutput` remote steps was overridden by the logic in `BaseStep.openRemoteOutputStepSocketsOnce()`.
- **Solution**: Added a new exit condition in `BaseStep.openRemoteOutputStepSocketsOnce()` to skip its logic if the step is a `MappingOutput` step.
- **Code Refactoring**: Reduced cognitive complexity in the methods handling remote socket openings to improve readability and maintainability.
For more details, refer to the related issue [PDI-20183](https://jira.pentaho.com/browse/PDI-20183).
[PDI-20183]: …

fix: Prevent MappingOutput configuration override in BaseStep

---

plugins/core/impl/pom.xml

- update commons-io to v2.16.1
QA validation depends on https://github.com/pentaho/pentaho-reporting/pull/1742

[PPP-5589][PPP-5620] Vulnerable Component: commons-io (PDI Core Plugin)

---

engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
engine/src/main/java/org/pentaho/di/job/JobMeta.java
engine/src/main/java/org/pentaho/di/repository/RepositoryImporter.java
engine/src/main/java/org/pentaho/di/shared/BaseSharedObjectsManager.java
engine/src/main/java/org/pentaho/di/shared/ChangeTrackingSharedObjectManager.java
engine/src/main/java/org/pentaho/di/shared/PassthroughManager.java
engine/src/main/java/org/pentaho/di/shared/SharedObjectUtil.java
engine/src/main/java/org/pentaho/di/shared/SharedObjectsManagementInterface.java
engine/src/main/java/org/pentaho/di/trans/TransMeta.java
engine/src/test/java/org/pentaho/di/base/AbstractMetaTest.java
plugins/pur/core/src/main/java/com/pentaho/repository/importexport/StreamToJobNodeConverter.java
plugins/pur/core/src/main/java/com/pentaho/repository/importexport/StreamToTransNodeConverter.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

- copy shared objects from the RepositoryBowl to the TransMeta or JobMeta before export in StreamToJobNodeConverter and StreamToTransNodeConverter.
- Strip object ids from meta before exporting
- move shared objects to RepositoryBowl and fix database connections on import in StreamToJobNodeConverter and StreamToTransNodeConverter
- new API to list names of used database connections from AbstractMeta (more efficient than asking the meta about each connection)
- SharedObjectUtil methods:
- copy used db and all other shared objects into meta from a (Repository) Bowl, for export
- moved patchDatabaseConnections here to use in other import mechanisms
- stripObjectIds, for use before export

[BACKLOG-43081] - import-export.sh working with global/local

---

engine/src/main/java/org/pentaho/di/partition/PartitionSchema.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PartitionDelegate.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonClustersDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonPartitionsDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/delegates/SpoonSlaveDelegate.java

- stop clearing object Id in PartitionSchema.clone
- stop checking for existing object in PartitionDelegate.elementToDataNode (now handled elsewhere)
- standardize on finding existing object ids in a case-insensitive manner for all shared object types in the repository
- Fix Spoon Delegate handling for checking for changed case. Only remove from the backing manager if the name changed *more* than just case.
- Clear the object ID if we're removing and adding to the manager so the repository sees the new object as a new object.

[BACKLOG-43080] - fix name collisions on edit and import

---

plugins/pentaho-reporting/assemblies/plugin/pom.xml

This pull request includes a small change to the `plugins/pentaho-reporting/assemblies/plugin/pom.xml` file. The change adds `ehcache-core` to the list of dependencies.
(cherry picked from commit https://github.com/pentaho/pentaho-kettle/commit/7f7d38b1fd9e1ab316aa5fc4348b658c924ba341)

[SP-6775] fix: add pentaho-repoting plugin missing dependency

---

plugins/json/core/src/main/java/org/pentaho/di/trans/steps/jsonoutput/JsonOutput.java

[BACKLOG-43558] - Json output related sonar changes

[BACKLOG-43558] - Json output related sonar changes

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java

This pull request includes changes to the `PurRepository` class to improve thread safety by adding read locks. The most important changes include adding a read lock at the beginning of the `loadAndCacheSharedObjects` method and unlocking it in the finally block. This will avoid a dead lock happening by making sure that a `readWriteLock` is always obtained before a `sharedObjectsLock`.
Thread safety improvements:
* [`plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java`](diffhunk://#diff-be1e027bd3bdaab8c997a83ea1f1509516efe8727c8c2de3cc1a69d6dd855ed7R1956): Added a read lock at the start of the `loadAndCacheSharedObjects` method to ensure thread safety when reading shared objects.
* [`plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java …

fix: avoid dead lock in `PurRepository.loadAndCacheSharedObject`

---

core/src/main/java/org/pentaho/di/connections/vfs/providers/other/OtherConnectionDetailsProvider.java

fix: DefaultFileSystemConfigBuilder.setUserAuthenticator does not throw Exceptions with 2.10.0 vfs2 [PPP-5649]

---

core/pom.xml

While these dependencies are marked as optional, vfs2 2.10.0 's default provider is Http5FileProvider that needs them

feat[PPP-5649]: add httpclient5 and httpcore5 dependencies

---

plugins/repo-vfs/assemblies/plugin/pom.xml
plugins/repo-vfs/repo-vfs-core/pom.xml

[BACKLOG-44499]-Upgrading repo-vfs plugin to support jersey
[BACKLOG-44499]: https://hv-eng.atlassian.net/browse/BACKLOG-44499?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-44499]-Upgrading repo-vfs plugin to support jersey

---

plugins/pur/core/src/test/java/com/pentaho/di/purge/UnifiedRepositoryPurgeServiceTest.java
plugins/pur/core/src/test/java/com/pentaho/di/revision/RevisionResourceTest.java

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation
[BACKLOG-43098]: https://hv-eng.atlassian.net/browse/BACKLOG-43098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[BACKLOG-43098]-Fixing broken testcases as part of tomcat upgradation

---

engine/src/main/java/org/pentaho/di/base/AbstractMeta.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/RepositoryProxy.java
plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/TransDelegate.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

- Better Repository change handling in AbstractMeta
- Call the ExtensionPoints needed by the projects plugin while loading from the Repository
- Store references to Shared Objects by Name when they don't have an ObjectId, allowing steps and JobEntries to refer to objects from a Project.
- cleaned up some PartitionSchema serialization that was going directly to the repository instead of through the Meta/Bowls.

[BACKLOG-41544] - Spoon execution with Projects in Repository

---

plugins/pur/core/src/main/java/org/pentaho/di/repository/pur/PurRepository.java
ui/src/main/java/org/pentaho/di/ui/spoon/Spoon.java

- allow Spoon.openFile to work on repository paths
- use repository path instead of just filename when opening a repository file from recents.

[BACKLOG-41542] - more support for repository file operations

---

engine/src/main/java/org/pentaho/di/base/MetaFileLoaderImpl.java

Fixes an issue where we were incorrectly passing along parent job params to child transformation. This change was originally introduced for BACKLOG-40920, but is apparently not actually needed to make that work.

[BACKLOG-44621] - revert change to copy parent job variables

---

core/src/main/java/org/pentaho/di/connections/vfs/provider/ConnectionFileSystem.java

origin PR: https://github.com/pentaho/pentaho-kettle/pull/10110

fix[SP-6919]: return default varSpace instead of null

---

core/src/main/java/org/pentaho/di/connections/ConnectionManager.java
core/src/main/java/org/pentaho/di/core/bowl/BowlManagerFactoryRegistry.java
core/src/main/java/org/pentaho/di/core/bowl/CachingManager.java
core/src/main/java/org/pentaho/di/core/bowl/CachingManagerFactory.java
core/src/main/java/org/pentaho/di/core/bowl/UpdateSubscriber.java
core/src/test/java/org/pentaho/di/connections/ConnectionManagerTest.java
engine/src/main/java/org/pentaho/di/core/KettleEnvironment.java
engine/src/main/java/org/pentaho/di/shared/BaseSharedObjectsManager.java
engine/src/test/java/org/pentaho/di/shared/DatabaseConnectionManagerTest.java

That opt in. This cache invalidation makes sure that changes made in parent/"management" bowls propagate to child/execution bowls that need to see those changes.

[BACKLOG-44645] - extend cache invalidation to all managers
