ui/src/org/pentaho/di/ui/core/namedconfig/NamedConfigurationWidget.java
=> [BACKLOG-974] Made NamedConfigurationWidget not editable and added a

core/src/org/pentaho/di/core/row/RowMeta.java, core/test-src/org/pentaho/di/core/row/RowMetaAddRemoveValueTest.java, core/test-src/org/pentaho/di/core/row/RowMetaTest.java, engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInput.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/PDI5436Test.java, engine/test-src/org/pentaho/di/trans/steps/denormaliser/DenormaliserAggregationsTest.java, engine/test-src/org/pentaho/di/trans/steps/fuzzymatch/FuzzyMatchTest.java, engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInputFieldsTest.java, engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java
Applied original MC path and additional fixes to this path.
This is ambiguous commits and possibly can bring some regressions.
See commits descriptions and junit tests results.
=> PDI-13204 - RowMeta indexOfValue method works in O(n) time

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterMetaInjection.java
Minor fix to prevent NPE when setting Boolean values ...
=> [PDI-9289] Setting a null Boolean results in NPE

engine/src/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseLoader.java
@mattyb149 would you mind to review/merge again, please
pull-request https://github.com/pentaho/pentaho-kettle/pull/907 has generated several failures in the  org.pentaho.di.trans.steps.ivwloader.IngresVectorwiseTest class.
Here the commit that corrects situation.
=> PDI-12555 - changes for VWloadMonitor correct work

core/src/org/pentaho/di/core/database/SqlCommentScrubber.java
// Make sure that the next character isn't a + which identifies a hint in Oracle (PDI-13054)
=> [PDI-13054] Update SqlCommentScrubber.java

core/src/org/pentaho/di/core/namedcluster/model/NamedCluster.java, ui/src/org/pentaho/di/ui/core/namedcluster/dialog/NamedClusterComposite.java
=> [PDI-13379] Password is not secure in new "Named cluster" dialog

core/src/org/pentaho/di/core/namedcluster/NamedClusterManager.java, core/src/org/pentaho/di/core/namedcluster/model/NamedCluster.java, ui/src/org/pentaho/di/ui/core/namedcluster/dialog/NamedClusterComposite.java
=> [PDI-13378] Cannot set variable as port number in new "Named cluster"

engine/src/org/pentaho/di/trans/steps/monetdbbulkloader/MonetDBBulkLoaderMeta.java
[BACKLOG-1950] - Not able to create an Instaview project
=> [BACKLOG-1950] - Not able to create an Instaview project

core/src/org/pentaho/di/core/row/RowMeta.java, core/test-src/org/pentaho/di/core/row/RowMetaTest.java
Cherry pick from master #970 and #972
=> [PDI-13394]: Only index ValueMetas with non-null names

engine/ivy.xml, ui/src/org/pentaho/di/ui/core/widget/TableView.java, ui/src/org/pentaho/di/ui/spoon/job/JobHistoryDelegate.java, ui/src/org/pentaho/di/ui/spoon/trans/TransHistoryDelegate.java
there are three commits:
1. small fix to Ivy.xml (not actually related to the fix)
2. checkstyle fix for subsequent smooth merge
3. backport of fix for http://jira.pentaho.com/browse/PDI-4589 (cherry pick of this commit https://github.com/pentaho/pentaho-kettle/pull/126) which fixes also the PDI-11768.
no unit tests since this is UI fix.
@mattyb149 would you mind to review since you were who merged the original fix.
@hudak @brosander
=> [SP-1172] - Backport of PDI-11768 - Log distorted after overwriting the job using "Save As" in spoon 5.0.x (5.0)

engine/src/org/pentaho/di/job/entries/snmptrap/JobEntrySNMPTrap.java, engine/test-src/org/pentaho/di/job/entries/snmptrap/JobEntrySNMPTrapTest.java
@brosander , @mattyb149 please, review it
=> [PDI-13332] Send SNMP Trap job entry does not encrypt passphrase

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/PrimitiveIntArrayLoadSaveValidator.java
save sizeFieldName attribute
@mbatchelor please review
=> [PDI-13260] - Excel-Input Step does not save all properties

core/src/org/pentaho/di/core/jdbc/ThinConnection.java, core/src/org/pentaho/di/core/jdbc/ThinDriver.java, core/test-src/org/pentaho/di/core/jdbc/ThinDriverTest.java
http://jira.pentaho.com/browse/PDI-13411
@mattyb149
=> [PDI-13411]ThinDriver returns null on connect when URL is not accepted

assembly/package-res/spoon.sh
@rmansoor, would you mind review/merge?
Additionally (beside the main fix): 
Some variables were changed to avoid complication while switching between catalogs.
Now at the end of spoon.sh script we are returning to initial catalog to ensure that user will be in the same directory as before running spoon.sh file.
=> [PDI-13365] - Spoon.sh: unable to run Spoon outside the spoon home dir

ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/test-src/org/pentaho/di/ui/spoon/SpoonTest.java
@mattyb149,  could you review and merge this backport  for https://github.com/pentaho/pentaho-kettle/pull/979
=> [SP-1692][PDI-13358] Copying Step with Error Handling Defined Leaves Wrong Step Name in Error Handling Settings

core/src/org/pentaho/di/cluster/SlaveConnectionManager.java, engine/src/org/pentaho/di/cluster/SlaveServer.java, engine/src/org/pentaho/di/www/Carte.java, engine/src/org/pentaho/di/www/RegisterSlaveServlet.java, engine/src/org/pentaho/di/www/SlaveServerConfig.java, engine/src/org/pentaho/di/www/SslConfiguration.java, engine/src/org/pentaho/di/www/WebServer.java, engine/test-src/org/pentaho/di/www/WebServerTest.java, ui/src/org/pentaho/di/ui/cluster/dialog/SlaveServerDialog.java, ui/src/org/pentaho/di/ui/cluster/dialog/messages/messages_en_US.properties
=> BACKLOG-2150

core/src/org/pentaho/di/core/encryption/CertificateGenEncryptUtil.java, core/test-src/org/pentaho/di/core/encryption/CertificateGenEncryptUtilTest.java, engine/src/org/pentaho/di/trans/TransMeta.java, engine/src/org/pentaho/di/trans/cluster/TransSplitter.java, engine/src/org/pentaho/di/trans/step/RemoteStep.java
What was done:
1) added initial functionality: key generation, session key encryption \
sharing
2) added rmote step encryption support
3) added unit tests for encoding \ decoding keys and random keys
generation
=> BACKLOG-2041 -- Create encrypted data transfer flow

ui/src/org/pentaho/di/ui/job/entries/xmlwellformed/JobEntryXMLWellFormedDialog.java
Fix an issue where the Wildcard field is not properly set when opening the dialog window
=> [PDI-12521] - Well Formed XML Dialog Wildcard

core/test-src/org/pentaho/di/core/encryption/CertificateGenEncryptUtilTest.java, engine/src/org/pentaho/di/trans/cluster/TransSplitter.java
What was done:
1) added dummy code to catch block of unit tests to make codestyle happy
2) removed unnecessary import after refactor
=> BACKLOG-2041 - Create encrypted data transfer flow

engine/src/org/pentaho/di/www/CarteServlet.java
Register Carte servlets as they become available.
http://jira.pentaho.com/browse/BACKLOG-632
@pentaho-nbaker
=> [BACKLOG-632]PluginTypeListener for Carte servlets

engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInput.java, engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInput_PDI_13435_Test.java
@mattyb149, @brosander,
please review the PR
=> [PDI-13435] - Mapping (sub-transformation) step returns an error

ui/src/org/pentaho/di/ui/trans/steps/accessoutput/AccessOutputDialog.java
Update the transformation step as being updated with the Commit Size dialog has been modified.
=> [PDI-13534] Access Output Commit Size Change

ui/src/org/pentaho/di/ui/trans/steps/randomvalue/RandomValueDialog.java
Fix an issue where setChanged wasn't called when a field's Type setting was updated in the Dialog window
=> [PDI-13523] Random Value track UI changes

engine/src/org/pentaho/di/trans/steps/propertyinput/PropertyInput.java
What was done:
1) changed the way we load properties from file -- removed intermediate
File usage and switched to direct InputStream use
2) no unit test is applied as we need a network share and heavy
refactoring of the code
3) It was manually tested on windows with the following scenarios: win ini
file both local and share, properties files both share and local
=> PDI-8746 -- Unable to use Windows UNC path in Property Input Step

engine/src/org/pentaho/di/job/entries/getpop/MailConnection.java
What was done:
1) changed java.io.File to KettleVFS
2) no unit tests available as we need network share for that
3) manually tested both network and local folder
=> PDI-10088 - UNC path does not work in Get mails(POP3/IMAP) step

engine/src/org/pentaho/di/job/JobMeta.java
initialize kettle.properties when load job from XML
@mbatchelor please review
=> [PDI-13510] - Database Logging does not log Jobs when Executing Remotely

engine/src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesAddedFunctions.java, test/org/pentaho/di/trans/steps/scriptvalues_mod/JavaScriptSpecialTest.java
Fix an issue where adding weekdays to a date improperly calculated Saturday and Sunday
=> [PDI-13486] Javascript DateAdd Weekday Calculation

engine/src/org/pentaho/di/core/compress/CompressionOutputStream.java, engine/src/org/pentaho/di/core/compress/zip/ZIPCompressionOutputStream.java, engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java, engine/test-src/org/pentaho/di/core/compress/CompressionOutputStreamTest.java, engine/test-src/org/pentaho/di/core/compress/gzip/GZIPCompressionOutputStreamTest.java, engine/test-src/org/pentaho/di/core/compress/snappy/SnappyCompressionOutputStreamTest.java, engine/test-src/org/pentaho/di/core/compress/zip/ZIPCompressionOutputStreamTest.java
@mattyb149, @brosander review it please
=> [PDI-13532] - Regression: Text file output creates bad zip files

ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
=> [BACKLOG-2264] - Fix for inject tooltip

core/src/org/pentaho/di/core/row/ValueMeta.java, core/src/org/pentaho/di/core/row/value/ValueMetaBase.java, core/src/org/pentaho/di/core/xml/XMLHandler.java, core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java, core/test-src/org/pentaho/di/core/xml/XMLHandlerUnitTest.java
@mattcasters, @brosander, @mattyb149
Could you review and merge it?
Thanks.
=> [PDI-13524] Log table issue when using Timestamp in transformation

core/test-src/org/pentaho/di/core/row/RowMetaTest.java, core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java
@kurtwalker,
It is fix for failed test, could you merge it?
=> [TEST] Fix failed test + checkstyle

engine/test-src/org/pentaho/di/trans/steps/dummytrans/DummyTransTest.java, test/org/pentaho/di/core/util/StringEvaluatorTest.java
=> [TEST] Fixed DummyTransTest and StringEvaluatorTest

engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java, ui/src/org/pentaho/di/ui/trans/steps/csvinput/CsvInputDialog.java
Resolves issue for old Mac line endings (\r) in step dialog window
=> PDI-695 - Freeze in "Get Fields" in CSV File Input

src/org/pentaho/di/job/Job.java
Backport of PDI-12318.
modified:   src/org/pentaho/di/job/Job.java
=> SP-1428 - Backport of PDI-12318 - NullPointerException running job with massive parallel Job/Transformation loads (4.8)

engine/src/org/pentaho/di/trans/TransMeta.java, engine/test-src/org/pentaho/di/trans/TransMetaTest.java
@mbatchelor, @mattcasters could you review it?
It may be related to PDI-13455 - It is possible to save empty jobs and transformations into the repository.
=> PDI-13452 - Automatic Documentation Output Step fails when receiving a reference that doesn't have any steps in it

engine/src/org/pentaho/di/trans/TransMeta.java, engine/test-src/org/pentaho/di/trans/TransMetaTest.java
@mbatchelor, @mattcasters could you review it?
It is backport https://github.com/pentaho/pentaho-kettle/pull/1022
=> [SP-1772] PDI-13452 - Automatic Documentation Output Step fails when receiving a reference that doesn't have any steps in it

core/src/org/pentaho/di/core/row/ValueMeta.java, core/src/org/pentaho/di/core/row/value/ValueMetaBase.java, core/src/org/pentaho/di/core/xml/XMLHandler.java, core/test-src/org/pentaho/di/core/row/RowMetaTest.java, core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java, core/test-src/org/pentaho/di/core/xml/XMLHandlerUnitTest.java
@brosander, @kurtwalker Could you review and merge the backport of https://github.com/pentaho/pentaho-kettle/pull/1090 for 5.3?
=> [SP-1729] - Backport of PDI-13524 - Log table issue when using Timestamp in transformation (5.3 Suite)	

build.xml
Add kettle multimodule build targets for continuous-sonar and build-sonar.
Also build-testless and continuous-testless convenience targets.
=> [ENGOPS-1014]

core/src/org/pentaho/di/core/extension/KettleExtensionPoint.java, engine/src/org/pentaho/di/trans/CheckStepsExtension.java, engine/src/org/pentaho/di/trans/TransMeta.java
to allow special handling of step validation:
BeforeCheckSteps/AfterCheckSteps/BeforeCheckStep/AfterCheckStep
@mattyb149 @deinspanjer
=> [BACKLOG-2443]  Adding 4 extension points to the ExtensionPointInterface

engine/src/org/pentaho/di/core/gui/AreaOwner.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/spoon/job/JobGraph.java, ui/src/org/pentaho/di/ui/spoon/trans/DelayTimer.java, ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
=> [BACKLOG-2264] - Keep menu open while the mouse stays hovered on the icon or context menu area

core/test-src/org/pentaho/di/core/row/value/ValueMetaStringTest.java, engine/test-src/org/pentaho/di/trans/steps/ifnull/IfNullTest.java, engine/test-src/org/pentaho/di/trans/steps/nullif/NullIfTest.java, engine/test-src/org/pentaho/test/util/FieldAccessor.java
@mattyb149 view it please
They passes as is.
But there are conditions that seem doubtful. The lines are marked with TODOs.
step tests FormulaTest and DataGridTest are not included here but they will follow soon.
=> PDI-13541 KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL setting is not respected properly

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInputMetaInjection.java, engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputMetaInjectionTest.java
The test is much bigger than the fix itself :)
=> [PDI-13405] - Text File Input doesn't support encoding injection

core/src/org/pentaho/di/core/database/DatabaseMeta.java, core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java, engine/src/org/pentaho/di/cluster/SlaveServer.java, engine/test-src/org/pentaho/di/cluster/SlaveServerTest.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonSlaveDelegate.java
cherry-pick https://github.com/pentaho/pentaho-kettle/pull/1099
=> SP-1744 - Backport of PDI-13544 - Spoon allows user to create duplicate connection and slave server x (5.3 Suite)

assembly/build.properties, assembly/ivy.xml
=> [BACKLOG-2457] - Updated dependency to point to the last artefact

engine/src/org/pentaho/di/job/entries/dtdvalidator/JobEntryDTDValidator.java, engine/src/org/pentaho/di/job/entries/writetolog/JobEntryWriteToLog.java, engine/test-src/org/pentaho/di/job/entries/dtdvalidator/JobEntryDTDValidatorLoadSaveTest.java, engine/test-src/org/pentaho/di/job/entries/writetolog/JobEntryWriteToLogLoadSaveTest.java, engine/test-src/org/pentaho/di/trans/steps/abort/AbortMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/blockingstep/BlockingStepMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/changefileencoding/ChangeFileEncodingMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/clonerow/CloneRowMetaTest.java, ui/src/org/pentaho/di/ui/job/entries/writetolog/JobEntryWriteToLogDialog.java
Added Load Save Tests for:
* Write to Log job entry
* DTD Validator job entry
* Abort step
* Blocking step
* Change File Encoding step
* Clone Row step
=> [TEST] New Load Save Tests

core/test-src/org/pentaho/di/core/row/value/ValueMetaStringTest.java, engine/test-src/org/pentaho/di/trans/steps/ifnull/IfNullTest.java, engine/test-src/org/pentaho/di/trans/steps/nullif/NullIfTest.java, engine/test-src/org/pentaho/test/util/FieldAccessor.java, test/org/pentaho/di/trans/steps/datagrid/DataGridTest.java, test/org/pentaho/di/trans/steps/formula/FormulaTest2.java, test/org/pentaho/test/util/FieldAccessorUtl.java
KETTLE_EMPTY_STRING_DIFFERS_FROM_NULL setting is not respected properly (5.3 Suite)
@mattyb149 could you review it, please?
=> [SP-1735] Backport of PDI-13541 - 

engine/src/org/pentaho/di/trans/TransMeta.java, engine/src/org/pentaho/di/trans/step/StepMetaChangeListenerInterface.java, engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java, engine/test-src/org/pentaho/di/trans/TransTest.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonStepsDelegate.java
Decision the resubmit. For looking how it goes.
=> PDI-13367 - ETL Metada Injection does not actualize the Source Step in the Inject Metadata tab when renaming the cited step

engine/src/org/pentaho/di/core/gui/SwingDirectGC.java, engine/src/org/pentaho/di/core/gui/SwingGC.java
=> [BACKLOG-2267] - Added missed colours

core/src/org/pentaho/di/core/svg/SvgSupport.java
@mdamour1976  please review.
These changes include fix for using SvgSupport in multiple threads environment. I've mentioned about the issue with AutoDoc step on today meeting. It was caused by this bug.
=> [BACKLOG-2267] - Fix for document factory and multiple threads

core/src/org/pentaho/di/core/database/PostgreSQLDatabaseMeta.java, test/org/pentaho/di/core/database/SequenceMetaTests.java, ui/src/org/pentaho/di/ui/trans/steps/addsequence/AddSequenceDialog.java
Add an override to return the necessary SQL to get the list of database sequences
=> [PDI-13592] "Add Sequence" UI issue for Postgres

core/src/org/pentaho/di/core/logging/KettleLogStore.java, core/src/org/pentaho/di/core/logging/LogChannelFactory.java, core/src/org/pentaho/di/core/logging/LogChannelInterfaceFactory.java, engine/src/org/pentaho/di/trans/step/BaseStep.java, engine/test-src/org/pentaho/di/trans/step/BaseStepTest.java, engine/test-src/org/pentaho/di/trans/steps/abort/AbortTest.java, engine/test-src/org/pentaho/di/trans/steps/dummytrans/DummyTransTest.java, engine/test-src/org/pentaho/di/trans/steps/mock/StepMockHelper.java, test/org/pentaho/di/trans/steps/mapping/MappingTest.java, testfiles/org/pentaho/di/trans/steps/mapping/pdi-13435/PDI-13435-main.ktr, testfiles/org/pentaho/di/trans/steps/mapping/pdi-13435/PDI-13435-sub-p1.ktr, testfiles/org/pentaho/di/trans/steps/mapping/pdi-13435/PDI-13435-sub-p2.ktr
Mapping (sub-transformation) step returns an error (5.0 Suite)
@mattyb149 could you review it?
=> [SP-1694] Regression PDI-13435 - 

ui/src/org/pentaho/di/ui/core/gui/GUIResource.java, ui/src/org/pentaho/di/ui/util/SwtSvgImageUtil.java
=> [BACKLOG-2157] PDI SVG/PNG image loading improvement

engine/src/org/pentaho/di/core/gui/SwingDirectGC.java, engine/src/org/pentaho/di/core/gui/SwingGC.java
=> [BACKLOG-2269] - Fix icon size for Swing GC

assembly/package-res/ui/menubar.xul
@mattyb149 could you review, please
=> PDI-13491 - Authentication Manager not saving connection

core/src/org/pentaho/di/core/gui/PrimitiveGCInterface.java, engine/src/org/pentaho/di/core/gui/GCInterface.java, engine/src/org/pentaho/di/core/gui/SwingDirectGC.java, engine/src/org/pentaho/di/core/gui/SwingGC.java, engine/src/org/pentaho/di/job/JobPainter.java, engine/src/org/pentaho/di/trans/TransPainter.java, ui/src/org/pentaho/di/ui/spoon/SWTDirectGC.java, ui/src/org/pentaho/di/ui/spoon/SWTGC.java
=> [BACKLOG-2269] - Add methods with default magnification to provide compatibility with plugins

engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java, engine/src/org/pentaho/di/trans/steps/transexecutor/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMetaTest.java
[BACKLOG-2903] - TransExecutor step does not report origin for fields it creates
=> [BACKLOG-2903] - TransExecutor step does not report origin for fields it creates

core/src/org/pentaho/di/core/row/value/ValueMetaBase.java, core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseSerializationTest.java
=> [PDI-13136] - deserialize to file timezone problem

engine/src/org/pentaho/di/trans/steps/dimensionlookup/DimensionCache.java, engine/test-src/org/pentaho/di/trans/steps/dimensionlookup/DimensionCacheTest.java
=> [PDI-13508] NPE in DimensionCache class after update to Java 1.7u76

ui/src/org/pentaho/di/ui/job/entries/ftp/JobEntryFTPDialog.java, ui/src/org/pentaho/di/ui/job/entries/ftpput/JobEntryFTPPUTDialog.java, ui/src/org/pentaho/di/ui/job/entries/ftpsget/JobEntryFTPSGetDialog.java, ui/src/org/pentaho/di/ui/job/entries/ftpsput/JobEntryFTPSPUTDialog.java, ui/src/org/pentaho/di/ui/job/entries/sftp/JobEntrySFTPDialog.java, ui/src/org/pentaho/di/ui/job/entries/sftpput/JobEntrySFTPPUTDialog.java
pressing ОйОнtest connectionОйОн button
What was done:
1) removed additional dialog when Test Folder button is pressed
=> PDI-11388 -- FTP job steps: inconsistency in messages, shown after

engine/src/org/pentaho/di/job/entries/getpop/JobEntryGetPOP.java, engine/src/org/pentaho/di/job/entries/getpop/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/job/entries/ftp/JobEntryFTPTest.java, engine/test-src/org/pentaho/di/job/entries/ftp/TestUtils.java, engine/test-src/org/pentaho/di/job/entries/getpop/JobEntryGetPOPTest.java, engine/test-src/org/pentaho/di/utils/FileUtilsTest.java, engine/test-src/org/pentaho/di/utils/TestUtils.java
Create attachments folder if it doesn't exist and "Create folder" setting is enabled in the job entry.
=> [PDI-11943] - Get Mail Job Entry Attachments

core/build.properties, core/ivy.xml, ui/build.properties, ui/build.xml
=> [BACKLOG-3031] - Move laf.properties back to ui jar & add kettle core dependencies

ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/test-src/org/pentaho/di/ui/spoon/SpoonActiveJobGraphTest.java
@mattyb149, @brosander please review
=> [BACKLOG-3014] - Closing a transformation or job when connect to DI Server

engine/test-src/org/pentaho/di/trans/steps/loadsave/MemoryRepository.java
@mattyb149 found this not implemented while adding LoadSaveTest for spark-submit
=> [TEST] Implemented MemoryRepository.countNrJobEntryAttributes() method.

assembly/package-res/yarn.sh, core/src/org/pentaho/di/core/Const.java, ui/src/org/pentaho/di/ui/core/ConstUI.java, ui/src/org/pentaho/di/ui/core/FormDataBuilder.java, ui/src/org/pentaho/di/ui/core/WidgetUtils.java, ui/src/org/pentaho/di/ui/core/widget/CheckBox.java, ui/src/org/pentaho/di/ui/core/widget/ControlSpaceKeyAdapter.java, ui/src/org/pentaho/di/ui/core/widget/Input.java, ui/src/org/pentaho/di/ui/core/widget/InputButton.java, ui/src/org/pentaho/di/ui/core/widget/InputText.java, ui/src/org/pentaho/di/ui/core/widget/InputTextVar.java, ui/src/org/pentaho/di/ui/job/dialog/JobDialog.java, ui/src/org/pentaho/di/ui/job/entry/JobStepDialog.java
refactored
more widgets added (for pentaho-yarn-kettle-plugin)
=> BACKLOG-2353 Allow repositories.xml, shared.xml , kettle.properties to be sent to YARN cluster

assembly/build-res/subfloor.xml, build-res/subfloor.xml, core/build-res/subfloor.xml, dbdialog/build-res/subfloor.xml, engine/build-res/subfloor.xml, plugins/kettle-gpload-plugin/build-res/subfloor.xml, plugins/kettle-hl7-plugin/build-res/subfloor.xml, plugins/kettle-openerp-plugin/build-res/subfloor.xml, plugins/kettle-palo-plugin/build-res/subfloor.xml, plugins/kettle5-log4j-plugin/build-res/subfloor.xml, plugins/market/build-res/subfloor.xml, plugins/star-modeler/build-res/subfloor.xml, ui/build-res/subfloor.xml
Merge of master into future-develop
=> Auto-Merge refreshing development branch

engine/src/org/pentaho/di/trans/steps/googleanalytics/messages/messages_en_US.properties, ui/src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialog.java
Properly substitute and decrypt variables stored in the AppName, Email, Password, and API Key fields when using the "Get Profiles" UI button
=> [PDI-13728] Google Analytics Dialog Variables

ui/src/org/pentaho/di/ui/trans/steps/jobexecutor/JobExecutorDialog.java
Fixes the browse files dialog, to filter for job files instead of transformations
=> [PDI-13178] Job Executor Browse File Filter

ui/src/org/pentaho/di/ui/trans/steps/mysqlbulkloader/MySQLBulkLoaderDialog.java
Flag the transformation as being changed if the checkboxes are modified.
=> [PDI-13300] MySQL BulkLoad dialog buttons

engine/src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderMeta.java, engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderMetaTest.java
Fix a repository issue where the field format is not saved to the repository
=> [PDI-8460] MySQLBulkLoaderMeta Test

engine/src/org/pentaho/di/trans/steps/groupby/GroupByMeta.java, engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByTest.java
Fix GroupByMeta to properly include Percentile aggregates when getting list of output fields for subsequent steps
=> [PDI-13584] Group By step not showing Percentile

build.xml, engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java, engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputMeta.java, test/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputSplittingTest.java, testfiles/org/pentaho/di/trans/steps/textfileoutput/pdi-12847.ktr
=> [PDI-12847] - TextFileOutput step splits the rows incorrectly

assembly/build.properties, assembly/ivy.xml
Package spark plugin
@mattyb149 @smaring @lgrill-pentaho
=> [BAD-170] Support for Spark

assembly/package-res/samples/jobs/Spark Submit/Spark submit.kjb
Sample job for spark submit job entry
=> [BAD-201] Create and Document Spark samples

core/src/org/pentaho/di/core/database/DatabaseInterface.java
=> [BACKLOG-3098] - Added javadoc missing parameter

engine/src/org/pentaho/di/core/plugins/StepPluginType.java, engine/src/org/pentaho/di/trans/step/messages/messages_en_US.properties
=> [BACKLOG-2454] - Added step folder for BA Server utils steps

ui/src/org/pentaho/di/ui/trans/step/BaseStepDialog.java
=> [BACKLOG-2192] - UX recommendations for Hadoop clusters UIs

ui/src/org/pentaho/di/ui/trans/steps/selectvalues/SelectValuesDialog.java
Flag when "Include Unspecified Fields" checkbox value is modified
=> [PDI-13768] Select Values Dialog flag when changed

ui/src/org/pentaho/di/ui/spoon/Spoon.java
@mattyb149 @mattcasters please review and merge
=> [PDI-13734] added the 'changed' flag setting after 'Clusterings' dialog invocation

ui/src/org/pentaho/di/ui/spoon/Spoon.java
picked from https://github.com/pentaho/pentaho-kettle/pull/1273
@mattyb149 @mattcasters please review and merge
=> [SP-1842][PDI-13734] added the 'changed' flag setting after 'Clusterings' dialog

core/src/org/pentaho/di/core/extension/KettleExtensionPoint.java, ui/src/org/pentaho/di/ui/repository/RepositoryExtension.java
=> [BACKLOG-3255] Cleanup some interactions with the Data Services

ui/src/org/pentaho/di/ui/job/entry/JobStepDialog.java
=> BACKLOG-2358 UX mocks for Copy files to carte Yarn cluster

engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInputMeta.java
=> [BACKLOG-1929] Dev - UI updates

engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java, engine/src/org/pentaho/di/trans/steps/groupby/GroupByMeta.java, engine/test-src/org/pentaho/di/trans/steps/groupby/GroupBySingleThreadedExecutionTest.java, engine/test-src/org/pentaho/di/trans/steps/stepsmetrics/StepMetricsSingleThreadedExecutionTest.java, engine/test-src/org/pentaho/test/util/SingleThreadedExecutionGuarder.java
=> [PDI-12749] - PMR: Bad Results in Group-By if an entire key is filtered earlier

core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
@mattyb149, @brosander, @deinspanjer, review it please.
This fixes the test for Windows, where Const.CR is \r\n
=> [TEST] - Fixing DatabaseUnitTest for Windows

ui/src/org/pentaho/di/ui/trans/debug/TransDebugDialog.java
=> [BACKLOG-3425] - Debug transformation doesn't display step icons

assembly/package-res/samples/jobs/Spark Submit/Spark submit.kjb
=> [BAD-272][CLEANUP] Remove spark.yarn.jar param, should be set in spark config instead

assembly/package-res/spoon.sh, assembly/package-res/yarn.sh
What was done:
1) added variable to indicate we are in YARn mode so not to use hardcoded
value
=> BACKLOG-3367  -- "Stop Yarn cluster" step is failing

engine/src/org/pentaho/di/job/entries/job/JobEntryJob.java
=> [BACKLOG-3559] NPE while running master job if referenced job contains

core/src/org/pentaho/di/core/util/StringUtil.java, engine/src/org/pentaho/di/job/entries/copyfiles/JobEntryCopyFiles.java
=> [BAD-290] Error appears if variables is used in both named cluster and

engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInputFieldsTest.java
- add environment initialisation to let the class be executed separately
- remove artificial plugins from the registry in the end
=> [TEST] - small changes in MappingInputFieldsTest

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java, plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMeta.java, plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/messages/messages_en_US.properties, plugins/googleanalytics/src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialog.java
Also updated some UI elements like tooltips, and removed unused code/messages, etc.
=> [PDI-13875] Added defensive code for missing dims/metrics

core/src/org/pentaho/di/core/row/ValueMeta.java, core/test-src/org/pentaho/di/core/row/ValueMetaTest.java
Remove the interface implementation, as the super class already implements the same interface
=> [PDI-13418] ValueMeta constants issue with UDJC

core/src/org/pentaho/di/core/plugins/PluginRegistry.java, core/test-src/org/pentaho/di/core/plugins/PluginRegistryConcurrencyTest.java
Actually, I suppose more precise solution should include fields' grouping and using separate locks for their utilisation. But better and much simplier just to re-implement the class :)
=> [Pdi 13756] - ConcurrentModificationException in plugin registry

engine/src/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRows.java, test/org/pentaho/di/trans/steps/splitfieldtorows/SplitFieldToRowsTest.java
@mattcasters, @brosander, @mattyb149 Could you review it, please? Thanks!
=> [PDI-11477] Split field to rows step omit trailing empty values

engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta_GetFields_Test.java
- use renaming always if they are specified
- add a unit test
=> [PDI-10600] - Merge Join breaks metadata of sub-transformation

build.xml, engine/src/org/pentaho/di/trans/TransMeta.java, engine/test-src/org/pentaho/di/trans/TransMetaTest.java, test/org/pentaho/di/trans/TransMeta_PDI_13634_Test.java, testfiles/org/pentaho/di/trans/pdi-13634-internal.ktr, testfiles/org/pentaho/di/trans/pdi-13634.ktr
1) pass cloned instance of RowMeta to StepMeta when retrieving fields
2) add a unit test for this change
3) add an integration test for real case
=> SP-1825 - Backport of PDI-13634 - GetFields Exception when multiple Stream Lookups in Simple Mapping (5.4 Suite)

engine/src/org/pentaho/di/trans/steps/sftpput/SFTPPut.java, engine/test-src/org/pentaho/di/trans/steps/sftpput/SFTPPutTest.java
- replace < with ==
- extract methods and add test cases for them
=> [PDI-13916] - SFTPPut step incorrectly checks input settings

engine/src/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStream.java, engine/test-src/org/pentaho/di/trans/steps/xmlinputstream/XMLInputStreamTest.java
There is a fix for attributes and EndElement also.
It's added unit tests.
=> [PDI-13713]: XML Input StAX reader doesn't add namespace info on attributes

core/src/org/pentaho/di/core/plugins/PluginRegistry.java, core/test-src/org/pentaho/di/core/plugins/PluginRegistryConcurrencyTest.java
=> SP-1856 - Backport of PDI-13756 - ConcurentModificationException in plugin registry (5.4 Suite)

core/src/org/pentaho/di/core/database/Database.java, core/src/org/pentaho/di/core/database/map/DatabaseConnectionMap.java, core/test-src/org/pentaho/di/core/database/DatabaseConnectingTest.java
make connections' map a CHM instance
eagerly initialize singleton
improve concurrency correctness by marking counters with 'volatile'
add an integration test
=> SP-1841 - Backport of PDI-12717 - Race condition in database connection creation (5.4 Suite)

engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta_GetFields_Test.java
use renaming always if they are specified
add a unit test
=> SP-1821 - Backport of PDI-10600 - Merge Join breaks metadata of sub-transformation (5.4 Suite)

build.xml, engine/src/org/pentaho/di/core/gui/JobTracker.java, engine/test-src/org/pentaho/di/core/gui/JobTrackerConcurrencyTest.java, engine/test-src/org/pentaho/di/core/gui/JobTrackerTest.java, test/org/pentaho/di/concurrency/ConcurrencyTestRunner.java, test/org/pentaho/di/concurrency/ExecutionResult.java, test/org/pentaho/di/concurrency/JobTrackerConcurrencyTest.java, test/org/pentaho/di/concurrency/PluginRegistryConcurrencyTest.java, test/org/pentaho/di/concurrency/StopOnErrorCallable.java
I've put two commits into this PR. The first is the fix itself with several tests.
The second is a kind of refactoring in tests. I noticed, that both concurrent tests have similar runners. Thus it makes sense to generalise it, separating runner from tests logic.
=> [PDI-13637] NPE when running looping transformation - at org.pentaho.di.core.gui.JobTracker.getJobTracker(JobTracker.java:125)

ui/src/org/pentaho/di/ui/core/dialog/AboutDialog.java, ui/src/org/pentaho/di/ui/core/dialog/Splash.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java
@mdamour1976  review it please.
=> [BACKLOG-3941] - Update Help->About to use splashscreen instead of dialog

engine/src/org/pentaho/di/core/util/JavaScriptUtils.java, engine/src/org/pentaho/di/trans/steps/script/Script.java, engine/src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesMod.java, engine/test-src/org/pentaho/di/core/util/JavaScriptUtilsTest.java, engine/test-src/org/pentaho/di/trans/steps/script/ScriptTest.java, engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesModTest.java, test/org/pentaho/di/trans/steps/scriptvalues_mod/JavaScriptSpecialTest.java, test/org/pentaho/di/trans/steps/scriptvalues_mod/JavaScriptStringTest.java
=> [PDI-9137] - Wrong interpretation of bignumber in java Script step

engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java, engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupData.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java
=> PDI-13780 - Database Lookup yields wrong results when preloading table into cache

engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java, engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupData.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java
=> SP-1876 - Backport of PDI-13780 - Database Lookup yields wrong results when preloading table into cache (5.4 Suite)

build.xml, engine/src/org/pentaho/di/trans/steps/sftpput/SFTPPut.java, engine/test-src/org/pentaho/di/trans/steps/sftpput/SFTPPutTest.java, test/org/pentaho/di/TestUtilities.java, test/org/pentaho/di/trans/steps/sftpput/SFTPPutIntegrationTest.java, testfiles/org/pentaho/di/trans/steps/sftpput/pdi-13897.ktr
- use remoteFilenameFieldName as a source for getting destination file name
- add some tests on checking different cases
- add an integration test for the case
picked from https://github.com/pentaho/pentaho-kettle/pull/1361/
@mattyb149 @brosander @rmansoor please merge
=> [SP-1944] - SFTP Put does not work when "Input is a stream" option is used

assembly/ivy.xml
[CLEANUP] - adding more dependencies required by the metaverse to the assembly
=> [CLEANUP] - adding more dependencies required by the metaverse to the assembly

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java
This is a PR containing Andrey's fix for this case, I verified locally that it works (using @matthewtckr 's reproduction transformation).
=> [SP-1977] - Backport of PDI-13981 - GA Input: Duplicate entry on 1001st entry

engine/src/org/pentaho/di/job/entries/xmlwellformed/JobEntryXMLWellFormed.java, engine/test-src/org/pentaho/di/job/entries/xmlwellformed/JobEntryXMLWellFormedLoadSaveTest.java, ui/src/org/pentaho/di/ui/job/entries/xmlwellformed/JobEntryXMLWellFormedDialog.java
Added a LoadSave test and getter/setter methods
=> [PDI-10290] XML Well Formed Job Entry Test

engine/src/org/pentaho/di/job/entries/ftp/JobEntryFTP.java, engine/test-src/org/pentaho/di/job/entries/ftp/JobEntryFTPTest.java
Update the logic to properly insert the datetime before the file extension
=> [PDI-5558] JobEntryFTP Fix adding date in target filename

ui/src/org/pentaho/di/ui/trans/steps/regexeval/RegexEvalDialog.java
Fix an issue where the field list is appended to each time the window gains focus, causing duplicate entries.
=> [PDI-13372] Fix Regex Eval Field List

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java
This is a forward-port PR containing Andrey's fix for this case, I verified locally that it works (using @matthewtckr 's reproduction transformation).
=> [PDI-13981] Google Analytics Input Step: Duplicate entry on 1001st entry

ui/src/org/pentaho/di/ui/trans/steps/sftpput/SFTPPutDialog.java, ui/test-src/org/pentaho/di/ui/trans/steps/sftpput/SFTPPutDialogTest.java
@deinspanjer @matthewtckr please, look it
=> PDI-13915 - Error message after clicking second time on Test connection button in SFTPPut step

plugins/ssh2-plugin/src/org/pentaho/di/job/entries/ssh2get/JobEntrySSH2GET.java, plugins/ssh2-plugin/src/org/pentaho/di/job/entries/ssh2put/JobEntrySSH2PUT.java
=> [BACKLOG-3964] - change job entries IS to provide backward compatibility

core/src/org/pentaho/di/core/logging/LoggingPlugin.java, core/src/org/pentaho/di/core/logging/LoggingPluginType.java, core/test-src/org/pentaho/di/core/logging/LoggingPluginTypeTest.java
=> [PDI-13857] - Second logger plugin will not be normally registered

assembly/ivy.xml
=> [BACKLOG-3726] Remove Instaview from all distributions

ui/test-src/org/pentaho/di/ui/trans/steps/sftpput/SFTPPutDialogTest.java
@mattyb149, @brosander, @deinspanjer, @mdamour1976, accept it please.
This PR turns off the test. @yuryilyukevich is on vacation now, I'll give the ball to him after he returns
=> [TEST] - turn off the test, because it fails on headless environment

ui/test-src/org/pentaho/di/ui/trans/steps/sftpput/SFTPPutDialogTest.java
@mattyb149, @brosander, @deinspanjer, review it please. This commit repairs the test, I've previously turned off
=> [TEST] - repair SFTPPutDialogTest

assembly/package-res/ui/spoon.xul, ui/src/org/pentaho/di/ui/core/PropsUI.java, ui/src/org/pentaho/di/ui/spoon/SpoonPerspectiveManager.java
I use Y/N instead true/false, like other UI props values.
=> [BACKLOG-3723] Add 'perspectiveRenderType' UI property for switch old/new perspectives switcher

ui/src/org/pentaho/di/ui/repository/RepositoryDirectoryUI.java, ui/src/org/pentaho/di/ui/repository/dialog/SelectDirectoryDialog.java
Last commit made a wrong assumption about requirement. Modification according conversation with Jens.
It turns out only / and /home should be restricted. Anythig else goes.
=> PDI-13867: Able to save job/transformation in the root folder

engine/src/org/pentaho/di/trans/steps/getxmldata/GetXMLDataMeta.java
@brosander @mattyb149 please review.
=> PDI-12650 - GetDataFromXml Xpath loop disabled using Single Threader

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java
Add additional logging during the startup phase of the step
=> [PDI-14062] Google Analytics Improved Logging

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java
=> [PDI-14062] 5.4 Backport of Google Analytics Improved Logging

plugins/googleanalytics/ivy.xml, plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java, plugins/googleanalytics/src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialog.java, plugins/googleanalytics/test-src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepTest.java
Cherry-picked commits from 5.4 to 5.3.
=> [SP-1994] - Backport of PDI-13981 - Google Analytics Duplicate row

engine/src/org/pentaho/di/job/entries/shell/JobEntryShell.java, engine/test-src/org/pentaho/di/job/entries/shell/JobEntryShellTest.java
@mattcasters, @brosander, would you mind of reviewing/merging
=> [PDI-12176] - "Execute a shell script" job fails with "No such file or directory" (when developed on Windows, executed on Linux)

core/src/org/pentaho/di/core/extension/ExtensionPointMap.java
=> [BACKLOG-4391] Getting a NPE when starting Spoon

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/messages/messages_en_US.properties, plugins/googleanalytics/src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialog.java
=> [BACKLOG-4259] [Google Analytics Step] Getting IO Error using the option "Sort"

engine/src/org/pentaho/di/base/AbstractMeta.java, engine/test-src/org/pentaho/di/trans/TransMetaTest.java
=> [BACKLOG-4319] prevent metastore db from overriding shared

ui/src/org/pentaho/di/ui/trans/dialog/TransPreviewProgressDialog.java
Mark generated transformation as running in preview mode
@rfellows please review
=> [BACKLOG-4224] KettleVFS error after perform a Preview

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java, engine/test-src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep_FormulaRecalculationTest.java
Although I mentioned that https://github.com/pentaho/pentaho-kettle/pull/1586 was not a backport, this fix is actually the same. It is done to keep consistency between two branches. @pamval is going to create another ticket for tracking activities related to future UI changes and keeping compatibility with the property I am introducing with this PR.
=> [PDI-12769] - When stream XSLX data enabled, formula recalculation does not work

core/src/org/pentaho/di/core/database/RedshiftDatabaseMeta.java, core/test-src/org/pentaho/di/core/database/RedshiftDatabaseMetaTest.java
@mbatchelor Mind reviewing this? Please and thanks!
=> [BACKLOG-2036] Unable to preview rows in Spoon with Redshift

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GoogleAnalyticsApiFacade.java, plugins/googleanalytics/test-src/org/pentaho/di/trans/steps/googleanalytics/GoogleAnalyticsApiFacadeTest.java
=> [BACKLOG-4543] [Google Analytics Step] The field Key File doesn't work with windows path

plugins/googleanalytics/src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialog.java
Wrap GoogleJsonResponseException with IOException and provide better looking message @mattyb149
=> [BACKLOG-4574] [Google Analytics Input Step] Treat JSON error messages to something more readable (not with JSON structure)

assembly/package-res/ui/laf.properties
errors of FileNotFoundException dispays
=> [BACKLOG-4310] [Spoon] Clicking "Explorer" of a repository several

assembly/package-res/ui/laf.properties
[Spoon] Clicking "Explorer" of a repository several errors of
FileNotFoundException displays
=> [BACKLOG-4310]

engine/src/org/pentaho/di/repository/kdr/KettleDatabaseRepository.java, engine/test-src/org/pentaho/di/repository/kdr/KettleDatabaseRepositoryUnitTest.java, ui/src/org/pentaho/di/ui/job/entries/job/JobEntryJobDialog.java, ui/src/org/pentaho/di/ui/job/entries/trans/JobEntryTransDialog.java, ui/src/org/pentaho/di/ui/job/entry/JobEntryDialog.java, ui/src/org/pentaho/di/ui/trans/step/BaseStepDialog.java, ui/src/org/pentaho/di/ui/trans/steps/jobexecutor/JobExecutorDialog.java, ui/src/org/pentaho/di/ui/trans/steps/mapping/MappingDialog.java, ui/src/org/pentaho/di/ui/trans/steps/simplemapping/SimpleMappingDialog.java, ui/src/org/pentaho/di/ui/trans/steps/transexecutor/TransExecutorDialog.java, ui/src/org/pentaho/di/ui/util/DialogUtils.java, ui/test-src/org/pentaho/di/ui/util/DialogUtilsTest.java
@mattyb149, @brosander, @deinspanjer, review it please.
The idea of the fix is to take into account "deleted" flag, that has been ignored previously. Also, it was set incorrectly. There will be a slightly different behaviour now: DB repository displayed ```/null```, EE server's plugin caused NPEs - henceforth, an empty string will be showed.
I don't like code duplication in dialog classes either, thus I created an improvement request for it: http://jira.pentaho.com/browse/PDI-14228
=> [PDI-6567] - Transformation entry in kettle job broken in Spoon if transformation is specified by reference and the target is later deleted

plugins/googleanalytics/src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialog.java
From https://github.com/pentaho/pentaho-kettle/pull/1495, I have restored the removed messaging from this commit https://github.com/pentaho/pentaho-kettle/commit/ba0311a2e3fc10a8cbf6065c0bc81be487f46968 which was causing the conflict.
=> [PDI-13980] Google Analytics NPE with Get Fields

engine/src/org/pentaho/di/trans/TransMeta.java, engine/test-src/org/pentaho/di/trans/TransMetaTest.java
@mattcasters, @brosander, @mattyb149, @pamval rebasing is done
=> [PDI-14055] - 5.3 Transformation cannot be read from repository after import

engine/src/org/pentaho/di/trans/TransMeta.java, engine/test-src/org/pentaho/di/trans/TransMetaTest.java
@mattcasters, @brosander, @mattyb149, @pamval rebasing for backport (https://github.com/pentaho/pentaho-kettle/pull/1618#event-386247891) is done too
=> [SP-2016] - PDI-14055 - PDI 5.3 Transformation cannot be read from repository after import

core/src/org/pentaho/di/core/hash/LongHashIndex.java, core/test-src/org/pentaho/di/core/hash/LongHashIndexTest.java
@deinspanjer  @mdamour1976 please review
=> PDI-11866 - Stream Value Lookup does not complete execution

ui/src/org/pentaho/di/ui/spoon/SharedObjectSyncUtil.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/test-src/org/pentaho/di/ui/spoon/SharedObjectSyncUtilTest.java
@mdamour1976  @deinspanjer  please review my changes
=> [BACKLOG-3912] - Synchronisation between loaded shared objects (e.g. database connections) (in memory sync only)

core/src/org/pentaho/di/core/database/DataSourceProviderInterface.java, core/src/org/pentaho/di/core/database/Database.java, core/src/org/pentaho/di/core/database/util/DatabaseUtil.java, core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
- introduce a new method for distinguishing the source where to look for data sources
- remove some legacy code, that is not used anymore
- add tests
@mattyb149, @brosander, @mattcasters, @deinspanjer, @pentaho-nbaker, @rmansoor,
Please review it and mention your opinions. This is a risky change, as it touches the core class.
/cc @pamval
=> [PDI-13961] - Spoon firstly tries to conect via JNDI although connection type is JDBC

core/src/org/pentaho/di/core/database/DatabaseMeta.java
- Some databases return different url according to parameters sent to them.
- Need to clear cached DatabaseInterfacesMap in case some database plugins are changed/added/removed
=> [BAD-215] Add Support for the Simba Driver

engine/src/org/pentaho/di/trans/steps/samplerows/SampleRows.java, engine/src/org/pentaho/di/trans/steps/samplerows/SampleRowsData.java
Unit tests not included, the SampleRows class is too tightly coupled and very dependent on its parent class BaseStep, and the SampleRowsData class is not even a bean, it's like a C struct.  The Sample Rows sample transformation is run as part of integration testing.
=> [BACKLOG-3674] Sample Rows should stop when sampling limit is reached

assembly/build.properties, assembly/build.xml, assembly/ivy.xml
present in a folder in spoon
@hudak @bmorrise @brosander
=> [BACKLOG-4941]  The dataservice JDBC zip needs to be

plugins/pdi-pur-plugin/ivy.xml
=> [BACKLOG-3825] pdi-pur-plugin: publish jar as default

engine/src/org/pentaho/di/trans/steps/olapinput/OlapInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/olapinput/OlapInputMetaTest.java
Update the XML and Repo serialization to encrypt password
=> [PDI-13458] OLAP Input Encrypt Password

build.xml, engine/src/org/pentaho/di/trans/steps/xsdvalidator/XsdValidator.java, engine/test-src/org/pentaho/di/trans/steps/xsdvalidator/XsdValidatorMetaTest.java, test/org/pentaho/di/trans/steps/xsdvalidator/XsdValidatorIntTest.java, test/org/pentaho/di/trans/steps/xsdvalidator/data.xml, test/org/pentaho/di/trans/steps/xsdvalidator/schema.xsd
Add support for other VFS objects, by way of using the getInputStream for the XSD Schema file.
=> [PDI-13661] XSD Validator with HDFS Files

ui/src/org/pentaho/di/ui/trans/steps/sql/ExecSQLDialog.java
Add Selection Listener to some SWT buttons so that Spoon knows that the Step's metadata has changed and needs to be saved.
=> [PDI-12511] Execute SQL Step - setChanged

ui/src/org/pentaho/di/ui/core/widget/TableView.java
=> SP-1931 - Backport of PDI-12959 - Value Mapper step reverts changes when you click on another field on a Mac OSX (5.4 Suite)

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/messages/messages_en_US.properties, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTest.java
=> [BACKLOG-3825][PDI-14076][PDI-6567] sync pdi-ee-plugin fixes

core/ivy.xml, core/src/org/pentaho/di/core/fileinput/NonAccessibleFileObject.java, plugins/kettle-gpload-plugin/ivy.xml, plugins/kettle5-log4j-plugin/ivy.xml, plugins/pdi-pur-plugin/ivy.xml, plugins/star-modeler/ivy.xml
!! Do not merge until we get the official go-ahead for VFS2.1.
=> [BACKLOG-4922]  Upgrading to vfs2.1

ui/src/org/pentaho/di/ui/core/widget/TableView.java
@mattyb149, @brosander  Please, look it
=> PDI-12959 - Value Mapper step reverts changes when you click on another field on a Mac OSX

engine/ivy.xml
Updated the poi dependency and required 3rd party dependencies.
@pentaho-nbaker @mbatchelor Let's discuss this before including ...
NOTE: there are other pull requests that all must go together
=> [PRD-5459] - Upgraded POI and associated 3rd party libraries

engine/src/org/pentaho/di/base/AbstractMeta.java, engine/src/org/pentaho/di/core/EngineMetaInterface.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/spoon/SpoonSlave.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTabsDelegate.java
=> [BACKLOG-3960] Refactored "hasMissingPlugins" method.

build.xml, engine/src/org/pentaho/di/trans/steps/rest/Rest.java, engine/src/org/pentaho/di/trans/steps/rest/RestData.java, engine/src/org/pentaho/di/trans/steps/rest/RestMeta.java, engine/src/org/pentaho/di/trans/steps/rest/messages/messages_en_US.properties, test/org/pentaho/di/trans/steps/rest/RestInputTest.java, test/org/pentaho/di/trans/steps/rest/SimpleRestService.java, ui/src/org/pentaho/di/ui/trans/steps/rest/RestDialog.java
1) Initial implementation of  Vladimir Dolzhenko with resolved conflicts to merge + additional changes to to this feature workable.
=> Pdi 13078: REST doesn't support matrix parameters

engine/src/org/pentaho/di/trans/cluster/TransSplitter.java, engine/src/org/pentaho/di/trans/messages/messages_en_US.properties, test/org/pentaho/di/cluster/PartitioningTest.java, test/org/pentaho/di/cluster/test-partitioning-on-master-and-clustering.ktr, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java
See comments to commits for detailed info.
=> BACKLOG-675  - NPEs in Spoon UI when running transformation with partitioning and clustering set up

engine/test-src/org/pentaho/di/trans/steps/rest/RestTest.java
Hi, @rpbouman 
Please merge this fix for the broken unit test: org.pentaho.di.trans.steps.rest.RestTest.testLoadSaveRoundTrip
=> [PDI-13072][TEST]: Fixed unit test.

ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java
@mattyb149, @brosander review it please.
=> [PDI-13900] - Modified transformation running without saving on cluster and on remote server

engine/src/org/pentaho/di/trans/steps/samplerows/SampleRows.java, engine/src/org/pentaho/di/trans/steps/samplerows/SampleRowsData.java
Close row result set when range span maximum is reached
=> [BACKLOG-3674]Set Sample Rows output done

ui/src/org/pentaho/di/ui/core/widget/TableView.java
=> [PDI-12959] Fixed mouseDown error when not in editable table cell

ui/src/org/pentaho/di/ui/core/widget/TableView.java
Backport of #1710 to 5.4 branch
=> [SP-1931][PDI-12959] Fixed mouseDown error when not in editable table cell

engine/src/org/pentaho/di/shared/SharedObjects.java
This fix will just log when a database type is not found, then continue to process the Shared Objects file. This will prevent errors when loading up a trans/job when there's an invalid entry in the Shared Objects file.  Also I adding formatting fixes and a toString() implementation.
There is no unit test attached. The constructor (and even the little part of code I was working in) depends on parsing XML, and it would take a LOT of mocking to test this change. The reproduction path for validation testing is straightforward, it doesn't allow for automation but this whole class needs a refactor before full unit testing can be done.
=> [BACKLOG-4802] Continue processing SharedObjects if DB type not found

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/messages/messages_en_US.properties, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTest.java
- unify changes made in PDI-14076 with transformations
- add tests
=> [PDI-14342] - 2 ETL transformations can have  the same name by renaming one of them

core/src/kettle-database-types.xml
Reverts pentaho/pentaho-kettle#1746
=> Revert "[BACKLOG-5064] Added data service client"

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInput.java, engine/src/org/pentaho/di/trans/steps/excelinput/WorkbookFactory.java, engine/src/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java, engine/src/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiWorkbook.java, test/org/pentaho/di/trans/steps/excelinput/StaxWorkBookTest.java, ui/src/org/pentaho/di/ui/trans/steps/excelinput/ExcelInputDialog.java
=> [PDI-5269] streaming poi cell type conversion and edge cases

ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTabsDelegate.java
Adds new signatures to SpoonTabsDelegate::addSpoonBrowser; keeps the default behaviour (show address bar).
=> [MARKET-308] Allow the opening of SpoonBrowser tabs without address bar

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java, engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java
- applying changes from 9e3e72d9d85ce5222a44b4ebe46d4e7163057e9e to new implementation of the step
@mattyb149, @brosander, review it please. This is a fix migration from https://github.com/pentaho/pentaho-kettle/pull/1731 to the new implementation
=> [PDI-14172] - Text file input Repeat doesn't work

engine/src/org/pentaho/di/trans/steps/tableinput/TableInputMeta.java
=> [BACKLOG-5170] Fix for missing data services in listServices

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java
Name is not set by the DataNode transformer
@mdamour1976 @mattyb149 
http://jira.pentaho.com/browse/PDI-14150
=> [PDI-14150]Set databaseMeta name to file title

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTest.java
- allow to move files
- add tests
@mattyb149, @brosander, @deinspanjer, review it please. This is a fix for critical regression found in the nick of time. Please do not ignore it
/cc @pamval
=> [BACKLOG-5173] - it is impossible to transfer KTR & JOB to another folder.

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositoryImporter.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTest.java
@rmansoor, @brosander here are commits for master (https://github.com/pentaho/pdi-ee-plugin/pull/280). Thanks.
=> [PDI - 14247] - Migrator imports wrong revision dates for jobs.

core/src/org/pentaho/di/core/vfs/KettleVFS.java, engine/src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutput.java
Added getFriendlyURI methods to KettleVFS which leverage the
corresponding VFS method.  Also added logic to cleanse the
filename in the event we aren't able to get a VFS FileObject.
@deinspanjer
=> [PDI-14349]  Password written to log

engine/src/org/pentaho/di/base/AbstractMeta.java
=> [BACKLOG-3431]AbstractMeta contentListeners getter

ui/src/org/pentaho/di/ui/core/PropsUI.java
=> [BACKLOG-5205] Change GUIOption cast exception to warning

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNamesMeta.java, engine/test-src/org/pentaho/di/trans/steps/getfilenames/GetFileNamesMetaTest.java, ui/src/org/pentaho/di/ui/trans/steps/getfilenames/GetFileNamesDialog.java
Fixed an issue with "Add to Result" boolean option when reading from repository
=> [PDI-14337] Get Filenames Serialization

core/src/org/pentaho/di/core/KettleClientEnvironment.java, core/src/org/pentaho/di/core/logging/LoggingPlugin.java, core/src/org/pentaho/di/core/logging/LoggingPluginType.java, plugins/kettle5-log4j-plugin/ivy.xml, plugins/kettle5-log4j-plugin/res/log4j.xml, plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/CentralLogStore.java, plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/log4j/Log4jLogging.java
@e-cuellar , @mdamour1976 same as https://github.com/pentaho/pentaho-kettle/pull/1768
=> [PDI-13206] - The Kettle5-log4j plugin doesn't work because init never gets called on the plugin

engine/src/org/pentaho/di/repository/filerep/KettleFileRepository.java
=> [BACKLOG-5231] Fix for transformation not opening in file system repo

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/messages/messages_en_US.properties
=> [BACKLOG-5165] Merged message.properties files

engine/src/org/pentaho/di/www/DefaultWebServerShutdownHandler.java
Pull request for master:
https://github.com/pentaho/pentaho-kettle/pull/1789
Ran engine unit tests (760 pass, 0 failures, 0 errors)
=> [BACKLOG-5272] carte (jetty) will not shutdown or respond to CTRL+C to kill it

assembly/package-res/docs/English/welcome/contents/2013/06/20/engage.html
=> [PDI-14402] Update to include codeks blog

engine/src/org/pentaho/di/core/util/CurrentDirectoryResolver.java, engine/src/org/pentaho/di/job/entries/job/JobEntryJob.java, engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java, engine/src/org/pentaho/di/trans/steps/jobexecutor/JobExecutorMeta.java, engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
Master:
https://github.com/pentaho/pentaho-kettle/pull/1795
All unit tests are still passing, did testing against filesystem/filerepo/dbrepo/direpo.
=> [BACKLOG-5269] Cannot Execute or Open Referenced Object (di-repo)

engine/src/org/pentaho/di/www/StopCarteServlet.java
Brings Carte in line with Pan and Kitchen
=> [BACKLOG-5297] - System.exit() in StopCarteServlet

engine/src/org/pentaho/di/www/WebServer.java
=> [BACKLOG-5301] Fixed issue with authentication in carte

core/src/org/pentaho/di/core/jdbc/ThinDriver.java
=> [BACKLOG-5343]Log deprecation warning when using old ThinDriver

core/src/org/pentaho/di/cluster/HttpUtil.java
=> [PDI-14427] Added secure option to data services

core/src/org/pentaho/di/cluster/HttpUtil.java, core/test-src/org/pentaho/di/cluster/HttpUtilTest.java
=> [PDI-14427]Add tests & constants for HttpUtils.constructUrl

ui/src/org/pentaho/di/ui/spoon/TransFileListener.java, ui/test-src/org/pentaho/di/ui/spoon/TransFileListenerTest.java
Added check for ObjectLocationSpecificationMethod of "filename" before performing any operations on the imported trans.
Also fixed some CheckStyle violations and added unit tests for TransFileListener.
=> [BACKLOG-5360] Fixed import of Trans that calls Job/Trans

test/org/pentaho/di/TestUtilities.java, test/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTests.java
=> [TEST] TestUtilities.checkRows not checking when fileNameColumn<=0

ui/src/org/pentaho/di/ui/spoon/JobFileListener.java, ui/test-src/org/pentaho/di/ui/spoon/JobFileListenerTest.java
@hudak I forgot to apply the stuff to JobFileListener in the last commit, mind a review? Please and thanks!
=> [BACKLOG-5360] Applied import logic to JobFileListener

plugins/googleanalytics/test-src/org/pentaho/di/trans/steps/googleanalytics/GoogleAnalyticsApiFacadeTest.java
- use Parameterized runner to test each sample
This is a trivial fix to repair the test as only first sample is checked now.
=> [TEST] - Fix GoogleAnalyticsApiFacadeTest

engine/test-src/org/pentaho/di/trans/steps/groupby/GroupBySingleThreadedExecutionIT.java, engine/test-src/org/pentaho/di/trans/steps/http/HTTPIT.java, engine/test-src/org/pentaho/di/trans/steps/httppost/HTTPPOSTIT.java, engine/test-src/org/pentaho/di/trans/steps/prioritizestreams/PrioritizeStreamsExecutionIT.java, engine/test-src/org/pentaho/di/trans/steps/rest/RestIT.java, engine/test-src/org/pentaho/di/trans/steps/stepsmetrics/StepMetricsSingleThreadedExecutionIT.java
=> [BACKLOG-5396] Rename integration tests in Kettle engine module

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java, plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GoogleAnalyticsApiFacade.java, plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/messages/messages_en_US.properties, plugins/googleanalytics/src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialog.java, plugins/googleanalytics/test-src/org/pentaho/di/ui/trans/steps/googleanalytics/GaInputStepDialogTest.java
Removed logging in favor of showing error message to user as logging from steps' editors falls into GENERAL category and will be show for every trans run in preview mode.
@mattyb149
=> [BACKLOG-4596] [Google Analytics Input Step] Pressing preview display all previous errors displayed in command line (seems is caching)

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/UserRoleDelegate.java
- show the correct message when role already exists
@mattyb149, @brosander, merge it please. My bad - have missed this.
/cc @pamval
=> [PDI-12814] - Need to prohibit empty names when adding new users or roles

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositoryExporter.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/messages/messages_en_US.properties, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
@mattcasters, @brosander, @mattyb149, @mbatchelor, here is backport of https://github.com/pentaho/pentaho-kettle/pull/1787 to 6.0 branch. Thanks.
=> SP-2165 - Backport of PDI-13028 - Export repository with rule: Job/Transformation with Note is not exported (6.0 Suite)

plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/GaInputStep.java, plugins/googleanalytics/src/org/pentaho/di/trans/steps/googleanalytics/messages/messages_en_US.properties
Wrap exception with more general IOE including reference to documentation
@mattyb149
=> [BACKLOG-5362] [Google Analytics Input Step] Improve the error message, removing JSon error

engine/src/org/pentaho/di/base/AbstractMeta.java, engine/test-src/org/pentaho/di/base/AbstractMetaTest.java, engine/test-src/org/pentaho/di/trans/RowProducerTest.java
=> [TEST] Added a couple of unit tests to engine

engine/src/org/pentaho/di/trans/steps/fileinput/BaseFileInputStep.java, engine/src/org/pentaho/di/trans/steps/fileinput/BaseFileInputStepData.java, engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInput.java, engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java, ui/src/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileCSVImportProgressDialog.java
Additional output field "Size" will be null if size cannot be retrieved.
=> [BACKLOG-5441] Fix size retrieve from VFS file.

plugins/star-modeler/ivy.xml, plugins/star-modeler/test-src/org/pentaho/di/starmodeler/ConceptUtilTest.java, plugins/star-modeler/test-src/org/pentaho/di/starmodeler/generator/JobGeneratorTest.java, plugins/star-modeler/test-src/org/pentaho/di/starmodeler/metastore/SharedDimensionMetaStoreUtilTest.java, plugins/star-modeler/test-src/org/pentaho/di/starmodeler/metastore/StarDomainMetaStoreUtilTest.java
@rmansoor @mdamour1976 please review the tests
=> [TEST] - added unit tests for Kettle Star Modeler Plugin

core/src/org/pentaho/di/core/parameters/DuplicateParamException.java, core/src/org/pentaho/di/core/parameters/NamedParamsDefault.java, core/src/org/pentaho/di/core/parameters/NamedParamsException.java, core/src/org/pentaho/di/core/parameters/UnknownParamException.java, core/test-src/org/pentaho/di/core/parameters/DuplicateParamExceptionTest.java, core/test-src/org/pentaho/di/core/parameters/NamedParamsDefaultTest.java, core/test-src/org/pentaho/di/core/parameters/NamedParamsExceptionTest.java, core/test-src/org/pentaho/di/core/parameters/UnknownParamExceptionTest.java
Changes to source are null checks and CheckStyle violations
=> [TEST] Added unit tests for org.pentaho.di.core.parameters package

ui/src/org/pentaho/di/ui/trans/steps/excelwriter/ExcelWriterStepDialog.java, ui/src/org/pentaho/di/ui/trans/steps/symmetriccrypto/symmetriccryptotrans/SymmetricCryptoTransDialog.java
(cherry picked from commit 5e4a8bc)
@mattyb149, @brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1486
=> [SP-2014] - Backport of PDI-14051 - Symmetric Cryptography step displays secret key on tool-tip as plain text (5.4 Suite)

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/UserRoleHelper.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/UserRoleHelperTest.java
@mattyb149, @brosander, review it please. This is test for ```UserRoleHelper```. I prepared it when was dealing with PDI-12814, but didn't include into its PRs
=> [TEST] - Add tests for UserRoleHelper

plugins/kettle5-log4j-plugin/ivy.xml, plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/log4j/Log4jLogging.java, plugins/kettle5-log4j-plugin/test-src/org/pentaho/di/core/logging/Log4jAppenderTest.java, plugins/kettle5-log4j-plugin/test-src/org/pentaho/di/core/logging/Log4jFileAppenderTest.java, plugins/kettle5-log4j-plugin/test-src/org/pentaho/di/core/logging/Log4jKettleLayoutTest.java, plugins/kettle5-log4j-plugin/test-src/org/pentaho/di/core/logging/Log4jPipedAppenderTest.java, plugins/kettle5-log4j-plugin/test-src/org/pentaho/di/core/logging/log4j/Log4jLoggingTest.java
@mdamour1976 please find someone who can review this. 
I marked some classes as deprecated in separate commit - they have negative effect on code coverage but I see no reason to waste time on them.
=> [BACKLOG-5408] - tests for kettle5-log4j-plugin

engine/src/org/pentaho/di/trans/steps/validator/Validator.java, engine/test-src/org/pentaho/di/trans/steps/validator/ValidatorTest.java
- fix the missed ! operator
- add tests
=> [PDI-13274] - Data Validator Validation Fails if Data Type is not String and Only Numeric data expected is checked

engine/src/org/pentaho/di/trans/step/BaseStepMeta.java, engine/test-src/org/pentaho/di/trans/step/BaseStepMetaCloningTest.java
- set ioMeta = null for clones to prevent sharing its instance among all clones
- add a test
=> [PDI-14419] - Table Input Step - Insert data from step - writes to other table input steps

engine/test-src/org/pentaho/di/base/AbstractMetaTest.java
Fixed the existing failure and added more coverage/tests
=> [TEST] Fixed AbstractMetaTest, added more

engine/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java
=> [TEST] basic tests for json input

core/src/org/pentaho/di/core/database/DatabaseMeta.java, core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java, engine/src/org/pentaho/di/repository/filerep/KettleFileRepository.java, engine/src/org/pentaho/di/repository/kdr/KettleDatabaseRepository.java, engine/test-src/org/pentaho/di/repository/filerep/KettleFileRepositoryTestBase.java, engine/test-src/org/pentaho/di/repository/filerep/KettleFileRepository_DatabaseNames_Test.java, engine/test-src/org/pentaho/di/repository/kdr/KettleDatabaseRepository_DatabaseNames_Test.java, engine/test-src/org/pentaho/di/repository/kdr/KettleDatabaseRepository_GetObjectInformation_Test.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_IT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_Test.java, ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsController.java, ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsControllerTest.java
=> [PDI-13353] - When having duplicate DB Connection names (difference in capitals) PDI defaults to the first

core/src/org/pentaho/di/core/util/DateDetector.java, core/src/org/pentaho/di/core/util/StringEvaluator.java, core/test-src/org/pentaho/di/core/util/DateDetectorTest.java, core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java
@mattcasters, @brosander, @mattyb149 
Could you review please?
=> [PIR-1187] Pentaho interactive reporting datetime prompt

engine/test-src/org/pentaho/di/job/JobMetaTest.java
@mattyb149, @brosander, review it please. This fixed failed test in kettle-engine-5.4
/cc @pamval
=> [SP-2156] - Backporting test to repair it

engine/test-src/org/pentaho/di/job/JobMetaTest.java
- backport changes from 32d8256a6d5331983ca5cf982ba65c189a24f355
this is a partial backport of https://github.com/pentaho/pentaho-kettle/pull/1855
=> [SP-2208] - Repair failed test

engine/src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMeta.java, engine/test-src/org/pentaho/di/trans/steps/getslavesequence/GetSlaveSequenceMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/normalizer/NormalizerMetaTest.java
Get Subfolders
Get Sequence ID from Slave
Row Normalizer
=> [TEST] LoadSaveTests

engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java, engine/test-src/org/pentaho/di/job/entries/trans/JobEntryTransTest.java
@brosander @mattyb149 please review
=> [PDI-14530] - When job fails the job entry is not updated fail icon

build.properties, build.xml, ivy.xml
=> [ENGOPS-1571] updated checkstyle

ui/src/org/pentaho/xul/swt/tab/TabItem.java, ui/src/org/pentaho/xul/swt/tab/TabSet.java, ui/test-src/org/pentaho/xul/swt/tab/TabSetTest.java
=> [PDI-14411] bad index after closing first tab

ui/src/org/pentaho/di/ui/cluster/dialog/ClusterSchemaDialog.java, ui/src/org/pentaho/di/ui/cluster/dialog/SlaveServerDialog.java, ui/src/org/pentaho/di/ui/partition/dialog/PartitionSchemaDialog.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonDBDelegate.java, ui/src/org/pentaho/di/ui/util/DialogUtils.java, ui/test-src/org/pentaho/di/ui/util/DialogUtilsTest.java
=> [PDI-14641] - Unable to rename database connection

dbdialog/ivy.xml, dbdialog/src/org/pentaho/ui/database/DatabaseConnectionDialog.java, dbdialog/src/org/pentaho/ui/database/event/DataHandler.java, dbdialog/src/org/pentaho/ui/database/event/FragmentHandler.java, dbdialog/test-src/org/pentaho/ui/database/DatabaseConnectionDialogTest.java, dbdialog/test-src/org/pentaho/ui/database/MessagesTest.java, dbdialog/test-src/org/pentaho/ui/database/event/DataHandlerTest.java, dbdialog/test-src/org/pentaho/ui/database/event/FragmentHandlerTest.java
Added defensive code where it was low-risk and allowed the unit tests to pass successfully.  Also added Mockito as a test dependency.
Lots of UI here, could probably eke out more coverage if necessary
=> [TEST] Added unit tests where possible

core/src/org/pentaho/di/core/database/MSSQLServerNativeDatabaseMeta.java
Use the supported getBinary JDBC method instead of getBlob
=> [PDI-14651] MSSQL Binary Fix

engine/src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesMeta.java, engine/test-src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesMetaTest.java
Properly save/load the Object Type setting
=> [PDI-14614] Get Repository Names Object Type issue

core/src/org/pentaho/di/core/database/Database.java
Use JDBC-compliant schema field name
=> [PDI-14433] Stored Procedure Schemas

ui/src/org/pentaho/di/ui/core/widget/TextVar.java, ui/src/org/pentaho/di/ui/job/entries/mail/JobEntryMailDialog.java, ui/src/org/pentaho/di/ui/job/entries/msgboxinfo/JobEntryMsgBoxInfoDialog.java
Update Multiline Textbox to show the variable indicator next to supported options
=> [PDI-14219] Variable Icon for Mail/MsgBox entries

engine/test-src/org/pentaho/di/trans/steps/zipfile/ZipFileMetaTest.java
please review and merge @pminutillo @kurtwalker @bytekast
=> [TEST] Increase code coverage

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInput.java, engine/src/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheet.java, engine/test-src/org/pentaho/di/trans/steps/excelinput/staxpoi/StaxPoiSheetTest.java
=> [PDI-14610][TEST] null cells for null values on streaming poi, tests

ui/src/org/pentaho/di/ui/spoon/AbstractGraph.java, ui/src/org/pentaho/di/ui/spoon/job/JobGraph.java, ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java, ui/test-src/org/pentaho/di/ui/spoon/GraphTest.java
=> [PDI-14185] right-click and selections; delete on job when no selections

engine/src/org/pentaho/di/core/gui/SwingGC.java
Thanks @agnielson for contributing the fix. His change unfortunately didn't conform to our check-style, but it was easy enough for me to put into my fork and provide the PR.
=> [PDI-14608] - Documentation Output not drawing error hops

core/ivy.xml, core/src/org/pentaho/di/core/sql/SQLFields.java, core/test-src/org/pentaho/di/core/sql/SQLFieldsUnitTest.java
http://jira.pentaho.com/browse/BACKLOG-5461
=> [BACKLOG-5461]SQL: DISTINCT is case insensitive

classpath.template
The Marketplace plugin has been replaced elsewhere
=> [CLEANUP] Update Classpath Template

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java, test/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepIntTest.java
Writer Header fields even if the fields are not defined in the step
=> [PDI-11374] Excel Writer - Write Header Fields

core/src/org/pentaho/di/core/util/DateDetector.java, core/src/org/pentaho/di/core/util/StringEvaluator.java, core/test-src/org/pentaho/di/core/util/DateDetectorTest.java, core/test-src/org/pentaho/di/core/util/StringEvaluatorTest.java
@brosander could you merge its backport for https://github.com/pentaho/pentaho-kettle/pull/1878 please?
=> [SP-2240][PIR-1187] Pentaho interactive reporting datetime prompt

engine/src/org/pentaho/di/trans/steps/validator/Validator.java, engine/test-src/org/pentaho/di/trans/steps/validator/ValidatorTest.java
- fix the missed ! operator
- add tests
(cherry picked from commit e1885a6)
@brosander, @hudak, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1871
=> [SP-2246] - Backport of PDI-13274 - Data Validator Validation Fails if Data Type is not String and Only Numeric data expected is checked (6.0 Suite)

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java, test/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepIntTest.java
@mbatchelor  could you review the backpor for 6.0  for https://github.com/pentaho/pentaho-kettle/pull/1471
=> [SP-2258][PDI-11374] Excel Writer - Write Header Fields

build.xml, engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java, test/org/pentaho/di/job/entries/trans/JobEntryTransIntTest.java
@mbatchelor  could you review the backport for https://github.com/pentaho/pentaho-kettle/pull/1926
=> [SP-2260][PDI-14676] Stop Trans when Job stops

build.xml, engine/src/org/pentaho/di/job/entries/trans/JobEntryTrans.java, test/org/pentaho/di/job/entries/trans/JobEntryTransIntTest.java
@mbatchelor could you review the backport for #1926
=> [SP-2261][PDI-14676] Stop Trans when Job stops

core/src/org/pentaho/di/core/database/MSSQLServerNativeDatabaseMeta.java
Use the supported getBinary JDBC method instead of getBlob
=> [SP-2262][PDI-14651] MSSQL Binary Fix

core/src/org/pentaho/di/core/database/MSSQLServerNativeDatabaseMeta.java
Use the supported getBinary JDBC method instead of getBlob
=> [SP-2263][PDI-14651] MSSQL Binary Fix

engine/src/org/pentaho/di/core/gui/SwingGC.java
@mbatchelor could you review the backport for https://github.com/pentaho/pentaho-kettle/pull/1938
=> [SP-2267][PDI-14608] - Documentation Output not drawing error hops

engine/src/org/pentaho/di/core/gui/SwingGC.java
@mbatchelor could you review the backport for #1938
=> [SP-2266][PDI-14608] - Documentation Output not drawing error hops

engine/src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesMeta.java, engine/src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMeta.java, engine/test-src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/getslavesequence/GetSlaveSequenceMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/normalizer/NormalizerMetaTest.java
@mbatchelor could you review if you have a chance?
It is a backport for  https://github.com/pentaho/pentaho-kettle/pull/1903 and for https://github.com/pentaho/pentaho-kettle/pull/1899
=> [SP-2264] [PDI-14614] Get Repository Names Object Type issue

engine/src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesMeta.java, engine/src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMeta.java, engine/test-src/org/pentaho/di/trans/steps/getrepositorynames/GetRepositoryNamesMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/getslavesequence/GetSlaveSequenceMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/getsubfolders/GetSubFoldersMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/normalizer/NormalizerMetaTest.java
@mbatchelor could you review if you have a chance?
It is a backport for #1903 and for #1899
=> [SP-2265] [PDI-14614] Get Repository Names Object Type issue

engine/src/org/pentaho/di/trans/steps/validator/Validator.java, engine/test-src/org/pentaho/di/trans/steps/validator/ValidatorTest.java
- fix the missed ! operator
- add tests
(cherry picked from commit e1885a6)
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1871
=> [SP-2247] - Backport of PDI-13274 - Data Validator Validation Fails if Data Type is not String and Only Numeric data expected is checked (5.4 Suite)

test/org/pentaho/di/job/entries/trans/JobEntryTransIntTest.java
@brosander, @hudak, @matthewtckr, @pamval, review it please.
This fixes failed compilation in kettle project
=> [PDI-14676] - Fix compilation fail in test

ui/src/org/pentaho/di/ui/spoon/JobFileListener.java, ui/test-src/org/pentaho/di/ui/spoon/JobFileListenerTest.java
- Applied import logic to JobFileListener (cherry picked from commit 9fa9d4a)
@brosander, @hudak, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1831
/cc @pamval
=> [SP-2271] - Backport of BACKLOG-5710 - Impossible Import of job that run other transformations. Fails with NPE (6.0 Suite)

engine/test-src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepTest.java
Updated unit test as the expected exception in the test was no longer thrown in the init method
=> [PDI-11374] Fix Unit Test

core/src/org/pentaho/di/core/exception/KettleRepositoryStatusException.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositoryConnector.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/messages/messages_en_US.properties, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryConnectorTest.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/spoon/messages/messages_en_US.properties
=> [BACKLOG-5701] - Implement the static login message UI in client tools

engine/test-src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepTest.java
Updated unit test as the expected exception in the test was no longer
thrown in the init method
=> [SP-2258][PDI-11374] Fix Unit Test

engine/test-src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepTest.java
Updated unit test as the expected exception in the test was no longer
thrown in the init method
=> [SP-2259][PDI-11374] Fix Unit Test

ui/src/org/pentaho/di/ui/trans/steps/textfileoutput/TextFileOutputDialog.java
* UI changes  - enable extension field in case of using filename from field
=> [BAD-297] - Hadoop file output fails append to file

plugins/kettle-s3csvinput-plugin/src/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta.java, plugins/kettle-s3csvinput-plugin/test-src/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta_GetFields_Test.java
- call recommended getFields() instead of deprecated
- add tests
@brosander, @hudak, review it please
=> [PDI-14194] - Error with S3 CSV Input step - Unable to Get Fields Correctly

engine/src/org/pentaho/di/trans/steps/cubeoutput/CubeOutputMeta.java
Update File extension to be consistent with the De-serialize to File step dialog window.
=> [PDI-14708] Update Default Serialize to File filename

engine/src/org/pentaho/di/job/Job.java, engine/test-src/org/pentaho/di/job/JobTest.java
- cleaning up log recodes ( due to log record timeout property ) after writing new info
@brosander, @mattcasters review it please
=> [PDI-14232] "Log line timeout (days)" not deleting old log table entries (job logging)

engine/src/org/pentaho/di/trans/Trans.java, engine/test-src/org/pentaho/di/trans/TransTest.java
- cleaning up log recodes ( due to log record timeout property ) after writing new info
@brosander, @mattcasters review it please
=> [PDI-9020]  Step logging not purging old data in database

core/test-src/org/pentaho/di/core/ConstTest.java
Just a quick fix for restoring build health
@mkambol
=> [Test] Remove failing test for now

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/messages/messages_en_US.properties
set of property
"AbsSecurityProvider.ERROR_0001_UNABLE_TO_INITIALIZE_AUTH_POLICY_WEBSVC"
because a duplicate issue no longer verifies.
=> [PDI-14543] Removed unused properties in pdi-pur-plugin. Uncommented the

core/src/org/pentaho/di/core/logging/LoggingRegistry.java, core/test-src/org/pentaho/di/core/logging/LoggingRegistryTest.java
-  If loggingSource duplicate found, check that original and found sources have the same parent and return logChanelId of the found source.
=> [PDI-14448] Kitchen logging changes for Local and DI server execution

engine/test-src/org/pentaho/di/trans/steps/tableoutput/TableOutputMetaTest.java, engine/test-src/org/pentaho/di/utils/TestUtils.java
- introduce a utility method for removing '\r' chars
@kurtwalker, your test is not passing on Windows. Mind reviewing this PR please?
/cc @brosander
=> [TEST] - fix TableOutputMetaTest for Windows

engine/src/org/pentaho/di/core/util/PluginMessages.java
- replace HashMap with ConcurrentHashMap
=> [PDI-8930] - PluginMessages can avoid synchronization if it uses ConcurrentHashMap

engine/src/org/pentaho/di/trans/step/StepIOMeta.java, engine/test-src/org/pentaho/di/trans/step/StepIOMetaIT.java
- decorate clone's list with the synchronized wrapper
- add simple integration tests
@brosander. review it please
=> [PDI-8935] - Possible bug - StepIOMeta.clone - the cloned streams is a plain ArrayList, the list being cloned is a synchronizedList

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInputMeta.java, engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java, engine/src/org/pentaho/di/trans/steps/metainject/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectMetaTest.java
=> [PDI-13901] - Export Linked Resources: Metadata Injection step not working

engine/test-src/org/pentaho/di/trans/steps/webservices/WebServiceMetaTest.java
@kurtwalker, this test also fails in Windows :smile: Merge it please
/cc @brosander
=> [TEST] - fix WebServiceMetaTest for Windows

plugins/kettle-s3csvinput-plugin/src/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta.java, plugins/kettle-s3csvinput-plugin/test-src/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta_GetFields_Test.java
@brosander, review it please. This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1981
=> [SP-2352] - Backport of PDI-14194 - Error with S3 CSV Input step - Unable to Get Fields Correctly (6.0 Suite)

engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java, engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupData.java, engine/src/org/pentaho/di/trans/steps/databaselookup/DefaultCache.java, engine/src/org/pentaho/di/trans/steps/databaselookup/readallcache/EqIndex.java, engine/src/org/pentaho/di/trans/steps/databaselookup/readallcache/GtIndex.java, engine/src/org/pentaho/di/trans/steps/databaselookup/readallcache/Index.java, engine/src/org/pentaho/di/trans/steps/databaselookup/readallcache/IsNullIndex.java, engine/src/org/pentaho/di/trans/steps/databaselookup/readallcache/LtIndex.java, engine/src/org/pentaho/di/trans/steps/databaselookup/readallcache/ReadAllCache.java, engine/src/org/pentaho/di/trans/steps/databaselookup/readallcache/SearchingContext.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/EqIndexTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/GeIndexTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/GtIndexTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/IndexTestBase.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/IsNullIndexTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/LeIndexTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/LtIndexTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/NeIndexTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/ReadAllCacheTest.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/readallcache/SearchingContextTest.java
=> [PDI-3314] - very slow database lookup if "not all equal conditions" and "load all rows at start"

ui/src/org/pentaho/di/ui/trans/dialog/TransDialog.java
- Showing metricsLogTable option instead of channelLogTable value when showMetricsLogTableOptions method is called.
@pamval, @brosander, review it please, This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1983
=> [SP-2378] Backport of PDI-13240 - Setting for 'Log record timeout' field under Logging - Metrics cannot be saved (6.0 Suite)

ui/src/org/pentaho/di/ui/trans/dialog/TransDialog.java
- Showing metricsLogTable option instead of channelLogTable value when -showMetricsLogTableOptions method is called.
@pamval, @brosander, review it please, This is a backport of #1983
=> [SP-2379] Backport of PDI-13240 - Setting for 'Log record timeout' field under Logging - Metrics cannot be saved (5.4 Suite)	

engine/src/org/pentaho/di/trans/Trans.java, engine/test-src/org/pentaho/di/trans/TransTest.java
- Сleaning up log recodes ( due to log record timeout property ) after writing new info
@pamval, @brosander, review it please, This is a backport of https://github.com/pentaho/pentaho-kettle/pull/1984
=> [SP-2380] Backport of PDI-9020 - Step logging not purging old data in database (6.0 Suite)

engine/src/org/pentaho/di/job/Job.java, engine/test-src/org/pentaho/di/job/JobTest.java
- Cleaning up log recodes ( due to log record timeout property ) after writing new info
@pamval, @brosander, review it please, This is a backport of #2031
=> [SP-2393] Backport of PDI-14232 - "Log line timeout (days)" not deleting old log table entries (job logging) (5.4 Suite)

engine/src/org/pentaho/di/job/Job.java, engine/test-src/org/pentaho/di/job/JobTest.java
- Cleaning up log recodes ( due to log record timeout property ) after writing new info
@pamval, @brosander, review it please, This is a backport of https://github.com/pentaho/pentaho-kettle/pull/2031
=> [SP-2392] Backport of PDI-14232 - "Log line timeout (days)" not deleting old log table entries (job logging) (6.0 Suite)

assembly/package-res/ui/menubar.xul
=> [BACKLOG-5676]  Correcting attribute reference in menubar.xul

engine/src/org/pentaho/di/imp/Import.java
Cherry-pick of https://github.com/pentaho/pentaho-kettle/pull/2007
@brosander 
Please take a look.
=> SP-2391 - Backport of PDI-14178 - Command-line Import Incorrectly Reports Exceptions (5.4 Suite)

engine/src/org/pentaho/di/imp/Import.java
Cherry-pick of https://github.com/pentaho/pentaho-kettle/pull/2007
@brosander 
Please take a look.
=> SP-2390 - Backport of PDI-14178 - Command-line Import Incorrectly Reports Exceptions (6.0 Suite)

core/src/org/pentaho/di/core/util/EnvUtil.java, core/test-src/org/pentaho/di/core/util/EnvUtilTest.java, engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValues_LocaleHandling_Test.java
- do not create locale instances for empty strings
=> [PDI-14823] - Using week in year date format with "Select values" step

engine/src/org/pentaho/di/www/AddExportServlet.java, engine/src/org/pentaho/di/www/AddJobServlet.java, engine/src/org/pentaho/di/www/BaseJobServlet.java, engine/src/org/pentaho/di/www/CarteDelegationHandler.java, engine/src/org/pentaho/di/www/JobMap.java, engine/src/org/pentaho/di/www/RunJobServlet.java, engine/src/org/pentaho/di/www/StartJobServlet.java, engine/src/org/pentaho/di/www/jaxrs/JobResource.java, test/org/pentaho/di/concurrency/JobMapConcurrencyTest.java
- Added synchronization of non-synchronized methods, touching common resources
- Refactored synchronization-area in some methods
- Removed unnecessary synchronization on the calls of  already-synchronized method
- Test written
Please, note, that test is placed in project-core test folder, where all concurrent tests (and concurrent-test executer) are located.
=> [PDI-8936] JobMap - Inconsistent synchronization can lead to corruption

core/src/org/pentaho/di/core/database/AS400DatabaseMeta.java, core/src/org/pentaho/di/core/database/DB2DatabaseMeta.java, core/src/org/pentaho/di/core/database/HypersonicDatabaseMeta.java, core/src/org/pentaho/di/core/database/KingbaseESDatabaseMeta.java, core/src/org/pentaho/di/core/database/MSSQLServerDatabaseMeta.java, core/src/org/pentaho/di/core/database/NetezzaDatabaseMeta.java, core/src/org/pentaho/di/core/database/OracleRDBDatabaseMeta.java, core/src/org/pentaho/di/core/database/VerticaDatabaseMeta.java, test/org/pentaho/di/core/database/SequenceMetaTests.java
=> [PDI-13609] Database Dialect Sequence Support

engine/src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputUtils.java, engine/src/org/pentaho/di/trans/steps/textfileinput/TextFileInput.java, engine/test-src/org/pentaho/di/trans/steps/fileinput/text/TextFileInputTest.java, engine/test-src/org/pentaho/di/trans/steps/textfileinput/TextFileInputTest.java
- in TextFileInput, set input string to null instead of setting result to null
- add test case
- fix Checkstyle violations
=> [PDI-14832] - Default values not working in TextFileInput

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java, test/org/pentaho/di/trans/TransTestFactory.java, test/org/pentaho/di/trans/steps/getfilenames/GetFileNamesIntTest.java
@mdamour1976 , @pamval 
Could you review the backport for https://github.com/pentaho/pentaho-kettle/pull/2032
=> [SP-2402][PDI-14800] Get Filenames step ignores parameters

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java, test/org/pentaho/di/trans/TransTestFactory.java, test/org/pentaho/di/trans/steps/getfilenames/GetFileNamesIntTest.java
@mdamour1976 , @pamval 
Could you review the backport for #2032
=> [PDI-14800] Get Filenames step ignores parameters

engine/test-src/org/pentaho/di/trans/TransTestingUtil.java
- recover failed test
@brosander, @pamval, merge it please to recover failed test
=> [SP-2404] - Backport of PDI-14823 - Using week in year date format with "Select values" step (6.0 Suite)

engine/src/org/pentaho/di/base/AbstractMeta.java, ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java, ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
=> [BACKLOG--5675] Add the Ability to remember run options

plugins/kettle-xml-plugin/ivy.xml
=> [CLEANUP] Missing dependency.

engine/src/org/pentaho/di/trans/steps/socketwriter/SocketWriter.java, engine/src/org/pentaho/di/trans/steps/socketwriter/SocketWriterData.java, engine/src/org/pentaho/di/www/SocketRepository.java
Properly release server sockets after transformation finishes
=> [PDI-14901] Clustering Release Sockets

ui/src/org/pentaho/di/ui/spoon/SpoonPluginManager.java, ui/test-src/org/pentaho/di/ui/spoon/SpoonPluginManagerTest.java
Refactored SpoonPluginManager, it now removes plugins on pluginRemoved
call.
@mattcasters @CodeOnCoffee would you mind rewieving?
=> [BACKLOG-5859] Allow pdi-dataservice bundles to be reinstalled in Spoon during runtime

engine/src/org/pentaho/di/job/entries/checkdbconnection/JobEntryCheckDbConnections.java
Add a case to properly set the millisecond precision for wait times
=> [PDI-14904] Check DB Connections Wait Times

engine/src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoader.java, engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderTest.java
Reverting https://github.com/pentaho/pentaho-kettle/pull/2103 changes. Will be sent into master branch.
=> Reverting PDI-11421 changes in 6.0 to be merged into master.

engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java, engine/test-src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookupUTest.java
- use only those fields that are needed for look-up (fix an error introduced in PDI-3314)
- add a test
@brosander, @deinspanjer, review it please
=> [BACKLOG-6496] - Database lookup step with "=" comparator fails on 6.1

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java, plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/RowOutputConverter.java, plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java
=> [PDI-10551] error line tweaks, error when no files

engine/src/org/pentaho/di/job/entries/dostounix/JobEntryDosToUnix.java
=> [PDI-14919] switch io.File delete+renameTo to nio.file.Files.move

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java
picked from https://github.com/pentaho/pentaho-kettle/pull/2129
=> [SP-2449] fixed the reference leak of cached objects

engine/src/org/pentaho/di/base/AbstractMeta.java, ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTransformationDelegate.java, ui/src/org/pentaho/di/ui/spoon/job/JobGraph.java, ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
=> [BACKLOG-6471] Run dialog cancel button fix

plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/GPLoadDataOutput.java
@pamval could you process ckeanup PR? Thanks!
=> [PDI-14749] Greenplum loader step does not handle TYPE_TIMESTAMP. Cleanup checkstyle violations.

plugins/googleanalytics/test-src/org/pentaho/di/trans/steps/googleanalytics/GaInputStepMetaInjectionTest.java, plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/RowOutputConverter.java, plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsonoutput/JsonOutput.java, plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsonoutput/JsonOutputMeta.java, plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsonoutput/JsonOutputMetaInjection.java, plugins/kettle-json-plugin/src/org/pentaho/di/ui/trans/steps/jsoninput/JsonInputDialog.java, plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsonoutput/JsonOutputTest.java
=> [TEST][CLEANUP] fix GaInputStepMetaInjectionTest.test; cleanup json-plugin

assembly/package-res/ui/laf.properties, ui/package-res/ui/images/cluster.svg, ui/package-res/ui/images/partition_schema.svg, ui/package-res/ui/images/slave.svg, ui/src/org/pentaho/di/ui/core/gui/GUIResource.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java
=> [PDI-14538] Resize icons in the PDI tree

ui/package-res/ui/images/job_tree.svg, ui/package-res/ui/images/transformation_tree.svg
=> [BACKLOG-6495] - Transformation/Job icons on the View tab need to be updated

ui/src/org/pentaho/di/ui/core/dialog/EnterSelectionDialog.java
=> [BACKLOG-6464] fixed buttons for mac OS. Ran checkstyle.

ui/src/org/pentaho/di/ui/core/dialog/EnterSelectionDialog.java
=> [BACKLOG-6464] really fixed buttons for mac OS. Ran checkstyle.

ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java
=> [BACKLOG-6471] bug fix for when user hits cancel button - ran checkstyle

engine/src/org/pentaho/di/core/injection/bean/BeanInjector.java, engine/test-src/org/pentaho/di/core/injection/MetaAnnotationInjectionTest.java
=> [BACKLOG-5722] Change metadata implementation for SelectValues step

ui/src/org/pentaho/di/ui/job/entries/mail/JobEntryMailDialog.java
=> [BACKLOG-6558] remove leftover ctrl-space listener

ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseController.java, ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/BrowseControllerTest.java
- accept new name only if user selects OK
- add tests
@brosander, review it please.
=> [PDI-14239] - DI Repository: New folder is created even after clicking on the button 'X' or "ESC" .

core/src/org/pentaho/di/core/RowMetaAndData.java, engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputField.java, engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java
=> [BACKLOG-6573] Regression with Metadata injecting the Excel input step

ui/src/org/pentaho/di/ui/repository/RepositoriesHelper.java
=> [BACKLOG-6464] changed ':' to '-'

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java, engine/test-src/org/pentaho/di/trans/steps/csvinput/CsvInputRowNumberTest.java
@brosander, review it please. For some reasons @hudak hasn't sent the PR, so it is me, who is doing it :smile:
=> [PDI-4837] - CSV File Input - fails to populate rownum, filenameField, input row count

engine/src/org/pentaho/di/trans/steps/denormaliser/DenormaliserMetaInjection.java, engine/test-src/org/pentaho/di/trans/steps/denormaliser/DenormaliserMetaInjectionIT.java, engine/test-src/org/pentaho/di/trans/steps/denormaliser/child.ktr, engine/test-src/org/pentaho/di/trans/steps/denormaliser/child2.ktr, engine/test-src/org/pentaho/di/trans/steps/denormaliser/pdi-11947.ktr
@mdamour1976 , @ddiroma  please review.
=> [PDI-11947] - Fields added to stream via denormaliser step in submappings cannot be recognised by modified javascript step  (and others)

engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java
http://jira.pentaho.com/browse/BACKLOG-6606
=> [BACKLOG-6606] Fixed issue with memory group by

ui/src/org/pentaho/di/ui/core/dialog/ArgumentsDialog.java
=> [BACKLOG-6445] - Made OK and Cancel Button the same size in OSX.

core/src/org/pentaho/di/core/util/StringUtil.java, core/src/org/pentaho/di/core/variables/Variables.java
Reverts pentaho/pentaho-kettle#2152
=> Revert "[BACKLOG-6555] - Changing properties variable type in Variables to Map"

core/src/org/pentaho/di/core/util/StringUtil.java, core/src/org/pentaho/di/core/variables/Variables.java, core/test-src/org/pentaho/di/core/util/StringUtilTest.java
Reverts pentaho/pentaho-kettle#2136
=> Revert "[PDI-8938] Synchronization in Variables class"

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputField.java, engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaInjectionTest.java, ui/test-src/org/pentaho/di/ui/spoon/SpoonFilterMatchingTest.java
=> [BACKLOG-6682] fix injectable trim type for excel input field

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputField.java, engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaInjectionTest.java, ui/test-src/org/pentaho/di/ui/spoon/SpoonFilterMatchingTest.java
@bmorrise @kcruzada please review
=> [BACKLOG-6682] fix injectable trim type for excel input field (6.1)

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositoryExporter.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
=> [BACKLOG-6748] overzealous close caused log error in java 8

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/LazyUnifiedRepositoryDirectory.java, ui/src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIRepositoryDirectory.java
UIRepositoryDirectory to first try to delete the directory from the
system and then from UI. Minor fix to LazyUnifiedRepositoryDirectory to
prevent IndexOutOfBoundsException on getSubdirectory( int i ) calls.
=> [BACKLOG-6700] Changed order of directory removal at

engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java
@bmorrise Please, merge it to 6.1. It's little correction of yesterday's MDI fix
=> [BACKLOG-6753] Better check source/target missed steps for MDI

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/LazyUnifiedRepositoryDirectory.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java
@rmansoor please review - this is for 6.1.0.0
=> [BACKLOG-6656] - LAZY_REPO: Error appears after click on new folder.

engine/test-src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterTest.java, engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java
@bmorrise Merge it to master also, please
=> Fix unit tests for after latest changes

engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java, engine/src/org/pentaho/di/trans/steps/metainject/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java, ui/src/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java
=> [BACKLOG-6767] - Add warning prompt to user when metadata injection mappings are missing

core/src/org/pentaho/di/core/database/BaseDatabaseMeta.java, core/src/org/pentaho/di/core/database/DatabaseInterfaceExtended.java, core/src/org/pentaho/di/core/database/DatabaseMeta.java, core/src/org/pentaho/di/core/database/OracleDatabaseMeta.java, core/test-src/org/pentaho/di/core/database/DatabaseMetaTest.java
- added new extending interface
- added general and Oracle specific implementation
@deinspanjer, review it please
=> [PDI-14979] - Add new method to DatabaseInterface in Kettle Core

engine/src/org/pentaho/di/job/JobMeta.java, engine/test-src/org/pentaho/di/job/JobExportIT.java, engine/test-src/org/pentaho/di/job/JobMetaTest.java, engine/test-src/org/pentaho/di/job/repo/folder/sample_job.kjb, engine/test-src/org/pentaho/di/job/repo/folder/sample_trans.ktr
- fixed current directory resolving when resources exporting
- added unit/integration tests
@akhayrutdinov, @brosander, review it please
=> [PDI-14653] Using export option with kitchen.sh

engine/src/org/pentaho/di/www/BaseJobServlet.java
What was done:
1) added setting of the metastore for uploaded jobs
=> BACKLOG-6794 -- Unable to run build model on diserver

ui/src/org/pentaho/di/ui/repository/controllers/RepositoriesController.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/xul/KettleDialog.java
=> [CHECKSTYLE] Removed some unused imports and reorder modifiers

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/LazyUnifiedRepositoryDirectory.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryPerformanceApp.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryTestBase.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/RepositoryTestLazySupport.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryIT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryTestBase.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepositoryUnitTest.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_IT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_Test.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_GetObjectInformation_IT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_MoveAndRename_IT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_RepositoryDirectory_IT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_Revisions_IT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_IT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java, plugins/pdi-pur-plugin/test/org/pentaho/di/ui/repository/pur/repositoryexplorer/model/UIEERepositoryDirectoryIT.java
@pentaho-nbaker @rmansoor please take a look at these changes - it will run all PUR tests that work with Repository 2 times with *LAZY_REPOSITORY* flag set to *true* and *false*.
=> [TEST] - run pur tests with Lazy and non-Lazy flag

engine/src/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java, engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java, engine/test-src/org/pentaho/di/trans/steps/jobexecutor/JobExecutorTest.java, engine/test-src/org/pentaho/di/trans/steps/transexecutor/TransExecutorUnitTest.java
- fixed job/trans execution grouping by field and by size
@brosander, @akhayrutdinov, please review the changes.
=> [PDI-14958] - Grouping in Transformation Executor stopped working

engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInputMetaCloningTest.java
@pedrofvteixeira, @pamval, start WM for this PR please
=> [PDI-14972] - Input Mapping Specification step not saving length and precision on export to xml

plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforcedelete/SalesforceDeleteDialog.java, plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java, plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinsert/SalesforceInsertDialog.java, plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceupdate/SalesforceUpdateDialog.java, plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceupsert/SalesforceUpsertDialog.java
Show real username when testing the Salesforce connection
=> [PDI-14403] Salesforce Error Message

core/src/org/pentaho/di/cluster/SlaveConnectionManager.java, core/test-src/org/pentaho/di/cluster/SlaveConnectionManagerTest.java
Change to initialize SSLContext only if keyStore is not set.
=> [PDI-14723] - HTTP client stopped work with client certificate

plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/AddXMLMeta.java, plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/XMLField.java, plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/messages/messages_en_US.properties, plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/addxml/AddXMLMetaInjectionTest.java
@bmorrise could you please review?
=> [BACKLOG-5733] - Add MDI support to XML Add

plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmlinputstream/messages/messages_en_US.properties
=> [PDI-15085] Moved XML Input Stream step to Input category

engine/src/org/pentaho/di/job/JobMeta.java, engine/test-src/org/pentaho/di/job/JobExportIT.java, engine/test-src/org/pentaho/di/job/JobMetaTest.java, engine/test-src/org/pentaho/di/job/repo/folder/sample_job.kjb, engine/test-src/org/pentaho/di/job/repo/folder/sample_trans.ktr
- fixed current directory resolving when resources exporting
- added unit/integration tests
@akhayrutdinov @brosander review please. It's a backport of #2249
=> [SP-2530][PDI-14653] - Using export option with kitchen.sh

plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java, plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/getxmldata/GetXMLDataTest.java
=>   [PDI-11018] getXMLData - Variables are overwritten

engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java, engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByAggregationTest.java
Better handling of null values for minimum and count distinct aggregates
http://jira.pentaho.com/browse/BACKLOG-7056
http://jira.pentaho.com/browse/PDI-14974
=> [BACKLOG-7056]MemoryGroupBy null handlling

engine/src/org/pentaho/di/job/JobMeta.java, engine/test-src/org/pentaho/di/job/JobExportTest.java, engine/test-src/org/pentaho/di/job/JobMetaTest.java, engine/test-src/org/pentaho/di/job/repo/folder/sample_job.kjb, engine/test-src/org/pentaho/di/job/repo/folder/sample_trans.ktr
- fixed current directory resolving when resources exporting
- added unit/integration tests
@akhayrutdinov @brosander review please. It's a backport of #2249.
=> [SP-2531][PDI-14653] - Using export option with kitchen.sh

engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta.java, engine/src/org/pentaho/di/trans/steps/tableoutput/TableOutputMeta.java, engine/test-src/org/pentaho/di/trans/steps/tableoutput/TableOutputMetaTest.java
Also addressing a test which was failing due to
a violation of an implicit invariant.
@mbatchelor
=> [PDI-15057]  Correcting a typo on an array copy.

assembly/package-res/yarn.sh
Reverts pentaho/pentaho-kettle#2305
=> Revert "[PDI-15058] - Container dir as karaf cache dir"

engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValues.java, engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java, engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaInjectionTest.java, engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValuesTest.java, engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValues_LocaleHandling_Test.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/trans/steps/selectvalues/SelectValuesDialog.java
=> [PDI-15032] - Metadata Injection on all tabs of select values step is causing error

engine/src/org/pentaho/di/trans/steps/getfilesrowscount/GetFilesRowsCountMeta.java, engine/test-src/org/pentaho/di/trans/steps/getfilesrowscount/GetFilesRowsCountMetaTest.java
GetFilesRowCountMeta.clone()
@pamval
=> [PDI-15057]  correcting arraycopy destination in

engine/src/org/pentaho/di/repository/RepositoryOperation.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/AbsSecurityProvider.java, plugins/pdi-pur-plugin/src/org/pentaho/di/ui/repository/pur/services/IAbsSecurityProvider.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/AbsSecurityProviderTest.java
- Since we have a separate "Schedule content" permission in permission list, we separately check permissions for this operation.
- Test written
More details:
**AbsSecurityProvider**
- Added check for scheduling action
- Refactored code a little
**IAbsSecurityProvider**
- Added constant for scheduling action
- Removed unnecessary public static final on fields, as this is done by default since this are variables of an interface.
**RepositoryOperation**
- Added enums for job and trans scheduling
@akhayrutdinov, could you please review it?
=> [PDI-15018] DI Server security not behaving properly.

engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java
@mkambol , @bmorrise, @brosander , @PavelSakoun  please review
=> [PDI-15032] - Metadata Injection on all tabs of select values step is causing error - revert public api change

plugins/salesforce/src/org/pentaho/di/trans/steps/salesforcedelete/SalesforceDeleteMeta.java
=> [BACKLOG-7205] space in salesforce delete label

plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/AddXML.java, plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/XMLField.java, plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/addxml/AddXMLMetaInjectionTest.java, plugins/kettle-xml-plugin/test-src/org/pentaho/di/trans/steps/addxml/AddXMLMetaTest.java
=> [BACKLOG-5733] - Add MDI support to XML Add - type conversion + fix error message

engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringTest.java, engine/test-src/org/pentaho/di/trans/steps/textfileoutput/TextFileOutputTest.java
=> [TEST] Correcting 2 test classes which had ambiguous

dbdialog/test-src/org/pentaho/ui/database/event/FragmentHandlerTest.java
=> [TEST] Fixing dbdialog test class with ambiguous

engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java, engine/test-src/org/pentaho/di/job/entries/sftp/SFTPClientTest.java
- changed gssapi auth to be enabled depending on -D parameter
- added/fixed unit tests
=> [PDI-14988] - Add option to disable interactive GSSAPI authentication

plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java
=> [TEST] fix failing json input tests after vfs change

ui/src/org/pentaho/di/ui/spoon/delegates/SpoonJobDelegate.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonStepsDelegate.java
=> [BACKLOG-7103] Undo issue in Kettle, wrong hop removed

assembly/ivy.xml, build.properties
=> [BACKLOG-6502] Added kettle-sap-plugin to xvy.xml

engine/src/org/pentaho/di/job/entries/zipfile/JobEntryZipFile.java, engine/test-src/org/pentaho/di/job/entries/zipfile/JobEntryZipFileIT.java
- fail on non-existing path
- in JobEntryZipFile, remove useless assignments (highlighted by Intelij)
- add a test
=> [PDI-15013] - Create zip files runs successfully with wrong Source path

engine/src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMeta.java, engine/test-src/org/pentaho/di/trans/steps/selectvalues/SelectValuesMetaTest.java
=> [PDI-15032] - Metadata Injection on all tabs of select values step is causing error - fix backward compatibility

plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceupsert/SalesforceUpsertDialog.java
=> [BACKLOG-7088][PDI-15139] salesforce upsert module fields fetching

ui/src/org/pentaho/di/ui/job/dialog/JobExecutionConfigurationDialog.java, ui/src/org/pentaho/di/ui/trans/dialog/TransExecutionConfigurationDialog.java
=> [BACKLOG-6444] - [Launcher] Increase the width for the field Log Level

core/src/org/pentaho/di/core/database/Database.java, core/test-src/org/pentaho/di/core/exception/LookupReferencesExceptionTest.java
@brosander, @mbatchelor, review it please. This is a backport of  https://github.com/pentaho/pentaho-kettle/pull/1376. Also I backported a fix for incorrect test.
=> [SP-2605] - Backport of PDI-13789 - Intermittent ConcurrentModificationException in Database.getValueFromSQLType (5.4 Suite)

engine/src/org/pentaho/di/repository/RepositoryOperation.java
- Adding SCHEDULE_TRANSFORMATION and SCHEDULE_JOB enums
@akhayrutdinov , review it please. It's a part of a backport of  https://github.com/pentaho/pentaho-kettle/pull/2326 and  for 5.4
=> [SP-2594] Backport of PDI-15018 - DI Server security not behaving properly. (5.4 Suite)

engine/src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMeta.java, engine/src/org/pentaho/di/trans/steps/replacestring/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMetaInjectionTest.java
=> [BACKLOG-7187] MDI for replace string step

assembly/package-res/ui/spoon.xul, ui/src/org/pentaho/di/ui/spoon/Spoon.java
=> [BACKLOG-7108] - Error creating a DB connection when connected to repository and no Job/Transformation open

engine/test-src/org/pentaho/di/job/entry/loadSave/LoadSaveTester.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/LoadSaveTester.java
Ensure when a step meta is cloned, that it contains all of the same information as XML or Repository serialization.
=> [TEST] Add clone method checks

engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java, engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectMapping.java, engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java, engine/src/org/pentaho/di/trans/steps/metainject/MetaInjectOutputField.java, engine/src/org/pentaho/di/trans/steps/metainject/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/core/injection/BaseMetadataInjectionTest.java, engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectMetaInjectionTest.java, engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectMetaTest.java
=> [BACKLOG-7186] - Metadata Injection for Metadata Injection step

engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java
git cherry-pick d072f1a94dbd6bd79cd83fe2ec44ac4bf8e4faa5
=> [BACKLOG-7662] - Fix allocate in constructor

ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java, ui/src/org/pentaho/di/ui/job/dialog/JobExecutionConfigurationDialog.java, ui/src/org/pentaho/di/ui/trans/dialog/TransExecutionConfigurationDialog.java
Changed to match OSX mock.  Rank checkstyles. @bmorrise
=> [BACKLOG-6425] -Changed layout for trans an job run dialogs.

engine/src/org/pentaho/di/trans/steps/mergejoin/messages/messages_en_US.properties
=> [BACKLOG-7185] MDI descriptions for merge join

dbdialog/src/org/pentaho/ui/database/event/DataHandler.java, dbdialog/test-src/org/pentaho/ui/database/event/DataHandlerTest.java
Added code to migrate connection to the new format once edited
@hudak
=> [BACKLOG-5453] Add the field "webapp name" for Pentaho Data Service database type (SWT Dialog)

engine/src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/mappinginput/MappingInputMeta_GetFields_Test.java
This reverts commit 69cfe50dad7e0ab86d43baa4c4fa2c6ce811069c.
Fixing problem Merge Join breaks metadata of sub-transformation http://jira.pentaho.com/browse/PDI-10600 
Regression http://jira.pentaho.com/browse/BACKLOG-4404  is not reproducible now.
@brosander @mchen-len-son Could you please review?
=> Revert "[PDI-10600] - Merge Join breaks metadata of sub-transformation"

ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java, ui/src/org/pentaho/di/ui/job/dialog/JobExecutionConfigurationDialog.java, ui/src/org/pentaho/di/ui/trans/dialog/TransExecutionConfigurationDialog.java
=> [BACKLOG-6425] Tweak Run Dialogs across operating systems - Linux

engine/src/org/pentaho/di/trans/steps/multimerge/MultiMergeJoinMeta.java, engine/test-src/org/pentaho/di/trans/steps/multimerge/MultiMergeJoinMetaTest.java
http://jira.pentaho.com/browse/SP-2659
Backport of PDI-15146 - Multiway Merge Join step loses all settings after saving to PDI repository (6.1 Suite)
@brosander @mchen-len-son Could you please review and merge?
=> 6.1 pdi 15146 backport

assembly/package-res/ui/spoon.xul, ui/package-res/ui/images/perspective_changer.svg, ui/src/org/pentaho/di/ui/spoon/SpoonPerspectiveManager.java
=> [BACKLOG-7155] Added new perspective view

ui/src/org/pentaho/di/ui/spoon/SpoonPerspectiveManager.java
=> [BACKLOG-7155] Added the perspectiveMap back in

engine/src/org/pentaho/di/trans/Trans.java, engine/src/org/pentaho/di/trans/step/BaseStep.java, engine/test-src/org/pentaho/di/trans/TransTest.java, engine/test-src/org/pentaho/di/trans/step/BaseStepTest.java
@bmorrise i fixed license header violations (from the previous PR https://github.com/pentaho/pentaho-kettle/pull/2446) and Michael agreed to my comments, so i guess it is time to review and process this pull request.
=> [BACKLOG-7997] - Can not execute partitioned clustered transformation

engine/src/org/pentaho/di/trans/steps/accessinput/AccessInputMeta.java, engine/test-src/org/pentaho/di/job/entries/sql/JobEntrySQLTest.java, engine/test-src/org/pentaho/di/job/entry/loadSave/JobEntryLoadSaveTestSupport.java, engine/test-src/org/pentaho/di/job/entry/loadSave/LoadSaveBase.java, engine/test-src/org/pentaho/di/job/entry/loadSave/LoadSaveTester.java, engine/test-src/org/pentaho/di/trans/steps/accessinput/AccessInputMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/addsequence/AddSequenceMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/analyticquery/AnalyticQueryMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/filestoresult/FilesToResultMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/LoadSaveTester.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/MemoryRepository.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/DatabaseMetaLoadSaveValidator.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/DefaultFieldLoadSaveValidatorFactory.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/IntLoadSaveValidator.java, engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/randomvalue/RandomValueMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/symmetriccrypto/symmetriccryptotrans/SymmetricCryptoTransMetaTest.java
Added LoadSaveTests for a couple of steps
Added the ability to test database connection step/jobentry attributes
=> LoadSave Tests

ui/src/org/pentaho/di/ui/core/dialog/ThinDialog.java
=> [BACKLOG-7462] Added thin dialog

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java, plugins/repositories-plugin/src/main/resources/web/create-new-connection.html, plugins/repositories-plugin/src/main/resources/web/creation-failure.html, plugins/repositories-plugin/src/main/resources/web/creation-success.html, plugins/repositories-plugin/src/main/resources/web/css/style.css, plugins/repositories-plugin/src/main/resources/web/index.html, plugins/repositories-plugin/src/main/resources/web/js/controllers.js, plugins/repositories-plugin/src/main/resources/web/js/models.js, plugins/repositories-plugin/src/main/resources/web/kettle-database-repository-details.html, plugins/repositories-plugin/src/main/resources/web/kettle-database-repository-select.html, plugins/repositories-plugin/src/main/resources/web/kettle-file-repository-details.html, plugins/repositories-plugin/src/main/resources/web/pentaho-repository-connection-details.html, plugins/repositories-plugin/src/main/resources/web/pentaho-repository.html, plugins/repositories-plugin/src/main/resources/web/repository-manager.html
=> [BACKLOG-7661] thin repo styling changes

plugins/pom.xml, plugins/repositories-plugin/pom.xml
tested and confirmed on master-snapshot job
=> [BACKLOG-8056] created parent pom for plugins; cleanup of repository-plugin

engine/src/org/pentaho/di/trans/steps/fileinput/text/messages/messages_en_US.properties, ui/src/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileInputDialog.java, ui/test-src/org/pentaho/di/ui/trans/steps/fileinput/text/TextFileInputDialogTest.java
- The 'Minimal Width' button ported to actual Text File Input step
- TextFileInputDialogTest switched from deprecated to actual Text File Input step
=> [PDI-15117] Issues with the GitHub code base according to the Text File Input step

plugins/repositories-plugin/src/main/resources/web/css/style.css, plugins/repositories-plugin/src/main/resources/web/kettle-database-repository-select.html, plugins/repositories-plugin/src/main/resources/web/pentaho-repository-connect.html
=> [BACKLOG-7661] styling changes to thin repo UI

plugins/repositories-plugin/src/main/resources/web/create-new-connection.html, plugins/repositories-plugin/src/main/resources/web/css/style.css, plugins/repositories-plugin/src/main/resources/web/kettle-database-repository-select.html, plugins/repositories-plugin/src/main/resources/web/kettle-file-repository-details.html, plugins/repositories-plugin/src/main/resources/web/pentaho-repository.html, plugins/repositories-plugin/src/main/resources/web/repository-manager.html
=> [BACKLOG-7157] style changes

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java, plugins/repositories-plugin/src/main/resources/web/pentaho-repository-connection-details.html
=> [BACKLOG-7463] Fixed an issue with saving and deleting

plugins/repositories-plugin/src/main/resources/web/create-new-connection.html, plugins/repositories-plugin/src/main/resources/web/css/style.css, plugins/repositories-plugin/src/main/resources/web/repository-manager.html
=> [BACKLOG-7463] Style fixes for thin repo

core/src/org/pentaho/di/core/row/ValueMetaInterface.java, core/src/org/pentaho/di/core/row/value/ValueMetaBase.java, core/src/org/pentaho/di/core/row/value/ValueMetaBigNumber.java, core/src/org/pentaho/di/core/row/value/ValueMetaBinary.java, core/src/org/pentaho/di/core/row/value/ValueMetaBoolean.java, core/src/org/pentaho/di/core/row/value/ValueMetaDate.java, core/src/org/pentaho/di/core/row/value/ValueMetaInteger.java, core/src/org/pentaho/di/core/row/value/ValueMetaInternetAddress.java, core/src/org/pentaho/di/core/row/value/ValueMetaNone.java, core/src/org/pentaho/di/core/row/value/ValueMetaNumber.java, core/src/org/pentaho/di/core/row/value/ValueMetaString.java, core/src/org/pentaho/di/core/row/value/ValueMetaTimestamp.java, core/test-src/org/pentaho/di/core/row/value/ValueMetaBaseTest.java, core/test-src/org/pentaho/di/core/row/value/ValueMetaFactoryTest.java, engine/src/org/pentaho/di/trans/steps/janino/Janino.java, engine/src/org/pentaho/di/trans/steps/janino/JaninoData.java, engine/src/org/pentaho/di/trans/steps/janino/JaninoMeta.java, engine/src/org/pentaho/di/trans/steps/janino/JaninoMetaFunction.java, engine/src/org/pentaho/di/trans/steps/janino/JaninoMetaInjection.java, engine/src/org/pentaho/di/trans/steps/janino/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/janino/JaninoMetaTest.java, test/org/pentaho/di/trans/steps/janino/JaninoMetaInjectionTest.java, test/org/pentaho/di/trans/steps/janino/JaninoStepTest.java
Add support for custom ValueMeta types in User-Defined Java Expression steps.
Adds a method to the ValueMetaInterface class.
=> [PDI-14347] UDJE Step allow ValueMeta plugins

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java, plugins/repositories-plugin/src/main/resources/web/create-new-connection.html, plugins/repositories-plugin/src/main/resources/web/js/controllers.js, plugins/repositories-plugin/src/main/resources/web/kettle-database-repository-select.html
=> [BACKLOG-7661] fixed default repository and small styling changes

plugins/repositories-plugin/src/main/resources/web/images/caution.svg, plugins/repositories-plugin/src/main/resources/web/images/close_notif.svg
=> [BACKLOG-7962] Added error images for thin repo connection

engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java, engine/test-src/org/pentaho/di/job/entries/sftp/SFTPClientTest.java
- changed gssapi auth to be enabled depending on -D parameter
=> [SP-2681] Backport of PDI-14988 - Add option to disable interactive GSSAPI authentication (6.1 Suite)

engine/src/org/pentaho/di/job/entries/sftp/SFTPClient.java, engine/test-src/org/pentaho/di/job/entries/sftp/SFTPClientTest.java
- changed gssapi auth to be enabled depending on -D parameter
=> [SP-2682] Backport of PDI-14988 - Add option to disable interactive GSSAPI authentication (5.4 Suite)

core/ivy.xml
=> [ENGOPS-1918] Update Commons-DBCP in Core

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java
=> [BACKLOG-8357] Check for username is null

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryDialog.java, plugins/repositories-plugin/src/main/resources/web/js/controllers.js, plugins/repositories-plugin/src/main/resources/web/js/models.js, plugins/repositories-plugin/src/main/resources/web/pentaho-repository-connect.html
=> [BACKLOG-8357] Show repository name on the login screen

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java, plugins/repositories-plugin/src/main/resources/web/js/controllers.js, plugins/repositories-plugin/src/main/resources/web/repository-manager.html
=> [BACKLOG-8357] Allow user to un-default a repository

engine/src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValuesAddedFunctions.java, engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValueAddFunctions_GetVariableScopeTest.java, engine/test-src/org/pentaho/di/trans/steps/scriptvalues_mod/ScriptValueAddFunctions_SetVariableScopeTest.java
- Refactoring (changing variable names, representing variable scopes as enums, separating logic of setting variable on different scope-levels in different methods)
- Starting to climb variable-space hierarchy from the step's transformation (not from the step itself, as the first call to step's parent will lead to the transformation itself, which is not the expected behavior)
=> [PDI-14852] setVariable in Javascript Step with scope of parent job does not work

engine/src/org/pentaho/di/trans/steps/accessinput/AccessInputMeta.java, engine/test-src/org/pentaho/di/job/entries/sql/JobEntrySQLTest.java, engine/test-src/org/pentaho/di/job/entry/loadSave/JobEntryLoadSaveTestSupport.java, engine/test-src/org/pentaho/di/job/entry/loadSave/LoadSaveBase.java, engine/test-src/org/pentaho/di/job/entry/loadSave/LoadSaveTester.java, engine/test-src/org/pentaho/di/trans/steps/accessinput/AccessInputMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/addsequence/AddSequenceMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/analyticquery/AnalyticQueryMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/filestoresult/FilesToResultMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/LoadSaveTester.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/MemoryRepository.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/DatabaseMetaLoadSaveValidator.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/DefaultFieldLoadSaveValidatorFactory.java, engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/IntLoadSaveValidator.java, engine/test-src/org/pentaho/di/trans/steps/mysqlbulkloader/MySQLBulkLoaderMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/randomvalue/RandomValueMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/replacestring/ReplaceStringMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/symmetriccrypto/symmetriccryptotrans/SymmetricCryptoTransMetaTest.java
=> [SP-2688] Backport of PDI-15288 - Microsoft Access Input step (Spoon) throws 'Unable to open dialog for this step' after Get Fields (6.1 Suite)

engine/src/org/pentaho/di/trans/steps/nullif/NullIfMeta.java, engine/src/org/pentaho/di/trans/steps/nullif/messages/messages_en_US.properties
=> [BACKLOG-8271] - Added annotations and messages for Null If step.

engine/src/org/pentaho/di/trans/steps/nullif/NullIf.java, engine/src/org/pentaho/di/trans/steps/nullif/NullIfMeta.java, engine/test-src/org/pentaho/di/trans/steps/nullif/NullIfMetaInjectionTest.java, engine/test-src/org/pentaho/di/trans/steps/nullif/NullIfMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/nullif/NullIfTest.java, ui/src/org/pentaho/di/ui/trans/steps/nullif/NullIfDialog.java
@mdamour1976 please review the changes.
=> [BACKLOG-8271] - Add Metadata Injection (MDI) support to the Null if step - array alignment

engine/src/org/pentaho/di/trans/steps/getvariable/GetVariable.java, engine/src/org/pentaho/di/trans/steps/getvariable/GetVariableMeta.java, engine/test-src/org/pentaho/di/trans/steps/getvariable/GetVariableMetaInjectionTest.java, engine/test-src/org/pentaho/di/trans/steps/getvariable/GetVariableMetaTest.java, ui/src/org/pentaho/di/ui/trans/steps/getvariable/GetVariableDialog.java
=> [BACKLOG-8421] - Add Metadata Injection (MDI) support to the Get Variables Step - array alignment

engine/src/org/pentaho/di/trans/steps/multimerge/MultiMergeJoinMeta.java
Step Dialog failed to open due to NPE
=> [CLEANUP] MultiMerge Clone NPE

engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStep.java, engine/src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepMeta.java, engine/src/org/pentaho/di/trans/steps/excelwriter/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/excelwriter/ExcelWriterStepMetaTest.java, ui/src/org/pentaho/di/ui/trans/steps/excelwriter/ExcelWriterStepDialog.java
Add a UI setting to enable hiding the Template sheet after the sheet for output is created
=> [PDI-13748] Hide Template Sheet option

plugins/repositories-plugin/src/main/resources/org/pentaho/di/ui/repo/messages/messages_en_US.properties
=> [BACKLOG-8583] Correct misspelling on the new dialog Login to Repository

engine/src/org/pentaho/di/trans/steps/accessoutput/AccessOutput.java, engine/src/org/pentaho/di/trans/steps/accessoutput/AccessOutputData.java, engine/src/org/pentaho/di/trans/steps/accessoutput/AccessOutputMeta.java, engine/src/org/pentaho/di/trans/steps/accessoutput/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/accessoutput/AccessOutputDataTest.java, engine/test-src/org/pentaho/di/trans/steps/accessoutput/AccessOutputMetaTest.java, engine/test-src/org/pentaho/di/trans/steps/accessoutput/AccessOutputTest.java, ui/src/org/pentaho/di/ui/trans/steps/accessoutput/AccessOutputDialog.java
Adds the ability to truncate an Access table before writing new rows
=> [PDI-13884] Access Output Truncate Table option

ui/src/org/pentaho/di/ui/trans/steps/userdefinedjavaclass/codeSnippits.xml, ui/test-src/org/pentaho/di/ui/trans/steps/userdefinedjavaclass/UserDefinedJavaClassCodeSnippitsTest.java
Removed tabs and other formatting changes
=> [CLEANUP] UDJC Snippet Formatting

core/src/org/pentaho/di/core/Const.java, engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupBy.java, engine/src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMeta.java, engine/src/org/pentaho/di/trans/steps/memgroupby/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByAggregationTest.java, engine/test-src/org/pentaho/di/trans/steps/memgroupby/MemoryGroupByMetaTest.java
SUM and Average should return the same type as they are aggregating, instead of always Numeric (w/ decimal) values.
=> [PDI-5537] MemoryGroupBy Aggregation Return Types

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositorySpoonStartExtensionPoint.java, plugins/repositories-plugin/src/main/resources/org/pentaho/di/ui/repo/messages/messages_en_US.properties
=> [BACKLOG-8416] Updated connection error messages

ui/src/org/pentaho/di/ui/core/dialog/EnterMappingDialog.java
Matches longest, best matches first
=> PDI-11865 Improved Field match guess algorithm handles SFDC reference fields

plugins/repositories-plugin/src/main/resources/org/pentaho/di/ui/repo/messages/messages_en_US.properties
=> [BACKLOG-8416] Added apostrophe for Windows messages

core/src/org/pentaho/di/core/xml/XMLCheck.java, core/src/org/pentaho/di/core/xml/XMLHandler.java, core/src/org/pentaho/di/core/xml/XMLParserFactoryProducer.java, core/test-src/org/pentaho/di/core/xml/XMLCheckTest.java, core/test-src/org/pentaho/di/core/xml/XMLHandlerUnitTest.java, core/test-src/org/pentaho/di/core/xml/XMLUtilsTest.java, engine/src/org/pentaho/di/core/util/SerializationHelper.java, engine/src/org/pentaho/di/repository/RepositoriesMeta.java, engine/src/org/pentaho/di/repository/RepositoryExportSaxParser.java, engine/src/org/pentaho/di/trans/steps/webservices/WebService.java, engine/test-src/org/pentaho/di/core/util/SerializationHelperTest.java, engine/test-src/org/pentaho/di/repository/RepositoriesMetaTest.java, engine/test-src/org/pentaho/di/repository/RepositoryExportSaxParserTest.java, engine/test-src/org/pentaho/test/util/XXEUtils.java, plugins/kettle-xml-plugin/src/org/pentaho/di/job/entries/dtdvalidator/DTDValidator.java, plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/addxml/AddXML.java, plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/xmljoin/XMLJoin.java, plugins/pdi-pur-plugin/src/com/pentaho/pdi/ws/RepositorySyncWebService.java, plugins/pdi-pur-plugin/src/com/pentaho/repository/importexport/PDIImportUtil.java, plugins/pdi-pur-plugin/test/com/pentaho/repository/importexport/PDIImportUtilTest.java
- Applying security to parsing, centralising xml-factory creation in XMLUtils class.
=> [PPP-3506][PPP-3533] pentaho-kettle: XXE Security Vulnerability in xml parsers

plugins/repositories-plugin/src/main/resources/web/css/style.css, plugins/repositories-plugin/src/main/resources/web/error-message.html, plugins/repositories-plugin/src/main/resources/web/images/close_notif.svg, plugins/repositories-plugin/src/main/resources/web/index.html, plugins/repositories-plugin/src/main/resources/web/js/app.js, plugins/repositories-plugin/src/main/resources/web/js/controllers.js, plugins/repositories-plugin/src/main/resources/web/js/models.js, plugins/repositories-plugin/src/main/resources/web/kettle-database-repository-details.html, plugins/repositories-plugin/src/main/resources/web/kettle-file-repository-details.html, plugins/repositories-plugin/src/main/resources/web/pentaho-repository-connect.html, plugins/repositories-plugin/src/main/resources/web/pentaho-repository-connection-details.html
=> [BACKLOG-7962] Implement error messages for thin repo flow

engine/src/org/pentaho/di/trans/steps/ssh/SSH.java, engine/src/org/pentaho/di/trans/steps/ssh/SSHData.java, engine/src/org/pentaho/di/trans/steps/ssh/SSHMeta.java, ui/src/org/pentaho/di/ui/trans/steps/ssh/SSHDialog.java
Moving and Deprecating the OpenConnection method to allow for easier unit testing of the Meta class in external plugins
=> [CLEANUP] Move SSH Connection Method to Data class

engine/src/org/pentaho/di/trans/steps/janino/Janino.java, test/org/pentaho/di/trans/steps/janino/JaninoStepTest.java
Cast an "Integer" return value to Long, to match the expected type of a ValueMetaInteger
=> [BACKLOG-8454] Spoon: "User Defined Java Expression" step fails

engine/src/org/pentaho/di/trans/steps/databaselookup/DatabaseLookup.java
Updated DatabaseLookup step -> enabled cache when "IS NULL" condition is used.
=> [PDI-15202] Enable cache on "IS NULL" condition (DatabaseLookup step)

assembly/package-res/ui/trans-toolbar.xul, core/src/org/pentaho/di/core/row/ValueDataUtil.java, engine/src/org/pentaho/di/trans/steps/calculator/Calculator.java, engine/src/org/pentaho/di/trans/steps/calculator/CalculatorMetaFunction.java, engine/src/org/pentaho/di/trans/steps/calculator/messages/messages_en_US.properties, engine/src/org/pentaho/di/trans/steps/calculator/messages/messages_fr_FR.properties, engine/src/org/pentaho/di/trans/steps/calculator/messages/messages_it_IT.properties, engine/test-src/org/pentaho/di/trans/steps/calculator/CalculatorUnitTest.java
Partly backport of https://github.com/pentaho/pentaho-kettle/pull/2620.
In the PR above there are two issues fixed: PDI-12388 and PDI-12923.
This PR is only for PDI-12388.
=> [SP-2729] Backport of PDI-12388 - Delete Hop Shortcut on Context Menu in PDI Transformation (5.4 Suite)

assembly/package-res/ui/trans-toolbar.xul, core/src/org/pentaho/di/core/row/ValueDataUtil.java, engine/src/org/pentaho/di/trans/steps/calculator/Calculator.java, engine/src/org/pentaho/di/trans/steps/calculator/CalculatorMetaFunction.java, engine/src/org/pentaho/di/trans/steps/calculator/messages/messages_en_US.properties, engine/src/org/pentaho/di/trans/steps/calculator/messages/messages_fr_FR.properties, engine/src/org/pentaho/di/trans/steps/calculator/messages/messages_it_IT.properties, engine/test-src/org/pentaho/di/trans/steps/calculator/CalculatorUnitTest.java
Partly backport of https://github.com/pentaho/pentaho-kettle/pull/2620.
In the PR above there are two issues fixed: PDI-12388 and PDI-12923.
This PR is only for PDI-12388.
@mchen-len-son , could you please review it?
=> [SP-2728] Backport of PDI-12388 - Delete Hop Shortcut on Context Menu in PDI Transformation (6.1 Suite)

engine/src/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java
Backport of https://github.com/pentaho/pentaho-kettle/pull/1456 + checkstyle
=> [SP-2722] Backport of PDI-14022 - Excel Output can't handle templates in *nix systems (5.4 Suite)

engine/src/org/pentaho/di/trans/steps/exceloutput/ExcelOutput.java
Backport of https://github.com/pentaho/pentaho-kettle/pull/1456 + checkstyle
=> [SP-2723] Backport of PDI-14022 - Excel Output can't handle templates  in *nix systems (6.1 Suite)

ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java, ui/src/org/pentaho/di/ui/job/dialog/JobExecutionConfigurationDialog.java, ui/src/org/pentaho/di/ui/trans/dialog/TransExecutionConfigurationDialog.java
Ran successful checkstyle
@bmorrise @mdamour1976
=> [BACKLOG-8199] UI Glitch when select the option Server

core/src/org/pentaho/di/core/extension/KettleExtensionPoint.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonStepsDelegate.java, ui/test-src/org/pentaho/di/ui/spoon/delegates/SpoonStepsDelegateTest.java
Data services part: https://github.com/pentaho/pdi-dataservice-server-plugin/pull/178
=> [BACKLOG-7526] Removing a step with a data service should allow remapping or deleting the service

engine/src/org/pentaho/di/trans/steps/metainject/MetaInject.java, engine/test-src/org/pentaho/di/trans/steps/StepMockUtil.java, engine/test-src/org/pentaho/di/trans/steps/metainject/MetaInjectTest.java, ui/src/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java
=> [BACKLOG-8827] design-time check and remove invalid target keys

engine/src/org/pentaho/di/job/entries/waitforsql/JobEntryWaitForSQL.java
backport of https://github.com/pentaho/pentaho-kettle/pull/2627
=> [SP-2750] Backport of PDI-15437 - JobEntryWaitForSQL doesn't succeed without errors (5.4 Suite)

engine/src/org/pentaho/di/job/entries/waitforsql/JobEntryWaitForSQL.java
backport of https://github.com/pentaho/pentaho-kettle/pull/2627
=> [SP-2749] Backport of PDI-15437 - JobEntryWaitForSQL doesn't succeed without errors (6.1 Suite)

engine/test-src/org/pentaho/di/trans/steps/loadsave/validator/DateLoadSaveValidator.java
=> [TEST] fix SlaveServer(Trans|Job)StatusTest.testSerialization

core/src/org/pentaho/di/core/BaseRowSet.java, engine/test-src/org/pentaho/di/concurrency/BaseRowSetConcurrentTest.java
=> [PDI-8941] BaseRowSet synchronization needs re-evaluated

core/src/org/pentaho/di/core/vfs/configuration/KettleSftpFileSystemConfigBuilder.java, core/test-src/org/pentaho/di/core/vfs/configuration/KettleSftpFileSystemConfigBuilderTest.java
Change to IdentityInfo as needed by VFS 2.1
=> [PDI-15501] VFS SFTP Identity Fix

build.xml, engine/src/org/pentaho/di/job/entries/waitforsql/JobEntryWaitForSQL.java, test/org/pentaho/di/job/entries/waitforsql/JobEntryWaitForSQLTest.java
~~Belt and Suspenders due to PDI-15437~~
Test Cases added
=> [PDI-15453] JobEntryWaitForSQL Wrong Error Count

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepositoryConnector.java, plugins/pdi-pur-plugin/src/org/pentaho/di/ui/repository/EESpoonPlugin.java, plugins/pdi-pur-plugin/test/org/pentaho/di/ui/repository/EESpoonPluginTest.java
=> [BACKLOG-9014] hide scheduler perspective from plugin instead of connector

engine/src/org/pentaho/di/trans/steps/getvariable/GetVariableMeta.java, engine/test-src/org/pentaho/di/trans/steps/getvariable/GetVariableMetaTest.java
Backport of https://github.com/pentaho/pentaho-kettle/pull/2652 + checkstyle
=> [SP-2777] Backport of PDI-13787 - Get Variables: Cannot convert String Variable value to Timestamp field (6.1 Suite)

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java, plugins/repositories-plugin/src/test/java/org/pentaho/di/ui/repo/RepositoryConnectControllerTest.java
=> [BACKLOG-9581] ensure object ids are cleared when switching repository

plugins/repositories-plugin/pom.xml
=> [TEST] fix javax.xml.parsers.DocumentBuilderFactory.setFeature issue

core/src/org/pentaho/di/core/BaseRowSet.java, engine/test-src/org/pentaho/di/concurrency/BaseRowSetConcurrentTest.java
- Test written
Backport of https://github.com/pentaho/pentaho-kettle/pull/2689
=> [SP-2796] Backport of PDI-8941 - BaseRowSet synchronization needs re-evaluated (6.1 Suite)

engine/src/org/pentaho/di/cluster/SlaveServer.java, engine/test-src/org/pentaho/di/concurrency/SlaveServerConcurrentTest.java
=> [PDI-8931] SlaveServer Synchronized methods need to be examined

ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
Backport of https://github.com/pentaho/pentaho-kettle/pull/2651
=> [SP-2781] Backport of PDI-15440 - Shift Click or Middle Mouse Click to Create Connector Generates Exception (Windows 10) (6.1 Suite)

ui/src/org/pentaho/di/ui/spoon/trans/TransGraph.java
Backport of https://github.com/pentaho/pentaho-kettle/pull/2735.
@mchen-len-son, could you review this PR please?
=> [SP-2785] Backport of PDI-15386 - PDI 5.4/6.1.0 - Excel Writer step does not retain the cell style when data format is also applied (5.4 Suite)

engine/src/org/pentaho/di/trans/steps/getvariable/GetVariableMeta.java, engine/test-src/org/pentaho/di/trans/steps/getvariable/GetVariableMetaTest.java
Backport of https://github.com/pentaho/pentaho-kettle/pull/2652 + checkstyle.
@pamval , @mchen-len-son , could you please review this PR?
=> [SP-2776] Backport of PDI-13787 - Get Variables: Cannot convert String Variable value to Timestamp field (5.4 Suite)

core/src/org/pentaho/di/core/BaseRowSet.java, engine/test-src/org/pentaho/di/concurrency/BaseRowSetConcurrentTest.java, engine/test-src/org/pentaho/di/concurrency/JobTrackerConcurrencyTest.java, engine/test-src/org/pentaho/di/concurrency/PluginRegistryConcurrencyTest.java
Backport of https://github.com/pentaho/pentaho-kettle/pull/2689 and https://github.com/pentaho/pentaho-kettle/pull/2688
=> [SP-2797] Backport of PDI-8941 - BaseRowSet synchronization needs re-evaluated (5.4 Suite)

core/src/org/pentaho/di/core/variables/Variables.java, core/test-src/org/pentaho/di/core/variables/VariablesTest.java
…ts to prove the ConcurrentModificationException no longer occurs.
=> [SP-2788]-Backport of PDI-15210 - Intermittent ConcurrentModificationException with DatabaseMeta.getQuotedSchemaTableCombination (6.1 Suite)

core/src/org/pentaho/di/core/vfs/configuration/KettleSftpFileSystemConfigBuilder.java, core/test-src/org/pentaho/di/core/vfs/configuration/KettleSftpFileSystemConfigBuilderTest.java
Change to IdentityInfo as needed by VFS 2.1
@brosander  Could you please merge it?
=> [SP-2775][PDI-15501] VFS SFTP Identity Fix

assembly/ivy.xml, core/ivy.xml, plugins/pdi-pur-plugin/ivy.xml
Reverts pentaho/pentaho-kettle#2745
=> Revert "[PDI-15105] Update javassist version"

engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMeta.java, engine/test-src/org/pentaho/di/trans/steps/transexecutor/TransExecutorMetaTest.java
Backport of https://github.com/pentaho/pentaho-kettle/pull/2400 to 6.1 codeline
@pamval @mbatchelor
=> [BACKLOG-7662] - The Transformation Executor step isn't editable

core/ivy.xml, core/src/org/pentaho/di/core/row/RowMeta.java, core/test-src/org/pentaho/di/core/row/RowMetaTest.java, engine/ivy.xml, engine/test-src/org/pentaho/di/trans/steps/fieldsplitter/FieldSplitterTest.java
there are two commits:
- fix a couple minor dependency inconsistencies
- real fix and unit tests
=> [PDI-15523] - Select Values Step Throws Errors when multiple fields with same field name occur

plugins/repositories-plugin/src/main/resources/web/pentaho-repository-connect.html
Change per PJ's request... @mdamour1976 @wseyler
=> [BACKLOG-8410] small Styling fix for login screen

plugins/repositories-plugin/src/main/resources/org/pentaho/di/ui/repo/plugin.properties
@mdamour1976 @bmorrise  please review
=> [BACKLOG-9786] change default port in new connection dialog

core/src/org/pentaho/di/core/database/Database.java, core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
-added tests for throw exception in methods commit() and pstm.close()
-added fix in disconnect() for close connection  in these cases
@brosander @mchen-len-son Could you please review?
=> [PDI-15507] Connections not being released after SQL Exception

core/src/org/pentaho/di/core/database/Database.java
[PDI-15507] Connections not being released after SQL Exception
fix error log message
@mchen-len-son Could you please review and merge.
=> [PDI-8928]  KettleDatabaseRepositoryConnectionDelegate - multiple un-synchronized methods that mutate objects

plugins/repositories-plugin/src/main/resources/web/create-new-connection.html, plugins/repositories-plugin/src/main/resources/web/pentaho-repository.html
=> [BACKLOG-9466] - Adding a new repo connection from the repository manager is causing confusion on the main screen

plugins/repositories-plugin/src/main/resources/web/js/controllers.js, plugins/repositories-plugin/src/main/resources/web/pentaho-repository-connect.html, plugins/repositories-plugin/src/main/resources/web/repository-manager.html
=> [BACKLOG-8410] - Changed tooltips to use the "title" tag

plugins/salesforce/test-src/org/pentaho/di/trans/steps/salesforce/SalesforceConnectionIT.java
Addresses change made in #2706
=> [TEST] Fix SFDC Connection Test

plugins/meta-inject-plugin/pom.xml
Fixes missing dependency caused by #2804
=> [CLEANUP] Add missing test dependency

engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java, engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByTest.java
@CodeOnCoffee, @deinspanjer, @bmorrise, @ddiroma, @pamval could you please take a look?
=> [PDI-15251] -VFS-based Variables do not work for "Group By" step's temp directory on Windows

core/src/org/pentaho/di/core/database/Database.java, core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
-added tests for throw exception in methods commit() and pstm.close()
-added fix in disconnect() for close connection  in these cases
@brosander @mchen-len-son Could you please merge?
=> [SP-2848][PDI-15507] Connections not being released after SQL Exception

core/src/org/pentaho/di/core/database/Database.java, core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
[SP-2847][PDI-15507] Connections not being released after SQL Exception
-added tests for throw exception in methods commit() and pstm.close()
-added fix in disconnect() for close connection  in these cases
@brosander @mchen-len-son Could you please merge?
=> [SP-2847][PDI-15507] Connections not being released after SQL Exception

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaTest.java
Added getValueOrEmptyIfNull() function for fileName, sheetName and field.getName() to make countNrStepAttributes() function working correctly.
Added appropriate unit test.
=> [PDI-15520] Settings for Excel Input step is lost after export/import to a repository

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java
[SP-2807][PDI-8928]  KettleDatabaseRepositoryConnectionDelegate - multiple un-synchronized methods that mutate objects
- extracted code for modifying sqlMap in separated method
- changed sqlMap from a HashMap to a ConcurrentHashMap
@lucboudreau @mchen-len-son Could you please review it?
=> [SP-2807][PDI-8928]  KettleDatabaseRepositoryConnectionDelegate

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java
[CHECKSTYLE]   fixed copyright year
@lucboudreau @mchen-len-son Could you please merge it?
=> [CHECKSTYLE]   fixed copyright year

engine/src/org/pentaho/di/repository/kdr/delegates/KettleDatabaseRepositoryConnectionDelegate.java
[SP-2808] [PDI-8928]  KettleDatabaseRepositoryConnectionDelegate - multiple un-synchronized methods that mutate objects
- extracted code for modifying sqlMap in separated method
- changed sqlMap from a HashMap to a ConcurrentHashMap
@lucboudreau @mchen-len-son Could you please review and merge it?
=> [SP-2808] [PDI-8928]  KettleDatabaseRepositoryConnectionDelegate

engine/src/org/pentaho/di/cluster/SlaveServer.java, engine/test-src/org/pentaho/di/concurrency/SlaveServerConcurrentTest.java, ui/src/org/pentaho/di/ui/cluster/dialog/SlaveServerDialog.java
- Test written
@lucboudreau @mchen-len-son Could you please merge it?
=> [SP-2811][PDI-8931] SlaveServer Synchronized methods need to be examined

engine/src/org/pentaho/di/trans/steps/ivwloader/IngresVectorwiseLoaderMeta.java
- getUsedDatabaseConnections() method is implemented for IngresVectorwiseLoaderMeta
=> [SP-2805] Backport of PDI-15161 - Vectorwise Bulk Loader Step does not save DB Connection (6.1 Suite)

engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java, engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByTest.java
@mchen-len-son, here is backport of https://github.com/pentaho/pentaho-kettle/commit/7587ab6c2ca9cef5b44bd799cf78694caf3b972c to 6.1.Thanks.
=> [SP-2871] - Backport of PDI-15251 - VFS-based Variables do not work f… 

engine/src/org/pentaho/di/trans/steps/groupby/GroupBy.java, engine/test-src/org/pentaho/di/trans/steps/groupby/GroupByTest.java
@mchen-len-son, here is backport of 7587ab6 to 5.4.Thanks.
=> [SP-2870] - Backport of PDI-15251 - VFS-based Variables do not work f… 

engine/src/org/pentaho/di/cluster/SlaveServer.java, engine/test-src/org/pentaho/di/concurrency/SlaveServerConcurrentTest.java
[SP-2811][PDI-8931]
- Test written
=> Sp 2811 backport pdi 8931

engine/src/org/pentaho/di/cluster/SlaveServer.java, engine/test-src/org/pentaho/di/concurrency/SlaveServerConcurrentTest.java, engine/test-src/org/pentaho/di/www/CarteTest.java
=> [SP-2812][PDI-8931]

plugins/repositories-plugin/src/main/resources/web/css/style.css, plugins/repositories-plugin/src/main/resources/web/js/controllers.js, plugins/repositories-plugin/src/main/resources/web/repository-manager.html
=> [BACKLOG-10324] Checkbox oddity in Repository Manager dialog

engine/src/org/pentaho/di/trans/steps/synchronizeaftermerge/messages/messages_en_US.properties
=> [BACKLOG-9361] - Add Metadata Injection (MDI) support to the Synchronize after merge step - fix UI message

assembly/ivy.xml
http://jira.pentaho.com/browse/BACKLOG-10143
https://github.com/pentaho/big-data-plugin/pull/715
=> [BACKLOG-10143]Remove pdi-spark-plugin

plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_DatabaseNames_IT.java, ui/src/org/pentaho/di/ui/repository/repositoryexplorer/controllers/ConnectionsController.java, ui/src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIDatabaseConnection.java, ui/test-src/org/pentaho/di/ui/repository/repositoryexplorer/model/UIDatabaseConnectionTest.java
[PDI-4945] Explore Repository Database Modified Dates
=> [PDI-4945] Explore Repository Database Modified Dates

plugins/repositories-plugin/src/main/resources/web/css/style.css
=> [BACKLOG-10294] fix for checkbox position change issue in QAT 313

ui/src/org/pentaho/di/ui/spoon/JobFileListener.java, ui/src/org/pentaho/di/ui/spoon/Spoon.java, ui/src/org/pentaho/di/ui/spoon/TransFileListener.java, ui/src/org/pentaho/di/ui/spoon/delegates/SpoonTabsDelegate.java
Most of the extension points introduced in https://github.com/pentaho/pentaho-kettle/pull/911 aren't being called.
@pentaho/millenniumfalcon and @mdamour1976 please review.
=> [BACKLOG-10562] Fix calls to extension points

plugins/meta-inject-plugin/src/main/java/org/pentaho/di/ui/trans/steps/metainject/MetaInjectDialog.java
=> [BACKLOG-10649] don't check trans when empty filename, npe with objectId

core/src/org/pentaho/di/core/plugins/BasePluginType.java
* Correction for the cases where Log Level was changed to Basic Level and not restored.
=> BACKLOG-10651 Ensuring that logel level is restored

core/src/org/pentaho/di/core/Const.java
Reverts pentaho/pentaho-kettle#2908
=> Revert "PDI-15653"

assembly/package-res/system/mondrian/mondrian.properties
Adding mondrian.properties to the assembly for things in the osgi container.
=> [BACKLOG-10029] - Preparing assemblies to not depend on agile-bi.

engine/test-src/org/pentaho/di/core/row/ValueDataUtilTest.java
=> [TEST] fixed failing tests

engine/src/org/pentaho/di/repository/ReconnectableRepository.java, plugins/pdi-pur-plugin/src/org/pentaho/di/repository/pur/PurRepository.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryDialog.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositorySessionTimeoutHandler.java, plugins/repositories-plugin/src/main/resources/org/pentaho/di/ui/repo/messages/messages_en_US.properties, plugins/repositories-plugin/src/main/resources/web/js/controllers.js
=> [BACKLOG-9374] - Handle Pentaho Repository timeout

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaTest.java
Added getValueOrEmptyIfNull() function for fileName, sheetName and field.getName() to make countNrStepAttributes() function working correctly.
Added appropriate unit test.
=> [SP-2883] Backport of PDI-15520 - Settings for Excel Input step is lost after export/import to a repository (6.1 Suite)

core/src/org/pentaho/di/core/database/Database.java, core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
[PDI-15507] Connections not being released after SQL Exception
modify fix for PDI-15507 return statements must not call closeConnection
test
@mbatchelor @mchen-len-son  Could you please review and merge it?
=> [PDI-15669] fix for PDI-15507 breaks transactional transformations

engine/src/org/pentaho/di/trans/steps/excelinput/ExcelInputMeta.java, engine/test-src/org/pentaho/di/trans/steps/excelinput/ExcelInputMetaTest.java
Added getValueOrEmptyIfNull() function for fileName, sheetName and field.getName() to make countNrStepAttributes() function working correctly.
Added appropriate unit test.
=> [SP-2884] Backport of PDI-15520 - Settings for Excel Input step is lost after export/import to a repository (5.4 Suite)

ui/src/org/pentaho/di/ui/spoon/Spoon.java
=> [SP-2839] Backport of PDI-14117 - Search entries on a Job (START and DUMMY entries) (5.4 Suite)

ui/src/org/pentaho/di/ui/spoon/Spoon.java
=> [SP-2840] Backport of PDI-14117 - Search entries on a Job (START and DUMMY entries) (6.1 Suite)

core/src/org/pentaho/di/core/database/Database.java, core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
[Sp 2847] pdi 15507 @mbatchelor @mchen-len-son Could you please review and merge it?
=> [Sp 2847] pdi 15507

core/src/org/pentaho/di/core/database/Database.java, core/test-src/org/pentaho/di/core/database/DatabaseUnitTest.java
=> [SP-2848][PDI-15507][PDI-15669] Connections not being released after SQL Exception

plugins/pdi-pur-plugin/src/org/pentaho/di/ui/repository/pur/repositoryexplorer/controller/TrashBrowseController.java, plugins/pdi-pur-plugin/src/org/pentaho/di/ui/repository/pur/repositoryexplorer/messages/messages_en_US.properties, plugins/pdi-pur-plugin/test/org/pentaho/di/ui/repository/pur/repositoryexplorer/controller/TrashBrowseControllerTest.java
BACKLOG-10137 Restoring Data Service references when restoring transformations from trash
=> BACKLOG-10137 Restoring Data Service references when restoring transformations from trash

core/src/org/pentaho/di/core/database/DatabaseMeta.java, core/src/org/pentaho/di/core/database/messages/messages_en_US.properties
=> [BISERVER-12713] L10N - Error messages are not translated to different languages

plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/GPLoadMeta.java, plugins/kettle-s3csvinput-plugin/src/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta.java
- added help links to S3 Csv Input step and Greenplum Load step
=> [PDI-14133] Transformation Steps Missing Help Links

plugins/kettle-gpload-plugin/src/org/pentaho/di/trans/steps/gpload/GPLoadMeta.java, plugins/kettle-s3csvinput-plugin/src/org/pentaho/di/trans/steps/s3csvinput/S3CsvInputMeta.java
- added help links to S3 Csv Input step and Greenplum Load step
=> [SP-2838][PDI-14133] Transformation Steps Missing Help Links

plugins/repositories-plugin/pom.xml, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryConnectController.java, plugins/repositories-plugin/src/test/java/org/pentaho/di/ui/repo/RepositoryConnectControllerTest.java
=> [BACKLOG-10653] repository status getting changed when not connected

plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforcedelete/SalesforceDeleteDialog.java, plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinput/SalesforceInputDialog.java, plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceinsert/SalesforceInsertDialog.java, plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceupdate/SalesforceUpdateDialog.java, plugins/salesforce/src/org/pentaho/di/ui/trans/steps/salesforceupsert/SalesforceUpsertDialog.java
=> [SP-2841]-Backport of PDI-14403 - Salesforce: Test Connection shows

ui/src/org/pentaho/di/ui/spoon/ExpandedContentManager.java
@pentaho/orlandocalisbon please review
I had to move away from the previous implementation because the key combination number exploded. This if-else can have multiple implementations, but i prefer to have it more verbose and at the same time easier to understand if we need to add more cases. Let me know what you think.
No unit tests are expected :)
=> [BACKLOG-11071] - Blocked keyboard shortcuts breaking DET interactions

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositorySessionTimeoutHandler.java
=> [BACKLOG-9374] - Handle Pentaho Repository timeout - repeat operation if case of failure

ui/src/org/pentaho/di/ui/spoon/ExpandedContentManager.java
This pr fixes checkstyle of https://github.com/pentaho/pentaho-kettle/pull/2991
@pentaho/orlandocalisbon please review
=> [BACKLOG-11071] - Updated keys to be blocked. Removed print key block

plugins/repositories-plugin/src/main/resources/META-INF/js/require.json
=> [CLEANUP] Update jquery version for repositories

engine/src/org/pentaho/di/trans/steps/csvinput/CsvInput.java, engine/test-src/org/pentaho/di/trans/steps/csvinput/PDI_15270_Test.java
@rmansoor, @kurtwalker, @mbatchelor, could you please take a look?
=> [PDI-15270] - CSV File Input mangles field containing substring in Enclosure

engine/src/org/pentaho/di/trans/steps/httppost/HTTPPOST.java
http://jira.pentaho.com/browse/PDI-15706
=> [PDI-15706] fixed HTTPPOST RequestEntity wrong length

dbdialog/src/org/pentaho/ui/database/event/DataHandler.java, dbdialog/test-src/org/pentaho/ui/database/event/DataHandlerTest.java
http://jira.pentaho.com/browse/BACKLOG-10097
=> [BACKLOG-10097]Default data services connections to the Pentaho Server

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositorySessionTimeoutHandler.java, plugins/repositories-plugin/src/test/java/org/pentaho/di/ui/repo/RepositorySessionTimeoutHandlerTest.java
@bmorrise , @mdamour1976 please review it
=> [BACKLOG-11196] - 'Login to Repository' dialog duplicates in Spoon if wrong username/password was specified

engine/src/org/pentaho/di/trans/steps/filterrows/FilterRowsMeta.java, engine/src/org/pentaho/di/trans/steps/filterrows/messages/messages_en_US.properties, engine/test-src/org/pentaho/di/trans/steps/filterrows/FilterRowsMetaInjectionTest.java
=> [BACKLOG-8210] Add Metadata Injection (MDI) support to the Filter rows

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/MetaStoreSessionTimeoutHandler.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositorySessionTimeoutHandler.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/SessionTimeoutHandler.java, plugins/repositories-plugin/src/test/java/org/pentaho/di/ui/repo/MetaStoreSessionTimeoutHandlerTest.java, plugins/repositories-plugin/src/test/java/org/pentaho/di/ui/repo/RepositorySessionTimeoutHandlerTest.java, plugins/repositories-plugin/src/test/java/org/pentaho/di/ui/repo/SessionTimeoutHandlerTest.java
=> [BACKLOG-9374] - Handle Pentaho Repository timeout - add handler for metastore

ui/src/org/pentaho/di/ui/job/entries/ftpput/JobEntryFTPPUTDialog.java
[PDI-15552] PDI: Getting error message when double-clicking 'Put A file with FTP' step
-added using empty string instead of null for port
=> [PDI-15552] PDI: Getting error message when double-clicking 'Put A file with FTP' step

core/src/org/pentaho/di/core/extension/KettleExtensionPoint.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryDialog.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RequestLoginToRepositoryExtensionPoint.java, plugins/repositories-plugin/src/main/resources/OSGI-INF/blueprint/beans.xml, plugins/repositories-plugin/src/main/resources/org/pentaho/di/ui/repo/messages/messages_en_US.properties
@bmorrise , @mdamour1976  please review
=> [BACKLOG-11180] - Old-style 'Repository Connection' dialog is accessible in Spoon

plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/CentralLogStore.java, plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/Log4jConsoleAppender.java, plugins/kettle5-log4j-plugin/src/org/pentaho/di/core/logging/LogWriter.java
@bmorrise , @mkambol please review
=> [BACKLOG-5447] - add @depricated annotation

ui/src/org/pentaho/di/ui/spoon/Spoon.java
=> [BACKLOG-11416] Set the selected step after an undo operation

engine/src/org/pentaho/di/www/CarteDelegationHandler.java, engine/src/org/pentaho/di/www/ListServerSocketServlet.java, engine/src/org/pentaho/di/www/TransformationMap.java, engine/test-src/org/pentaho/di/concurrency/TransformationMapConcurrentTest.java
=> PDI-8937 - Fixed inconsistent synchronization in TransformationMap. Replaced with concurrent collections and removed  redundant synchronized blocks.

ui/src/org/pentaho/di/ui/core/widget/TableView.java
=> [BACKLOG-11435] revert swt4.3 windows ccombo workaround after upgrade

plugins/meta-inject-plugin/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java
=> [BACKLOG-11688] - Unable to export transformation with metadata injection step

plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositoryServiceSessionTimeoutHandler.java, plugins/repositories-plugin/src/main/java/org/pentaho/di/ui/repo/RepositorySessionTimeoutHandler.java, plugins/repositories-plugin/src/test/java/org/pentaho/di/ui/repo/RepositoryServiceSessionTimeoutHandlerTest.java
@bmorrise , @mdamour1976  please review
=> [BACKLOG-9374] - Handle Pentaho Repository timeout - add timeout hadlers for repository services

ui/src/org/pentaho/di/ui/core/dialog/ErrorWithDetailsDialog.java
http://jira.pentaho.com/browse/BACKLOG-11729
=> [BACKLOG-11729] Fix for error dialog sizing

core/src/org/pentaho/di/core/xml/XMLParserFactoryProducer.java, plugins/kettle-xml-plugin/src/org/pentaho/di/trans/steps/getxmldata/GetXMLData.java, plugins/kettle-xml-plugin/src/org/pentaho/di/ui/trans/steps/getxmldata/LoopNodesImportProgressDialog.java, plugins/kettle-xml-plugin/src/org/pentaho/di/ui/trans/steps/getxmldata/XMLInputFieldsImportProgressDialog.java, plugins/xml-input-stream/src/org/pentaho/di/trans/steps/xmlinputsax/XMLInputSaxDataRetriever.java, plugins/xml-input-stream/src/org/pentaho/di/trans/steps/xmlinputsax/XMLInputSaxFieldRetriever.java
@mbatchelor, @rmansoor, @pamval, @CodeOnCoffee, could you please take a look?
=> [PPP-3506] - XXE Security Vulnerability in xml parsers

ui/package-res/ui/images/kettle_logo_small.svg
- fixed kettle_logo_small.svg icon
=> [BACKLOG-11620] Update product App icons and splash screens

engine/src/org/pentaho/di/www/TransformationMap.java, engine/test-src/org/pentaho/di/www/TransformationMapTest.java
=> [BACKLOG-11853] - /kettle/listSocket method fails in 7.0.0.0

core/src/org/pentaho/di/core/row/value/ValueMetaInternetAddress.java, core/test-src/org/pentaho/di/core/row/value/ValueMetaInternetAddressTest.java
=> [BACKLOG-11693]Use default binary string conversion for Internet Address

engine/src/org/pentaho/di/www/TransformationMap.java, engine/test-src/org/pentaho/di/www/TransformationMapTest.java
@dkincade, @bmorrise , @mdamour1976 please review
=> [BACKLOG-11853] - /kettle/listSocket method fails in 7.0.0.0 (#3076)

ui/src/org/pentaho/di/ui/job/entries/ftpput/JobEntryFTPPUTDialog.java
[SP-2969][PDI-15552] PDI: Getting error message when double-clicking 'Put A file with FTP' step
-added using empty string instead of null for port
=> [SP-2969][PDI-15552] PDI: Getting error message when double-clicking 'Put A file with FTP' step

plugins/kettle-drools5-plugin/ivy.xml
@pamval, @mbatchelor, could you please take a look?
=> [BACKLOG-11939] - Drools upgrade bringing in vulnerable xstream jar

plugins/elasticsearch-bulk-insert/src/org/pentaho/di/trans/steps/elasticsearchbulk/ElasticSearchBulkMeta.java, plugins/meta-inject-plugin/src/main/java/org/pentaho/di/trans/steps/metainject/MetaInjectMeta.java, plugins/meta-inject-plugin/src/main/resources/OSGI-INF/blueprint/pentaho-metainject-pdi-blueprint.xml, plugins/meta-inject-plugin/src/main/resources/org/pentaho/di/trans/steps/metainject/messages/messages_en_US.properties
=> [BACKLOG-11918] MetaInject and ElasticSearch help documentation update

plugins/googleanalytics/ivy.xml
=> [PPP-3571] Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577

engine/src/org/pentaho/di/trans/steps/filterrows/FilterRowsMeta.java, engine/test-src/org/pentaho/di/trans/steps/filterrows/FilterRowsMetaTest.java
Reverts previous fixes that caused this regression
2fa882af41b0baaee72d4cc0faa7fa44921326aa
3c46aa03c8f54ecb00995aa01388c5cd61b15222
=> [BACKLOG-12003]Persist Filter step output when target is renamed

ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java
=> [BACKLOG-10378] run dialog flashing on open

plugins/repositories-plugin/src/main/resources/web/css/style.css, plugins/repositories-plugin/src/main/resources/web/repository-manager.html
@bmorrise @mdamour1976 
NOTE: the case calls for "approximately 344px." But 347px allows for exactly 20px above and below the "Add" button.
=> [BACKLOG-10385] Increase repository manager list container height

engine/src/org/pentaho/di/trans/TransPainter.java
=> [BACKLOG-11809] ui not compiling

plugins/repositories-plugin/src/main/resources/web/js/app.js
@bmorrise @mdamour1976 @AlexanderBuloichik
=> [BACKLOG-10527] Fix for cursor jump focusing

plugins/repositories-plugin/src/main/resources/web/js/controllers.js
=> [BACKLOG-10383] Make the repository list item de-selectable

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java, plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java
=> [PDI-15379] - Skip checking equality of results size if it's size is 0;

engine/src/org/pentaho/di/base/AbstractMeta.java, engine/src/org/pentaho/di/core/gui/BasePainter.java, engine/src/org/pentaho/di/job/JobMeta.java, engine/src/org/pentaho/di/job/JobPainter.java, engine/src/org/pentaho/di/repository/RepositoryImporter.java, engine/src/org/pentaho/di/trans/TransMeta.java, engine/src/org/pentaho/di/trans/TransPainter.java, plugins/pdi-pur-plugin/test/org/pentaho/di/repository/pur/PurRepository_SharedObjects_Links_IT.java, ui/src/org/pentaho/di/ui/core/dialog/ConfigurationDialog.java
Reverts pentaho/pentaho-kettle#3150
=> Revert "[BACKLOG-11809] Merge some common methods in the Trans- and Job- classes"

ui/src/org/pentaho/xul/swt/tab/TabSet.java
=> [BACKLOG-11436] workaround 2 rows in tab toolbar

core/src/org/pentaho/di/core/Const.java, core/src/org/pentaho/di/core/messages/messages_en_US.properties, core/src/org/pentaho/di/core/variables/Variables.java, ui/src/org/pentaho/di/ui/core/widget/ControlSpaceKeyAdapter.java
variables and highlight the important ones
=> [BACKLOG-11407] Variable dropdown has to indicate the deprecated

core/src/org/pentaho/di/core/Const.java, core/src/org/pentaho/di/core/messages/messages_en_US.properties, core/src/org/pentaho/di/core/variables/Variables.java, ui/src/org/pentaho/di/ui/core/widget/ControlSpaceKeyAdapter.java
Reverts pentaho/pentaho-kettle#3160
=> Revert "[BACKLOG-11407] Variable dropdown has to indicate the deprecated"

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java
isReadable & isWriteable defaults setted
=> PDI-14797 Get Filenames Step issue with VFS and WinSSHD

engine/src/org/pentaho/di/job/JobExecutionConfiguration.java
-fix regression opening run dialog with transformation without file
=> [SP-2959][PDI-15296] Arguments (legacy) do not work in Spoon 6.1

core/src/org/pentaho/di/core/Const.java, engine/src/kettle-variables.xml, engine/src/org/pentaho/di/trans/steps/jobexecutor/JobExecutor.java, engine/src/org/pentaho/di/trans/steps/transexecutor/TransExecutor.java, ui/src/org/pentaho/di/ui/spoon/trans/LogBrowser.java
Added a delay for discard (log) lines logic to make spoon log tab able to read logs before they will be removed from buffer.
=> [PDI-15156] Problem setting variables row-by-row when using Job Executor

engine/src/org/pentaho/di/job/entries/getpop/JobEntryGetPOP.java, engine/src/org/pentaho/di/job/entries/sftp/JobEntrySFTP.java, ui/src/org/pentaho/di/ui/job/entries/getpop/JobEntryGetPOPDialog.java, ui/src/org/pentaho/di/ui/job/entries/sftp/JobEntrySFTPDialog.java, ui/src/org/pentaho/di/ui/job/entries/sftpput/JobEntrySFTPPUTDialog.java, ui/src/org/pentaho/di/ui/trans/steps/mailinput/MailInputDialog.java, ui/src/org/pentaho/di/ui/trans/steps/ssh/SSHDialog.java
[PDI-15703] Test transformation fails with encrypted password in a parameter for several steps
-added decrypting password
=> [PDI-15703] Test transformation fails with encrypted password in a parameter for several steps

plugins/googleanalytics/ivy.xml
=> [SP-3006] Backport of PPP-3571 - Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577 (7.0 Suite)

plugins/googleanalytics/ivy.xml
=> [SP-3007] Backport of PPP-3571 - Use of vulnerable component httpclient-4.2.5.jar - CVE-2014-3577 (6.1 Suite)

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInput.java, plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/InputsReader.java, plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java
Backport of BACKLOG-7448 - JSON Input should load documents from url coming in as field value
=> Sp 3003 - Backport of BACKLOG-7448 - JSON Input should load documents from url coming in as field value

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/JsonInputMeta.java, plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputMetaTest.java
Backport of PDI-15707 - JSON Input is not processing HDFS files that come from a Field when connected to repository (6.1 Suite)
=> Sp 3018 - Backport of PDI-15707 - JSON Input is not processing HDFS files that come from a Field when connected to repository (6.1 Suite) - 

plugins/kettle-json-plugin/src/org/pentaho/di/trans/steps/jsoninput/reader/FastJsonReader.java, plugins/kettle-json-plugin/test-src/org/pentaho/di/trans/steps/jsoninput/JsonInputTest.java
[PDI-15379] - Skip checking equality of results size if it's size is 0;
=> SP 3025 - Backport of PDI-15379 - Component failure "Input JSON" only in version 6.1.0.1-196.

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java
isReadable & isWriteable defaults setted
=> SP-3054 Get Filenames Step issue with VFS and WinSSHD

engine/src/org/pentaho/di/trans/steps/getfilenames/GetFileNames.java
isReadable & isWriteable defaults setted
=> SP-3055 Get Filenames Step issue with VFS and WinSSHD
